import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  curriculumSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'A1 - Beginner',
      link: {
        type: 'generated-index',
        title: 'A1: Beginner Ukrainian',
        description: 'Start your Ukrainian journey! Learn the Cyrillic alphabet, basic phrases, and fundamental grammar.',
        slug: '/a1',
      },
      items: [{type: 'autogenerated', dirName: 'a1'}],
    },
    {
      type: 'category',
      label: 'A2 - Elementary',
      link: {
        type: 'generated-index',
        title: 'A2: Elementary Ukrainian',
        description: 'Build on basics with all 7 cases, verb aspects, and comparison.',
        slug: '/a2',
      },
      items: [{type: 'autogenerated', dirName: 'a2'}],
    },
    {
      type: 'category',
      label: 'B1 - Intermediate',
      link: {
        type: 'generated-index',
        title: 'B1: Intermediate Ukrainian',
        description: 'Master aspect pairs, motion verbs, and complex sentences.',
        slug: '/b1',
      },
      items: [{type: 'autogenerated', dirName: 'b1'}],
    },
    {
      type: 'category',
      label: 'B2 - Upper-Intermediate',
      link: {
        type: 'generated-index',
        title: 'B2: Upper-Intermediate Ukrainian',
        description: 'Explore literature, academic writing, and professional contexts.',
        slug: '/b2',
      },
      items: [{type: 'autogenerated', dirName: 'b2'}],
    },
    {
      type: 'category',
      label: 'C1 - Advanced',
      link: {
        type: 'generated-index',
        title: 'C1: Advanced Ukrainian',
        description: 'Achieve full complexity with specialized topics.',
        slug: '/c1',
      },
      items: [{type: 'autogenerated', dirName: 'c1'}],
    },
    {
      type: 'category',
      label: 'C2 - Mastery',
      link: {
        type: 'generated-index',
        title: 'C2: Mastery Ukrainian',
        description: 'Native-level proficiency and cultural mastery.',
        slug: '/c2',
      },
      items: [{type: 'autogenerated', dirName: 'c2'}],
    },
  ],
};

export default sidebars;
