import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Learn Ukrainian
 *
 * Uses autogenerated items - modules are automatically discovered from folders.
 * Each level folder has a _category.json that controls its appearance.
 */
const sidebars: SidebarsConfig = {
  curriculumSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'A1 - Beginner',
      items: [{type: 'autogenerated', dirName: 'a1'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'A2 - Elementary',
      items: [{type: 'autogenerated', dirName: 'a2'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'B1 - Intermediate',
      items: [{type: 'autogenerated', dirName: 'b1'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'B2 - Upper-Intermediate',
      items: [{type: 'autogenerated', dirName: 'b2'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'C1 - Advanced',
      items: [{type: 'autogenerated', dirName: 'c1'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'C2 - Mastery',
      items: [{type: 'autogenerated', dirName: 'c2'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'LIT - Literature',
      items: [{type: 'autogenerated', dirName: 'lit'}],
      collapsed: true,
    },
    {
      type: 'html',
      value: '<hr style="margin: 1rem 0; border-color: var(--ifm-color-emphasis-300);" />',
    },
    {
      type: 'html',
      value: '<span style="font-size: 0.75rem; text-transform: uppercase; font-weight: 600; color: var(--ifm-color-emphasis-600); padding: 0.5rem 0.75rem;">Optional Tracks</span>',
    },
    {
      type: 'category',
      label: 'B2-HIST - Історія України',
      items: [{type: 'autogenerated', dirName: 'b2-hist'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'C1-HIST - Історіографія',
      items: [{type: 'autogenerated', dirName: 'c1-hist'}],
      collapsed: true,
    },

    {
      type: 'category',
      label: 'C1-BIO - Біографії українців',
      items: [{type: 'autogenerated', dirName: 'c1-bio'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'B2-PRO - Професійна українська',
      items: [{type: 'autogenerated', dirName: 'b2-pro'}],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'C1-PRO - Фахова українська',
      items: [{type: 'autogenerated', dirName: 'c1-pro'}],
      collapsed: true,
    },
  ],
};

export default sidebars;
