import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  curriculumSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'A1 - Beginner',
      link: {
        type: 'doc',
        id: 'a1/index',
      },
      items: [{type: 'autogenerated', dirName: 'a1'}],
    },
    {
      type: 'category',
      label: 'A2 - Elementary',
      link: {
        type: 'doc',
        id: 'a2/index',
      },
      items: [{type: 'autogenerated', dirName: 'a2'}],
    },
    {
      type: 'category',
      label: 'B1 - Intermediate',
      link: {
        type: 'doc',
        id: 'b1/index',
      },
      items: [{type: 'autogenerated', dirName: 'b1'}],
    },
    {
      type: 'category',
      label: 'B2 - Upper-Intermediate',
      link: {
        type: 'doc',
        id: 'b2/index',
      },
      items: [{type: 'autogenerated', dirName: 'b2'}],
    },
    {
      type: 'category',
      label: 'C1 - Advanced',
      link: {
        type: 'doc',
        id: 'c1/index',
      },
      items: [{type: 'autogenerated', dirName: 'c1'}],
    },
    {
      type: 'category',
      label: 'C2 - Mastery',
      link: {
        type: 'doc',
        id: 'c2/index',
      },
      items: [{type: 'autogenerated', dirName: 'c2'}],
    },
    {
      type: 'category',
      label: 'LIT - Literature',
      link: {
        type: 'doc',
        id: 'lit/index',
      },
      items: [{type: 'autogenerated', dirName: 'lit'}],
    },
  ],
};

export default sidebars;
