#!/usr/bin/env python3
"""Generate Хрестоматія reading MDX files from folk primary-reading blocks.

The generator is deliberately conservative: it only writes a reading when a
folk module contains a structured ``:::primary-reading`` block, the quoted
fragment can be matched to a public-domain literary corpus row, and the output
slug is not already occupied by a hand-authored reading.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
import unicodedata
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.etymology.transliterate import transliterate
from scripts.readings.clean_text_resolver import load_work_index, resolve_clean_text
from scripts.readings.primary_text_demand import DEFAULT_PLANS_DIR, build_manifest
from scripts.readings.rights_classifier import classify_rights

CURRICULUM_ROOT = PROJECT_ROOT / "curriculum" / "l2-uk-en"
FOLK_ROOT = CURRICULUM_ROOT / "folk"
READINGS_ROOT = PROJECT_ROOT / "site" / "src" / "content" / "readings"
SOURCES_DB = PROJECT_ROOT / "data" / "sources.db"
GENERATED_MARKER = "AUTO-GENERATED by scripts/readings/generate_readings.py"

_PRIMARY_BLOCK_RE = re.compile(r":::primary-reading\s*\n(?P<body>.*?)\n:::\s*", re.DOTALL)
_ATTRIBUTION_RE = re.compile(
    r"^—\s*(?P<author>[^,\n]+),\s*«(?P<title>[^»]+)»(?:\s*\((?P<note>[^)\n]+)\))?",
    re.MULTILINE,
)
_PLAN_SOURCE_CHUNK_RE = re.compile(r"\bchunk\s+([0-9a-f]+_c\d+)\b", re.IGNORECASE)
_PLAN_TITLE_STRIP_CHARS = " \t\r\n«»“”„\"'`"
_STRESS_RE = re.compile("[\u0300\u0301]")
_NON_WORD_RE = re.compile(r"[^\w]+", re.UNICODE)


@dataclass(frozen=True)
class ResourceHint:
    title: str
    source_ref: str
    role: str
    notes: str
    packet_chunk_id: str | None


@dataclass(frozen=True)
class PrimaryReadingCandidate:
    module_dir: Path
    track: str
    slug: str
    author: str
    title: str
    note: str
    quote_lines: tuple[str, ...]

    @property
    def work_key(self) -> str:
        return f"{_text_key(self.author)}::{_text_key(self.title)}"


@dataclass(frozen=True)
class CorpusText:
    chunk_id: str
    author: str
    work: str
    work_id: str
    year: int | None
    genre: str
    language_period: str
    source_file: str
    source_url: str
    text: str


@dataclass(frozen=True)
class VerificationResult:
    matched: bool
    confidence: float
    detail: str


@dataclass
class ResolvedReading:
    candidate: PrimaryReadingCandidate
    corpus: CorpusText
    slug: str
    module_dirs: list[Path] = field(default_factory=list)
    tracks: set[str] = field(default_factory=set)
    study_links: str | None = None
    taught_in: tuple[str, ...] = ()
    source_chunk_ids: tuple[str, ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class WrittenReading:
    slug: str
    path: Path
    action: str
    source_chunk_id: str


@dataclass(frozen=True)
class SkippedReading:
    title: str
    slug: str | None
    reason: str


@dataclass(frozen=True)
class GenerationSummary:
    written: tuple[WrittenReading, ...]
    skipped: tuple[SkippedReading, ...]
    existing: tuple[WrittenReading, ...]

    @property
    def generated_count(self) -> int:
        return sum(1 for item in self.written if item.action == "created")


QuoteVerifier = Callable[[PrimaryReadingCandidate, CorpusText], VerificationResult]


CURATED_METADATA: dict[str, dict[str, Any]] = {
    "koliadka-yak-shche-ne-bulo": {
        "title": "«Як ще не було початку світа» (космогонічна колядка)",
        "title_en": "\"When the world had no beginning\" (cosmogonic carol)",
        "genre": "Колядка",
        "order": 20,
    },
    "duma-marusia-bohuslavka": {
        "title": "Дума про Марусю Богуславку",
        "title_en": "The Duma of Marusia Bohuslavka",
        "genre": "Дума",
        "order": 10,
    },
    "shchedrivka-oi-syvaia-ta-i-zozulechka": {
        "title": "«Ой сивая та і зозулечка» (щедрівка з тріадою світил)",
        "title_en": "\"Oh, the grey cuckoo\" (shchedrivka with a triad of lights)",
        "genre": "Щедрівка",
        "collector": "корпус ukrlib-narod-dumy; збирач не зазначений",
        "year": "традиційний текст; корпусна дата 1600",
        "period": "Зимова календарна обрядовість",
        "excerpt": (
            "Щедрівка з образом саду й трьох теремів: місяць відповідає "
            "господареві, сонце — господині, а дрібні зірки — дітям."
        ),
        "source": (
            "Народна творчість; корпус ukrlib-narod-dumy. Текст у суспільному "
            "надбанні; подано дослівно за корпусним записом — архаїчні й "
            "діалектні форми збережено."
        ),
        "intro": (
            "Це **повний текст** щедрівки «Ой сивая та і зозулечка», яку "
            "розбирають у модулі {links}. Тут збережено корпусний запис із "
            "рефреном і приміткою до його повторення."
        ),
        "order": 30,
    },
}

SLUG_ALIASES: dict[str, str] = {
    "народна творчість::як ще не було початку світа": "koliadka-yak-shche-ne-bulo",
    "народна творчість::дума про марусю богуславку": "duma-marusia-bohuslavka",
    "народна творчість::ой сивая та і зозулечка": "shchedrivka-oi-syvaia-ta-i-zozulechka",
    "народна творчість::ой сивая та і зозуленька": "shchedrivka-oi-syvaia-ta-i-zozulechka",
    "стус в::як добре що смерті не боюсь я": "stus-yak-dobre-te-shcho-smerti",
}


def parse_primary_readings(module_dir: Path) -> list[PrimaryReadingCandidate]:
    """Extract structured primary-reading blocks from a module."""
    module_path = module_dir / "module.md"
    if not module_path.exists():
        return []
    text = module_path.read_text(encoding="utf-8")
    candidates: list[PrimaryReadingCandidate] = []
    for block_match in _PRIMARY_BLOCK_RE.finditer(text):
        block = block_match.group("body")
        attr = _ATTRIBUTION_RE.search(block)
        if attr is None:
            continue
        quote_lines = tuple(_quote_lines(block))
        if not quote_lines:
            continue
        candidates.append(
            PrimaryReadingCandidate(
                module_dir=module_dir,
                track=module_dir.parent.name,
                slug=module_dir.name,
                author=attr.group("author").strip(),
                title=attr.group("title").strip(),
                note=(attr.group("note") or "").strip(),
                quote_lines=quote_lines,
            )
        )
    return candidates


def load_resource_hints(module_dir: Path) -> list[ResourceHint]:
    """Load resource rows that can point a primary block at a corpus chunk."""
    path = module_dir / "resources.yaml"
    if not path.exists():
        return []
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    if not isinstance(raw, list):
        return []
    hints: list[ResourceHint] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        hints.append(
            ResourceHint(
                title=str(item.get("title") or ""),
                source_ref=str(item.get("source_ref") or ""),
                role=str(item.get("role") or ""),
                notes=str(item.get("notes") or ""),
                packet_chunk_id=str(item["packet_chunk_id"]) if item.get("packet_chunk_id") else None,
            )
        )
    return hints


def generate_for_modules(
    module_dirs: Sequence[Path],
    *,
    output_dir: Path = READINGS_ROOT,
    sources_db: Path = SOURCES_DB,
    dry_run: bool = False,
    quote_verifier: QuoteVerifier | None = None,
) -> GenerationSummary:
    """Generate readings for the given folk module directories."""
    verifier = quote_verifier or verify_candidate_against_corpus
    output_dir.mkdir(parents=True, exist_ok=True)
    lookup = CorpusLookup(sources_db)
    resolved_by_slug: dict[str, ResolvedReading] = {}
    skipped: list[SkippedReading] = []

    for module_dir in sorted(Path(path) for path in module_dirs):
        hints = load_resource_hints(module_dir)
        for candidate in _dedupe_candidates(parse_primary_readings(module_dir)):
            slug = reading_slug(candidate)
            corpus = lookup.resolve(candidate, hints)
            if corpus is None:
                skipped.append(SkippedReading(candidate.title, slug, "no matching corpus text"))
                continue
            if not is_public_domain(corpus, track=candidate.track):
                skipped.append(SkippedReading(candidate.title, slug, "corpus row is not public-domain"))
                continue
            verdict = verifier(candidate, corpus)
            if not verdict.matched:
                skipped.append(
                    SkippedReading(
                        candidate.title,
                        slug,
                        f"quote verification failed: {verdict.detail}",
                    )
                )
                continue

            resolved = resolved_by_slug.get(slug)
            if resolved is None:
                resolved_by_slug[slug] = ResolvedReading(
                    candidate=candidate,
                    corpus=corpus,
                    slug=slug,
                    module_dirs=[module_dir],
                    tracks={candidate.track},
                )
            else:
                resolved.module_dirs.append(module_dir)
                resolved.tracks.add(candidate.track)

    written, existing = _write_resolved_readings(
        resolved_by_slug,
        output_dir=output_dir,
        dry_run=dry_run,
    )

    return GenerationSummary(tuple(written), tuple(skipped), tuple(existing))


def generate_from_demand(
    *,
    plans_dir: Path = DEFAULT_PLANS_DIR,
    track: str | None = None,
    output_dir: Path = READINGS_ROOT,
    sources_db: Path = SOURCES_DB,
    dry_run: bool = False,
) -> GenerationSummary:
    """Generate readings from primary-text demand manifest entries."""
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest = build_manifest(plans_dir, track=track)
    index = load_work_index(sources_db)
    chunk_rows = _load_corpus_chunk_rows(sources_db)
    resolved_by_slug: dict[str, ResolvedReading] = {}
    skipped: list[SkippedReading] = []

    for entry in manifest.get("entries", []):
        if not isinstance(entry, dict):
            continue
        work = str(entry.get("work") or "").strip()
        author = str(entry.get("author") or "").strip()
        taught_by = _entry_taught_by(entry)
        resolution, resolved_work, resolved_author = _resolve_clean_text_for_demand(work, author, index)
        candidate_title = str(resolution.get("matched_work") or resolved_work or work)
        candidate_author = str(resolution.get("matched_author") or resolved_author or author)
        candidate = PrimaryReadingCandidate(
            module_dir=plans_dir,
            track=_first_taught_value(taught_by, "track") or track or "",
            slug=_first_taught_value(taught_by, "slug") or "",
            author=candidate_author,
            title=candidate_title,
            note="",
            quote_lines=(),
        )
        slug = _unique_reading_slug(reading_slug(candidate), candidate, resolved_by_slug)

        if not resolution["in_corpus"]:
            skipped.append(SkippedReading(work, slug, "not in corpus"))
            continue
        if not resolution["hostable_full"]:
            skipped.append(
                SkippedReading(
                    work,
                    slug,
                    "in-copyright — needs browser-verified free-full-text link",
                )
            )
            continue

        clean_source = resolution["clean_text_source"]
        if not clean_source or not clean_source.get("chunk_ids"):
            skipped.append(SkippedReading(work, slug, "hostable corpus text missing chunks"))
            continue

        corpus = _read_corpus_chunks(chunk_rows, clean_source["chunk_ids"])
        if corpus is None:
            skipped.append(SkippedReading(work, slug, "corpus chunk text unavailable"))
            continue

        verdict = _verify_rendered_text_attested(corpus, candidate.title)
        if not verdict.matched:
            skipped.append(
                SkippedReading(
                    work,
                    slug,
                    f"quote verification failed: {verdict.detail}",
                )
            )
            continue

        tracks = {
            str(item.get("track") or "").strip()
            for item in taught_by
            if str(item.get("track") or "").strip()
        }
        resolved_by_slug[slug] = ResolvedReading(
            candidate=candidate,
            corpus=corpus,
            slug=slug,
            tracks=tracks,
            study_links=_study_links_from_taught_by(taught_by, plans_dir),
            taught_in=tuple(
                str(item.get("slug") or "").strip()
                for item in taught_by
                if str(item.get("slug") or "").strip()
            ),
            source_chunk_ids=tuple(str(chunk_id) for chunk_id in clean_source["chunk_ids"]),
        )

    written, existing = _write_resolved_readings(
        resolved_by_slug,
        output_dir=output_dir,
        dry_run=dry_run,
    )
    return GenerationSummary(tuple(written), tuple(skipped), tuple(existing))


def generate_from_plan(
    plan_path: Path,
    *,
    output_dir: Path = READINGS_ROOT,
    sources_db: Path = SOURCES_DB,
    dry_run: bool = False,
    quote_verifier: QuoteVerifier | None = None,
) -> GenerationSummary:
    """Generate hosted reading MDX files from one plan's readings block."""
    verifier = quote_verifier or verify_candidate_against_corpus
    output_dir.mkdir(parents=True, exist_ok=True)
    raw_plan = yaml.safe_load(plan_path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw_plan, dict):
        return GenerationSummary((), (SkippedReading(plan_path.stem, None, "plan is not a mapping"),), ())

    readings = raw_plan.get("readings")
    if not isinstance(readings, list):
        return GenerationSummary((), (), ())

    level = str(raw_plan.get("level") or plan_path.parent.name).strip().lower()
    module_slug = str(raw_plan.get("slug") or plan_path.stem).strip()
    study_links = _study_link_from_plan(raw_plan, plan_path, level=level, slug=module_slug)
    lookup = CorpusLookup(sources_db)
    hosted_values = _hosted_reading_values()
    resolved_by_slug: dict[str, ResolvedReading] = {}
    skipped: list[SkippedReading] = []

    for entry in readings:
        if not isinstance(entry, dict):
            continue
        hosting = str(entry.get("hosting") or "").strip().casefold()
        if hosting not in hosted_values:
            continue

        raw_title = str(entry.get("title") or "").strip()
        slug = str(entry.get("reading_slug") or "").strip()
        if not slug:
            skipped.append(SkippedReading(raw_title or "<untitled>", None, "missing reading_slug"))
            continue
        if not raw_title:
            skipped.append(SkippedReading("<untitled>", slug, "missing title"))
            continue

        source = str(entry.get("source") or "").strip()
        source_chunk_id = _source_chunk_id(source)
        candidate_title = _plan_candidate_title(raw_title)
        candidate = PrimaryReadingCandidate(
            module_dir=plan_path.parent,
            track=level,
            slug=module_slug,
            author=_plan_entry_author(entry),
            title=candidate_title,
            note=str(entry.get("genre") or "").strip(),
            quote_lines=(candidate_title,),
        )
        hints = _plan_resource_hints(candidate, source, source_chunk_id, raw_title)
        corpus = lookup.resolve(candidate, hints)
        if corpus is None:
            skipped.append(SkippedReading(raw_title, slug, "no matching corpus text"))
            continue
        rights_corpus = _plan_rights_corpus(candidate, corpus, entry)
        if not is_public_domain(rights_corpus, track=candidate.track):
            skipped.append(SkippedReading(raw_title, slug, "corpus row is not public-domain"))
            continue
        verdict = verifier(candidate, corpus)
        if not verdict.matched:
            skipped.append(
                SkippedReading(
                    raw_title,
                    slug,
                    f"quote verification failed: {verdict.detail}",
                )
            )
            continue

        resolved_by_slug[slug] = ResolvedReading(
            candidate=candidate,
            corpus=corpus,
            slug=slug,
            tracks={level} if level else set(),
            study_links=study_links,
            taught_in=(module_slug,) if module_slug else (),
            source_chunk_ids=(source_chunk_id or corpus.chunk_id,),
            metadata=_plan_reading_metadata(entry),
        )

    written, existing = _write_resolved_readings(
        resolved_by_slug,
        output_dir=output_dir,
        dry_run=dry_run,
    )
    return GenerationSummary(tuple(written), tuple(skipped), tuple(existing))


def _write_resolved_readings(
    resolved_by_slug: dict[str, ResolvedReading],
    *,
    output_dir: Path,
    dry_run: bool,
) -> tuple[list[WrittenReading], list[WrittenReading]]:
    written: list[WrittenReading] = []
    existing: list[WrittenReading] = []
    for slug, resolved in sorted(resolved_by_slug.items()):
        path = output_dir / f"{slug}.mdx"
        rendered = render_reading(resolved)
        if path.exists():
            current = path.read_text(encoding="utf-8")
            if GENERATED_MARKER not in current:
                existing.append(WrittenReading(slug, path, "existing-hand-authored", resolved.corpus.chunk_id))
                continue
            if current == rendered:
                existing.append(WrittenReading(slug, path, "unchanged", resolved.corpus.chunk_id))
                continue
            if not dry_run:
                path.write_text(rendered, encoding="utf-8")
            written.append(WrittenReading(slug, path, "updated", resolved.corpus.chunk_id))
            continue

        if not dry_run:
            path.write_text(rendered, encoding="utf-8")
        written.append(WrittenReading(slug, path, "created", resolved.corpus.chunk_id))
    return written, existing


class CorpusLookup:
    """Resolve primary-reading candidates to literary corpus rows."""

    def __init__(self, db_path: Path) -> None:
        self.db_path = db_path

    def resolve(
        self,
        candidate: PrimaryReadingCandidate,
        hints: Sequence[ResourceHint],
    ) -> CorpusText | None:
        if not self.db_path.exists():
            return None
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            for hint in _matching_hints(candidate, hints):
                if hint.packet_chunk_id:
                    row = conn.execute(
                        """
                        SELECT chunk_id, author, work, work_id, year, genre,
                               language_period, source_file, source_url, text
                        FROM literary_texts
                        WHERE chunk_id = ?
                        """,
                        (hint.packet_chunk_id,),
                    ).fetchone()
                    corpus = _row_to_corpus(row)
                    if corpus and verify_candidate_against_corpus(candidate, corpus).matched:
                        return corpus

            rows = self._candidate_rows(conn, candidate)
            scored = [
                (self._score(candidate, row), _row_to_corpus(row))
                for row in rows
            ]
            for _score, corpus in sorted(scored, key=lambda pair: pair[0], reverse=True):
                if corpus and verify_candidate_against_corpus(candidate, corpus).matched:
                    return corpus
        return None

    def _candidate_rows(
        self,
        conn: sqlite3.Connection,
        candidate: PrimaryReadingCandidate,
    ) -> list[sqlite3.Row]:
        rows: list[sqlite3.Row] = []
        seen: set[str] = set()

        def add(query: str, params: tuple[Any, ...]) -> None:
            for row in conn.execute(query, params).fetchall():
                chunk_id = str(row["chunk_id"])
                if chunk_id in seen:
                    continue
                seen.add(chunk_id)
                rows.append(row)

        select = """
            SELECT chunk_id, author, work, work_id, year, genre,
                   language_period, source_file, source_url, text
            FROM literary_texts
        """
        for title_variant in _title_lookup_variants(candidate.title):
            title_like = f"%{title_variant}%"
            add(
                f"{select} WHERE author = ? AND (work LIKE ? OR text LIKE ?) LIMIT 25",
                (candidate.author, title_like, title_like),
            )
        first_line = next((line for line in candidate.quote_lines if line.strip()), "")
        if first_line:
            add(
                f"{select} WHERE author = ? AND text LIKE ? LIMIT 25",
                (candidate.author, f"%{first_line.strip()}%"),
            )
        return rows

    @staticmethod
    def _score(candidate: PrimaryReadingCandidate, row: sqlite3.Row) -> int:
        text_key = _block_key(str(row["text"]))
        score = 0
        for line in candidate.quote_lines:
            line_key = _line_key(line)
            if line_key and line_key in text_key:
                score += 10
        if _text_key(candidate.title) and _text_key(candidate.title) in _text_key(str(row["work"])):
            score += 5
        return score


def verify_candidate_against_corpus(
    candidate: PrimaryReadingCandidate,
    corpus: CorpusText,
) -> VerificationResult:
    """Verify that every embedded quote line is attested in the corpus text."""
    text_key = _block_key(corpus.text)
    missing = [
        line for line in candidate.quote_lines
        if _line_key(line) and _line_key(line) not in text_key
    ]
    if missing:
        return VerificationResult(
            matched=False,
            confidence=0.0,
            detail=f"{len(missing)} quoted line(s) missing from {corpus.chunk_id}",
        )
    return VerificationResult(
        matched=True,
        confidence=1.0,
        detail=f"all quoted lines found in {corpus.chunk_id}",
    )


def is_public_domain(
    corpus: CorpusText,
    *,
    track: str | None = None,
    current_year: int | None = None,
) -> bool:
    """Fail closed unless the row has a conservative public-domain signal."""
    try:
        verdict = classify_rights(
            corpus.author,
            corpus.work,
            corpus.year,
            corpus.source_file,
            track or corpus.language_period,
            current_year=current_year,
        )
    except (FileNotFoundError, ValueError):
        return _legacy_is_public_domain(corpus)
    return verdict["rights_class"] == "public_domain"


def _legacy_is_public_domain(corpus: CorpusText) -> bool:
    if corpus.author == "Народна творчість" and corpus.source_file.startswith("ukrlib-narod"):
        return True
    return corpus.year is not None and corpus.year <= 1928


def reading_slug(candidate: PrimaryReadingCandidate) -> str:
    alias = SLUG_ALIASES.get(candidate.work_key)
    if alias:
        return alias
    prefix = _genre_prefix(candidate.note)
    base = transliterate(candidate.title)
    return f"{prefix}-{base}" if prefix and not base.startswith(prefix) else base


def render_reading(resolved: ResolvedReading) -> str:
    candidate = resolved.candidate
    corpus = resolved.corpus
    metadata = _metadata_for(resolved)
    tracks = sorted(resolved.tracks)
    study_links = resolved.study_links or _study_links(resolved.module_dirs)
    body_text = _display_text(corpus.text, candidate.title)
    quote = _blockquote(body_text)
    intro_template = metadata.pop("intro", None)
    if intro_template:
        intro = intro_template.format(links=study_links)
    else:
        intro = (
            f"Це **повний текст** твору «{candidate.title}», який розбирають у модулі "
            f"{study_links}. Текст подано за корпусним записом без редакторського "
            "осучаснення рядків."
        )

    lines = [
        *(_frontmatter(metadata, tracks)),
        "",
        "import PrimaryReading from '@site/src/components/PrimaryReading';",
        "",
        _wrap_intro(intro),
        "",
        "<PrimaryReading>",
        "",
        quote,
        "",
        "</PrimaryReading>",
        "",
        f"**Джерело:** {metadata['source']}",
        "",
        f"**Де вивчають:** {study_links}",
        "",
        f"{{/* {GENERATED_MARKER}; source_chunk_id: {corpus.chunk_id} */}}",
        "",
    ]
    return "\n".join(lines)


def discover_folk_module_dirs(root: Path = FOLK_ROOT) -> list[Path]:
    """Return certified-looking folk module directories in deterministic order."""
    return sorted(path for path in root.iterdir() if (path / "module.md").exists())


def format_summary(summary: GenerationSummary, *, project_root: Path = PROJECT_ROOT) -> str:
    lines = [
        "Readings generation summary",
        f"Written: {len(summary.written)}",
        f"Existing/skipped because present: {len(summary.existing)}",
        f"Skipped: {len(summary.skipped)}",
    ]
    for item in summary.written:
        lines.append(
            f"- {item.action}: {_display_path(item.path, project_root)} "
            f"(chunk {item.source_chunk_id})"
        )
    for item in summary.existing:
        lines.append(
            f"- {item.action}: {_display_path(item.path, project_root)} "
            f"(chunk {item.source_chunk_id})"
        )
    for item in summary.skipped:
        suffix = f" [{item.slug}]" if item.slug else ""
        lines.append(f"- skipped{suffix}: {item.title} — {item.reason}")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("module_dirs", nargs="*", type=Path, help="Folk module directories to scan")
    parser.add_argument("--all-folk", action="store_true", help="Scan all built folk modules")
    parser.add_argument("--from-demand", action="store_true", help="Generate from primary-text demand manifest")
    parser.add_argument("--from-plan", type=Path, help="Generate hosted readings from a single plan YAML")
    parser.add_argument("--track", help="Only scan one plans track when using --from-demand")
    parser.add_argument("--plans-dir", type=Path, default=DEFAULT_PLANS_DIR)
    parser.add_argument("--output-dir", type=Path, default=READINGS_ROOT)
    parser.add_argument("--sources-db", type=Path, default=SOURCES_DB)
    parser.add_argument("--dry-run", action="store_true", help="Report writes without changing files")
    parser.add_argument("--json", action="store_true", help="Print machine-readable summary")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.from_plan:
        if args.from_demand or args.module_dirs or args.all_folk or args.track:
            parser.error("--from-plan cannot be combined with other generation modes or --track")
        summary = generate_from_plan(
            args.from_plan,
            output_dir=args.output_dir,
            sources_db=args.sources_db,
            dry_run=args.dry_run,
        )
    elif args.from_demand:
        if args.module_dirs or args.all_folk:
            parser.error("--from-demand cannot be combined with folk module dirs or --all-folk")
        summary = generate_from_demand(
            plans_dir=args.plans_dir,
            track=args.track,
            output_dir=args.output_dir,
            sources_db=args.sources_db,
            dry_run=args.dry_run,
        )
    else:
        if args.track:
            parser.error("--track requires --from-demand")
        module_dirs = discover_folk_module_dirs() if args.all_folk else args.module_dirs
        if not module_dirs:
            parser.error("pass one or more module dirs, --all-folk, or --from-demand")

        summary = generate_for_modules(
            module_dirs,
            output_dir=args.output_dir,
            sources_db=args.sources_db,
            dry_run=args.dry_run,
        )
    if args.json:
        print(
            json.dumps(
                {
                    "written": [item.__dict__ | {"path": item.path.as_posix()} for item in summary.written],
                    "existing": [item.__dict__ | {"path": item.path.as_posix()} for item in summary.existing],
                    "skipped": [item.__dict__ for item in summary.skipped],
                },
                ensure_ascii=False,
                indent=2,
            )
        )
    else:
        print(format_summary(summary))
    return 0


def _dedupe_candidates(candidates: Sequence[PrimaryReadingCandidate]) -> list[PrimaryReadingCandidate]:
    by_key: dict[str, PrimaryReadingCandidate] = {}
    for candidate in candidates:
        existing = by_key.get(candidate.work_key)
        if existing is None or len(candidate.quote_lines) > len(existing.quote_lines):
            by_key[candidate.work_key] = candidate
    return list(by_key.values())


def _hosted_reading_values() -> set[str]:
    try:
        from scripts.build.linear_pipeline import _HOSTED_READING_VALUES
    except (ImportError, AttributeError):
        return {"host", "hosted"}
    return {str(value).strip().casefold() for value in _HOSTED_READING_VALUES}


def _source_chunk_id(source: str) -> str | None:
    match = _PLAN_SOURCE_CHUNK_RE.search(source)
    return match.group(1) if match else None


def _plan_candidate_title(title: str) -> str:
    return title.strip(_PLAN_TITLE_STRIP_CHARS) or title.strip()


def _plan_entry_author(entry: dict[str, Any]) -> str:
    explicit = str(entry.get("author") or "").strip()
    if explicit:
        return explicit
    source = str(entry.get("source") or "").strip()
    source_author = source.split(";", 1)[0].strip()
    return source_author or "Народна творчість"


def _plan_resource_hints(
    candidate: PrimaryReadingCandidate,
    source: str,
    source_chunk_id: str | None,
    raw_title: str,
) -> list[ResourceHint]:
    if not source_chunk_id:
        return []
    return [
        ResourceHint(
            title=candidate.title,
            source_ref=source,
            role="plan-reading",
            notes=raw_title,
            packet_chunk_id=source_chunk_id,
        )
    ]


def _plan_reading_metadata(entry: dict[str, Any]) -> dict[str, Any]:
    metadata: dict[str, Any] = {}
    for key in ("title", "title_en", "genre", "source"):
        value = str(entry.get(key) or "").strip()
        if value:
            metadata[key] = value
    return metadata


def _plan_rights_corpus(
    candidate: PrimaryReadingCandidate,
    corpus: CorpusText,
    entry: dict[str, Any],
) -> CorpusText:
    license_value = str(entry.get("license") or "").strip().casefold().replace("-", "_")
    if license_value != "public_domain":
        return corpus
    return CorpusText(
        chunk_id=corpus.chunk_id,
        author=candidate.author or corpus.author,
        work=candidate.title or corpus.work,
        work_id=corpus.work_id,
        year=corpus.year,
        genre=corpus.genre,
        language_period=corpus.language_period,
        source_file=corpus.source_file,
        source_url=corpus.source_url,
        text=corpus.text,
    )


def _study_link_from_plan(plan: dict[str, Any], plan_path: Path, *, level: str, slug: str) -> str:
    title = str(plan.get("title") or plan_path.stem).strip()
    return f"[{_track_label(level)} · «{title}»](/{level}/{slug}/)"


def _title_lookup_variants(title: str) -> list[str]:
    quoted = re.findall(r"«([^»]+)»", title)
    stripped = title.strip(_PLAN_TITLE_STRIP_CHARS)
    return _ordered_unique([title, stripped, *quoted])


def _quote_lines(block: str) -> Iterable[str]:
    for raw_line in block.splitlines():
        if not raw_line.startswith(">"):
            continue
        line = raw_line[1:]
        if line.startswith(" "):
            line = line[1:]
        yield line.rstrip()


def _matching_hints(
    candidate: PrimaryReadingCandidate,
    hints: Sequence[ResourceHint],
) -> Iterable[ResourceHint]:
    title_key = _text_key(candidate.title)
    for hint in hints:
        haystack = _text_key(" ".join([hint.title, hint.source_ref, hint.notes]))
        if title_key and title_key in haystack:
            yield hint


def _row_to_corpus(row: sqlite3.Row | None) -> CorpusText | None:
    if row is None:
        return None
    year_raw = row["year"]
    try:
        year = int(year_raw) if year_raw is not None else None
    except (TypeError, ValueError):
        year = None
    return CorpusText(
        chunk_id=str(row["chunk_id"]),
        author=str(row["author"] or ""),
        work=str(row["work"] or ""),
        work_id=str(row["work_id"] or ""),
        year=year,
        genre=str(row["genre"] or ""),
        language_period=str(row["language_period"] or ""),
        source_file=str(row["source_file"] or ""),
        source_url=str(row["source_url"] or ""),
        text=str(row["text"] or ""),
    )


def _resolve_clean_text_for_demand(
    work: str,
    author: str,
    index: Any,
) -> tuple[dict[str, Any], str, str]:
    fallback: tuple[dict[str, Any], str, str] | None = None
    for work_variant in _demand_work_variants(work):
        for author_variant in _demand_author_variants(author):
            resolution = resolve_clean_text(work_variant, author_variant, index)
            if fallback is None:
                fallback = (resolution, work_variant, author_variant)
            if resolution["in_corpus"]:
                return resolution, work_variant, author_variant
    if fallback is not None:
        return fallback
    return resolve_clean_text(work, author, index), work, author


def _demand_work_variants(work: str) -> list[str]:
    variants = _ordered_unique([work.strip()])
    without_trailing_note = re.sub(r"\s*\([^)]*\)\s*$", "", work).strip()
    variants = _ordered_unique([*variants, without_trailing_note])

    quoted = re.search(r"«([^»]+)»", work)
    if quoted:
        variants = _ordered_unique([*variants, quoted.group(1).strip()])

    plain_quoted = work.strip().strip("\"'“”„")
    return _ordered_unique([*variants, plain_quoted])


def _demand_author_variants(author: str) -> list[str]:
    author = author.strip()
    tokens = re.findall(r"[^\W\d_]+", author, flags=re.UNICODE)
    variants = [author]
    if len(tokens) >= 2:
        if "," in author or len(tokens[0]) == 1 or len(tokens[1]) <= 2:
            surname = tokens[0]
            given = tokens[1]
        else:
            given = tokens[0]
            surname = tokens[-1]
        variants.append(f"{surname} {given[0]}.")
    return _ordered_unique(variants)


def _ordered_unique(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        normalized = value.strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        result.append(normalized)
    return result


def _load_corpus_chunk_rows(db_path: Path) -> dict[str, sqlite3.Row]:
    rows_by_chunk_id: dict[str, sqlite3.Row] = {}
    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """
            SELECT chunk_id, author, work, work_id, year, genre, language_period,
                   source_file, source_url, text
            FROM literary_texts
            ORDER BY chunk_id, id
            """
        ).fetchall()
    for row in rows:
        rows_by_chunk_id.setdefault(str(row["chunk_id"]), row)
    return rows_by_chunk_id


def _read_corpus_chunks(rows_by_chunk_id: dict[str, sqlite3.Row], chunk_ids: Sequence[Any]) -> CorpusText | None:
    if not chunk_ids:
        return None
    rows: list[sqlite3.Row] = []
    for chunk_id in chunk_ids:
        row = rows_by_chunk_id.get(str(chunk_id))
        if row is None:
            return None
        rows.append(row)

    first = _row_to_corpus(rows[0])
    if first is None:
        return None
    text = "\n\n".join(str(row["text"] or "").strip() for row in rows if str(row["text"] or "").strip())
    if not text:
        return None
    return CorpusText(
        chunk_id=_chunk_id_label(chunk_ids),
        author=first.author,
        work=first.work,
        work_id=first.work_id,
        year=first.year,
        genre=first.genre,
        language_period=first.language_period,
        source_file=first.source_file,
        source_url=first.source_url,
        text=text,
    )


def _chunk_id_label(chunk_ids: Sequence[Any]) -> str:
    values = [str(chunk_id) for chunk_id in chunk_ids]
    if len(values) <= 1:
        return values[0] if values else ""
    return f"{values[0]}-{values[-1]}"


def _verify_rendered_text_attested(corpus: CorpusText, candidate_title: str) -> VerificationResult:
    rendered_text = _display_text(corpus.text, candidate_title)
    rendered_key = _block_key(rendered_text)
    if not rendered_key:
        return VerificationResult(False, 0.0, "rendered text is empty")
    if rendered_key not in _block_key(corpus.text):
        return VerificationResult(False, 0.0, f"rendered text not attested in chunk {corpus.chunk_id}")
    return VerificationResult(True, 1.0, f"attested in chunk {corpus.chunk_id}")


def _entry_taught_by(entry: dict[str, Any]) -> list[dict[str, Any]]:
    taught_by = entry.get("taught_by")
    if not isinstance(taught_by, list):
        return []
    return [item for item in taught_by if isinstance(item, dict)]


def _first_taught_value(taught_by: Sequence[dict[str, Any]], key: str) -> str:
    for item in taught_by:
        value = str(item.get(key) or "").strip()
        if value:
            return value
    return ""


def _unique_reading_slug(
    base_slug: str,
    candidate: PrimaryReadingCandidate,
    resolved_by_slug: dict[str, ResolvedReading],
) -> str:
    existing = resolved_by_slug.get(base_slug)
    if existing is None or existing.candidate.work_key == candidate.work_key:
        return base_slug

    author_suffix = transliterate(candidate.author)
    slug = f"{base_slug}-{author_suffix}" if author_suffix else base_slug
    counter = 2
    while slug in resolved_by_slug and resolved_by_slug[slug].candidate.work_key != candidate.work_key:
        slug = f"{base_slug}-{author_suffix}-{counter}" if author_suffix else f"{base_slug}-{counter}"
        counter += 1
    return slug


def _metadata_for(resolved: ResolvedReading) -> dict[str, Any]:
    candidate = resolved.candidate
    corpus = resolved.corpus
    slug = resolved.slug
    curated = dict(CURATED_METADATA.get(slug, {}))
    curated.update(resolved.metadata)
    genre = curated.get("genre") or _genre_from_note(candidate.note) or _genre_from_corpus(corpus.genre)
    source_file = corpus.source_file or "corpus"
    metadata = {
        "title": curated.get("title") or f"«{candidate.title}»" + (f" ({candidate.note})" if candidate.note else ""),
        **({"title_en": curated["title_en"]} if curated.get("title_en") else {}),
        "genre": genre,
        "author": candidate.author,
        "collector": curated.get("collector") or f"корпус {source_file}; збирач не зазначений",
        "year": curated.get("year") or _year_label(corpus),
        "period": curated.get("period") or _period_label(corpus),
        "tracks": [],
        "excerpt": curated.get("excerpt") or _fallback_excerpt(candidate, corpus),
        "source": curated.get("source") or (
            f"{candidate.author}; корпус {source_file}. Текст у суспільному надбанні; "
            "подано дослівно за корпусним записом."
        ),
        "public_domain": True,
        "order": curated.get("order") or _default_order(slug),
        **({"intro": curated["intro"]} if curated.get("intro") else {}),
    }
    if resolved.taught_in:
        metadata["taught_in"] = list(resolved.taught_in)
    if resolved.source_chunk_ids:
        metadata["source_chunk_ids"] = list(resolved.source_chunk_ids)
    return metadata


def _frontmatter(metadata: dict[str, Any], tracks: Sequence[str]) -> list[str]:
    ordered_keys = [
        "title",
        "title_en",
        "genre",
        "author",
        "collector",
        "year",
        "period",
        "tracks",
        "taught_in",
        "source_chunk_ids",
        "excerpt",
        "source",
        "public_domain",
        "order",
    ]
    lines = ["---"]
    for key in ordered_keys:
        if key == "tracks":
            lines.append(f"tracks: [{', '.join(_yaml_quote(track) for track in tracks)}]")
            continue
        if key not in metadata:
            continue
        value = metadata[key]
        if key == "public_domain":
            lines.append("public_domain: true")
        elif isinstance(value, (list, tuple)):
            lines.append(f"{key}: [{', '.join(_yaml_quote(str(item)) for item in value)}]")
        elif isinstance(value, int):
            lines.append(f"{key}: {value}")
        else:
            lines.append(f"{key}: {_yaml_quote(str(value))}")
    lines.append("---")
    return lines


def _display_text(raw_text: str, candidate_title: str) -> str:
    lines = raw_text.replace("\r\n", "\n").replace("\r", "\n").splitlines()
    while lines and not lines[0].strip():
        lines.pop(0)
    if lines and _looks_like_title_line(lines[0], candidate_title):
        lines.pop(0)
        while lines and not lines[0].strip():
            lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def _looks_like_title_line(line: str, candidate_title: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if _text_key(stripped) == _text_key(candidate_title):
        return True
    has_letters = any(char.isalpha() for char in stripped)
    return has_letters and stripped.upper() == stripped


def _blockquote(text: str) -> str:
    return "\n".join(f"> {line}" if line else ">" for line in text.splitlines())


def _study_links(module_dirs: Sequence[Path]) -> str:
    links = []
    for module_dir in sorted(module_dirs):
        title = _module_title(module_dir)
        track_label = _track_label(module_dir.parent.name)
        links.append(f"[{track_label} · «{title}»](/{module_dir.parent.name}/{module_dir.name}/)")
    return "; ".join(links)


def _study_links_from_taught_by(taught_by: Sequence[dict[str, Any]], plans_dir: Path) -> str:
    links: list[str] = []
    seen: set[tuple[str, str]] = set()
    for item in sorted(taught_by, key=lambda entry: (str(entry.get("track") or ""), str(entry.get("slug") or ""))):
        track = str(item.get("track") or "").strip()
        slug = str(item.get("slug") or "").strip()
        if not track or not slug or (track, slug) in seen:
            continue
        seen.add((track, slug))
        title = _plan_title(track, slug, plans_dir)
        links.append(f"[{_track_label(track)} · «{title}»](/{track}/{slug}/)")
    return "; ".join(links)


def _plan_title(track: str, slug: str, plans_dir: Path) -> str:
    plan = plans_dir / track / f"{slug}.yaml"
    if plan.exists():
        raw = yaml.safe_load(plan.read_text(encoding="utf-8")) or {}
        if isinstance(raw, dict) and raw.get("title"):
            return str(raw["title"]).strip()
    return slug.replace("-", " ")


def _track_label(track: str) -> str:
    return "Фольклор" if track == "folk" else track.upper()


def _module_title(module_dir: Path) -> str:
    md = module_dir / "module.md"
    if not md.exists():
        return module_dir.name
    for line in md.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    plan = CURRICULUM_ROOT / "plans" / module_dir.parent.name / f"{module_dir.name}.yaml"
    if plan.exists():
        raw = yaml.safe_load(plan.read_text(encoding="utf-8")) or {}
        if isinstance(raw, dict) and raw.get("title"):
            return str(raw["title"]).strip()
    return module_dir.name.replace("-", " ")


def _wrap_intro(text: str, width: int = 96) -> str:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return "\n".join(lines)


def _genre_prefix(note: str) -> str:
    note_key = _text_key(note)
    if "щедрівка" in note_key:
        return "shchedrivka"
    if "колядка" in note_key:
        return "koliadka"
    if "дума" in note_key:
        return "duma"
    return ""


def _genre_from_note(note: str) -> str:
    note_key = _text_key(note)
    if "щедрівка" in note_key:
        return "Щедрівка"
    if "колядка" in note_key:
        return "Колядка"
    if "дума" in note_key:
        return "Дума"
    return ""


def _genre_from_corpus(genre: str) -> str:
    return {
        "carol": "Календарно-обрядова пісня",
        "duma": "Дума",
        "poem": "Вірш",
        "poetry": "Поезія",
        "novel": "Роман",
    }.get(genre, genre or "Народний текст")


def _year_label(corpus: CorpusText) -> str:
    is_traditional = _text_key(corpus.author) in {"народна творчість", "традиційний текст"}
    if corpus.year is None:
        return "традиційний текст" if is_traditional else "рік не зазначено"
    if is_traditional:
        return f"традиційний текст; корпусна дата {corpus.year}"
    return str(corpus.year)


def _period_label(corpus: CorpusText) -> str:
    return {
        "middle_ukrainian": "Ранньомодерна / традиційна усна культура",
        "modern": "Нова українська література",
    }.get(corpus.language_period, corpus.language_period or "Традиційна усна культура")


def _fallback_excerpt(candidate: PrimaryReadingCandidate, corpus: CorpusText) -> str:
    display = _display_text(corpus.text, candidate.title)
    first = next((line.strip() for line in display.splitlines() if line.strip()), candidate.title)
    return f"{_genre_from_note(candidate.note) or _genre_from_corpus(corpus.genre)}: {first}"


def _default_order(slug: str) -> int:
    return 1000 + sum(ord(char) for char in slug) % 8000


def _yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _text_key(text: str) -> str:
    normalized = unicodedata.normalize("NFC", text).casefold()
    normalized = _STRESS_RE.sub("", normalized)
    normalized = normalized.replace("’", "'").replace("ʼ", "'")
    normalized = _NON_WORD_RE.sub(" ", normalized)
    return re.sub(r"\s+", " ", normalized).strip()


def _line_key(line: str) -> str:
    return _text_key(re.sub(r"\s+\d+$", "", line.strip()))


def _block_key(text: str) -> str:
    return _text_key(re.sub(r"\b\d+\b", " ", text))


def _display_path(path: Path, project_root: Path) -> str:
    try:
        return path.resolve().relative_to(project_root).as_posix()
    except ValueError:
        return path.as_posix()


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BrokenPipeError:
        raise SystemExit(0) from None
