#!/usr/bin/env python3
"""Generate Хрестоматія reading MDX files from folk primary-reading blocks.

The generator is deliberately conservative: it only writes a reading when a
folk module contains a structured ``:::primary-reading`` block, the quoted
fragment can be matched to a public-domain literary corpus row, and the output
slug is not already occupied by a hand-authored reading.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
import unicodedata
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.etymology.transliterate import transliterate

CURRICULUM_ROOT = PROJECT_ROOT / "curriculum" / "l2-uk-en"
FOLK_ROOT = CURRICULUM_ROOT / "folk"
READINGS_ROOT = PROJECT_ROOT / "site" / "src" / "content" / "readings"
SOURCES_DB = PROJECT_ROOT / "data" / "sources.db"
GENERATED_MARKER = "AUTO-GENERATED by scripts/readings/generate_readings.py"

_PRIMARY_BLOCK_RE = re.compile(r":::primary-reading\s*\n(?P<body>.*?)\n:::\s*", re.DOTALL)
_ATTRIBUTION_RE = re.compile(
    r"^—\s*(?P<author>[^,\n]+),\s*«(?P<title>[^»]+)»(?:\s*\((?P<note>[^)\n]+)\))?",
    re.MULTILINE,
)
_STRESS_RE = re.compile("[\u0300\u0301]")
_NON_WORD_RE = re.compile(r"[^\w]+", re.UNICODE)


@dataclass(frozen=True)
class ResourceHint:
    title: str
    source_ref: str
    role: str
    notes: str
    packet_chunk_id: str | None


@dataclass(frozen=True)
class PrimaryReadingCandidate:
    module_dir: Path
    track: str
    slug: str
    author: str
    title: str
    note: str
    quote_lines: tuple[str, ...]

    @property
    def work_key(self) -> str:
        return f"{_text_key(self.author)}::{_text_key(self.title)}"


@dataclass(frozen=True)
class CorpusText:
    chunk_id: str
    author: str
    work: str
    work_id: str
    year: int | None
    genre: str
    language_period: str
    source_file: str
    source_url: str
    text: str


@dataclass(frozen=True)
class VerificationResult:
    matched: bool
    confidence: float
    detail: str


@dataclass
class ResolvedReading:
    candidate: PrimaryReadingCandidate
    corpus: CorpusText
    slug: str
    module_dirs: list[Path] = field(default_factory=list)
    tracks: set[str] = field(default_factory=set)


@dataclass(frozen=True)
class WrittenReading:
    slug: str
    path: Path
    action: str
    source_chunk_id: str


@dataclass(frozen=True)
class SkippedReading:
    title: str
    slug: str | None
    reason: str


@dataclass(frozen=True)
class GenerationSummary:
    written: tuple[WrittenReading, ...]
    skipped: tuple[SkippedReading, ...]
    existing: tuple[WrittenReading, ...]

    @property
    def generated_count(self) -> int:
        return sum(1 for item in self.written if item.action == "created")


QuoteVerifier = Callable[[PrimaryReadingCandidate, CorpusText], VerificationResult]


CURATED_METADATA: dict[str, dict[str, Any]] = {
    "koliadka-yak-shche-ne-bulo": {
        "title": "«Як ще не було початку світа» (космогонічна колядка)",
        "title_en": "\"When the world had no beginning\" (cosmogonic carol)",
        "genre": "Колядка",
        "order": 20,
    },
    "duma-marusia-bohuslavka": {
        "title": "Дума про Марусю Богуславку",
        "title_en": "The Duma of Marusia Bohuslavka",
        "genre": "Дума",
        "order": 10,
    },
    "shchedrivka-oi-syvaia-ta-i-zozulechka": {
        "title": "«Ой сивая та і зозулечка» (щедрівка з тріадою світил)",
        "title_en": "\"Oh, the grey cuckoo\" (shchedrivka with a triad of lights)",
        "genre": "Щедрівка",
        "collector": "корпус ukrlib-narod-dumy; збирач не зазначений",
        "year": "традиційний текст; корпусна дата 1600",
        "period": "Зимова календарна обрядовість",
        "excerpt": (
            "Щедрівка з образом саду й трьох теремів: місяць відповідає "
            "господареві, сонце — господині, а дрібні зірки — дітям."
        ),
        "source": (
            "Народна творчість; корпус ukrlib-narod-dumy. Текст у суспільному "
            "надбанні; подано дослівно за корпусним записом — архаїчні й "
            "діалектні форми збережено."
        ),
        "intro": (
            "Це **повний текст** щедрівки «Ой сивая та і зозулечка», яку "
            "розбирають у модулі {links}. Тут збережено корпусний запис із "
            "рефреном і приміткою до його повторення."
        ),
        "order": 30,
    },
}

SLUG_ALIASES: dict[str, str] = {
    "народна творчість::як ще не було початку світа": "koliadka-yak-shche-ne-bulo",
    "народна творчість::дума про марусю богуславку": "duma-marusia-bohuslavka",
    "народна творчість::ой сивая та і зозулечка": "shchedrivka-oi-syvaia-ta-i-zozulechka",
    "народна творчість::ой сивая та і зозуленька": "shchedrivka-oi-syvaia-ta-i-zozulechka",
}


def parse_primary_readings(module_dir: Path) -> list[PrimaryReadingCandidate]:
    """Extract structured primary-reading blocks from a module."""
    module_path = module_dir / "module.md"
    if not module_path.exists():
        return []
    text = module_path.read_text(encoding="utf-8")
    candidates: list[PrimaryReadingCandidate] = []
    for block_match in _PRIMARY_BLOCK_RE.finditer(text):
        block = block_match.group("body")
        attr = _ATTRIBUTION_RE.search(block)
        if attr is None:
            continue
        quote_lines = tuple(_quote_lines(block))
        if not quote_lines:
            continue
        candidates.append(
            PrimaryReadingCandidate(
                module_dir=module_dir,
                track=module_dir.parent.name,
                slug=module_dir.name,
                author=attr.group("author").strip(),
                title=attr.group("title").strip(),
                note=(attr.group("note") or "").strip(),
                quote_lines=quote_lines,
            )
        )
    return candidates


def load_resource_hints(module_dir: Path) -> list[ResourceHint]:
    """Load resource rows that can point a primary block at a corpus chunk."""
    path = module_dir / "resources.yaml"
    if not path.exists():
        return []
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    if not isinstance(raw, list):
        return []
    hints: list[ResourceHint] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        hints.append(
            ResourceHint(
                title=str(item.get("title") or ""),
                source_ref=str(item.get("source_ref") or ""),
                role=str(item.get("role") or ""),
                notes=str(item.get("notes") or ""),
                packet_chunk_id=str(item["packet_chunk_id"]) if item.get("packet_chunk_id") else None,
            )
        )
    return hints


def generate_for_modules(
    module_dirs: Sequence[Path],
    *,
    output_dir: Path = READINGS_ROOT,
    sources_db: Path = SOURCES_DB,
    dry_run: bool = False,
    quote_verifier: QuoteVerifier | None = None,
) -> GenerationSummary:
    """Generate readings for the given folk module directories."""
    verifier = quote_verifier or verify_candidate_against_corpus
    output_dir.mkdir(parents=True, exist_ok=True)
    lookup = CorpusLookup(sources_db)
    resolved_by_slug: dict[str, ResolvedReading] = {}
    skipped: list[SkippedReading] = []

    for module_dir in sorted(Path(path) for path in module_dirs):
        hints = load_resource_hints(module_dir)
        for candidate in _dedupe_candidates(parse_primary_readings(module_dir)):
            slug = reading_slug(candidate)
            corpus = lookup.resolve(candidate, hints)
            if corpus is None:
                skipped.append(SkippedReading(candidate.title, slug, "no matching corpus text"))
                continue
            if not is_public_domain(corpus):
                skipped.append(SkippedReading(candidate.title, slug, "corpus row is not public-domain"))
                continue
            verdict = verifier(candidate, corpus)
            if not verdict.matched:
                skipped.append(
                    SkippedReading(
                        candidate.title,
                        slug,
                        f"quote verification failed: {verdict.detail}",
                    )
                )
                continue

            resolved = resolved_by_slug.get(slug)
            if resolved is None:
                resolved_by_slug[slug] = ResolvedReading(
                    candidate=candidate,
                    corpus=corpus,
                    slug=slug,
                    module_dirs=[module_dir],
                    tracks={candidate.track},
                )
            else:
                resolved.module_dirs.append(module_dir)
                resolved.tracks.add(candidate.track)

    written: list[WrittenReading] = []
    existing: list[WrittenReading] = []
    for slug, resolved in sorted(resolved_by_slug.items()):
        path = output_dir / f"{slug}.mdx"
        rendered = render_reading(resolved)
        if path.exists():
            current = path.read_text(encoding="utf-8")
            if GENERATED_MARKER not in current:
                existing.append(WrittenReading(slug, path, "existing-hand-authored", resolved.corpus.chunk_id))
                continue
            if current == rendered:
                existing.append(WrittenReading(slug, path, "unchanged", resolved.corpus.chunk_id))
                continue
            if not dry_run:
                path.write_text(rendered, encoding="utf-8")
            written.append(WrittenReading(slug, path, "updated", resolved.corpus.chunk_id))
            continue

        if not dry_run:
            path.write_text(rendered, encoding="utf-8")
        written.append(WrittenReading(slug, path, "created", resolved.corpus.chunk_id))

    return GenerationSummary(tuple(written), tuple(skipped), tuple(existing))


class CorpusLookup:
    """Resolve primary-reading candidates to literary corpus rows."""

    def __init__(self, db_path: Path) -> None:
        self.db_path = db_path

    def resolve(
        self,
        candidate: PrimaryReadingCandidate,
        hints: Sequence[ResourceHint],
    ) -> CorpusText | None:
        if not self.db_path.exists():
            return None
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            for hint in _matching_hints(candidate, hints):
                if hint.packet_chunk_id:
                    row = conn.execute(
                        """
                        SELECT chunk_id, author, work, work_id, year, genre,
                               language_period, source_file, source_url, text
                        FROM literary_texts
                        WHERE chunk_id = ?
                        """,
                        (hint.packet_chunk_id,),
                    ).fetchone()
                    corpus = _row_to_corpus(row)
                    if corpus and verify_candidate_against_corpus(candidate, corpus).matched:
                        return corpus

            rows = self._candidate_rows(conn, candidate)
            scored = [
                (self._score(candidate, row), _row_to_corpus(row))
                for row in rows
            ]
            for _score, corpus in sorted(scored, key=lambda pair: pair[0], reverse=True):
                if corpus and verify_candidate_against_corpus(candidate, corpus).matched:
                    return corpus
        return None

    def _candidate_rows(
        self,
        conn: sqlite3.Connection,
        candidate: PrimaryReadingCandidate,
    ) -> list[sqlite3.Row]:
        rows: list[sqlite3.Row] = []
        seen: set[str] = set()

        def add(query: str, params: tuple[Any, ...]) -> None:
            for row in conn.execute(query, params).fetchall():
                chunk_id = str(row["chunk_id"])
                if chunk_id in seen:
                    continue
                seen.add(chunk_id)
                rows.append(row)

        select = """
            SELECT chunk_id, author, work, work_id, year, genre,
                   language_period, source_file, source_url, text
            FROM literary_texts
        """
        title_like = f"%{candidate.title}%"
        add(
            f"{select} WHERE author = ? AND (work LIKE ? OR text LIKE ?) LIMIT 25",
            (candidate.author, title_like, title_like),
        )
        first_line = next((line for line in candidate.quote_lines if line.strip()), "")
        if first_line:
            add(
                f"{select} WHERE author = ? AND text LIKE ? LIMIT 25",
                (candidate.author, f"%{first_line.strip()}%"),
            )
        return rows

    @staticmethod
    def _score(candidate: PrimaryReadingCandidate, row: sqlite3.Row) -> int:
        text_key = _block_key(str(row["text"]))
        score = 0
        for line in candidate.quote_lines:
            line_key = _line_key(line)
            if line_key and line_key in text_key:
                score += 10
        if _text_key(candidate.title) and _text_key(candidate.title) in _text_key(str(row["work"])):
            score += 5
        return score


def verify_candidate_against_corpus(
    candidate: PrimaryReadingCandidate,
    corpus: CorpusText,
) -> VerificationResult:
    """Verify that every embedded quote line is attested in the corpus text."""
    text_key = _block_key(corpus.text)
    missing = [
        line for line in candidate.quote_lines
        if _line_key(line) and _line_key(line) not in text_key
    ]
    if missing:
        return VerificationResult(
            matched=False,
            confidence=0.0,
            detail=f"{len(missing)} quoted line(s) missing from {corpus.chunk_id}",
        )
    return VerificationResult(
        matched=True,
        confidence=1.0,
        detail=f"all quoted lines found in {corpus.chunk_id}",
    )


def is_public_domain(corpus: CorpusText) -> bool:
    """Fail closed unless the row has a conservative public-domain signal."""
    if corpus.author == "Народна творчість" and corpus.source_file.startswith("ukrlib-narod"):
        return True
    return corpus.year is not None and corpus.year <= 1928


def reading_slug(candidate: PrimaryReadingCandidate) -> str:
    alias = SLUG_ALIASES.get(candidate.work_key)
    if alias:
        return alias
    prefix = _genre_prefix(candidate.note)
    base = transliterate(candidate.title)
    return f"{prefix}-{base}" if prefix and not base.startswith(prefix) else base


def render_reading(resolved: ResolvedReading) -> str:
    candidate = resolved.candidate
    corpus = resolved.corpus
    metadata = _metadata_for(resolved)
    tracks = sorted(resolved.tracks)
    study_links = _study_links(resolved.module_dirs)
    body_text = _display_text(corpus.text, candidate.title)
    quote = _blockquote(body_text)
    intro_template = metadata.pop("intro", None)
    if intro_template:
        intro = intro_template.format(links=study_links)
    else:
        intro = (
            f"Це **повний текст** твору «{candidate.title}», який розбирають у модулі "
            f"{study_links}. Текст подано за корпусним записом без редакторського "
            "осучаснення рядків."
        )

    lines = [
        *(_frontmatter(metadata, tracks)),
        "",
        "import PrimaryReading from '@site/src/components/PrimaryReading';",
        "",
        _wrap_intro(intro),
        "",
        "<PrimaryReading>",
        "",
        quote,
        "",
        "</PrimaryReading>",
        "",
        f"**Джерело:** {metadata['source']}",
        "",
        f"**Де вивчають:** {study_links}",
        "",
        f"{{/* {GENERATED_MARKER}; source_chunk_id: {corpus.chunk_id} */}}",
        "",
    ]
    return "\n".join(lines)


def discover_folk_module_dirs(root: Path = FOLK_ROOT) -> list[Path]:
    """Return certified-looking folk module directories in deterministic order."""
    return sorted(path for path in root.iterdir() if (path / "module.md").exists())


def format_summary(summary: GenerationSummary, *, project_root: Path = PROJECT_ROOT) -> str:
    lines = [
        "Readings generation summary",
        f"Written: {len(summary.written)}",
        f"Existing/skipped because present: {len(summary.existing)}",
        f"Skipped: {len(summary.skipped)}",
    ]
    for item in summary.written:
        lines.append(
            f"- {item.action}: {_display_path(item.path, project_root)} "
            f"(chunk {item.source_chunk_id})"
        )
    for item in summary.existing:
        lines.append(
            f"- {item.action}: {_display_path(item.path, project_root)} "
            f"(chunk {item.source_chunk_id})"
        )
    for item in summary.skipped:
        suffix = f" [{item.slug}]" if item.slug else ""
        lines.append(f"- skipped{suffix}: {item.title} — {item.reason}")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("module_dirs", nargs="*", type=Path, help="Folk module directories to scan")
    parser.add_argument("--all-folk", action="store_true", help="Scan all built folk modules")
    parser.add_argument("--output-dir", type=Path, default=READINGS_ROOT)
    parser.add_argument("--sources-db", type=Path, default=SOURCES_DB)
    parser.add_argument("--dry-run", action="store_true", help="Report writes without changing files")
    parser.add_argument("--json", action="store_true", help="Print machine-readable summary")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    module_dirs = discover_folk_module_dirs() if args.all_folk else args.module_dirs
    if not module_dirs:
        parser.error("pass one or more module dirs, or --all-folk")

    summary = generate_for_modules(
        module_dirs,
        output_dir=args.output_dir,
        sources_db=args.sources_db,
        dry_run=args.dry_run,
    )
    if args.json:
        print(
            json.dumps(
                {
                    "written": [item.__dict__ | {"path": item.path.as_posix()} for item in summary.written],
                    "existing": [item.__dict__ | {"path": item.path.as_posix()} for item in summary.existing],
                    "skipped": [item.__dict__ for item in summary.skipped],
                },
                ensure_ascii=False,
                indent=2,
            )
        )
    else:
        print(format_summary(summary))
    return 0


def _dedupe_candidates(candidates: Sequence[PrimaryReadingCandidate]) -> list[PrimaryReadingCandidate]:
    by_key: dict[str, PrimaryReadingCandidate] = {}
    for candidate in candidates:
        existing = by_key.get(candidate.work_key)
        if existing is None or len(candidate.quote_lines) > len(existing.quote_lines):
            by_key[candidate.work_key] = candidate
    return list(by_key.values())


def _quote_lines(block: str) -> Iterable[str]:
    for raw_line in block.splitlines():
        if not raw_line.startswith(">"):
            continue
        line = raw_line[1:]
        if line.startswith(" "):
            line = line[1:]
        yield line.rstrip()


def _matching_hints(
    candidate: PrimaryReadingCandidate,
    hints: Sequence[ResourceHint],
) -> Iterable[ResourceHint]:
    title_key = _text_key(candidate.title)
    for hint in hints:
        haystack = _text_key(" ".join([hint.title, hint.source_ref, hint.notes]))
        if title_key and title_key in haystack:
            yield hint


def _row_to_corpus(row: sqlite3.Row | None) -> CorpusText | None:
    if row is None:
        return None
    year_raw = row["year"]
    try:
        year = int(year_raw) if year_raw is not None else None
    except (TypeError, ValueError):
        year = None
    return CorpusText(
        chunk_id=str(row["chunk_id"]),
        author=str(row["author"] or ""),
        work=str(row["work"] or ""),
        work_id=str(row["work_id"] or ""),
        year=year,
        genre=str(row["genre"] or ""),
        language_period=str(row["language_period"] or ""),
        source_file=str(row["source_file"] or ""),
        source_url=str(row["source_url"] or ""),
        text=str(row["text"] or ""),
    )


def _metadata_for(resolved: ResolvedReading) -> dict[str, Any]:
    candidate = resolved.candidate
    corpus = resolved.corpus
    slug = resolved.slug
    curated = dict(CURATED_METADATA.get(slug, {}))
    genre = curated.get("genre") or _genre_from_note(candidate.note) or _genre_from_corpus(corpus.genre)
    source_file = corpus.source_file or "corpus"
    return {
        "title": curated.get("title") or f"«{candidate.title}»" + (f" ({candidate.note})" if candidate.note else ""),
        **({"title_en": curated["title_en"]} if curated.get("title_en") else {}),
        "genre": genre,
        "author": candidate.author,
        "collector": curated.get("collector") or f"корпус {source_file}; збирач не зазначений",
        "year": curated.get("year") or _year_label(corpus),
        "period": curated.get("period") or _period_label(corpus),
        "tracks": [],
        "excerpt": curated.get("excerpt") or _fallback_excerpt(candidate, corpus),
        "source": curated.get("source") or (
            f"{candidate.author}; корпус {source_file}. Текст у суспільному надбанні; "
            "подано дослівно за корпусним записом."
        ),
        "public_domain": True,
        "order": curated.get("order") or _default_order(slug),
        **({"intro": curated["intro"]} if curated.get("intro") else {}),
    }


def _frontmatter(metadata: dict[str, Any], tracks: Sequence[str]) -> list[str]:
    ordered_keys = [
        "title",
        "title_en",
        "genre",
        "author",
        "collector",
        "year",
        "period",
        "tracks",
        "excerpt",
        "source",
        "public_domain",
        "order",
    ]
    lines = ["---"]
    for key in ordered_keys:
        if key == "tracks":
            lines.append(f"tracks: [{', '.join(_yaml_quote(track) for track in tracks)}]")
            continue
        if key not in metadata:
            continue
        value = metadata[key]
        if key == "public_domain":
            lines.append("public_domain: true")
        elif isinstance(value, int):
            lines.append(f"{key}: {value}")
        else:
            lines.append(f"{key}: {_yaml_quote(str(value))}")
    lines.append("---")
    return lines


def _display_text(raw_text: str, candidate_title: str) -> str:
    lines = raw_text.replace("\r\n", "\n").replace("\r", "\n").splitlines()
    while lines and not lines[0].strip():
        lines.pop(0)
    if lines and _looks_like_title_line(lines[0], candidate_title):
        lines.pop(0)
        while lines and not lines[0].strip():
            lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def _looks_like_title_line(line: str, candidate_title: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if _text_key(stripped) == _text_key(candidate_title):
        return True
    has_letters = any(char.isalpha() for char in stripped)
    return has_letters and stripped.upper() == stripped


def _blockquote(text: str) -> str:
    return "\n".join(f"> {line}" if line else ">" for line in text.splitlines())


def _study_links(module_dirs: Sequence[Path]) -> str:
    links = []
    for module_dir in sorted(module_dirs):
        title = _module_title(module_dir)
        track_label = "Фольклор" if module_dir.parent.name == "folk" else module_dir.parent.name.upper()
        links.append(f"[{track_label} · «{title}»](/{module_dir.parent.name}/{module_dir.name}/)")
    return "; ".join(links)


def _module_title(module_dir: Path) -> str:
    md = module_dir / "module.md"
    if not md.exists():
        return module_dir.name
    for line in md.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    plan = CURRICULUM_ROOT / "plans" / module_dir.parent.name / f"{module_dir.name}.yaml"
    if plan.exists():
        raw = yaml.safe_load(plan.read_text(encoding="utf-8")) or {}
        if isinstance(raw, dict) and raw.get("title"):
            return str(raw["title"]).strip()
    return module_dir.name.replace("-", " ")


def _wrap_intro(text: str, width: int = 96) -> str:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return "\n".join(lines)


def _genre_prefix(note: str) -> str:
    note_key = _text_key(note)
    if "щедрівка" in note_key:
        return "shchedrivka"
    if "колядка" in note_key:
        return "koliadka"
    if "дума" in note_key:
        return "duma"
    return ""


def _genre_from_note(note: str) -> str:
    note_key = _text_key(note)
    if "щедрівка" in note_key:
        return "Щедрівка"
    if "колядка" in note_key:
        return "Колядка"
    if "дума" in note_key:
        return "Дума"
    return ""


def _genre_from_corpus(genre: str) -> str:
    return {
        "carol": "Календарно-обрядова пісня",
        "duma": "Дума",
    }.get(genre, genre or "Народний текст")


def _year_label(corpus: CorpusText) -> str:
    if corpus.year is None:
        return "традиційний текст"
    return f"традиційний текст; корпусна дата {corpus.year}"


def _period_label(corpus: CorpusText) -> str:
    return {
        "middle_ukrainian": "Ранньомодерна / традиційна усна культура",
        "modern": "Нова українська література",
    }.get(corpus.language_period, corpus.language_period or "Традиційна усна культура")


def _fallback_excerpt(candidate: PrimaryReadingCandidate, corpus: CorpusText) -> str:
    display = _display_text(corpus.text, candidate.title)
    first = next((line.strip() for line in display.splitlines() if line.strip()), candidate.title)
    return f"{_genre_from_note(candidate.note) or 'Народний текст'}: {first}"


def _default_order(slug: str) -> int:
    return 1000 + sum(ord(char) for char in slug) % 8000


def _yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _text_key(text: str) -> str:
    normalized = unicodedata.normalize("NFC", text).casefold()
    normalized = _STRESS_RE.sub("", normalized)
    normalized = normalized.replace("’", "'").replace("ʼ", "'")
    normalized = _NON_WORD_RE.sub(" ", normalized)
    return re.sub(r"\s+", " ", normalized).strip()


def _line_key(line: str) -> str:
    return _text_key(re.sub(r"\s+\d+$", "", line.strip()))


def _block_key(text: str) -> str:
    return _text_key(re.sub(r"\b\d+\b", " ", text))


def _display_path(path: Path, project_root: Path) -> str:
    try:
        return path.resolve().relative_to(project_root).as_posix()
    except ValueError:
        return path.as_posix()


if __name__ == "__main__":
    raise SystemExit(main())
