from collections import Counter

# Extracted from bulk_ocr_gemini.py
MIN_LINES_FOR_REPETITION_CHECK = 10
REPETITION_LINE_THRESHOLD = 5
REPETITION_TAIL_UNIQUE_MAX = 10
REPETITION_TAIL_WINDOW = 30

def is_shadow_repetition(text: str) -> bool:
    """True if output shows Gemini-style generation loop (same line repeated).

    This is the original shadow uniqueness check extracted from bulk_ocr_gemini.py.
    """
    lines = [line.strip() for line in text.splitlines() if len(line.strip()) > 5]
    if len(lines) < MIN_LINES_FOR_REPETITION_CHECK:
        return False

    most_count = Counter(lines).most_common(1)[0][1] if lines else 0
    tail_unique = len(set(lines[-REPETITION_TAIL_WINDOW:])) if lines else 0
    return (
        most_count >= REPETITION_LINE_THRESHOLD
        and tail_unique < REPETITION_TAIL_UNIQUE_MAX
    )

def has_substring_repetition(text: str, window: int = 15, threshold: int = 4) -> bool:
    """Detect repetition-loop in short files (<100 lines).

    Returns True if any window-char substring appears threshold+ times.
    Catches single-line cases like
      "**пра́во** ... полаб. *provü*, схв. *пра̏во* ..." × 9
    that the shadow uniqueness check skips due to its guard.

    Used in conjunction with, not as a replacement for, shadow uniqueness.
    """
    if len(text) < window:
        return False

    counts = Counter()
    for i in range(len(text) - window + 1):
        substring = text[i:i+window]
        counts[substring] += 1
        if counts[substring] >= threshold:
            return True

    return False

def is_gemini_hallucination(text: str) -> tuple[bool, str]:
    """Detects hallucination patterns generated by vision-LLM OCR on dense print.

    Returns a tuple of (flagged, reason).
    """
    if is_shadow_repetition(text):
        return True, "shadow uniqueness check failed (large repetition loop)"

    if has_substring_repetition(text):
        return True, "substring repetition check failed (single-line repetition)"

    # Stub for semantic hallucination (fake cognates)
    # This cannot be reliably detected statically and requires RAG verification against ESUM
    # See docs/bug-autopsies/gemini-ocr-hallucinations.md for details.

    return False, "clean"
