#!/usr/bin/env python3
"""Check ADR hygiene for the learn-ukrainian project.

Sister to ``check_decisions.py``. ADRs live at ``docs/architecture/adr/``;
their process is codified at ``docs/best-practices/adr-management.md``.

Validations:
    - Numbering: sequential, no duplicates, no gaps
    - Required fields: Status, Date, Deciders, Related on each ADR
    - Stale Proposed: any Proposed ADR older than --stale-proposed-days
    - Broken supersede chains: "Superseded by ADR-M" where M doesn't exist,
      or where M doesn't reference N in its Related section
    - Index drift: README.md <!-- ADR-INDEX-START --> block matches reality
    - Orphaned references: code / doc references to ADR-N where N missing

Usage:
    .venv/bin/python scripts/audit/check_adrs.py                # full report
    .venv/bin/python scripts/audit/check_adrs.py --quiet        # one-liner
    .venv/bin/python scripts/audit/check_adrs.py --json         # machine output
    .venv/bin/python scripts/audit/check_adrs.py --rebuild-index  # fix index
    .venv/bin/python scripts/audit/check_adrs.py --check-promotions

Exit codes:
    0 = clean
    1 = warnings (stale Proposed, index drift — advisory)
    2 = errors (broken chain, missing field, numbering gap — block CI)

Related:
    - docs/best-practices/adr-management.md (process doc)
    - docs/architecture/adr/README.md (index — regenerated by --rebuild-index)
    - scripts/audit/check_decisions.py (sister tool for the decision journal)
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
ADR_DIR = PROJECT_ROOT / "docs" / "architecture" / "adr"
README_PATH = ADR_DIR / "README.md"
DECISIONS_YAML = PROJECT_ROOT / "docs" / "decisions" / "decisions.yaml"

ADR_FILENAME_RE = re.compile(r"^adr-(\d{3})-(.+)\.md$")
# Accept any of `:`, `—`, `-`, `.` as the heading separator — historical
# ADRs in this repo use different formats. New ADRs should follow the
# template (colon), but don't reject existing work over typography.
ADR_HEADING_RE = re.compile(r"^#\s+ADR-(\d+)\s*[:—–\-\.]\s+(.+)$", re.MULTILINE)
# Status may be a plain bold line OR a blockquote-wrapped bold line, and
# the colon may be inside or outside the bold. All of these show up in
# real ADRs in this repo.
STATUS_LINE_RE = re.compile(
    r"^\s*(?:>\s*)?\*\*Status(?:\*\*:|:\*\*)\s*(.+?)\s*$",
    re.MULTILINE,
)
DATE_LINE_RE = re.compile(
    r"^\s*(?:>\s*)?\*\*Date(?:\*\*:|:\*\*)\s*(.+?)\s*$",
    re.MULTILINE,
)
DECIDERS_LINE_RE = re.compile(
    r"^\s*(?:>\s*)?\*\*Deciders(?:\*\*:|:\*\*)\s*(.+?)\s*$",
    re.MULTILINE,
)
RELATED_LINE_RE = re.compile(
    r"^\s*(?:>\s*)?\*\*Related(?:\*\*:|:\*\*)",
    re.MULTILINE,
)
# "Proposed" is the template word; "DRAFT" is what earlier ADRs used.
# Treat both as the same lifecycle stage.
PROPOSED_RE = re.compile(r"(?:proposed|draft)", re.IGNORECASE)
SUPERSEDED_RE = re.compile(r"Superseded by ADR-(\d+)", re.IGNORECASE)

# Directories that DO get scanned for orphaned "ADR-N" references. We
# deliberately exclude docs/session-state/ because session handoffs are
# historical snapshots; referencing a proposed-but-unfiled ADR in a
# dated handoff is legitimate (records the proposal at the time). We
# also exclude docs/bug-autopsies/ for the same reason — historical.
ORPHAN_REF_SCOPES: tuple[str, ...] = (
    "scripts",
    "docs/best-practices",
    "docs/architecture",
    "curriculum",
    "claude_extensions",
)

INDEX_START = "<!-- ADR-INDEX-START"
INDEX_END = "<!-- ADR-INDEX-END -->"

STALE_PROPOSED_DAYS_DEFAULT = 14
PROMOTION_CANDIDATE_DAYS_DEFAULT = 180


@dataclass
class AdrRecord:
    """One parsed ADR file."""

    number: int
    filename: str
    title: str
    status: str
    date_str: str
    has_deciders: bool
    has_related: bool
    superseded_by: int | None  # the N in "Superseded by ADR-N"
    path: Path

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": f"ADR-{self.number:03d}",
            "number": self.number,
            "title": self.title,
            "status": self.status,
            "date": self.date_str,
            "filename": self.filename,
            "superseded_by": (
                f"ADR-{self.superseded_by:03d}" if self.superseded_by else None
            ),
        }


@dataclass
class CheckResult:
    """Aggregated findings."""

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    adrs: list[AdrRecord] = field(default_factory=list)
    promotion_candidates: list[dict[str, Any]] = field(default_factory=list)

    @property
    def exit_code(self) -> int:
        if self.errors:
            return 2
        if self.warnings:
            return 1
        return 0


def _parse_adr(path: Path) -> AdrRecord | None:
    """Parse one ADR file; return None if it's not a valid ADR (e.g. template)."""
    content = path.read_text("utf-8")

    filename_match = ADR_FILENAME_RE.match(path.name)
    if not filename_match:
        return None

    filename_number = int(filename_match.group(1))

    heading_match = ADR_HEADING_RE.search(content)
    if not heading_match:
        return None

    heading_number = int(heading_match.group(1))
    title = heading_match.group(2).strip()

    status_match = STATUS_LINE_RE.search(content)
    date_match = DATE_LINE_RE.search(content)
    deciders_match = DECIDERS_LINE_RE.search(content)
    related_match = RELATED_LINE_RE.search(content)

    status = status_match.group(1).strip() if status_match else ""
    date_str = date_match.group(1).strip() if date_match else ""

    superseded_by = None
    sup_match = SUPERSEDED_RE.search(status)
    if sup_match:
        superseded_by = int(sup_match.group(1))

    # Filename and heading number must match (sanity check)
    if filename_number != heading_number:
        # Treat as a parse failure — caller records an error
        return AdrRecord(
            number=filename_number,
            filename=path.name,
            title=f"[heading mismatch: file={filename_number} heading={heading_number}] {title}",
            status=status,
            date_str=date_str,
            has_deciders=bool(deciders_match),
            has_related=bool(related_match),
            superseded_by=superseded_by,
            path=path,
        )

    return AdrRecord(
        number=filename_number,
        filename=path.name,
        title=title,
        status=status,
        date_str=date_str,
        has_deciders=bool(deciders_match),
        has_related=bool(related_match),
        superseded_by=superseded_by,
        path=path,
    )


def _load_adrs() -> list[AdrRecord]:
    """Load all ADR records from docs/architecture/adr/."""
    records: list[AdrRecord] = []
    if not ADR_DIR.exists():
        return records

    for path in sorted(ADR_DIR.glob("adr-*.md")):
        if path.name == "adr-template.md":
            continue
        record = _parse_adr(path)
        if record is not None:
            records.append(record)

    return sorted(records, key=lambda r: r.number)


def _check_numbering(records: list[AdrRecord], result: CheckResult) -> None:
    """Flag gaps, duplicates, and non-sequential numbering."""
    if not records:
        return

    seen: dict[int, str] = {}
    for rec in records:
        if rec.number in seen:
            result.errors.append(
                f"ADR-{rec.number:03d}: duplicate — {seen[rec.number]} and {rec.filename}"
            )
            continue
        seen[rec.number] = rec.filename

    numbers = sorted(seen.keys())
    expected = list(range(numbers[0], numbers[-1] + 1))
    missing = [n for n in expected if n not in numbers]
    if missing:
        result.warnings.append(
            f"ADR numbering gap(s): missing {', '.join(f'ADR-{n:03d}' for n in missing)}. "
            f"Acceptable only if the number was drafted and rejected pre-merge."
        )


def _check_required_fields(records: list[AdrRecord], result: CheckResult) -> None:
    """Every ADR needs Status, Date, and Related. Deciders is recommended
    (historical ADRs pre-date the convention; don't break CI over it)."""
    for rec in records:
        hard_missing = []
        soft_missing = []
        if not rec.status:
            hard_missing.append("Status")
        if not rec.date_str:
            hard_missing.append("Date")
        if not rec.has_related:
            hard_missing.append("Related")
        if not rec.has_deciders:
            # Deciders is REQUIRED per the template for new ADRs but ADRs
            # 001-006 predate the convention. Warn, don't error.
            soft_missing.append("Deciders")
        if hard_missing:
            result.errors.append(
                f"{rec.filename}: missing required field(s): {', '.join(hard_missing)}"
            )
        if soft_missing:
            result.warnings.append(
                f"{rec.filename}: missing recommended field(s): {', '.join(soft_missing)}. "
                f"Acceptable on ADRs predating the template convention; required on new ADRs."
            )


def _check_stale_proposed(
    records: list[AdrRecord], result: CheckResult, days: int
) -> None:
    """Proposed ADRs older than `days` are stale."""
    today = date.today()
    for rec in records:
        if not PROPOSED_RE.search(rec.status):
            continue
        try:
            adr_date = datetime.strptime(rec.date_str, "%Y-%m-%d").date()
        except ValueError:
            continue
        age = (today - adr_date).days
        if age > days:
            result.warnings.append(
                f"{rec.filename}: in Proposed/DRAFT status for {age} days "
                f"(stale after {days}). Finalize to Accepted or explicitly close out."
            )


def _check_supersede_chains(records: list[AdrRecord], result: CheckResult) -> None:
    """If ADR-N says "Superseded by ADR-M", ADR-M must exist and reference N."""
    by_number = {rec.number: rec for rec in records}

    for rec in records:
        if rec.superseded_by is None:
            continue
        m = rec.superseded_by
        if m not in by_number:
            result.errors.append(
                f"{rec.filename}: claims supersede by ADR-{m:03d} but that ADR does not exist"
            )
            continue
        new_rec = by_number[m]
        new_content = new_rec.path.read_text("utf-8")
        # The new ADR should mention ADR-N somewhere in its header / related block
        if f"ADR-{rec.number:03d}" not in new_content and f"ADR-{rec.number}" not in new_content:
            result.errors.append(
                f"{new_rec.filename}: supersedes ADR-{rec.number:03d} but doesn't reference it back"
            )


def _build_index_block(records: list[AdrRecord]) -> str:
    """Produce the README table between the sentinel comments."""
    header = "| ID  | Title | Status |\n|-----|-------|--------|"
    rows = []
    for rec in records:
        rows.append(
            f"| [ADR-{rec.number:03d}]({rec.filename}) | {rec.title} | {rec.status} |"
        )
    body = "\n".join([header, *rows])
    return (
        f"{INDEX_START} — do not hand-edit. Regenerated by "
        f"scripts/audit/check_adrs.py --rebuild-index -->\n"
        f"{body}\n"
        f"{INDEX_END}"
    )


def _check_index_drift(records: list[AdrRecord], result: CheckResult) -> None:
    """README.md index block should match reality."""
    if not README_PATH.exists():
        result.warnings.append(f"{README_PATH.relative_to(PROJECT_ROOT)} missing")
        return

    readme = README_PATH.read_text("utf-8")
    expected = _build_index_block(records)

    # Find the existing block
    start = readme.find(INDEX_START)
    end = readme.find(INDEX_END)
    if start < 0 or end < 0:
        result.warnings.append(
            f"{README_PATH.name} is missing the ADR-INDEX sentinels; "
            f"run --rebuild-index to insert them."
        )
        return

    current = readme[start : end + len(INDEX_END)]
    if current.strip() != expected.strip():
        result.warnings.append(
            f"{README_PATH.name} index drift — run "
            f"`scripts/audit/check_adrs.py --rebuild-index` to regenerate"
        )


def _rebuild_index(records: list[AdrRecord]) -> bool:
    """Regenerate the README.md index block in place. Returns True if changed."""
    if not README_PATH.exists():
        return False

    readme = README_PATH.read_text("utf-8")
    start = readme.find(INDEX_START)
    end = readme.find(INDEX_END)
    if start < 0 or end < 0:
        return False

    new_block = _build_index_block(records)
    before = readme[:start]
    after = readme[end + len(INDEX_END) :]
    new_readme = before + new_block + after
    if new_readme == readme:
        return False
    README_PATH.write_text(new_readme, "utf-8")
    return True


def _check_orphaned_refs(records: list[AdrRecord], result: CheckResult) -> None:
    """Grep the repo for ADR-N references; flag any N that doesn't exist."""
    existing = {rec.number for rec in records}
    ref_re = re.compile(r"ADR-(\d+)")

    # Scoped to ORPHAN_REF_SCOPES — session-state and bug-autopsies are
    # historical snapshots that legitimately reference proposed-but-
    # unfiled ADRs (the proposal record itself).
    orphaned: dict[int, list[str]] = {}

    for top in ORPHAN_REF_SCOPES:
        top_path = PROJECT_ROOT / top
        if not top_path.exists():
            continue
        try:
            grep = subprocess.run(
                ["git", "grep", "-n", "-E", "ADR-[0-9]+", top],
                capture_output=True,
                text=True,
                cwd=PROJECT_ROOT,
                timeout=30,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return

        for line in grep.stdout.splitlines():
            for match in ref_re.findall(line):
                n = int(match)
                if n not in existing:
                    orphaned.setdefault(n, []).append(line[:120])

    for n, hits in sorted(orphaned.items()):
        result.warnings.append(
            f"Orphaned reference to ADR-{n:03d} (doesn't exist) — "
            f"first hit: {hits[0]}"
        )


def _check_promotions(result: CheckResult, promotion_days: int) -> None:
    """Decisions active beyond `promotion_days` are ADR promotion candidates."""
    if not DECISIONS_YAML.exists():
        return

    try:
        import yaml
    except ImportError:  # pragma: no cover
        return

    payload = yaml.safe_load(DECISIONS_YAML.read_text("utf-8")) or {}
    decisions = payload.get("decisions") or []
    today = date.today()

    for dec in decisions:
        if dec.get("status") != "active":
            continue
        date_str = dec.get("date")
        if not date_str:
            continue
        try:
            dec_date = datetime.strptime(str(date_str).strip('"'), "%Y-%m-%d").date()
        except ValueError:
            continue
        age = (today - dec_date).days
        if age >= promotion_days:
            result.promotion_candidates.append(
                {
                    "id": dec.get("id"),
                    "title": dec.get("title"),
                    "age_days": age,
                    "scope": dec.get("scope"),
                }
            )


def run_check(
    *,
    stale_proposed_days: int = STALE_PROPOSED_DAYS_DEFAULT,
    promotion_days: int = PROMOTION_CANDIDATE_DAYS_DEFAULT,
    check_promotions_flag: bool = False,
) -> CheckResult:
    """Run all checks and return aggregated findings."""
    result = CheckResult()
    result.adrs = _load_adrs()

    if not result.adrs:
        result.warnings.append(
            f"No ADRs found at {ADR_DIR.relative_to(PROJECT_ROOT)}"
        )
        return result

    _check_numbering(result.adrs, result)
    _check_required_fields(result.adrs, result)
    _check_stale_proposed(result.adrs, result, stale_proposed_days)
    _check_supersede_chains(result.adrs, result)
    _check_index_drift(result.adrs, result)
    _check_orphaned_refs(result.adrs, result)

    if check_promotions_flag:
        _check_promotions(result, promotion_days)

    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate ADRs at docs/architecture/adr/: numbering, "
        "required fields, stale Proposed, supersede chains, index drift, "
        "orphaned references.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  .venv/bin/python scripts/audit/check_adrs.py\n"
            "  .venv/bin/python scripts/audit/check_adrs.py --quiet\n"
            "  .venv/bin/python scripts/audit/check_adrs.py --json\n"
            "  .venv/bin/python scripts/audit/check_adrs.py --rebuild-index\n"
            "  .venv/bin/python scripts/audit/check_adrs.py --check-promotions\n\n"
            "Outputs: stderr report OR stdout JSON depending on --json. "
            "--rebuild-index modifies docs/architecture/adr/README.md in place.\n\n"
            "Exit codes: 0 clean, 1 warnings (advisory), 2 errors (block CI).\n\n"
            "Related: docs/best-practices/adr-management.md, "
            "scripts/audit/check_decisions.py (sister tool)."
        ),
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Print one-liner suitable for SessionStart hook INFO array",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Machine-readable output (for Monitor API or programmatic use)",
    )
    parser.add_argument(
        "--rebuild-index",
        action="store_true",
        help="Regenerate the ADR index block in docs/architecture/adr/README.md",
    )
    parser.add_argument(
        "--check-promotions",
        action="store_true",
        help="Flag decision-journal entries old enough to consider ADR promotion",
    )
    parser.add_argument(
        "--stale-proposed-days",
        type=int,
        default=STALE_PROPOSED_DAYS_DEFAULT,
        help=f"Days after which Proposed ADR is stale (default {STALE_PROPOSED_DAYS_DEFAULT})",
    )
    parser.add_argument(
        "--promotion-days",
        type=int,
        default=PROMOTION_CANDIDATE_DAYS_DEFAULT,
        help=(
            f"Age (days) at which an active decision becomes an ADR "
            f"promotion candidate (default {PROMOTION_CANDIDATE_DAYS_DEFAULT})"
        ),
    )
    args = parser.parse_args(argv)

    if args.rebuild_index:
        records = _load_adrs()
        changed = _rebuild_index(records)
        if changed:
            print(f"Rewrote ADR index in {README_PATH.relative_to(PROJECT_ROOT)}")
        else:
            print("ADR index already up to date.")
        return 0

    result = run_check(
        stale_proposed_days=args.stale_proposed_days,
        promotion_days=args.promotion_days,
        check_promotions_flag=args.check_promotions,
    )

    if args.json:
        payload = {
            "total": len(result.adrs),
            "errors": result.errors,
            "warnings": result.warnings,
            "promotion_candidates": result.promotion_candidates,
            "adrs": [r.as_dict() for r in result.adrs],
        }
        print(json.dumps(payload, indent=2))
        return result.exit_code

    if args.quiet:
        parts: list[str] = []
        if result.errors:
            parts.append(f"{len(result.errors)} ADR error(s)")
        if result.warnings:
            parts.append(f"{len(result.warnings)} ADR warning(s)")
        if result.promotion_candidates:
            parts.append(f"{len(result.promotion_candidates)} promotion candidate(s)")
        if parts:
            print("; ".join(parts))
        return result.exit_code

    # Full report to stderr
    if result.errors:
        print("ADR ERRORS:", file=sys.stderr)
        for err in result.errors:
            print(f"  - {err}", file=sys.stderr)
    if result.warnings:
        print("ADR warnings:", file=sys.stderr)
        for warn in result.warnings:
            print(f"  - {warn}", file=sys.stderr)
    if result.promotion_candidates:
        print("Decision → ADR promotion candidates:", file=sys.stderr)
        for cand in result.promotion_candidates:
            print(
                f"  - {cand['id']} ({cand['age_days']}d active): {cand['title']}",
                file=sys.stderr,
            )

    if not result.errors and not result.warnings and not result.promotion_candidates:
        print(f"ADR check: {len(result.adrs)} ADRs — all clean.", file=sys.stderr)

    return result.exit_code


if __name__ == "__main__":
    raise SystemExit(main())
