"""Generate sharded Word Atlas practice decks.

The production deck is generated by the finalizer after the 39 MB manifest and
VESUM database have been hydrated locally. This script is deterministic and can
also run against a small committed fixture with a JSON-backed VESUM verifier.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import random
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

PROJECT_ROOT = Path(__file__).resolve().parents[2]
AUDIT_DIR = PROJECT_ROOT / "scripts" / "audit"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(AUDIT_DIR) not in sys.path:
    sys.path.insert(0, str(AUDIT_DIR))

from lexeme_filter import is_practice_eligible

DEFAULT_MANIFEST = Path("site/src/data/lexicon-manifest.json")
DEFAULT_OUT_DIR = Path("site/src/data")
DEFAULT_ALLOWLIST = Path("site/src/data/lexicon-practice-reviewed-sources.json")
DEFAULT_TARGET = 3000
DEFAULT_RAW_LIMIT = 550_000
DEFAULT_GZIP_LIMIT = 140_000
SCHEMA_VERSION = 1
CEFR_ORDER = ("A1", "A2", "B1", "B2", "C1", "C2")
CEFR_RANK = {level: index for index, level in enumerate(CEFR_ORDER)}
NUMBER_KEYS = ("singular", "plural")

CASE_LABELS_UA = {
    "nominative": "називний",
    "genitive": "родовий",
    "dative": "давальний",
    "accusative": "знахідний",
    "instrumental": "орудний",
    "locative": "місцевий",
    "vocative": "кличний",
}

CASE_VESUM_TAGS = {
    "nominative": "v_naz",
    "genitive": "v_rod",
    "dative": "v_dav",
    "accusative": "v_zna",
    "instrumental": "v_oru",
    "locative": "v_mis",
    "vocative": "v_kly",
}

CASE_RULES = {
    "accusative_direct_object": {
        "case": "accusative",
        "trigger": "direct-object",
        "triggerLabel": "прямий додаток",
        "feedbackTemplate": "бачити/мати/читати + знахідний ({lemma} -> {form})",
    },
    "locative_static_u": {
        "case": "locative",
        "trigger": "у/в (static location)",
        "triggerLabel": "у/в (статична позиція)",
        "feedbackTemplate": "у/в (статична позиція) -> місцевий ({lemma} -> {form})",
    },
    "locative_static_na": {
        "case": "locative",
        "trigger": "на (static location)",
        "triggerLabel": "на (статична позиція)",
        "feedbackTemplate": "на (статична позиція) -> місцевий ({lemma} -> {form})",
    },
}


class VesumVerifier(Protocol):
    """Small injectable interface around scripts.verification.vesum.verify_words."""

    def verify_words(
        self,
        words: list[str],
        pos_filter: str | None = None,
    ) -> dict[str, list[dict[str, Any]]]:
        """Return VESUM matches keyed by submitted word form."""


@dataclass(frozen=True)
class BuildConfig:
    target: int = DEFAULT_TARGET
    raw_limit: int = DEFAULT_RAW_LIMIT
    gzip_limit: int = DEFAULT_GZIP_LIMIT
    fixture_note: str | None = None
    source_label: str = "manifest"


@dataclass(frozen=True)
class ReviewedSourceAllowlist:
    reviewed: frozenset[tuple[str, str]]

    @classmethod
    def from_path(cls, path: Path) -> ReviewedSourceAllowlist:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return cls.from_payload(payload)

    @classmethod
    def from_payload(cls, payload: Any) -> ReviewedSourceAllowlist:
        reviewed: set[tuple[str, str]] = set()
        rows = payload.get("reviewed") if isinstance(payload, dict) else payload
        if not isinstance(rows, list):
            raise ValueError("reviewed allowlist must be a list or an object with reviewed list")
        for row in rows:
            if isinstance(row, str):
                reviewed.add(("reviewed", row))
            elif isinstance(row, dict):
                status = _clean_text(row.get("status")) or "reviewed"
                path = _clean_text(row.get("path"))
                if path:
                    reviewed.add((status, path))
        return cls(frozenset(reviewed))

    def allows(self, provenance: Any) -> bool:
        if not isinstance(provenance, dict):
            return False
        status = _clean_text(provenance.get("status"))
        path = _clean_text(provenance.get("path"))
        if not status or not path:
            return False
        return (status, path) in self.reviewed


class RealVesumVerifier:
    """Runtime adapter for the production VESUM helper."""

    def verify_words(
        self,
        words: list[str],
        pos_filter: str | None = None,
    ) -> dict[str, list[dict[str, Any]]]:
        from scripts.verification.vesum import verify_words

        return verify_words(words, pos_filter=pos_filter)


class JsonVesumVerifier:
    """Fixture verifier used by tests and fixture-only local generation."""

    def __init__(self, payload: dict[str, Any]) -> None:
        self.payload = payload

    @classmethod
    def from_path(cls, path: Path) -> JsonVesumVerifier:
        return cls(json.loads(path.read_text(encoding="utf-8")))

    def verify_words(
        self,
        words: list[str],
        pos_filter: str | None = None,
    ) -> dict[str, list[dict[str, Any]]]:
        result: dict[str, list[dict[str, Any]]] = {}
        for word in words:
            matches = self.payload.get(word, [])
            if not isinstance(matches, list):
                matches = []
            if pos_filter:
                matches = [row for row in matches if isinstance(row, dict) and row.get("pos") == pos_filter]
            result[word] = [row for row in matches if isinstance(row, dict)]
        return result


def _has_text(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _clean_text(value: Any) -> str | None:
    return value.strip() if _has_text(value) else None


def _plain(value: str) -> str:
    return (
        value.casefold()
        .replace("\u0301", "")
        .replace("́", "")
        .replace("’", "'")
        .replace("ʼ", "'")
        .strip()
    )


def _headword(gloss: str) -> str:
    head = gloss.split(";")[0].split(",")[0].strip().casefold()
    return head.split()[0] if head.split() else head


def _stable_lemma_id(entry: dict[str, Any]) -> str:
    slug = _clean_text(entry.get("url_slug")) or _clean_text(entry.get("slug"))
    if slug:
        return slug
    key = "\x1f".join(
        (
            _clean_text(entry.get("lemma")) or "",
            _clean_text(entry.get("gloss")) or "",
            _clean_text(entry.get("pos")) or "",
        )
    )
    return hashlib.sha1(key.encode("utf-8")).hexdigest()[:16]


def _manifest_fingerprint(entries: list[dict[str, Any]]) -> str:
    payload = json.dumps(entries, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def _cefr_level(entry: dict[str, Any]) -> str | None:
    enrichment = entry.get("enrichment")
    if not isinstance(enrichment, dict):
        return None
    cefr = enrichment.get("cefr")
    level = cefr.get("level") if isinstance(cefr, dict) else cefr
    level_text = _clean_text(level)
    return level_text if level_text in CEFR_RANK else None


def _ipa(entry: dict[str, Any]) -> str | None:
    enrichment = entry.get("enrichment")
    if isinstance(enrichment, dict):
        for key in ("ipa", "pronunciation"):
            value = _clean_text(enrichment.get(key))
            if value:
                return value
    return _clean_text(entry.get("ipa"))


def _heritage(entry: dict[str, Any]) -> str | None:
    enrichment = entry.get("enrichment")
    if isinstance(enrichment, dict):
        heritage = enrichment.get("heritage")
        if isinstance(heritage, dict):
            value = _clean_text(heritage.get("classification")) or _clean_text(heritage.get("status"))
            if value:
                return value
        value = _clean_text(heritage)
        if value:
            return value
    status = entry.get("heritage_status")
    if isinstance(status, dict):
        for key in ("classification", "status", "label", "category"):
            value = _clean_text(status.get(key))
            if value:
                return value
    return None


def _severity(entry: dict[str, Any]) -> str | None:
    enrichment = entry.get("enrichment")
    if isinstance(enrichment, dict):
        severity = enrichment.get("severity")
        if isinstance(severity, dict):
            value = _clean_text(severity.get("level")) or _clean_text(severity.get("label"))
            if value:
                return value
        value = _clean_text(severity)
        if value:
            return value
    return _clean_text(entry.get("severity"))


def _paradigm(entry: dict[str, Any]) -> dict[str, Any]:
    enrichment = entry.get("enrichment")
    if not isinstance(enrichment, dict):
        return {"cases": {}}
    morphology = enrichment.get("morphology")
    if not isinstance(morphology, dict):
        return {"cases": {}}
    paradigm = morphology.get("paradigm")
    if not isinstance(paradigm, dict):
        return {"cases": {}}
    cases = paradigm.get("cases")
    if not isinstance(cases, dict):
        return {"cases": {}}
    clean_cases: dict[str, dict[str, str]] = {}
    for case_name, forms in cases.items():
        if not isinstance(case_name, str) or not isinstance(forms, dict):
            continue
        case_key = case_name.strip().casefold()
        clean_forms: dict[str, str] = {}
        for number in NUMBER_KEYS:
            value = _clean_text(forms.get(number))
            if value:
                clean_forms[number] = value
        if clean_forms:
            clean_cases[case_key] = clean_forms
    return {"cases": clean_cases}


def _vesum_pos(pos: str | None) -> str | None:
    if not pos:
        return None
    pos_key = pos.casefold()
    if pos_key in {"noun", "verb", "adj", "adjective", "adv", "adverb"}:
        return {"adjective": "adj", "adverb": "adv"}.get(pos_key, pos_key)
    return pos_key


def _course_usage(entry: dict[str, Any]) -> list[dict[str, Any]]:
    usage = entry.get("course_usage")
    if not isinstance(usage, list):
        return []
    return [item for item in usage if isinstance(item, dict)]


def _course_key(entry: dict[str, Any]) -> tuple[str, str, str]:
    usage = _course_usage(entry)
    first = usage[0] if usage else {}
    return (
        str(first.get("track") or ""),
        str(first.get("slug") or first.get("module") or ""),
        _stable_lemma_id(entry),
    )


def _cloze_sources(entry: dict[str, Any]) -> list[dict[str, Any]]:
    sources: list[dict[str, Any]] = []

    def add(value: Any) -> None:
        if isinstance(value, list):
            sources.extend(row for row in value if isinstance(row, dict))
        elif isinstance(value, dict):
            sources.append(value)

    add(entry.get("cloze"))
    add(entry.get("practice_cloze"))
    practice = entry.get("practice")
    if isinstance(practice, dict):
        add(practice.get("cloze"))
    enrichment = entry.get("enrichment")
    if isinstance(enrichment, dict):
        enrichment_practice = enrichment.get("practice")
        if isinstance(enrichment_practice, dict):
            add(enrichment_practice.get("cloze"))
    for usage in _course_usage(entry):
        add(usage.get("cloze"))
        add(usage.get("practice_cloze"))
    return sources


def _all_paradigm_forms(paradigm: dict[str, Any]) -> list[str]:
    cases = paradigm.get("cases")
    if not isinstance(cases, dict):
        return []
    forms: list[str] = []
    seen: set[str] = set()
    for case_forms in cases.values():
        if not isinstance(case_forms, dict):
            continue
        for number in NUMBER_KEYS:
            value = _clean_text(case_forms.get(number))
            if value and value not in seen:
                seen.add(value)
                forms.append(value)
    return forms


def _match_has_case(match: dict[str, Any], case_name: str) -> bool:
    tag = CASE_VESUM_TAGS.get(case_name)
    tags = str(match.get("tags") or "")
    return bool(tag and tag in tags)


def _verify_paradigm(
    lemma_plain: str,
    pos: str | None,
    paradigm: dict[str, Any],
    verifier: VesumVerifier,
) -> bool:
    forms = _all_paradigm_forms(paradigm)
    if not forms:
        return False
    verified = verifier.verify_words(forms, _vesum_pos(pos))
    for form in forms:
        matches = verified.get(form, [])
        if not matches:
            return False
        if not any(_plain(str(match.get("lemma") or "")) == lemma_plain for match in matches):
            return False
    return True


def _verify_discriminative_form(
    lemma_plain: str,
    pos: str | None,
    form: str,
    case_name: str,
    verifier: VesumVerifier,
) -> bool:
    matches = verifier.verify_words([form], _vesum_pos(pos)).get(form, [])
    if len(matches) != 1:
        return False
    match = matches[0]
    if _plain(str(match.get("lemma") or "")) != lemma_plain:
        return False
    return _match_has_case(match, case_name)


def _case_form(
    paradigm: dict[str, Any],
    case_name: str,
    number: str,
) -> str | None:
    cases = paradigm.get("cases")
    if not isinstance(cases, dict):
        return None
    forms = cases.get(case_name)
    if not isinstance(forms, dict):
        return None
    return _clean_text(forms.get(number))


def _case_rule_payload(rule_id: str, lemma: str, form: str) -> dict[str, str] | None:
    rule = CASE_RULES.get(rule_id)
    if not rule:
        return None
    return {
        "ruleId": rule_id,
        "case": str(rule["case"]),
        "caseLabel": CASE_LABELS_UA[str(rule["case"])],
        "trigger": str(rule["trigger"]),
        "triggerLabel": str(rule["triggerLabel"]),
        "feedback": str(rule["feedbackTemplate"]).format(lemma=lemma, form=form),
    }


def _candidate_sentence_level(candidate: dict[str, Any], fallback: str) -> str:
    level = _clean_text(candidate.get("cefr")) or _clean_text(candidate.get("level")) or fallback
    return level if level in CEFR_RANK else fallback


def _cloze_candidate_ok_for_level(candidate: dict[str, Any], word_level: str) -> bool:
    sentence_level = _candidate_sentence_level(candidate, word_level)
    return CEFR_RANK[sentence_level] <= CEFR_RANK[word_level]


def _pick_decoy(
    answer: dict[str, Any],
    lexemes: list[dict[str, Any]],
    rng: random.Random,
    case_name: str,
) -> tuple[dict[str, Any], str] | None:
    answer_head = _headword(answer["gloss"])
    candidates: list[tuple[dict[str, Any], str]] = []
    for lexeme in lexemes:
        if lexeme["lemmaId"] == answer["lemmaId"]:
            continue
        if lexeme.get("pos") != answer.get("pos"):
            continue
        if _headword(lexeme["gloss"]) == answer_head:
            continue
        forms = lexeme.get("paradigm", {}).get("cases", {})
        if not isinstance(forms, dict):
            continue
        case_forms = forms.get(case_name)
        if not isinstance(case_forms, dict):
            continue
        decoy_form = _clean_text(case_forms.get("singular")) or _clean_text(case_forms.get("plural"))
        if decoy_form and _plain(decoy_form) != _plain(lexeme["lemma"]):
            candidates.append((lexeme, decoy_form))
    if not candidates:
        return None
    return rng.choice(candidates)


def _make_options(
    cloze: dict[str, Any],
    answer: dict[str, Any],
    lexemes: list[dict[str, Any]],
    rng: random.Random,
) -> list[dict[str, str]]:
    decoy = _pick_decoy(answer, lexemes, rng, cloze["blankCase"])
    if decoy is None:
        return []
    decoy_lexeme, decoy_form = decoy
    options = [
        {
            "optionId": f"{cloze['clozeId']}:answer",
            "label": cloze["form"],
            "lemmaId": answer["lemmaId"],
            "kind": "answer",
            "case": cloze["blankCase"],
        },
        {
            "optionId": f"{cloze['clozeId']}:lemma",
            "label": answer["lemma"],
            "lemmaId": answer["lemmaId"],
            "kind": "same-root-lemma",
            "case": "nominative",
        },
        {
            "optionId": f"{cloze['clozeId']}:decoy-lemma",
            "label": decoy_lexeme["lemma"],
            "lemmaId": decoy_lexeme["lemmaId"],
            "kind": "decoy-lemma",
            "case": "nominative",
        },
        {
            "optionId": f"{cloze['clozeId']}:decoy-oblique",
            "label": decoy_form,
            "lemmaId": decoy_lexeme["lemmaId"],
            "kind": "decoy-oblique",
            "case": cloze["blankCase"],
        },
    ]
    rng.shuffle(options)
    return options


def validate_option_set(cloze: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    options = cloze.get("options")
    if not isinstance(options, list) or len(options) < 4:
        return ["option set must contain at least four options"]
    labels = [str(option.get("label") or "") for option in options if isinstance(option, dict)]
    normalized = [_plain(label) for label in labels]
    if len(set(normalized)) != len(normalized):
        errors.append("option labels must be unique after normalization")
    answer_count = sum(1 for label in normalized if label == _plain(str(cloze.get("form") or "")))
    if answer_count != 1:
        errors.append("answer form must be present exactly once")
    oblique_count = sum(
        1
        for option in options
        if isinstance(option, dict)
        and option.get("case") not in {None, "", "nominative"}
        and option.get("kind") != "answer"
    )
    if oblique_count < 1:
        errors.append("option set must contain at least one oblique distractor")
    root_counts: dict[str, int] = {}
    for option in options:
        if not isinstance(option, dict):
            continue
        lemma_id = str(option.get("lemmaId") or "")
        root_counts[lemma_id] = root_counts.get(lemma_id, 0) + 1
    pair_count = sum(1 for count in root_counts.values() if count >= 2)
    if pair_count == 1:
        errors.append("option set must not contain exactly one same-root pair")
    lengths = [len(label) for label in labels]
    if lengths and max(lengths) - min(lengths) > 12:
        errors.append("option label lengths exceed bounded distribution")
    return errors


def _build_lexeme(entry: dict[str, Any], verifier: VesumVerifier) -> dict[str, Any] | None:
    lemma = _clean_text(entry.get("lemma"))
    gloss = _clean_text(entry.get("gloss"))
    level = _cefr_level(entry)
    if not lemma or not gloss or not level:
        return None
    paradigm = _paradigm(entry)
    lemma_plain = _plain(lemma)
    pos = _clean_text(entry.get("pos"))
    if not _verify_paradigm(lemma_plain, pos, paradigm, verifier):
        return None
    return {
        "lemmaId": _stable_lemma_id(entry),
        "lemma": lemma,
        "lemmaPlain": lemma_plain,
        "ipa": _ipa(entry),
        "gloss": gloss,
        "pos": pos,
        "cefr": level,
        "heritage": _heritage(entry),
        "severity": _severity(entry),
        "paradigm": paradigm,
        "semanticBucket": _clean_text(entry.get("semantic_bucket")),
    }


def _build_cloze_items(
    entry: dict[str, Any],
    lexeme: dict[str, Any],
    allowlist: ReviewedSourceAllowlist,
    verifier: VesumVerifier,
    deck_version: str,
) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for index, candidate in enumerate(_cloze_sources(entry)):
        provenance = candidate.get("provenance")
        if not allowlist.allows(provenance):
            continue
        rule_id = _clean_text(candidate.get("caseRuleId")) or _clean_text(candidate.get("ruleId"))
        if not rule_id or rule_id not in CASE_RULES:
            continue
        case_name = str(CASE_RULES[rule_id]["case"])
        candidate_case = _clean_text(candidate.get("blankCase"))
        if candidate_case and candidate_case != case_name:
            continue
        if not _cloze_candidate_ok_for_level(candidate, lexeme["cefr"]):
            continue
        number = _clean_text(candidate.get("number")) or "singular"
        if number not in NUMBER_KEYS:
            continue
        form = _case_form(lexeme["paradigm"], case_name, number)
        if not form or _plain(form) == lexeme["lemmaPlain"]:
            continue
        if not _verify_discriminative_form(
            lexeme["lemmaPlain"],
            lexeme.get("pos"),
            form,
            case_name,
            verifier,
        ):
            continue
        sentence = _clean_text(candidate.get("sentence"))
        cloze_en = _clean_text(candidate.get("clozeEn")) or _clean_text(candidate.get("translation"))
        if not sentence or "___" not in sentence or not cloze_en:
            continue
        frame_key = "\x1f".join((deck_version, lexeme["lemmaId"], sentence, rule_id))
        sentence_frame_id = "sf_" + hashlib.sha1(frame_key.encode("utf-8")).hexdigest()[:12]
        cloze_id = f"{lexeme['lemmaId']}:cloze:{index + 1}"
        case_rule = _case_rule_payload(rule_id, lexeme["lemma"], form)
        if not case_rule:
            continue
        items.append(
            {
                "clozeId": cloze_id,
                "lemmaId": lexeme["lemmaId"],
                "sentenceFrameId": sentence_frame_id,
                "sentence": sentence,
                "blankCase": case_name,
                "form": form,
                "caseRule": case_rule,
                "clozeEn": cloze_en,
                "provenance": {
                    "status": provenance["status"],
                    "path": provenance["path"],
                    "cardId": _clean_text(provenance.get("cardId")),
                },
            }
        )
    return items


def _level_payload(
    schema: str,
    deck_version: str,
    level: str,
    config: BuildConfig,
    body_key: str,
    body_value: Any,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "schema": schema,
        "schemaVersion": SCHEMA_VERSION,
        "deckVersion": deck_version,
        "level": level,
        "source": config.source_label,
    }
    if config.fixture_note:
        payload["fixtureNote"] = config.fixture_note
    payload[body_key] = body_value
    return payload


def build_practice_shards(
    entries: list[dict[str, Any]],
    allowlist: ReviewedSourceAllowlist,
    verifier: VesumVerifier,
    config: BuildConfig | None = None,
) -> dict[str, dict[str, dict[str, Any]]]:
    if config is None:
        config = BuildConfig()
    if config.target < 0:
        raise ValueError("target must be non-negative")
    deck_version = f"atlas-practice-v{SCHEMA_VERSION}-{_manifest_fingerprint(entries)}"
    rng_seed = int(hashlib.sha256(deck_version.encode("utf-8")).hexdigest()[:16], 16)
    rng = random.Random(rng_seed)
    eligible = [entry for entry in entries if is_practice_eligible(entry)]
    course_entries = [entry for entry in eligible if _course_usage(entry)]
    fill_entries = [entry for entry in eligible if not _course_usage(entry)]
    course_entries.sort(key=_course_key)
    fill_entries.sort(
        key=lambda entry: (CEFR_RANK.get(_cefr_level(entry) or "", len(CEFR_RANK)), _stable_lemma_id(entry))
    )
    selected = list(course_entries)
    if len(selected) < config.target:
        selected.extend(fill_entries[: config.target - len(selected)])

    lexemes_by_entry: list[tuple[dict[str, Any], dict[str, Any]]] = []
    for entry in selected[: config.target]:
        lexeme = _build_lexeme(entry, verifier)
        if lexeme:
            lexemes_by_entry.append((entry, lexeme))

    all_lexemes = [lexeme for _, lexeme in lexemes_by_entry]
    cloze_by_level: dict[str, list[dict[str, Any]]] = {level: [] for level in CEFR_ORDER}
    cloze_ids_by_lemma: dict[str, list[str]] = {}
    for entry, lexeme in lexemes_by_entry:
        items = _build_cloze_items(entry, lexeme, allowlist, verifier, deck_version)
        for item in items:
            item["options"] = _make_options(item, lexeme, all_lexemes, rng)
            option_errors = validate_option_set(item)
            if option_errors:
                continue
            cloze_by_level[lexeme["cefr"]].append(item)
            cloze_ids_by_lemma.setdefault(lexeme["lemmaId"], []).append(item["clozeId"])

    shards: dict[str, dict[str, dict[str, Any]]] = {}
    for level in CEFR_ORDER:
        level_lexemes = [lexeme for lexeme in all_lexemes if lexeme["cefr"] == level]
        if not level_lexemes:
            continue
        level_cloze = cloze_by_level[level]
        index_items = []
        for order, lexeme in enumerate(level_lexemes):
            cloze_ids = cloze_ids_by_lemma.get(lexeme["lemmaId"], [])
            modes = ["flashcards", "matching", "choice"]
            if cloze_ids:
                modes.append("cloze")
            index_items.append(
                {
                    "lemmaId": lexeme["lemmaId"],
                    "lemma": lexeme["lemma"],
                    "cefr": level,
                    "modes": modes,
                    "hasCloze": bool(cloze_ids),
                    "clozeIds": cloze_ids,
                    "newOrder": order,
                }
            )
        coverage = round(len({item["lemmaId"] for item in level_cloze}) / len(level_lexemes), 4)
        index_payload = _level_payload(
            "atlas-practice-index",
            deck_version,
            level,
            config,
            "items",
            index_items,
        )
        index_payload["counts"] = {
            "lexemes": len(level_lexemes),
            "cloze": len(level_cloze),
            "clozeEligibleLexemes": len({item["lemmaId"] for item in level_cloze}),
            "clozeCoverage": coverage,
        }
        lexeme_payload = _level_payload(
            "atlas-practice-lexemes",
            deck_version,
            level,
            config,
            "lexemes",
            level_lexemes,
        )
        cloze_payload = _level_payload(
            "atlas-practice-cloze",
            deck_version,
            level,
            config,
            "cloze",
            level_cloze,
        )
        shards[level] = {
            "index": index_payload,
            "lexemes": lexeme_payload,
            "cloze": cloze_payload,
        }
    return shards


def read_manifest(path: Path) -> list[dict[str, Any]]:
    manifest = json.loads(path.read_text(encoding="utf-8"))
    entries = manifest.get("entries") if isinstance(manifest, dict) else manifest
    if not isinstance(entries, list):
        raise ValueError("manifest entries must be a list")
    return [entry for entry in entries if isinstance(entry, dict)]


def _json_bytes(payload: dict[str, Any]) -> bytes:
    text = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    return text.encode("utf-8")


def _size_budget(payload: dict[str, Any], raw_limit: int, gzip_limit: int) -> dict[str, int | bool]:
    raw = _json_bytes(payload)
    gzipped = gzip.compress(raw, mtime=0)
    return {
        "rawBytes": len(raw),
        "gzipBytes": len(gzipped),
        "rawLimitBytes": raw_limit,
        "gzipLimitBytes": gzip_limit,
        "ok": len(raw) <= raw_limit and len(gzipped) <= gzip_limit,
    }


def apply_size_budgets(
    shards: dict[str, dict[str, dict[str, Any]]],
    raw_limit: int,
    gzip_limit: int,
) -> None:
    for level_shards in shards.values():
        for payload in level_shards.values():
            payload["sizeBudget"] = _size_budget(payload, raw_limit, gzip_limit)
            if not payload["sizeBudget"]["ok"]:
                raise ValueError(
                    f"{payload['schema']}.{payload['level']} exceeds size budget: "
                    f"{payload['sizeBudget']}"
                )


def write_shards(shards: dict[str, dict[str, dict[str, Any]]], out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for level, level_shards in sorted(shards.items()):
        for kind, payload in sorted(level_shards.items()):
            path = out_dir / f"lexicon-practice-{kind}.{level}.json"
            path.write_bytes(_json_bytes(payload))
            written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--reviewed-allowlist", type=Path, default=DEFAULT_ALLOWLIST)
    parser.add_argument("--vesum-fixture", type=Path)
    parser.add_argument("--target", type=int, default=DEFAULT_TARGET)
    parser.add_argument("--raw-limit", type=int, default=DEFAULT_RAW_LIMIT)
    parser.add_argument("--gzip-limit", type=int, default=DEFAULT_GZIP_LIMIT)
    parser.add_argument("--fixture-note", type=str)
    args = parser.parse_args(argv)

    entries = read_manifest(args.manifest)
    allowlist = ReviewedSourceAllowlist.from_path(args.reviewed_allowlist)
    verifier: VesumVerifier = (
        JsonVesumVerifier.from_path(args.vesum_fixture)
        if args.vesum_fixture
        else RealVesumVerifier()
    )
    config = BuildConfig(
        target=args.target,
        raw_limit=args.raw_limit,
        gzip_limit=args.gzip_limit,
        fixture_note=args.fixture_note,
        source_label="fixture" if args.vesum_fixture else "manifest",
    )
    shards = build_practice_shards(entries, allowlist, verifier, config)
    apply_size_budgets(shards, config.raw_limit, config.gzip_limit)
    written = write_shards(shards, args.out_dir)
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
