"""Generate sharded Word Atlas practice decks.

The production deck is generated by the finalizer after the 39 MB manifest and
VESUM database have been hydrated locally. This script is deterministic and can
also run against a small committed fixture with a JSON-backed VESUM verifier.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import random
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

PROJECT_ROOT = Path(__file__).resolve().parents[2]
AUDIT_DIR = PROJECT_ROOT / "scripts" / "audit"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(AUDIT_DIR) not in sys.path:
    sys.path.insert(0, str(AUDIT_DIR))

from lexeme_filter import SURFACE_CLOZE, is_practice_eligible, is_surface_admitted

DEFAULT_MANIFEST = Path("site/src/data/lexicon-manifest.json")
# Deck shards are served as literal static files from public/ (not via dynamic .json.ts
# endpoints) so the fetch URL resolves identically in dev and prod — astro's
# `trailingSlash: 'always'` otherwise serves a dynamic endpoint only at the trailing-slash
# path in dev while a static host serves it only without one (no single URL works for both).
DEFAULT_OUT_DIR = Path("site/public/lexicon")
DEFAULT_ALLOWLIST = Path("site/src/data/lexicon-practice-reviewed-sources.json")
DEFAULT_CLOZE_SOURCES = Path("site/src/data/lexicon-practice-cloze-sources.json")
# Keep the default above the current all-eligible deck size. A lower default
# silently contracts the committed practice surface during routine cloze regen.
DEFAULT_TARGET = 6000
DEFAULT_RAW_LIMIT = 550_000
DEFAULT_GZIP_LIMIT = 140_000
SCHEMA_VERSION = 1
CEFR_ORDER = ("A1", "A2", "B1", "B2", "C1", "C2")
CEFR_RANK = {level: index for index, level in enumerate(CEFR_ORDER)}
MEANING_MC_MAX_WORDS = 4
MEANING_MC_MAX_CHARS = 32
NUMBER_KEYS = ("singular", "plural")
NO_PAIR_PROBABILITY = {
    "A1": 0.70,
    "A2": 0.62,
    "B1": 0.55,
    "B2": 0.50,
    "C1": 0.45,
    "C2": 0.45,
}

CASE_LABELS_UA = {
    "nominative": "називний",
    "genitive": "родовий",
    "dative": "давальний",
    "accusative": "знахідний",
    "instrumental": "орудний",
    "locative": "місцевий",
    "vocative": "кличний",
}

CASE_VESUM_TAGS = {
    "nominative": "v_naz",
    "genitive": "v_rod",
    "dative": "v_dav",
    "accusative": "v_zna",
    "instrumental": "v_oru",
    "locative": "v_mis",
    "vocative": "v_kly",
}

CASE_RULES = {
    "accusative_direct_object": {
        "case": "accusative",
        "trigger": "direct-object",
        "triggerLabel": "прямий додаток",
        "feedbackTemplate": "бачити/мати/читати + знахідний ({lemma} -> {form})",
    },
    "locative_static_u": {
        "case": "locative",
        "trigger": "у/в (static location)",
        "triggerLabel": "у/в (статична позиція)",
        "feedbackTemplate": "у/в (статична позиція) -> місцевий ({lemma} -> {form})",
    },
    "locative_static_na": {
        "case": "locative",
        "trigger": "на (static location)",
        "triggerLabel": "на (статична позиція)",
        "feedbackTemplate": "на (статична позиція) -> місцевий ({lemma} -> {form})",
    },
}


class VesumVerifier(Protocol):
    """Small injectable interface around scripts.verification.vesum.verify_words."""

    def verify_words(
        self,
        words: list[str],
        pos_filter: str | None = None,
    ) -> dict[str, list[dict[str, Any]]]:
        """Return VESUM matches keyed by submitted word form."""


@dataclass(frozen=True)
class BuildConfig:
    target: int = DEFAULT_TARGET
    raw_limit: int = DEFAULT_RAW_LIMIT
    gzip_limit: int = DEFAULT_GZIP_LIMIT
    fixture_note: str | None = None
    source_label: str = "manifest"


@dataclass(frozen=True)
class ReviewedSourceAllowlist:
    reviewed: frozenset[tuple[str, str]]

    @classmethod
    def from_path(cls, path: Path) -> ReviewedSourceAllowlist:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return cls.from_payload(payload)

    @classmethod
    def from_payload(cls, payload: Any) -> ReviewedSourceAllowlist:
        reviewed: set[tuple[str, str]] = set()
        rows = payload.get("reviewed") if isinstance(payload, dict) else payload
        if not isinstance(rows, list):
            raise ValueError("reviewed allowlist must be a list or an object with reviewed list")
        for row in rows:
            if isinstance(row, str):
                reviewed.add(("reviewed", row))
            elif isinstance(row, dict):
                status = _clean_text(row.get("status")) or "reviewed"
                path = _clean_text(row.get("path"))
                if path:
                    reviewed.add((status, path))
        return cls(frozenset(reviewed))

    def allows(self, provenance: Any) -> bool:
        if not isinstance(provenance, dict):
            return False
        status = _clean_text(provenance.get("status"))
        path = _clean_text(provenance.get("path"))
        if not status or not path:
            return False
        return (status, path) in self.reviewed


class RealVesumVerifier:
    """Runtime adapter for the production VESUM helper."""

    def verify_words(
        self,
        words: list[str],
        pos_filter: str | None = None,
    ) -> dict[str, list[dict[str, Any]]]:
        from scripts.verification.vesum import verify_words

        return verify_words(words, pos_filter=pos_filter)


class JsonVesumVerifier:
    """Fixture verifier used by tests and fixture-only local generation."""

    def __init__(self, payload: dict[str, Any]) -> None:
        self.payload = payload

    @classmethod
    def from_path(cls, path: Path) -> JsonVesumVerifier:
        return cls(json.loads(path.read_text(encoding="utf-8")))

    def verify_words(
        self,
        words: list[str],
        pos_filter: str | None = None,
    ) -> dict[str, list[dict[str, Any]]]:
        result: dict[str, list[dict[str, Any]]] = {}
        for word in words:
            matches = self.payload.get(word, [])
            if not isinstance(matches, list):
                matches = []
            if pos_filter:
                matches = [row for row in matches if isinstance(row, dict) and row.get("pos") == pos_filter]
            result[word] = [row for row in matches if isinstance(row, dict)]
        return result


def _has_text(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _clean_text(value: Any) -> str | None:
    return value.strip() if _has_text(value) else None


def _plain(value: str) -> str:
    return (
        value.casefold()
        .replace("\u0301", "")
        .replace("́", "")
        .replace("’", "'")
        .replace("ʼ", "'")
        .strip()
    )


def _headword(gloss: str) -> str:
    head = gloss.split(";")[0].split(",")[0].strip().casefold()
    return head.split()[0] if head.split() else head


_FUNCTION_POS = frozenset(
    {
        "adp",
        "conj",
        "conjunction",
        "det",
        "determiner",
        "interj",
        "interjection",
        "particle",
        "prep",
        "preposition",
        "pron",
        "pronoun",
        "sconj",
    }
)
_FUNCTION_GLOSS_HEADWORDS = frozenset(
    {
        "and",
        "because",
        "but",
        "if",
        "nor",
        "or",
        "than",
        "that",
        "though",
        "unless",
        "until",
        "when",
        "where",
        "whether",
        "while",
        "yet",
    }
)
_UKRAINIAN_ROMANIZATION = {
    "а": "a",
    "б": "b",
    "в": "v",
    "г": "h",
    "ґ": "g",
    "д": "d",
    "е": "e",
    "є": "ie",
    "ж": "zh",
    "з": "z",
    "и": "y",
    "і": "i",
    "ї": "i",
    "й": "i",
    "к": "k",
    "л": "l",
    "м": "m",
    "н": "n",
    "о": "o",
    "п": "p",
    "р": "r",
    "с": "s",
    "т": "t",
    "у": "u",
    "ф": "f",
    "х": "kh",
    "ц": "ts",
    "ч": "ch",
    "ш": "sh",
    "щ": "shch",
    "ь": "",
    "ю": "iu",
    "я": "ia",
    "'": "",
}


def _gloss_clean(gloss: str) -> str:
    first_sense = re.split(r"[;,]", gloss, maxsplit=1)[0]
    return re.sub(r"\s+", " ", first_sense).strip()


def _meaning_label_word_count(label: str) -> int:
    return len(re.findall(r"[^\W_]+(?:[-'][^\W_]+)?", label, flags=re.UNICODE))


def _meaning_label_is_phrase(label: str) -> bool:
    clean = re.sub(r"\s+", " ", label).strip()
    return (
        not clean
        or "?" in clean
        or "(" in clean
        or ")" in clean
        or _meaning_label_word_count(clean) > MEANING_MC_MAX_WORDS
    )


def _romanize_ukrainian_plain(value: str) -> str:
    return "".join(_UKRAINIAN_ROMANIZATION.get(char, char) for char in value.casefold())


def _ascii_key(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.casefold())


def _is_transliteration_only_gloss(gloss_clean: str, lemma_plain: str) -> bool:
    romanized = _ascii_key(_romanize_ukrainian_plain(lemma_plain))
    return bool(romanized) and _ascii_key(gloss_clean) == romanized


def _meaning_mc_eligible(gloss_clean: str, lemma_plain: str, pos: str | None) -> bool:
    if not gloss_clean or len(gloss_clean) > MEANING_MC_MAX_CHARS:
        return False
    if _meaning_label_is_phrase(gloss_clean):
        return False
    if re.search(r"[.!:]$", gloss_clean):
        return False
    if _headword(gloss_clean) in _FUNCTION_GLOSS_HEADWORDS:
        return False
    if pos and pos.casefold() in _FUNCTION_POS:
        return False
    return not _is_transliteration_only_gloss(gloss_clean, lemma_plain)


def _stable_lemma_id(entry: dict[str, Any]) -> str:
    slug = _clean_text(entry.get("url_slug")) or _clean_text(entry.get("slug"))
    if slug:
        return slug
    key = "\x1f".join(
        (
            _clean_text(entry.get("lemma")) or "",
            _clean_text(entry.get("gloss")) or "",
            _clean_text(entry.get("pos")) or "",
        )
    )
    return hashlib.sha1(key.encode("utf-8")).hexdigest()[:16]


def _manifest_fingerprint(entries: list[dict[str, Any]]) -> str:
    payload = json.dumps(entries, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def _normalize_cefr(value: Any) -> str | None:
    if isinstance(value, dict):
        value = value.get("level") or value.get("cefr")
    level_text = _clean_text(value)
    if not level_text:
        return None
    match = re.search(r"\b([ABC][12])\b", level_text.upper())
    if not match:
        return None
    level = match.group(1)
    return level if level in CEFR_RANK else None


def _cefr_level(entry: dict[str, Any]) -> str | None:
    enrichment = entry.get("enrichment")
    if isinstance(enrichment, dict):
        level = _normalize_cefr(enrichment.get("cefr"))
        if level:
            return level
    level = _normalize_cefr(entry.get("cefr"))
    if level:
        return level
    for usage in _course_usage(entry):
        level = _normalize_cefr(usage.get("track"))
        if level:
            return level
    return None


def _ipa(entry: dict[str, Any]) -> str | None:
    enrichment = entry.get("enrichment")
    if isinstance(enrichment, dict):
        for key in ("ipa", "pronunciation"):
            value = _clean_text(enrichment.get(key))
            if value:
                return value
    return _clean_text(entry.get("ipa"))


def _heritage(entry: dict[str, Any]) -> str | None:
    enrichment = entry.get("enrichment")
    if isinstance(enrichment, dict):
        heritage = enrichment.get("heritage")
        if isinstance(heritage, dict):
            value = _clean_text(heritage.get("classification")) or _clean_text(heritage.get("status"))
            if value:
                return value
        value = _clean_text(heritage)
        if value:
            return value
    status = entry.get("heritage_status")
    if isinstance(status, dict):
        for key in ("classification", "status", "label", "category"):
            value = _clean_text(status.get(key))
            if value:
                return value
    return None


def _severity(entry: dict[str, Any]) -> str | None:
    enrichment = entry.get("enrichment")
    if isinstance(enrichment, dict):
        severity = enrichment.get("severity")
        if isinstance(severity, dict):
            value = _clean_text(severity.get("level")) or _clean_text(severity.get("label"))
            if value:
                return value
        value = _clean_text(severity)
        if value:
            return value
    return _clean_text(entry.get("severity"))


def _paradigm(entry: dict[str, Any]) -> dict[str, Any]:
    enrichment = entry.get("enrichment")
    if not isinstance(enrichment, dict):
        return {"cases": {}}
    morphology = enrichment.get("morphology")
    if not isinstance(morphology, dict):
        return {"cases": {}}
    paradigm = morphology.get("paradigm")
    if not isinstance(paradigm, dict):
        return {"cases": {}}
    cases = paradigm.get("cases")
    if not isinstance(cases, dict):
        return {"cases": {}}
    clean_cases: dict[str, dict[str, str]] = {}
    for case_name, forms in cases.items():
        if not isinstance(case_name, str) or not isinstance(forms, dict):
            continue
        case_key = case_name.strip().casefold()
        clean_forms: dict[str, str] = {}
        for number in NUMBER_KEYS:
            value = _clean_text(forms.get(number))
            if value:
                clean_forms[number] = value
        if clean_forms:
            clean_cases[case_key] = clean_forms
    return {"cases": clean_cases}


def _vesum_pos(pos: str | None) -> str | None:
    if not pos:
        return None
    pos_key = pos.casefold()
    if pos_key in {"noun", "verb", "adj", "adjective", "adv", "adverb"}:
        return {"adjective": "adj", "adverb": "adv"}.get(pos_key, pos_key)
    return pos_key


def _course_usage(entry: dict[str, Any]) -> list[dict[str, Any]]:
    usage = entry.get("course_usage")
    if isinstance(usage, dict):
        return [usage]
    if not isinstance(usage, list):
        return []
    return [item for item in usage if isinstance(item, dict)]


def _course_key(entry: dict[str, Any]) -> tuple[str, str, str]:
    usage = _course_usage(entry)
    first = usage[0] if usage else {}
    return (
        str(first.get("track") or ""),
        str(first.get("slug") or first.get("module") or ""),
        _stable_lemma_id(entry),
    )


def _cloze_join_key(row: dict[str, Any]) -> tuple[str, str] | None:
    lemma_id = _clean_text(row.get("lemmaId"))
    if lemma_id:
        return ("lemmaId", lemma_id)
    lemma = _clean_text(row.get("lemma"))
    if lemma:
        return ("lemma", _plain(lemma))
    return None


def _all_paradigm_forms(paradigm: dict[str, Any]) -> list[str]:
    cases = paradigm.get("cases")
    if not isinstance(cases, dict):
        return []
    forms: list[str] = []
    seen: set[str] = set()
    for case_forms in cases.values():
        if not isinstance(case_forms, dict):
            continue
        for number in NUMBER_KEYS:
            value = _clean_text(case_forms.get(number))
            if value and value not in seen:
                seen.add(value)
                forms.append(value)
    return forms


def _match_cases(match: dict[str, Any]) -> set[str]:
    tokens = set(str(match.get("tags") or "").replace(":", " ").split())
    return {
        case_name
        for case_name, tag in CASE_VESUM_TAGS.items()
        if tag in tokens
    }


def _verify_paradigm(
    lemma_plain: str,
    pos: str | None,
    paradigm: dict[str, Any],
    verifier: VesumVerifier,
) -> bool:
    forms = _all_paradigm_forms(paradigm)
    if not forms:
        return False
    verified = verifier.verify_words(forms, _vesum_pos(pos))
    for form in forms:
        matches = verified.get(form, [])
        if not matches:
            return False
        if not any(_plain(str(match.get("lemma") or "")) == lemma_plain for match in matches):
            return False
    return True


def _verify_discriminative_form(
    lemma_plain: str,
    pos: str | None,
    form: str,
    case_name: str,
    verifier: VesumVerifier,
) -> bool:
    matches = verifier.verify_words([form], _vesum_pos(pos)).get(form, [])
    if len(matches) != 1:
        return False
    match = matches[0]
    if _plain(str(match.get("lemma") or "")) != lemma_plain:
        return False
    return _match_cases(match) == {case_name}


def _case_form(
    paradigm: dict[str, Any],
    case_name: str,
    number: str,
) -> str | None:
    cases = paradigm.get("cases")
    if not isinstance(cases, dict):
        return None
    forms = cases.get(case_name)
    if not isinstance(forms, dict):
        forms = cases.get(CASE_LABELS_UA.get(case_name, ""))
    if not isinstance(forms, dict):
        return None
    return _clean_text(forms.get(number))


def _case_rule_payload(rule_id: str, lemma: str, form: str) -> dict[str, str] | None:
    rule = CASE_RULES.get(rule_id)
    if not rule:
        return None
    return {
        "ruleId": rule_id,
        "case": str(rule["case"]),
        "caseLabel": CASE_LABELS_UA[str(rule["case"])],
        "trigger": str(rule["trigger"]),
        "triggerLabel": str(rule["triggerLabel"]),
        "feedback": str(rule["feedbackTemplate"]).format(lemma=lemma, form=form),
    }


def _candidate_sentence_level(candidate: dict[str, Any], fallback: str) -> str:
    return _normalize_cefr(candidate.get("cefr")) or _normalize_cefr(candidate.get("level")) or fallback


def _cloze_candidate_ok_for_level(candidate: dict[str, Any], word_level: str) -> bool:
    sentence_level = _candidate_sentence_level(candidate, word_level)
    return CEFR_RANK[sentence_level] <= CEFR_RANK[word_level]


def _eligible_decoys(
    answer: dict[str, Any],
    lexemes: list[dict[str, Any]],
    case_name: str,
    number: str,
) -> list[tuple[dict[str, Any], str]]:
    answer_head = _headword(answer["gloss"])
    candidates: list[tuple[dict[str, Any], str]] = []
    for lexeme in lexemes:
        if lexeme["lemmaId"] == answer["lemmaId"]:
            continue
        if lexeme.get("pos") != answer.get("pos"):
            continue
        if CEFR_RANK[lexeme["cefr"]] > CEFR_RANK[answer["cefr"]]:
            continue
        if _headword(lexeme["gloss"]) == answer_head:
            continue
        decoy_form = _case_form(lexeme.get("paradigm", {}), case_name, number)
        if decoy_form and _plain(decoy_form) != _plain(lexeme["lemma"]):
            candidates.append((lexeme, decoy_form))
    return candidates


def _pick_decoy(
    answer: dict[str, Any],
    lexemes: list[dict[str, Any]],
    rng: random.Random,
    case_name: str,
    number: str,
) -> tuple[dict[str, Any], str] | None:
    candidates = _eligible_decoys(answer, lexemes, case_name, number)
    if not candidates:
        return None
    return rng.choice(candidates)


def _option(
    cloze_id: str,
    suffix: str,
    label: str,
    lemma_id: str,
    kind: str,
    case_name: str,
    pos: str | None,
) -> dict[str, str]:
    return {
        "optionId": f"{cloze_id}:{suffix}",
        "label": label,
        "lemmaId": lemma_id,
        "kind": kind,
        "case": case_name,
        "pos": pos or "",
    }


def _option_strategy_for_level(level: str, rng: random.Random) -> str:
    no_pair_probability = NO_PAIR_PROBABILITY.get(level, NO_PAIR_PROBABILITY["B1"])
    return "no-pair" if rng.random() < no_pair_probability else "two-pair"


def _make_two_pair_options(
    cloze: dict[str, Any],
    answer: dict[str, Any],
    lexemes: list[dict[str, Any]],
    rng: random.Random,
) -> list[dict[str, str]]:
    decoy = _pick_decoy(answer, lexemes, rng, cloze["blankCase"], cloze["number"])
    if decoy is None:
        return []
    decoy_lexeme, decoy_form = decoy
    options = [
        _option(
            cloze["clozeId"],
            "answer",
            cloze["form"],
            answer["lemmaId"],
            "answer",
            cloze["blankCase"],
            answer.get("pos"),
        ),
        _option(
            cloze["clozeId"],
            "lemma",
            answer["lemma"],
            answer["lemmaId"],
            "same-root-lemma",
            "nominative",
            answer.get("pos"),
        ),
        _option(
            cloze["clozeId"],
            "decoy-lemma",
            decoy_lexeme["lemma"],
            decoy_lexeme["lemmaId"],
            "decoy-lemma",
            "nominative",
            decoy_lexeme.get("pos"),
        ),
        _option(
            cloze["clozeId"],
            "decoy-oblique",
            decoy_form,
            decoy_lexeme["lemmaId"],
            "decoy-oblique",
            cloze["blankCase"],
            decoy_lexeme.get("pos"),
        ),
    ]
    rng.shuffle(options)
    return options


def _make_no_pair_options(
    cloze: dict[str, Any],
    answer: dict[str, Any],
    lexemes: list[dict[str, Any]],
    rng: random.Random,
) -> list[dict[str, str]]:
    decoys = _eligible_decoys(answer, lexemes, cloze["blankCase"], cloze["number"])
    rng.shuffle(decoys)
    if len(decoys) < 3:
        return []
    options = [
        _option(
            cloze["clozeId"],
            "answer",
            cloze["form"],
            answer["lemmaId"],
            "answer",
            cloze["blankCase"],
            answer.get("pos"),
        )
    ]
    for index, (decoy_lexeme, decoy_form) in enumerate(decoys[:3], start=1):
        label = decoy_form if index <= 2 else decoy_lexeme["lemma"]
        case_name = cloze["blankCase"] if index <= 2 else "nominative"
        kind = "decoy-oblique" if index <= 2 else "decoy-lemma"
        options.append(
            _option(
                cloze["clozeId"],
                f"decoy-{index}",
                label,
                decoy_lexeme["lemmaId"],
                kind,
                case_name,
                decoy_lexeme.get("pos"),
            )
        )
    rng.shuffle(options)
    return options


def _make_options(
    cloze: dict[str, Any],
    answer: dict[str, Any],
    lexemes: list[dict[str, Any]],
    rng: random.Random,
) -> list[dict[str, str]]:
    strategy = _option_strategy_for_level(answer["cefr"], rng)
    options = (
        _make_no_pair_options(cloze, answer, lexemes, rng)
        if strategy == "no-pair"
        else _make_two_pair_options(cloze, answer, lexemes, rng)
    )
    if not options:
        strategy = "two-pair"
        options = _make_two_pair_options(cloze, answer, lexemes, rng)
    for option in options:
        option["strategy"] = strategy
    return options


def _initial_capitalization(value: Any) -> bool | None:
    text = _clean_text(value)
    if not text:
        return None
    for char in text:
        if char.isalpha():
            return char.upper() == char and char.lower() != char
    return None


def validate_option_set(cloze: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    options = cloze.get("options")
    if not isinstance(options, list) or len(options) < 4:
        return ["option set must contain at least four options"]
    labels = [str(option.get("label") or "") for option in options if isinstance(option, dict)]
    if any(_meaning_label_is_phrase(label) for label in labels):
        errors.append("option labels must not be phrase glosses")
    normalized = [_plain(label) for label in labels]
    if len(set(normalized)) != len(normalized):
        errors.append("option labels must be unique after normalization")
    answer_count = sum(1 for label in normalized if label == _plain(str(cloze.get("form") or "")))
    if answer_count != 1:
        errors.append("answer form must be present exactly once")
    accepted = [cloze.get("form")]
    accepted_alt = cloze.get("acceptedAlt")
    if isinstance(accepted_alt, list):
        accepted.extend(accepted_alt)
    accepted_normalized = {_plain(str(value)) for value in accepted if _clean_text(value)}
    distractors = [
        option
        for option in options
        if isinstance(option, dict) and option.get("kind") != "answer"
    ]
    if any(_plain(str(option.get("label") or "")) in accepted_normalized for option in distractors):
        errors.append("accepted alternate must not equal a distractor")
    answer_labels = [
        str(option.get("label") or "")
        for option in options
        if isinstance(option, dict) and option.get("kind") == "answer"
    ]
    answer_cap = _initial_capitalization(answer_labels[0] if answer_labels else cloze.get("form"))
    distractor_caps = {
        cap
        for cap in (
            _initial_capitalization(option.get("label"))
            for option in distractors
            if isinstance(option, dict)
        )
        if cap is not None
    }
    if answer_cap is not None and len(distractor_caps) == 1 and answer_cap not in distractor_caps:
        errors.append("answer capitalization must not uniquely reveal the answer")
    oblique_count = sum(
        1
        for option in options
        if isinstance(option, dict)
        and option.get("case") not in {None, "", "nominative"}
    )
    blank_case = _clean_text(cloze.get("blankCase")) or "nominative"
    if blank_case != "nominative" and oblique_count < 2:
        errors.append("option set must contain at least two oblique-looking forms")
    pos_values = {
        str(option.get("pos") or "")
        for option in options
        if isinstance(option, dict) and option.get("pos")
    }
    if len(pos_values) > 1:
        errors.append("option set must stay within one POS bucket")
    root_counts: dict[str, int] = {}
    for option in options:
        if not isinstance(option, dict):
            continue
        lemma_id = str(option.get("lemmaId") or "")
        root_counts[lemma_id] = root_counts.get(lemma_id, 0) + 1
    pair_count = sum(1 for count in root_counts.values() if count >= 2)
    if pair_count == 1:
        errors.append("option set must not contain exactly one same-root pair")
    if pair_count > 1 and any(count > 2 for count in root_counts.values()):
        errors.append("option set must not contain answer-equivalent root leaks")
    lengths = [len(label) for label in labels]
    if lengths and max(lengths) - min(lengths) > 12:
        errors.append("option label lengths exceed bounded distribution")
    return errors


def validate_option_sets(cloze_items: list[dict[str, Any]]) -> list[str]:
    positions: list[int] = []
    for item in cloze_items:
        options = item.get("options")
        if not isinstance(options, list):
            continue
        normalized_answer = _plain(str(item.get("form") or ""))
        for index, option in enumerate(options):
            if isinstance(option, dict) and _plain(str(option.get("label") or "")) == normalized_answer:
                positions.append(index)
                break
    if len(positions) > 1 and len(set(positions)) == 1:
        return ["answer position must vary across the deck"]
    return []


def _build_lexeme(entry: dict[str, Any], verifier: VesumVerifier) -> dict[str, Any] | None:
    lemma = _clean_text(entry.get("lemma"))
    gloss = _clean_text(entry.get("gloss"))
    level = _cefr_level(entry)
    if not lemma or not gloss or not level:
        return None
    lemma_plain = _plain(lemma)
    pos = _clean_text(entry.get("pos"))
    gloss_clean = _gloss_clean(gloss)
    meaning_mc_eligible = _meaning_mc_eligible(gloss_clean, lemma_plain, pos)
    # Recognition (matching/choice/flashcard) needs only lemma+gloss+level, so the word is
    # ALWAYS kept. Attach the paradigm for flashcard declensions ONLY when every form
    # VESUM-verifies; otherwise blank it so the UI never displays an unverified declension.
    paradigm = _paradigm(entry)
    if not _verify_paradigm(lemma_plain, pos, paradigm, verifier):
        paradigm = {"cases": {}}
    return {
        "lemmaId": _stable_lemma_id(entry),
        "lemma": lemma,
        "lemmaPlain": lemma_plain,
        "ipa": _ipa(entry),
        "gloss": gloss,
        "glossClean": gloss_clean,
        "meaningMcEligible": meaning_mc_eligible,
        "pos": pos,
        "cefr": level,
        "heritage": _heritage(entry),
        "severity": _severity(entry),
        "paradigm": paradigm,
        "semanticBucket": _clean_text(entry.get("semantic_bucket")),
    }


def _candidate_rule_id(candidate: dict[str, Any], case_name: str) -> str | None:
    raw_rule = (
        candidate.get("caseRuleId")
        or candidate.get("ruleId")
        or candidate.get("caseRule")
    )
    if isinstance(raw_rule, dict):
        raw_rule = raw_rule.get("ruleId") or raw_rule.get("id")
    rule_id = _clean_text(raw_rule)
    if rule_id:
        if rule_id in CASE_RULES and CASE_RULES[rule_id]["case"] == case_name:
            return rule_id
        return None
    for fallback_id, rule in CASE_RULES.items():
        if rule["case"] == case_name:
            return fallback_id
    return None


def _infer_number(paradigm: dict[str, Any], case_name: str, form: str | None) -> str | None:
    if form:
        normalized = _plain(form)
        for number in NUMBER_KEYS:
            candidate = _case_form(paradigm, case_name, number)
            if candidate and _plain(candidate) == normalized:
                return number
    return "singular"


def _accepted_alts(candidate: dict[str, Any]) -> list[str]:
    raw = candidate.get("acceptedAlt")
    if raw is None:
        raw = candidate.get("accepted_alt")
    if isinstance(raw, list):
        return [value for value in (_clean_text(item) for item in raw) if value]
    text = _clean_text(raw)
    if not text:
        return []
    return [value for value in (part.strip() for part in text.split("|")) if value]


def _build_cloze_items(
    lexeme: dict[str, Any],
    cloze_rows: list[dict[str, Any]],
    allowlist: ReviewedSourceAllowlist,
    verifier: VesumVerifier,
    deck_version: str,
) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for index, candidate in enumerate(cloze_rows):
        provenance = candidate.get("provenance")
        if not allowlist.allows(provenance):
            continue
        case_name = _clean_text(candidate.get("blankCase"))
        if not case_name or case_name not in CASE_LABELS_UA:
            continue
        rule_id = _candidate_rule_id(candidate, case_name)
        if not rule_id:
            continue
        if not _cloze_candidate_ok_for_level(candidate, lexeme["cefr"]):
            continue
        curated_form = _clean_text(candidate.get("form"))
        number = _clean_text(candidate.get("number")) or _infer_number(
            lexeme["paradigm"],
            case_name,
            curated_form,
        )
        if number not in NUMBER_KEYS:
            continue
        form = curated_form or _case_form(lexeme["paradigm"], case_name, number)
        if not form or _plain(form) == lexeme["lemmaPlain"]:
            continue
        if not _verify_discriminative_form(
            lexeme["lemmaPlain"],
            lexeme.get("pos"),
            form,
            case_name,
            verifier,
        ):
            continue
        sentence = _clean_text(candidate.get("sentence"))
        cloze_en = _clean_text(candidate.get("clozeEn")) or _clean_text(candidate.get("translation"))
        if not sentence or "___" not in sentence or not cloze_en:
            continue
        frame_key = "\x1f".join((deck_version, lexeme["lemmaId"], sentence, rule_id))
        sentence_frame_id = "sf_" + hashlib.sha1(frame_key.encode("utf-8")).hexdigest()[:12]
        cloze_id = _clean_text(candidate.get("clozeId")) or f"{lexeme['lemmaId']}:cloze:{index + 1}"
        case_rule = _case_rule_payload(rule_id, lexeme["lemma"], form)
        if not case_rule:
            continue
        items.append(
            {
                "clozeId": cloze_id,
                "lemmaId": lexeme["lemmaId"],
                "sentenceFrameId": sentence_frame_id,
                "sentence": sentence,
                "blankCase": case_name,
                "form": form,
                "number": number,
                "lemma": lexeme["lemma"],
                "caseRule": case_rule,
                "clozeEn": cloze_en,
                "cefr": _clean_text(candidate.get("cefr")) or lexeme["cefr"],
                "acceptedAlt": _accepted_alts(candidate),
                "provenance": {
                    "status": provenance["status"],
                    "path": provenance["path"],
                    "cardId": _clean_text(provenance.get("cardId")),
                },
            }
        )
    return items


def _level_payload(
    schema: str,
    deck_version: str,
    level: str,
    config: BuildConfig,
    body_key: str,
    body_value: Any,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "schema": schema,
        "schemaVersion": SCHEMA_VERSION,
        "deckVersion": deck_version,
        "level": level,
        "source": config.source_label,
    }
    if config.fixture_note:
        payload["fixtureNote"] = config.fixture_note
    payload[body_key] = body_value
    return payload


def build_practice_shards(
    entries: list[dict[str, Any]],
    allowlist: ReviewedSourceAllowlist,
    verifier: VesumVerifier,
    cloze_sources: list[dict[str, Any]] | None = None,
    config: BuildConfig | None = None,
) -> dict[str, dict[str, dict[str, Any]]]:
    if isinstance(cloze_sources, BuildConfig) and config is None:
        config = cloze_sources
        cloze_sources = None
    if config is None:
        config = BuildConfig()
    if config.target < 0:
        raise ValueError("target must be non-negative")
    deck_version = f"atlas-practice-v{SCHEMA_VERSION}-{_manifest_fingerprint(entries)}"
    rng_seed = int(hashlib.sha256(deck_version.encode("utf-8")).hexdigest()[:16], 16)
    rng = random.Random(rng_seed)
    eligible = [entry for entry in entries if is_practice_eligible(entry)]
    course_entries = [entry for entry in eligible if _course_usage(entry)]
    fill_entries = [entry for entry in eligible if not _course_usage(entry)]
    course_entries.sort(key=_course_key)
    fill_entries.sort(
        key=lambda entry: (CEFR_RANK.get(_cefr_level(entry) or "", len(CEFR_RANK)), _stable_lemma_id(entry))
    )
    selected = list(course_entries)
    if len(selected) < config.target:
        selected.extend(fill_entries[: config.target - len(selected)])

    lexemes_by_entry: list[tuple[dict[str, Any], dict[str, Any]]] = []
    for entry in selected[: config.target]:
        lexeme = _build_lexeme(entry, verifier)
        if lexeme:
            lexemes_by_entry.append((entry, lexeme))

    all_lexemes = [lexeme for _, lexeme in lexemes_by_entry]
    cloze_sources = cloze_sources or []
    cloze_by_lemma_id: dict[str, list[dict[str, Any]]] = {}
    cloze_by_lemma: dict[str, list[dict[str, Any]]] = {}
    for row in cloze_sources:
        key = _cloze_join_key(row)
        if key is None:
            continue
        key_type, key_value = key
        target = cloze_by_lemma_id if key_type == "lemmaId" else cloze_by_lemma
        target.setdefault(key_value, []).append(row)
    cloze_by_level: dict[str, list[dict[str, Any]]] = {level: [] for level in CEFR_ORDER}
    cloze_ids_by_lemma: dict[str, list[str]] = {}
    for _entry, lexeme in lexemes_by_entry:
        if is_surface_admitted(_entry, SURFACE_CLOZE):
            source_rows = [
                *cloze_by_lemma_id.get(lexeme["lemmaId"], []),
                *cloze_by_lemma.get(lexeme["lemmaPlain"], []),
            ]
        else:
            source_rows = []
        items = _build_cloze_items(lexeme, source_rows, allowlist, verifier, deck_version)
        for item in items:
            item["options"] = _make_options(item, lexeme, all_lexemes, rng)
            option_errors = validate_option_set(item)
            if option_errors:
                continue
            cloze_by_level[lexeme["cefr"]].append(item)
            cloze_ids_by_lemma.setdefault(lexeme["lemmaId"], []).append(item["clozeId"])

    shards: dict[str, dict[str, dict[str, Any]]] = {}
    for level in CEFR_ORDER:
        level_lexemes = [lexeme for lexeme in all_lexemes if lexeme["cefr"] == level]
        if not level_lexemes:
            continue
        level_cloze = cloze_by_level[level]
        option_set_errors = validate_option_sets(level_cloze)
        if option_set_errors:
            print(
                f"WARN: {level} cloze option mix skipped deck-level validation: {option_set_errors}",
                file=sys.stderr,
            )
            level_cloze = []
            for item in cloze_by_level[level]:
                cloze_ids_by_lemma.get(item["lemmaId"], []).clear()
        index_items = []
        for order, lexeme in enumerate(level_lexemes):
            cloze_ids = cloze_ids_by_lemma.get(lexeme["lemmaId"], [])
            modes = ["flashcards"]
            if lexeme.get("meaningMcEligible"):
                modes.extend(["matching", "choice"])
            if cloze_ids:
                modes.append("cloze")
            index_items.append(
                {
                    "lemmaId": lexeme["lemmaId"],
                    "lemma": lexeme["lemma"],
                    "cefr": level,
                    "modes": modes,
                    "hasCloze": bool(cloze_ids),
                    "clozeIds": cloze_ids,
                    "newOrder": order,
                }
            )
        coverage = round(len({item["lemmaId"] for item in level_cloze}) / len(level_lexemes), 4)
        if level == "A1" and coverage < 0.10:
            print(
                f"WARN: A1 clozeCoverage {coverage:.4f} below 0.10; recognition deck still emitted",
                file=sys.stderr,
            )
        index_payload = _level_payload(
            "atlas-practice-index",
            deck_version,
            level,
            config,
            "items",
            index_items,
        )
        index_payload["counts"] = {
            "lexemes": len(level_lexemes),
            "cloze": len(level_cloze),
            "clozeEligibleLexemes": len({item["lemmaId"] for item in level_cloze}),
            "clozeCoverage": coverage,
        }
        lexeme_payload = _level_payload(
            "atlas-practice-lexemes",
            deck_version,
            level,
            config,
            "lexemes",
            level_lexemes,
        )
        cloze_payload = _level_payload(
            "atlas-practice-cloze",
            deck_version,
            level,
            config,
            "cloze",
            level_cloze,
        )
        shards[level] = {
            "index": index_payload,
            "lexemes": lexeme_payload,
            "cloze": cloze_payload,
        }
    return shards


def read_manifest(path: Path) -> list[dict[str, Any]]:
    manifest = json.loads(path.read_text(encoding="utf-8"))
    entries = manifest.get("entries") if isinstance(manifest, dict) else manifest
    if not isinstance(entries, list):
        raise ValueError("manifest entries must be a list")
    return [entry for entry in entries if isinstance(entry, dict)]


def read_cloze_sources(path: Path | None) -> list[dict[str, Any]]:
    if path is None or not path.exists():
        print("WARN: no curated cloze sources found; emitting recognition-only deck", file=sys.stderr)
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise ValueError("cloze sources must be a list")
    rows = [row for row in payload if isinstance(row, dict)]
    if not rows:
        print("WARN: curated cloze sources empty; emitting recognition-only deck", file=sys.stderr)
    return rows


def _json_bytes(payload: dict[str, Any]) -> bytes:
    text = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    return text.encode("utf-8")


def _size_budget(payload: dict[str, Any], raw_limit: int, gzip_limit: int) -> dict[str, int | bool]:
    raw = _json_bytes(payload)
    gzipped = gzip.compress(raw, mtime=0)
    return {
        "rawBytes": len(raw),
        "gzipBytes": len(gzipped),
        "rawLimitBytes": raw_limit,
        "gzipLimitBytes": gzip_limit,
        "ok": len(raw) <= raw_limit and len(gzipped) <= gzip_limit,
    }


def apply_size_budgets(
    shards: dict[str, dict[str, dict[str, Any]]],
    raw_limit: int,
    gzip_limit: int,
) -> None:
    for level, level_shards in shards.items():
        while True:
            oversized: list[dict[str, Any]] = []
            for payload in level_shards.values():
                payload["sizeBudget"] = _size_budget(payload, raw_limit, gzip_limit)
                if not payload["sizeBudget"]["ok"]:
                    oversized.append(payload)
            if not oversized:
                break

            schemas = ", ".join(f"{payload['schema']}.{level}" for payload in oversized)
            print(f"WARN: {schemas} exceeds size budget; trimming {level} shard", file=sys.stderr)
            index_items = level_shards.get("index", {}).get("items", [])
            if not isinstance(index_items, list) or not index_items:
                break
            removed = index_items.pop()
            removed_lemma_id = removed.get("lemmaId") if isinstance(removed, dict) else None
            if not removed_lemma_id:
                break
            lexemes = level_shards.get("lexemes", {}).get("lexemes", [])
            if isinstance(lexemes, list):
                lexemes[:] = [
                    lexeme
                    for lexeme in lexemes
                    if not isinstance(lexeme, dict) or lexeme.get("lemmaId") != removed_lemma_id
                ]
            cloze_items = level_shards.get("cloze", {}).get("cloze", [])
            if isinstance(cloze_items, list):
                cloze_items[:] = [
                    item
                    for item in cloze_items
                    if not isinstance(item, dict) or item.get("lemmaId") != removed_lemma_id
                ]
            counts = level_shards.get("index", {}).get("counts")
            if isinstance(counts, dict) and isinstance(lexemes, list) and isinstance(cloze_items, list):
                counts["lexemes"] = len(lexemes)
                counts["cloze"] = len(cloze_items)
                counts["clozeEligibleLexemes"] = len(
                    {item["lemmaId"] for item in cloze_items if isinstance(item, dict)}
                )
                counts["clozeCoverage"] = (
                    round(counts["clozeEligibleLexemes"] / len(lexemes), 4) if lexemes else 0
                )


def write_shards(shards: dict[str, dict[str, dict[str, Any]]], out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for level, level_shards in sorted(shards.items()):
        for kind, payload in sorted(level_shards.items()):
            path = out_dir / f"practice-{kind}.{level}.json"
            path.write_bytes(_json_bytes(payload))
            written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--reviewed-allowlist", type=Path, default=DEFAULT_ALLOWLIST)
    parser.add_argument("--cloze-sources", type=Path, default=DEFAULT_CLOZE_SOURCES)
    parser.add_argument("--vesum-fixture", type=Path)
    parser.add_argument("--target", type=int, default=DEFAULT_TARGET)
    parser.add_argument("--raw-limit", type=int, default=DEFAULT_RAW_LIMIT)
    parser.add_argument("--gzip-limit", type=int, default=DEFAULT_GZIP_LIMIT)
    parser.add_argument("--fixture-note", type=str)
    args = parser.parse_args(argv)

    entries = read_manifest(args.manifest)
    allowlist = ReviewedSourceAllowlist.from_path(args.reviewed_allowlist)
    cloze_sources = read_cloze_sources(args.cloze_sources)
    verifier: VesumVerifier = (
        JsonVesumVerifier.from_path(args.vesum_fixture)
        if args.vesum_fixture
        else RealVesumVerifier()
    )
    config = BuildConfig(
        target=args.target,
        raw_limit=args.raw_limit,
        gzip_limit=args.gzip_limit,
        fixture_note=args.fixture_note,
        source_label="fixture" if args.vesum_fixture else "manifest",
    )
    shards = build_practice_shards(entries, allowlist, verifier, cloze_sources, config)
    apply_size_budgets(shards, config.raw_limit, config.gzip_limit)
    written = write_shards(shards, args.out_dir)
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
