"""Removal-only containment regressions for #9160."""

from __future__ import annotations

import copy
import json
import sqlite3
from pathlib import Path
from typing import Any

import pytest

from scripts.audit.generate_practice_deck import JsonVesumVerifier, _build_lexeme, main
from scripts.audit.practice_quality_gate import audit_practice_shards
from scripts.practice.meaning_containment import (
    REVIEWED_WRONG_LEMMAS,
    _balla_maps_lemma,
    _bound_dmklinger_row,
    _candidate_alternatives,
    _key,
    candidate_balla_heads,
    english_candidates_support_display,
    english_head,
    load_dmklinger_rows,
    load_sum11_definitions,
    meaning_problem,
    source_bound_meaning,
    split_english_alternatives,
)

# Evidence below is copied by script from the frozen inputs named in
# docs/practice/meaning-source-9160.md, never retyped: Atlas fields from
# data/atlas.db, and `dmklinger_uk_en` / `balla_en_uk` rows from sources.db.
_BALLA_IMPRESSION = "n 1) враження 2) уявлення, поняття, думка a vague ~ of smth. — неясне (невиразне) уявлення про щось 3) вплив; сприйняття 4) відбиток, слід 5) друк. друкування; перевидання; передруковування; стереотипне видання 6) тираж 7) жив. ґрунт, фон (в картині) 8) мед. удавлювання"
_BALLA_ARRANGE = "v 1) доводити до ладу, упорядковувати 2) розташовувати (в певному порядку); систематизувати; класифікувати 3) домовлятися, приходити до згоди, умовлятися to ~ with smb. about smth. — домовитися з кимсь про щось to ~ for an appointment — домовитися про побачення 4) улагоджувати (суперечку), урегулювати 5) вживати заходів, підготовляти (для — for) 6) пристосовувати; переробляти to ~ a novel for the stage — інсценувати роман 7) муз. аранжувати 8) військ. вишиковувати 9) тех. монтувати; установлювати, закріпляти (на верстаті)"
_BALLA_ELECTRON = "n фіз. електрон ~ theory — електроніка ~ microscope — електронний мікроскоп ~ tube — електронна лампа"
_BALLA_ELECTRONIC = "adj фіз. електронний ~ brain — розм. «електронний мозок», електронна обчислювальна машина"
_ATLAS: dict[str, dict] = {
    'новий': {"lemma": "новий", "url_slug": "новий", "gloss": "new, masculine", "pos": "adjective", "cefr": "A1", "enrichment": {"translation": {"en": ["new"], "source": "learner_english_gloss"}}},
    'зазначати': {"lemma": "зазначати", "url_slug": "зазначати", "gloss": "to state, note", "pos": "verb", "cefr": "B2", "enrichment": {"translation": {"en": ["to mention, to note", "to indicate, to point out"], "source": "dmklinger"}}},
    'казка': {"lemma": "казка", "url_slug": "казка", "gloss": "розповідний твір про вигаданих осіб і події, переважно за участю фантастичних сил", "pos": "noun", "cefr": "A2", "enrichment": {"translation": {"en": ["fable (fictitious narration to enforce some useful truth or precept)", "fairy tale (folktale)"], "source": "dmklinger"}}},
    'аптекар': {"lemma": "аптекар", "url_slug": "аптекар", "gloss": "pharmacist, pharmacy worker", "pos": "noun:m", "cefr": "A2", "enrichment": {"translation": {"en": ["pharmacist (professional who dispenses prescription drugs)"], "source": "dmklinger"}}},
    'задонатити': {"lemma": "задонатити", "url_slug": "задонатити", "gloss": "to donate", "pos": "verb", "cefr": "B2", "enrichment": {"translation": {"en": ["(colloquial) to donate"], "source": "dmklinger"}}},
    'мотиваційний': {"lemma": "мотиваційний", "url_slug": "мотиваційний", "gloss": "motivation (attributive), motivational", "pos": "adj", "cefr": "B2", "enrichment": {"translation": {"en": ["motivational (tending or intended to motivate)", "(relational) motivation (attributive), motivational"], "source": "dmklinger"}}},
    'дно': {"lemma": "дно", "url_slug": "дно", "gloss": "bed (of a river), bottom (of a lake)", "pos": "noun", "cefr": "B1", "enrichment": {"translation": {"en": ["ground (bottom of a body of water)", "bed (of a river), bottom (of a lake)", "bottom part (of an object)", "(figuratively) lowest stratum (of a capitalist society)", "bottom (bed of a body of water)", "bottom (lowest part of a container)"], "source": "dmklinger"}}},
    'ураження': {"lemma": "ураження", "url_slug": "ураження", "gloss": "impression (overall effect of something)", "pos": "noun", "cefr": "A1", "enrichment": {"translation": {"en": ["impression (overall effect of something)"], "source": "dmklinger"}}},
    'електронний': {"lemma": "електронний", "url_slug": "електронний", "gloss": "electron (attributive)", "pos": "adj", "cefr": "A1", "enrichment": {"translation": {"en": ["electronic (pertaining to electrons)", "(relational) electron (attributive)", "electronic (of or pertaining to the Internet)", "generated by electronic device", "electronic (operating on behavior of electrons)"], "source": "dmklinger"}}},
    'музичний': {"lemma": "музичний", "url_slug": "музичний", "gloss": "music (adjective), musical", "pos": "adjective", "cefr": "A1", "enrichment": {"translation": {"en": ["music (adjective), musical"], "source": "learner_english_gloss"}}},
    'тікати': {"lemma": "тікати", "url_slug": "тікати", "gloss": "to tick (of a clock)", "pos": "verb", "cefr": "A1", "enrichment": {"translation": {"en": ["(intransitive) to tick (of a clock)", "flee (to run away; to escape)", "(intransitive) to run away, to flee", "scoot (to walk fast; to go quickly; to run away hastily)"], "source": "dmklinger"}}},
    'слізний': {"lemma": "слізний", "url_slug": "слізний", "gloss": "tear (water from the eyes); lacrimal", "pos": "adjective", "cefr": None, "enrichment": {"translation": {"en": ["tear (water from the eyes)"], "source": "learner_english_gloss"}}},
    'звати': {"lemma": "звати", "url_slug": "звати", "gloss": "to call / be named", "pos": "verb", "cefr": "A1", "enrichment": {"translation": {"en": ["to call [to be called; to be named]                                                                            Conjugation: 1st (-уть)", "call (to request, summon, or beckon)", "(transitive, intransitive, reflexive) to call", "(transitive, intransitive) to summon", "(transitive, intransitive) to invite (for a visit, wedding, guest etc.)"], "source": "learner_english_gloss"}}},
    'очікувати': {"lemma": "очікувати", "url_slug": "очікувати", "gloss": "to wait for, to await", "pos": "verb", "cefr": "A1", "enrichment": {"translation": {"en": ["to expect, to wait for, to anticipate                                                                          Conjugation: 1st (-ють) | ―", "wait (delay until some event)", "(transitive) to wait", "be in for (able to expect)", "remain (to await; to be left to)"], "source": "learner_english_gloss"}}},
    'снідати': {"lemma": "снідати", "url_slug": "снідати", "gloss": "to have breakfast", "pos": "infinitive", "cefr": "A1", "enrichment": {"translation": {"en": ["to have breakfast                                                                                       Conjugation: 1st (-ють)", "to have breakfast", "breakfast (to eat the morning meal)", "to have lunch", "to have dinner/supper"], "source": "learner_english_gloss"}}},
    'збільшити': {"lemma": "збільшити", "url_slug": "збільшити", "gloss": "to increase, to augment", "pos": "verb", "cefr": "A1", "enrichment": {"translation": {"en": ["to increase sth [to increase]                                                               Conjugation: 1st (-ють) | 2nd (-ать)", "increase (make larger)", "(transitive) to increase, to augment", "magnify (to make larger)", "(transitive) to enlarge, to magnify"], "source": "learner_english_gloss"}}},
    'сірий': {"lemma": "сірий", "url_slug": "сірий", "gloss": "grey, masculine", "pos": "adj", "cefr": "A1", "enrichment": {"translation": {"en": ["gray"], "source": "learner_english_gloss"}}},
    'довкілля': {"lemma": "довкілля", "url_slug": "довкілля", "gloss": "environment", "pos": "noun", "cefr": "A1", "enrichment": {"translation": {"en": ["environment (natural world or ecosystem)", "environment, milieu", "(rare) environs, neighbourhood"], "source": "dmklinger"}}},
    'ремонт': {"lemma": "ремонт", "url_slug": "ремонт", "gloss": "renovation; repair", "pos": "noun:m", "cefr": "A2", "enrichment": {"translation": {"en": ["act of repairing something", "renovation (act or process of renovating)"], "source": "dmklinger"}}},
    'перед': {"lemma": "перед", "url_slug": "перед", "gloss": "in front of; before", "pos": "preposition", "cefr": "B1", "enrichment": {"translation": {"en": ["1) before something; 2) in front of", "before (in front of in space) (preposition)", "just before, in front of (expressing position in space or time) (+ instrumental) (preposition)", "in front of (at or near the front part of) (preposition)", "just before, in front of (expressing motion towards) (+ accusative) (preposition)", "before (earlier than) (preposition)", "ago (+ instrumental) (preposition)"], "source": "learner_english_gloss"}}},
    'змішати': {"lemma": "змішати", "url_slug": "змішати", "gloss": "to mix, to blend, to mingle, to commingle, to compound", "pos": "verb", "cefr": "B1", "enrichment": {"translation": {"en": ["mix (stir two or more substances together)", "to mix, to blend, to mingle, to commingle, to compound", "(transitive, dated, rare) to disconcert, to dismay", "to mess up (cause disorder in)", "mix (combine items from two or more sources normally kept separate)", "(colloquial) to mix up, to confuse"], "source": "dmklinger"}}},
    'влаштувати': {"lemma": "влаштувати", "url_slug": "влаштувати", "gloss": "to arrange, to organize, to establish", "pos": "verb", "cefr": "B2", "enrichment": {"translation": {"en": ["to arrange, to organize; to suit [to settle, to get (a job)]", "(colloquial) to make", "to settle, to put in order (:affairs)", "to place, to fix up, to set up (:somebody in a position)"], "source": "learner_english_gloss"}}},
    'проігнорувати': {"lemma": "проігнорувати", "url_slug": "проігнорувати", "gloss": "to ignore, to disregard (deliberately pay no attention to)", "pos": "verb", "cefr": "B2", "enrichment": {"translation": {"en": ["ignore (to deliberately pay no attention to)", "to ignore, to disregard (deliberately pay no attention to)"], "source": "dmklinger"}}},
    'впливати': {"lemma": "впливати", "url_slug": "впливати", "gloss": "to swim in", "pos": "verb", "cefr": "B1", "enrichment": {"translation": {"en": ["to influence, to affect", "transitive: to exert an influence upon", "to swim in", "to float in", "govern ((intr.) to have a determining influence)", "to sail in"], "source": "learner_english_gloss"}}},
    'пора': {"lemma": "пора", "url_slug": "пора", "gloss": "time, period", "pos": "noun", "cefr": "A1", "enrichment": {"translation": {"en": ["pore (a tiny opening in the skin)", "aperture, pore", "time, period"], "source": "dmklinger"}}},
}
_SOURCE_ROWS: dict[str, list[dict]] = {
    'новий': [{"id": 28, "word": "нови́й", "pos": "adjective", "translations": ["new"]}],
    'зазначати': [{"id": 1164, "word": "зазнача́ти", "pos": "verb", "translations": ["to mention, to note", "to indicate, to point out"]}],
    'казка': [{"id": 2308, "word": "ка́зка", "pos": "noun", "translations": ["fable (fictitious narration to enforce some useful truth or precept)", "fairy tale (folktale)"]}],
    'аптекар': [{"id": 22128, "word": "апте́кар", "pos": "noun", "translations": ["pharmacist (professional who dispenses prescription drugs)"]}],
    'задонатити': [{"id": 26176, "word": "задона́тити", "pos": "verb", "translations": ["(colloquial) to donate"]}],
    'мотиваційний': [{"id": 8812, "word": "мотиваці́йний", "pos": "adjective", "translations": ["motivational (tending or intended to motivate)", "(relational) motivation (attributive), motivational"]}],
    'дно': [{"id": 15181, "word": "дно", "pos": "noun", "translations": ["ground (bottom of a body of water)", "bed (of a river), bottom (of a lake)", "bottom part (of an object)", "(figuratively) lowest stratum (of a capitalist society)", "bottom (bed of a body of water)", "bottom (lowest part of a container)", "bottom (lowest part)"]}],
    'ураження': [{"id": 5644, "word": "ура́ження", "pos": "noun", "translations": ["impression (overall effect of something)"]}],
    'електронний': [{"id": 1141, "word": "електро́нний", "pos": "adjective", "translations": ["electronic (pertaining to electrons)", "(relational) electron (attributive)", "electronic (of or pertaining to the Internet)", "generated by electronic device", "electronic (operating on behavior of electrons)"]}],
    'музичний': [{"id": 1674, "word": "музи́чний", "pos": "adjective", "translations": ["musical (of or relating to music)"]}],
    'тікати': [{"id": 5752, "word": "ті́кати", "pos": "verb", "translations": ["(intransitive) to tick (of a clock)"]}, {"id": 5753, "word": "тіка́ти", "pos": "verb", "translations": ["flee (to run away; to escape)", "(intransitive) to run away, to flee", "scoot (to walk fast; to go quickly; to run away hastily)"]}],
    'слізний': [{"id": 22927, "word": "слі́зний", "pos": "adjective", "translations": ["(relational) tear (water from the eyes); lacrimal", "(figuratively) plaintive, sorrowful, tearful"]}],
    'звати': [{"id": 5225, "word": "зва́ти", "pos": "verb", "translations": ["call (to request, summon, or beckon)", "(transitive, intransitive, reflexive) to call", "(transitive, intransitive) to summon", "(transitive, intransitive) to invite (for a visit, wedding, guest etc.)"]}],
    'очікувати': [{"id": 1161, "word": "очі́кувати", "pos": "verb", "translations": ["wait (delay until some event)", "(transitive) to wait", "be in for (able to expect)", "expect (to consider reasonably due)", "expect (to consider obligatory)", "remain (to await; to be left to)", "await (transitive: to wait for)", "wait on (wait for an event)", "wait on (wait for a person to do something)"]}],
    'снідати': [{"id": 14035, "word": "сні́дати", "pos": "verb", "translations": ["breakfast (to eat the morning meal)", "to have breakfast, to breakfast", "to have lunch", "to have dinner/supper"]}],
    'збільшити': [{"id": 1641, "word": "збі́льшити", "pos": "verb", "translations": ["increase (make larger)", "(transitive) to increase, to augment", "magnify (to make larger)", "(transitive) to enlarge, to magnify"]}],
    'сірий': [{"id": 4243, "word": "сі́рий", "pos": "adjective", "translations": ["gray, grey (color)"]}],
    'довкілля': [{"id": 3601, "word": "довкі́лля", "pos": "noun", "translations": ["environment (natural world or ecosystem)", "environment, milieu", "(rare) environs, neighbourhood"]}],
    'ремонт': [{"id": 1617, "word": "ремо́нт", "pos": "noun", "translations": ["act of repairing something", "renovation (act or process of renovating)"]}],
    'перед': [{"id": 20412, "word": "пе́ред", "pos": "particle", "translations": ["before (in front of in space) (preposition)", "just before, in front of (expressing position in space or time) (+ instrumental) (preposition)", "in front of (at or near the front part of) (preposition)", "just before, in front of (expressing motion towards) (+ accusative) (preposition)", "before (earlier than) (preposition)", "ago (+ instrumental) (preposition)"]}, {"id": 21490, "word": "пе́ре́д", "pos": "noun", "translations": ["front, front part"]}],
    'змішати': [{"id": 13728, "word": "зміша́ти", "pos": "verb", "translations": ["mix (stir two or more substances together)", "to mix, to blend, to mingle, to commingle, to compound", "(transitive, dated, rare) to disconcert, to dismay", "to mess up (cause disorder in)", "mix (combine items from two or more sources normally kept separate)", "(colloquial) to mix up, to confuse"]}],
    'влаштувати': [{"id": 3000, "word": "влаштува́ти", "pos": "verb", "translations": ["to arrange, to organize, to establish", "(colloquial) to make", "to settle, to put in order (:affairs)", "to place, to fix up, to set up (:somebody in a position)"]}],
    'проігнорувати': [{"id": 5100, "word": "проігнорува́ти", "pos": "verb", "translations": ["ignore (to deliberately pay no attention to)", "to ignore, to disregard (deliberately pay no attention to)"]}],
    'впливати': [{"id": 735, "word": "вплива́ти", "pos": "verb", "translations": ["transitive: to exert an influence upon", "to swim in", "to influence, to affect, to have an effect (на, + accusative)", "to float in", "govern ((intr.) to have a determining influence)", "to sail in", "govern (to exercise a determining influence on)", "affect (to influence or alter)"]}],
    'пора': [{"id": 2811, "word": "по́ра", "pos": "noun", "translations": ["pore (a tiny opening in the skin)", "aperture, pore"]}, {"id": 2812, "word": "пора́", "pos": "noun", "translations": ["time, period"]}],
    'лев': [{"id": 1082, "word": "Лев", "pos": "noun", "translations": ["Leo (astrological sign) (proper noun)", "(astronomy) Leo (constellation) (proper noun)", "a male given name, Lev, equivalent to English Leo (proper noun)", "(astronomy) Leo (zodiac sign) (proper noun)", "Leo (constellation) (proper noun)", "Leo (male given name) (proper noun)"]}, {"id": 19260, "word": "лев", "pos": "noun", "translations": ["lion (big cat Panthera leo)", "A person with a Leo star sign", "(numismatics) lev (currency of Bulgaria)", "lev (currency of Bulgaria)", "Someone with a Leo star sign"]}],
    'лютий': [{"id": 1215, "word": "лю́тий", "pos": "noun", "translations": ["February (second month of the Roman, Julian, and Gregorian calendars) (proper noun)", "February (second month of the Gregorian calendar)"]}, {"id": 3841, "word": "лю́тий", "pos": "adjective", "translations": ["fierce (extremely violent, severe, ferocious or savage)", "fierce, cruel, severe", "ferocious (Marked by extreme and violent energy)", "severe (very bad or intense)"]}],
    'покуття': [{"id": 22035, "word": "Поку́ття", "pos": "noun", "translations": ["Pokuttia, Pokuttya, Pokutia (a historical region in Ukraine) (proper noun)"]}],
    'лікарняний': [{"id": 4327, "word": "лікарня́ний", "pos": "adjective", "translations": ["Relating to a hospital"]}, {"id": 18067, "word": "лікарня́ний", "pos": "noun", "translations": ["sick day (day off due to sickness)"]}],
}


_EVAL_CASES: dict[str, dict] = {
    entry["lemma"]: entry
    for entry in json.loads((Path(__file__).parent / "fixtures/meaning_9160_eval_cases.json").read_text(encoding="utf-8"))
}


def _atlas(lemma: str, **enrichment: Any) -> dict[str, Any]:
    entry = copy.deepcopy(_ATLAS[lemma])
    entry["enrichment"].update(copy.deepcopy(enrichment))
    return entry


def _rows(*lemmas: str) -> dict[str, list[dict]]:
    return {_key(lemma): copy.deepcopy(_SOURCE_ROWS[lemma]) for lemma in lemmas}


@pytest.mark.parametrize("lemma", sorted(REVIEWED_WRONG_LEMMAS))
def test_all_reviewed_wrong_senses_are_quarantined(lemma: str) -> None:
    assert meaning_problem("ordinary meaning", lemma) == "reviewed_wrong_sense"


@pytest.mark.parametrize(
    ("text", "reason"),
    [
        ("Це визначення. Інший текст далі.", "dictionary_fragment"),
        ("Текст «прикладу»", "example_quotation"),
        ("Текст (Автор, 1985)", "dated_citation"),
        ("Прикм. до слова", "dictionary_fragment"),
        ("Присл. до слова", "dictionary_fragment"),
        ("Дієприкм. до слова", "dictionary_fragment"),
        ("слово 1》 значення", "dictionary_fragment"),
        ("слово || значення", "dictionary_fragment"),
        ("СЛОВО, ч. значення", "dictionary_fragment"),
    ],
)
def test_prohibited_patterns(text: str, reason: str) -> None:
    assert meaning_problem(text, "тест") == reason


@pytest.mark.parametrize(
    ("raw", "head"),
    [
        ("1) bill, check; 2) score", "bill"),
        ("to avoid Conjugation: 1st", "to avoid"),
        ("numeral first", "first"),
        ("anatomy: tooth", "tooth"),
        ("(imperfective) to move", "to move"),
        ("with pronoun or adverb, meaning any", ""),
        ("masculine possessive of учи́тель", ""),
        ("short form of пе́вний", ""),
        ("introducing adverbial clause", ""),
        ("indicating time", ""),
    ],
)
def test_english_dictionary_markers_and_fragments(raw: str, head: str) -> None:
    assert english_head(raw) == head


def test_same_word_sum11_is_rejected() -> None:
    assert meaning_problem("Звичайне пояснення слова", "тест", ["Звичайне пояснення слова."]) == "same_word_sum11"


def test_sum11_lookup_folds_ukrainian_capitalization(tmp_path: Path) -> None:
    db = tmp_path / "sources.db"
    with sqlite3.connect(db) as conn:
        conn.execute("CREATE TABLE sum11 (word TEXT, definition TEXT)")
        conn.execute("INSERT INTO sum11 VALUES (?, ?)", ("слово", "Звичайне пояснення слова."))
    assert load_sum11_definitions({"Слово"}, db)["Слово"] == ["Звичайне пояснення слова."]


def test_dmklinger_rows_keep_case_and_pos_partitions(tmp_path: Path) -> None:
    db = tmp_path / "sources.db"
    with sqlite3.connect(db) as conn:
        conn.execute("CREATE TABLE dmklinger_uk_en (id INTEGER, word TEXT, pos TEXT, translations TEXT, source TEXT)")
        conn.executemany("INSERT INTO dmklinger_uk_en VALUES (?, ?, ?, ?, 'dmklinger UK→EN')", [
            (row["id"], row["word"], row["pos"], json.dumps(row["translations"], ensure_ascii=False))
            for lemma in ("покуття", "лікарняний", "лев", "лютий", "впливати") for row in _SOURCE_ROWS[lemma]
        ])
    loaded = load_dmklinger_rows({"покуття", "лікарняний", "Лев", "лютий", "впливати"}, db)
    assert [row["id"] for row in loaded["лев"]] == [1082, 19260]

    def bound_id(lemma: str, pos: str, display: str) -> int | None:
        bound = _bound_dmklinger_row({"lemma": lemma, "pos": pos}, display, loaded)
        if bound is None:
            return None
        row, candidate = bound
        assert candidate == row["translations"][0]
        return row["id"]

    # A lowercase common noun never receives the capitalised region's row.
    assert bound_id("покуття", "noun", "Pokuttia") is None
    assert bound_id("Покуття", "noun", "Pokuttia") == 22035
    # The noun never receives the adjective row's meaning, and vice versa.
    assert bound_id("лікарняний", "noun", "Relating to a hospital") is None
    assert bound_id("лікарняний", "noun", "sick day (day off due to sickness)") == 18067
    assert bound_id("лікарняний", "adjective", "Relating to a hospital") == 4327
    # Mixed-name records bind per case-preserving row, not per merged entry.
    assert bound_id("лев", "noun", "Leo (astrological sign)") is None
    assert bound_id("лев", "noun", "lion (big cat Panthera leo)") == 19260
    assert bound_id("лев", "noun", "lion") is None  # the source qualifier stays load-bearing
    assert bound_id("Лев", "noun", "Leo (astrological sign)") == 1082
    # A trailing English "(proper noun)" tag alone does not exclude a lowercase month.
    assert bound_id("лютий", "noun", "February (second month of the Roman, Julian, and Gregorian calendars)") == 1215
    assert bound_id("лютий", "noun", "fierce (extremely violent, severe, ferocious or savage)") is None
    assert bound_id("лютий", "adjective", "fierce (extremely violent, severe, ferocious or savage)") == 3841
    # Only a row's primary candidate binds; a later mixed-in sense does not.
    assert bound_id("впливати", "verb", "to swim in") is None


def test_stress_homograph_partitions_are_unresolved() -> None:
    rows = _rows("пора", "тікати")
    # по́ра "pore" and пора́ "time" share case and POS; the unstressed Atlas
    # headword cannot select one, even when the display matches only one row.
    assert _bound_dmklinger_row({"lemma": "пора", "pos": "noun"}, "time", rows) is None
    assert _bound_dmklinger_row({"lemma": "тікати", "pos": "verb"}, "flee (to run away; to escape)", rows) is None
    result = _build_lexeme(_atlas("пора"), JsonVesumVerifier({}), {}, {}, rows)
    assert result is not None
    assert result["gloss"] == result["glossClean"] == ""
    assert result["meaningSource"] is None
    assert result["meaningMcEligible"] is False
    assert result["meaningWithheldReason"] == "unresolved_source_homograph"
    # Control: the same row alone would bind, so the partition is what withholds.
    alone = {"пора": [row for row in rows["пора"] if row["id"] == 2812]}
    assert _bound_dmklinger_row({"lemma": "пора", "pos": "noun"}, "time", alone)[0]["id"] == 2812


@pytest.mark.parametrize("lemma", ["покуття", "лікарняний"])
def test_wrong_case_or_source_pos_is_withheld_from_meaning_modes(lemma: str) -> None:
    entry = _EVAL_CASES[lemma]
    result = _build_lexeme(entry, JsonVesumVerifier({}), {}, {}, _rows(lemma))
    assert result is not None
    assert result["gloss"] == result["glossClean"] == ""
    assert result["meaningSource"] is None
    assert result["meaningMcEligible"] is False
    assert result["meaningWithheldReason"] == "unbound_independent_row"


def test_existing_attributed_english_is_retained() -> None:
    entry = _atlas("новий")
    assert source_bound_meaning(entry, "new", "new", None, level="A1", balla={}, dmklinger_rows=_rows("новий")) == ({
        "source": "learner_english_gloss", "field": "enrichment.translation.en",
        "mechanism": "learner_dmklinger_corrob", "supportRule": "unique_case_pos_primary_candidate_row",
        "sourceTable": "dmklinger_uk_en", "sourceRowId": 28, "sourceWord": "нови́й", "sourcePos": "adjective",
        "sourceCandidate": "new",
    }, None)
    # Without the independent row snapshot, or without a row, nothing is admitted.
    assert source_bound_meaning(entry, "new", "new", None, level="A1", balla={}) == (
        None, "missing_independent_snapshot")
    assert source_bound_meaning(entry, "new", "new", None, level="A1", balla={}, dmklinger_rows={}) == (
        None, "unbound_independent_row")


def test_only_the_supported_atlas_head_is_displayed() -> None:
    entry = _atlas("зазначати")

    def bind(display: str, level: str = "B2") -> tuple[dict | None, str | None]:
        return source_bound_meaning(entry, display, display, None, level=level, balla={},
                                    dmklinger_rows=_rows("зазначати"))

    # The whole multi-head gloss is never one sense, and a source-only
    # alternative cannot displace the Atlas head.
    assert bind("to state, note")[1] == "unbound_english_sense"
    assert bind("to mention")[1] == "unbound_english_sense"
    # An Atlas head that the attributed field does not attest is withheld.
    assert bind("to state")[1] == "unattributed_english"
    assert bind("to note")[0]["sourceRowId"] == 1164
    # A1 displays only the first Atlas head.
    assert bind("to note", level="A1")[1] == "unbound_english_sense"


def test_ukrainian_atlas_gloss_never_anchors_an_english_meaning() -> None:
    # Supersedes the earlier A1/A2 single-head allowance: a Ukrainian Atlas
    # gloss has no English sense anchor, so an attributed English candidate
    # cannot be tied to the displayed lexeme, even with a matching source row.
    entry = _atlas("казка")
    for level in ("A1", "A2"):
        assert source_bound_meaning(
            entry, "fairy tale (folktale)", "fairy tale (folktale)", None, level=level, balla={},
            dmklinger_rows=_rows("казка"),
        ) == (None, "unbound_original_sense")


def test_balla_lookup_includes_candidate_on_ukrainian_atlas_row() -> None:
    entry = {"lemma": "тест", "gloss": "Пояснення", "enrichment": {
        "translation": {"en": ["explanation"], "source": "learner_english_gloss"}}}
    assert "explanation" in candidate_balla_heads([entry])


@pytest.mark.parametrize(
    ("lemma", "reason"),
    [
        # The only source alternative keeps its sense qualifier.
        ("аптекар", "unattributed_english"),
        # "(colloquial)" is a load-bearing register label, never stripped.
        ("задонатити", "unattributed_english"),
    ],
)
def test_source_alternative_must_match_the_whole_display(lemma: str, reason: str) -> None:
    # Supersedes "supported head survives extra text": removing a source
    # qualifier or register label would change the admitted meaning (AC-02).
    result = _build_lexeme(_atlas(lemma), JsonVesumVerifier({}), {}, {}, _rows(lemma))
    assert result is not None
    assert result["gloss"] == result["glossClean"] == ""
    assert result["meaningSource"] is None
    assert result["meaningWithheldReason"] == reason


def test_embedded_source_word_is_not_a_display_head() -> None:
    entry = {"lemma": "тест", "url_slug": "test", "gloss": "American", "pos": "noun", "cefr": "A2",
             "enrichment": {"translation": {"en": ["American man"], "source": "dmklinger"}}}
    result = _build_lexeme(entry, JsonVesumVerifier({}), {}, {}, {})
    assert result is not None
    assert result["gloss"] == result["glossClean"] == ""
    assert result["meaningWithheldReason"] == "unattributed_english"


def test_unaligned_ukrainian_gloss_with_multiple_english_heads_stays_withheld() -> None:
    result = _build_lexeme(_atlas("казка"), JsonVesumVerifier({}), {}, {}, _rows("казка"))
    assert result is not None
    assert result["gloss"] == result["glossClean"] == ""
    assert result["meaningMcEligible"] is False
    assert result["meaningWithheldReason"] == "unbound_original_sense"


def test_attributive_noun_label_does_not_displace_adjective_meaning() -> None:
    entry = _atlas("мотиваційний")
    # The attributive noun head is never an admissible display.
    assert source_bound_meaning(entry, "motivation", "motivation", None, level="B2", balla={},
                                dmklinger_rows=_rows("мотиваційний"))[1] == "unbound_english_sense"
    # Bare "motivational" appears only inside the second, "(relational)"
    # candidate; the row's primary candidate keeps its qualifier. The adjective
    # is withheld (#8977 residual) rather than bound across candidates.
    result = _build_lexeme(entry, JsonVesumVerifier({}), {}, {}, _rows("мотиваційний"))
    assert result is not None
    assert result["gloss"] == result["glossClean"] == ""
    assert result["meaningWithheldReason"] == "unbound_independent_row"


# Under the row contract every pinned case is withheld at its first failing
# rule. The earlier correct heads (dictionary, successfully, to tame, ...) had
# no independently bound primary row candidate; they are #8977 coverage
# residuals, not admissions to restore in this removal-only round.
_EVALUATION_EXPECTED_REASON = {
    "безсоння": "unbound_original_sense", "буквально": "unbound_original_sense",
    "конфлікт": "unbound_original_sense", "прем'єра": "unbound_original_sense",
    "сила": "unbound_original_sense", "як-от": "unbound_original_sense",
    "бирка": "unattributed_english", "виконуватися": "unattributed_english",
    "замітка": "unattributed_english", "лиман": "unattributed_english",
    "потемнілий": "unattributed_english", "приборкати": "unattributed_english",
    "під'їзд": "unattributed_english", "словник": "unattributed_english",
    "спростувати": "unattributed_english", "щеплення": "unattributed_english",
    "зосереджуватися": "unbound_primary_learner_sense", "одягатися": "unbound_primary_learner_sense",
    "водночас": "unresolved_source_homograph",
    "бризнути": "unbound_independent_row", "перший": "unbound_independent_row",
    "рік": "unbound_independent_row", "стрічка": "unbound_independent_row",
    "успішно": "unbound_independent_row", "покуття": "unbound_independent_row",
    "лікарняний": "unbound_independent_row",
}


@pytest.mark.parametrize("entry", list(_EVAL_CASES.values()), ids=lambda entry: entry["lemma"])
def test_independent_evaluation_rows_follow_source_bound_classes(entry: dict) -> None:
    """Pinned held-out errors, withholding cases, and the case/POS failures."""
    # Every fixture carries all copied source rows for its own headword key.
    assert all(_key(row["word"]) == _key(entry["lemma"]) for row in entry["source_rows"])
    result = _build_lexeme(entry, JsonVesumVerifier({}), {}, {}, {_key(entry["lemma"]): entry["source_rows"]})
    assert result is not None
    assert result["gloss"] == result["glossClean"] == ""
    assert result["meaningSource"] is None
    assert result["meaningMcEligible"] is False
    assert result["meaningWithheldReason"] == _EVALUATION_EXPECTED_REASON[entry["lemma"]]


def test_english_does_not_replace_a_ukrainian_display() -> None:
    entry = {"lemma": "тест", "gloss": "Пояснення", "enrichment": {"translation": {"en": ["explanation"], "source": "dmklinger"}}}
    assert source_bound_meaning(entry, "Пояснення", "Пояснення", None)[0] is None
    assert source_bound_meaning(entry, "Пояснення", "Пояснення", None, dmklinger_rows={}) == (
        None, "unsafe_display_fields")


def test_reverse_index_is_not_an_attributed_meaning() -> None:
    entry = {"lemma": "тест", "gloss": "test", "enrichment": {"translation": {"en": ["test"], "source": "e2u reverse index"}}}
    assert source_bound_meaning(entry, "test", "test", None, dmklinger_rows={})[1] == "unsupported_english_source"
    sense = {"id": "test_s1", "source": "e2u reverse index", "learner_en": ["test"]}
    assert source_bound_meaning(entry, "test", "test", sense, dmklinger_rows={})[1] == "unsupported_english_source"


@pytest.mark.parametrize(
    ("lemma", "balla", "reason"),
    [
        # Row 15181's primary candidate is "ground (...)"; a later candidate
        # cannot bind (superseded: the earlier Balla-supported retention).
        ("дно", {}, "unbound_independent_row"),
        # The source row itself carries the враження sense; Balla vetoes it.
        ("ураження", {"impression": [_BALLA_IMPRESSION]}, "reverse_source_conflict"),
        ("електронний", {"electron": [_BALLA_ELECTRON]}, "unbound_english_sense"),
        ("музичний", {}, "unbound_english_sense"),
        ("тікати", {}, "unattributed_english"),
        ("слізний", {}, "unbound_independent_row"),
    ],
)
def test_qualified_head_requires_same_lemma_independent_support(
    lemma: str, balla: dict[str, list[str]], reason: str,
) -> None:
    result = _build_lexeme(_atlas(lemma), JsonVesumVerifier({}), {}, balla, _rows(lemma))
    assert result is not None
    assert result["gloss"] == result["glossClean"] == ""
    assert result["meaningSource"] is None
    assert result["meaningWithheldReason"] == reason


@pytest.mark.parametrize("text", [
    "used before awkward consonant clusters and chiefly before мно́ю",
    "female equivalent of нача́льник", "endearing form of мале́нький",
    "female equivalent of незнайо́мець", "female equivalent of однокла́сник",
    "kiwi 2",
])
def test_cross_reference_and_numbered_english_fragments_are_withheld(text: str) -> None:
    assert meaning_problem(text, "тест") == "dictionary_fragment"


@pytest.mark.parametrize("raw", [
    "intensified form of (superlative) найкра́ще (najkrášče)",
    "form of інший", "alternative form of інший", "diminutive of інший",
    "endearing form of інший", "female equivalent of інший",
    "male equivalent of інший", "a specific spelling of інший",
    "alternative letter-case form of інший", "dialectal form of інший",
    "used as a friendly form of інший",
])
def test_cross_reference_source_vocabulary_cannot_become_a_head(raw: str) -> None:
    assert english_head(raw) == ""
    assert _candidate_alternatives(raw) == set()


def test_mixed_script_fragment_is_rejected_before_qualifier_splitting() -> None:
    raw = "intensified form of (superlative) найкра́ще (najkrášče)"
    entry = {"lemma": "якнайкраще", "url_slug": "якнайкраще", "gloss": "прислівник до якнайкращий",
             "pos": "adv", "cefr": "A2", "enrichment": {"translation": {"en": [raw], "source": "kaikki"}}}
    result = _build_lexeme(entry, JsonVesumVerifier({}), {}, {}, {})
    assert result is not None and result["gloss"] == ""
    assert result["meaningWithheldReason"] == "unsafe_display_fields"


@pytest.mark.parametrize("raw", ["intensified form of another word", "form of another word",
                                "alternative form of another word", "diminutive of another word",
                                "female equivalent of another word", "a specific spelling of another word"])
def test_english_only_cross_reference_stubs_are_not_meanings(raw: str) -> None:
    assert english_head(raw) == ""


@pytest.mark.parametrize(("lemma", "gloss"), [
    ("навколішки", "onto one's knees (get down, get up, fall, etc.)"),
    ("інтелектуальний", "intellectual (pertaining to, or performed by, the intellect)"),
    ("практикувати", "to practise (perform or observe in a habitual fashion; put into practice; apply in practice)"),
    ("зіграти", "to play (to render (a musical title, compositional style, film title, etc.) using a musical instrument or device)"),
])
def test_qualifier_pieces_are_never_top_level_alternatives(lemma: str, gloss: str) -> None:
    assert split_english_alternatives(gloss) == [gloss]
    for piece in ("get up", "or performed by", "put into practice", "compositional style"):
        assert not english_candidates_support_display([gloss], piece)
    entry = {"lemma": lemma, "url_slug": lemma, "gloss": gloss, "pos": "verb", "cefr": "B1",
             "enrichment": {"translation": {"en": [gloss], "source": "dmklinger"}}}
    result = _build_lexeme(entry, JsonVesumVerifier({}), {}, {}, {})
    assert result is not None and result["gloss"] == ""
    assert result["meaningWithheldReason"] == "unbound_english_sense"


def test_top_level_slash_is_an_alternative() -> None:
    assert split_english_alternatives("to call / be named") == ["to call", "be named"]
    entry = _atlas("звати")
    # The slash-joined gloss is two heads, never one display.
    assert source_bound_meaning(entry, "to call / be named", "to call / be named", None, level="A1", balla={},
                                dmklinger_rows=_rows("звати"))[1] == "unbound_english_sense"
    # Superseded: "to call" was retained via a Balla head. No attributed
    # candidate or source row states that bare head, so it is withheld.
    result = _build_lexeme(entry, JsonVesumVerifier({}), {}, {}, _rows("звати"))
    assert result is not None and result["gloss"] == ""
    assert result["meaningWithheldReason"] == "unattributed_english"


@pytest.mark.parametrize(("lemma", "enrichment", "balla", "expected", "reason"), [
    ("очікувати", {}, {}, "", "unbound_independent_row"),
    ("снідати", {}, {}, "", "unbound_primary_learner_sense"),
    # A recorded aspect partner and a "див." card are not row evidence.
    ("збільшити", {"verb_pedagogy": {"aspect_partner": {
        "lemma": "збільшувати", "source": "Anna Ohoiko", "url_slug": "збільшувати"}}}, {}, "", "unattributed_english"),
    # British/American spelling of the same source alternative binds row 4243.
    ("сірий", {}, {}, "grey", None),
    ("довкілля", {}, {}, "", "unbound_independent_row"),
    ("ремонт", {}, {}, "", "unattributed_english"),
    ("ураження", {}, {"impression": [_BALLA_IMPRESSION]}, "", "reverse_source_conflict"),
])
def test_independent_support_uses_same_sense_variants_and_forward_evidence(
    lemma: str, enrichment: dict, balla: dict, expected: str, reason: str | None,
) -> None:
    # Superseded: Balla synonym bridges, aspect partners and forward cards no
    # longer admit a head; only a uniquely bound source row does.
    result = _build_lexeme(_atlas(lemma, **enrichment), JsonVesumVerifier({}), {}, balla, _rows(lemma))
    assert result is not None
    assert result["gloss"] == result["glossClean"] == expected
    assert result["meaningWithheldReason"] == reason
    if expected:
        assert result["meaningSource"]["sourceRowId"] == 4243


def test_learner_list_first_sense_must_fit_atlas_head() -> None:
    result = _build_lexeme(_atlas("впливати"), JsonVesumVerifier({}), {}, {}, _rows("впливати"))
    assert result is not None and result["gloss"] == ""
    assert result["meaningWithheldReason"] == "unbound_primary_learner_sense"
    assert _bound_dmklinger_row(_atlas("впливати"), "to swim in", _rows("впливати")) is None


@pytest.mark.parametrize(("lemma", "enrichment", "balla", "expected", "reason"), [
    # Atlas preposition vs source particle, and no exact attributed head.
    ("перед", {}, {}, "", "unattributed_english"),
    ("змішати", {"definition_cards": [{"id": "vts", "definitions": [
        "зміша́ти I див. змішувати . II - а ю, - а єш, док. , перех. , розм. Викликати у кого-небудь "
        "збентеження, ніяковість; збентежити, засоромити."]}]}, {}, "", "unbound_independent_row"),
    # Row 3000 binds "to arrange", but Balla maps arrange to other lemmas and
    # the aspect partner is not evidence, so the conservative veto holds.
    ("влаштувати", {"verb_pedagogy": {"aspect_partner": {
        "lemma": "влаштовувати", "source": "Anna Ohoiko", "url_slug": "влаштовувати"}}},
     {"arrange": [_BALLA_ARRANGE]}, "", "reverse_source_conflict"),
    ("проігнорувати", {}, {}, "", "unbound_independent_row"),
    ("зазначати", {}, {}, "to note", None),
])
def test_independent_support_handles_source_phrasing_and_recorded_aspect_links(
    lemma: str, enrichment: dict, balla: dict, expected: str, reason: str | None,
) -> None:
    result = _build_lexeme(_atlas(lemma, **enrichment), JsonVesumVerifier({}), {}, balla, _rows(lemma))
    assert result is not None
    assert result["gloss"] == result["glossClean"] == expected
    assert result["meaningWithheldReason"] == reason
    if expected:
        assert result["meaningSource"]["sourceRowId"] == 1164


def test_balla_example_is_not_a_headword_mapping() -> None:
    # "~ microscope — електронний мікроскоп" is an example, not a head mapping.
    assert not _balla_maps_lemma([_BALLA_ELECTRON], "електронний")
    assert _balla_maps_lemma([_BALLA_ELECTRONIC], "електронний")
    assert _balla_maps_lemma([_BALLA_IMPRESSION], "враження")
    assert not _balla_maps_lemma([_BALLA_IMPRESSION], "ураження")


def test_withheld_lexeme_keeps_nonmeaning_record() -> None:
    entry = {"lemma": "тест", "url_slug": "test", "gloss": "Прикм. до слова", "pos": "adj",
             "enrichment": {"cefr": {"level": "B1"}}}
    lexeme = _build_lexeme(entry, JsonVesumVerifier({}), {})
    assert lexeme is not None
    assert lexeme["lemmaId"] == "test"
    assert lexeme["gloss"] == lexeme["glossClean"] == ""
    assert lexeme["meaningMcEligible"] is False


def test_production_builder_requires_same_word_source_snapshot(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["--sources-db", str(tmp_path / "missing.db")]) == 1
    assert "requires --sources-db" in capsys.readouterr().err


def test_gate_handles_empty_sources_database(tmp_path: Path) -> None:
    db = tmp_path / "empty.db"
    sqlite3.connect(db).close()
    (tmp_path / "practice-lexemes.A1.json").write_text(
        json.dumps({"lexemes": [{"lemmaId": "x", "lemma": "тест", "gloss": "test", "glossClean": "test",
                                "meaningSource": {"source": "source", "field": "translation.en"}}]}), encoding="utf-8"
    )
    _, violations = audit_practice_shards(tmp_path, verify_vesum=False, check_volume=False, sources_db=db)
    assert any(item["type"] == "SOURCE_DB_INVALID" for item in violations)


def test_gate_checks_both_meaning_fields_without_optional_database(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    from scripts.audit import practice_quality_gate

    monkeypatch.setattr(practice_quality_gate, "DEFAULT_SOURCES_DB", tmp_path / "absent.db")
    (tmp_path / "practice-lexemes.A1.json").write_text(
        json.dumps({"lexemes": [{"lemmaId": "x", "lemma": "тест", "gloss": "test",
                                "glossClean": "test (Author, 1980)",
                                "meaningSource": {"source": "source", "field": "translation.en"}}]}), encoding="utf-8"
    )
    _, violations = audit_practice_shards(tmp_path, verify_vesum=False, check_volume=False)
    assert any(item["type"] == "UNSAFE_PRACTICE_MEANING" and "glossClean" in item["message"] for item in violations)
    assert not any(item["type"] == "SOURCE_DB_INVALID" for item in violations)
