"""Tests for the Git hook delegator installer (scripts/install_git_hooks.sh)."""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
INSTALLER_SCRIPT = REPO_ROOT / "scripts/install_git_hooks.sh"
REQUIRED_HOOKS = (
    "pre-commit",
    "commit-msg",
    "pre-push",
    "post-merge",
    "post-checkout",
    "post-commit",
)
SUPPORT_FILES = (
    "_lib.sh",
    "check-pytest-stamp.py",
    "pytest_stamp.py",
)


def _clean_env(extra: dict[str, str] | None = None) -> dict[str, str]:
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    if extra:
        env.update(extra)
    return env


def _run(
    command: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        capture_output=True,
        check=check,
        cwd=cwd,
        env=_clean_env(env),
        text=True,
        timeout=60,
    )


def _git(
    repo: Path,
    *args: str,
    env: dict[str, str] | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    return _run(["git", *args], cwd=repo, env=env, check=check)


def _write_executable(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    path.chmod(0o755)


def _fixture_repository(tmp_path: Path) -> tuple[Path, dict[str, str]]:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-b", "main")
    _git(repo, "config", "user.email", "hook-test@example.invalid")
    _git(repo, "config", "user.name", "Hook Test")

    (repo / "scripts").mkdir()
    shutil.copy2(INSTALLER_SCRIPT, repo / "scripts/install_git_hooks.sh")
    (repo / "scripts/install_git_hooks.sh").chmod(0o755)

    hook_log = tmp_path / "hook.log"
    env = {
        "HOOK_LOG": str(hook_log),
    }

    for hook_name in REQUIRED_HOOKS:
        if hook_name == "commit-msg":
            _write_executable(
                repo / f".githooks/{hook_name}",
                '#!/usr/bin/env bash\nset -euo pipefail\nprintf "commit-msg:%s\\n" "$1" >> "$HOOK_LOG"\n',
            )
        else:
            _write_executable(
                repo / f".githooks/{hook_name}",
                f'#!/usr/bin/env bash\nset -euo pipefail\nprintf "{hook_name}\\n" >> "$HOOK_LOG"\n',
            )

    for support_file in SUPPORT_FILES:
        (repo / f".githooks/{support_file}").write_text(f"# {support_file}\n", encoding="utf-8")

    (repo / "README.md").write_text("initial\n", encoding="utf-8")
    _git(repo, "add", ".")
    _git(repo, "commit", "-m", "initial commit", env=env)

    return repo, env


def test_installer_unsets_core_hooks_path_and_creates_delegators(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    # Simulate prior state where core.hooksPath was pointed at .githooks
    _git(repo, "config", "core.hooksPath", ".githooks", env=env)
    assert _git(repo, "config", "--get", "core.hooksPath", env=env).stdout.strip() == ".githooks"

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert result.returncode == 0
    for hook_name in REQUIRED_HOOKS:
        assert f"{hook_name}: installed" in result.stdout

    # (a) core.hooksPath is unset
    check_config = _git(repo, "config", "--get", "core.hooksPath", env=env, check=False)
    assert check_config.returncode != 0

    # (b) delegators present + executable
    hooks_dir = repo / ".git/hooks"
    for hook_name in REQUIRED_HOOKS:
        delegator = hooks_dir / hook_name
        assert delegator.is_file(), f"Expected delegator at {delegator}"
        assert os.access(delegator, os.X_OK), f"Delegator at {delegator} must be executable"
        content = delegator.read_text(encoding="utf-8")
        assert "# generated by scripts/install_git_hooks.sh" in content
        assert f'hook="$root/.githooks/{hook_name}"' in content

    # Non-hook files must not have delegators
    for support_file in SUPPORT_FILES:
        assert not (hooks_dir / support_file).exists()


def test_commit_in_linked_worktree_triggers_tracked_hook(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)

    worktree = tmp_path / "worktree"
    _git(repo, "worktree", "add", "-b", "feature", str(worktree), env=env)

    (worktree / "change.txt").write_text("worktree change\n", encoding="utf-8")
    _git(worktree, "add", "change.txt", env=env)
    _git(worktree, "commit", "-m", "feature commit", env=env)

    hook_log = Path(env["HOOK_LOG"]).read_text(encoding="utf-8").splitlines()
    # commit-msg, pre-commit, and post-commit in linked worktree triggered the tracked hook
    assert "pre-commit" in hook_log
    assert any(line.startswith("commit-msg:") for line in hook_log)
    assert "post-commit" in hook_log


def test_installer_is_idempotent(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)

    # First run: installed
    run1 = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert run1.returncode == 0
    for hook_name in REQUIRED_HOOKS:
        assert f"{hook_name}: installed" in run1.stdout

    # Second run: kept
    run2 = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert run2.returncode == 0
    for hook_name in REQUIRED_HOOKS:
        assert f"{hook_name}: kept" in run2.stdout

    check_config = _git(repo, "config", "--get", "core.hooksPath", env=env, check=False)
    assert check_config.returncode != 0

    # Commit inside a LINKED worktree and verify tracked hooks fire
    worktree = tmp_path / "worktree"
    _git(repo, "worktree", "add", "-b", "feature-idempotent", str(worktree), env=env)
    (worktree / "change.txt").write_text("idempotent change\n", encoding="utf-8")
    _git(worktree, "add", "change.txt", env=env)
    _git(worktree, "commit", "-m", "idempotent commit", env=env)

    hook_log = Path(env["HOOK_LOG"]).read_text(encoding="utf-8").splitlines()
    assert "pre-commit" in hook_log
    assert any(line.startswith("commit-msg:") for line in hook_log)
    assert "post-commit" in hook_log


# Wrappers exactly as Entire CLI 0.8.42 writes them (`entire configure --force`) when no
# <name>.pre-entire exists yet, and after one exists (chain block appended).
ENTIRE_WRAPPERS = {
    "commit-msg": (
        "#!/bin/sh\n"
        "# Entire CLI hooks\n"
        "# Commit-msg hook: strip trailer if no user content (allows aborting empty commits)\n"
        'if command -v entire >/dev/null 2>&1; then entire hooks git commit-msg "$1" || true; '
        "else printf '%s\\n' '[entire] Entire CLI is enabled but not installed or not on PATH. "
        "Skipping Entire Git hook; continuing. Installation guide: "
        "https://docs.entire.io/cli/installation#installation-methods' >&2 || :; fi\n"
    ),
    "pre-push": (
        "#!/bin/sh\n"
        "# Entire CLI hooks\n"
        "# Pre-push hook: push session logs alongside user's push\n"
        '# $1 is the remote name (e.g., "origin")\n'
        'if command -v entire >/dev/null 2>&1; then entire hooks git pre-push "$1"; else :; fi\n'
    ),
    "post-commit": (
        "#!/bin/sh\n"
        "# Entire CLI hooks\n"
        "# Post-commit hook: condense session data if commit has Entire-Checkpoint trailer\n"
        "if command -v entire >/dev/null 2>&1; then entire hooks git post-commit 2>/dev/null || true; else :; fi\n"
    ),
}


def _entire_chained(hook_name: str) -> str:
    return (
        ENTIRE_WRAPPERS[hook_name] + "# Chain: run pre-existing hook\n"
        '_entire_hook_dir="$(dirname "$0")"\n'
        f'if [ -x "$_entire_hook_dir/{hook_name}.pre-entire" ]; then\n'
        f'    "$_entire_hook_dir/{hook_name}.pre-entire" "$@"\n'
        "fi\n"
    )


def _install_entire_wrappers(repo: Path, env: dict[str, str], tmp_path: Path) -> Path:
    """Install Entire's unchained wrappers plus a stub `entire` that logs its calls."""
    hooks_dir = repo / ".git/hooks"
    for hook_name, content in ENTIRE_WRAPPERS.items():
        _write_executable(hooks_dir / hook_name, content)
    stub_bin = tmp_path / "bin"
    _write_executable(
        stub_bin / "entire",
        '#!/bin/sh\nprintf "entire:%s\\n" "$*" >> "$HOOK_LOG"\n',
    )
    env["PATH"] = f"{stub_bin}{os.pathsep}{os.environ['PATH']}"
    return hooks_dir


def test_entire_wrappers_gain_entire_chain_block(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    hooks_dir = _install_entire_wrappers(repo, env, tmp_path)

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    for hook_name in ENTIRE_WRAPPERS:
        assert f"{hook_name}: added Entire chain to {hook_name}.pre-entire" in result.stdout
        assert f"{hook_name}: chained-under-entire" in result.stdout
        # Byte-identical to what Entire itself writes once <name>.pre-entire exists.
        assert (hooks_dir / hook_name).read_text(encoding="utf-8") == _entire_chained(hook_name)
        assert os.access(hooks_dir / hook_name, os.X_OK)
        pre_entire = hooks_dir / f"{hook_name}.pre-entire"
        assert os.access(pre_entire, os.X_OK)
        assert "# generated by scripts/install_git_hooks.sh" in pre_entire.read_text(encoding="utf-8")

    rerun = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert "added Entire chain" not in rerun.stdout
    for hook_name in ENTIRE_WRAPPERS:
        assert f"{hook_name}: chained-under-entire" in rerun.stdout
        assert (hooks_dir / hook_name).read_text(encoding="utf-8") == _entire_chained(hook_name)

    worktree = tmp_path / "worktree"
    _git(repo, "worktree", "add", "-b", "feature-entire", str(worktree), env=env)
    (worktree / "wt-file.txt").write_text("entire payload\n", encoding="utf-8")
    _git(worktree, "add", "wt-file.txt", env=env)
    _git(worktree, "commit", "-m", "chained commit in worktree", env=env)

    hook_log = Path(env["HOOK_LOG"]).read_text(encoding="utf-8").splitlines()
    assert any(line.startswith("entire:hooks git commit-msg ") for line in hook_log)
    assert any(line.startswith("commit-msg:") for line in hook_log)
    assert "entire:hooks git post-commit" in hook_log
    assert "post-commit" in hook_log


def test_failing_repo_hooks_block_commit_and_push_under_entire(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    _install_entire_wrappers(repo, env, tmp_path)
    remote = tmp_path / "remote.git"
    _git(tmp_path, "init", "--bare", "-b", "main", str(remote))
    _git(repo, "remote", "add", "origin", str(remote))
    _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)

    for hook_name in ("commit-msg", "pre-push"):
        _write_executable(
            repo / f".githooks/{hook_name}",
            f'#!/usr/bin/env bash\nprintf "{hook_name}-stdin:%s\\n" "$(wc -l)" >> "$HOOK_LOG"\nexit 1\n',
        )

    commit = _git(repo, "commit", "--allow-empty", "-m", "blocked", env=env, check=False)
    assert commit.returncode != 0
    assert _git(repo, "rev-list", "--count", "HEAD", env=env).stdout.strip() == "1"

    push = _git(repo, "push", "origin", "HEAD:refs/heads/probe", env=env, check=False)
    assert push.returncode != 0
    assert _git(remote, "for-each-ref", "refs/heads/probe", env=env).stdout == ""

    hook_log = Path(env["HOOK_LOG"]).read_text(encoding="utf-8").splitlines()
    assert "entire:hooks git pre-push origin" in hook_log
    # The repo pre-push still receives git's ref list on stdin after Entire's hook ran.
    assert "pre-push-stdin:1" in hook_log


def _write_pre_commit_config(repo: Path, text: str) -> None:
    (repo / ".pre-commit-config.yaml").write_text(text, encoding="utf-8")


CHECK_CONFIG = """\
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: local
    hooks:
      - id: one
        stages: [pre-commit, manual]
      - id: two
        stages:
          - push
      - id: three
        entry: x
"""


def test_check_fails_until_entire_wrappers_chain(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    _write_pre_commit_config(repo, CHECK_CONFIG)
    _install_entire_wrappers(repo, env, tmp_path)
    hooks_dir = repo / ".git/hooks"
    # Host state before #9195: delegators at <name>.pre-entire beside Entire's unchained wrappers.
    _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    for hook_name, content in ENTIRE_WRAPPERS.items():
        _write_executable(hooks_dir / hook_name, content)
    (hooks_dir / "pre-commit").unlink()

    before = _run(["bash", "scripts/install_git_hooks.sh", "--check"], cwd=repo, env=env, check=False)
    assert before.returncode == 1
    assert "commit-msg: UNREACHABLE" in before.stderr
    assert "pre-push: UNREACHABLE" in before.stderr
    assert "pre-commit: UNREACHABLE" in before.stderr
    assert "manual" not in before.stdout + before.stderr
    # --check is read-only.
    assert (hooks_dir / "pre-push").read_text(encoding="utf-8") == ENTIRE_WRAPPERS["pre-push"]
    assert not (hooks_dir / "pre-commit").exists()

    _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    after = _run(["bash", "scripts/install_git_hooks.sh", "--check"], cwd=repo, env=env)
    assert "commit-msg: ok (chained under Entire)" in after.stdout
    assert "pre-push: ok (chained under Entire)" in after.stdout
    assert "pre-commit: ok (delegator)" in after.stdout


def test_check_rejects_foreign_pre_entire_and_missing_tracked_hook(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    _write_pre_commit_config(repo, "default_install_hook_types: [pre-push, pre-merge-commit]\nrepos: []\n")
    hooks_dir = _install_entire_wrappers(repo, env, tmp_path)
    _write_executable(hooks_dir / "pre-push.pre-entire", "#!/bin/sh\nexit 0\n")

    install = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert "pre-push: skipped" in install.stdout

    check = _run(["bash", "scripts/install_git_hooks.sh", "--check"], cwd=repo, env=env, check=False)
    assert check.returncode == 1
    assert "pre-push: UNREACHABLE" in check.stderr
    assert "pre-merge-commit: UNREACHABLE — no executable tracked hook" in check.stderr


def test_check_covers_every_stage_the_repository_config_declares(tmp_path: Path) -> None:
    yaml = pytest.importorskip("yaml")
    config_text = (REPO_ROOT / ".pre-commit-config.yaml").read_text(encoding="utf-8")
    config = yaml.safe_load(config_text)
    aliases = {"commit": "pre-commit", "push": "pre-push", "merge-commit": "pre-merge-commit"}
    declared = set(config.get("default_install_hook_types", [])) | set(config.get("default_stages", []))
    for repo_entry in config["repos"]:
        for hook in repo_entry["hooks"]:
            declared |= set(hook.get("stages", []))
    declared = {aliases.get(stage, stage) for stage in declared} - {"manual"}
    assert {"commit-msg", "pre-push"} <= declared

    repo, env = _fixture_repository(tmp_path)
    _write_pre_commit_config(repo, config_text)
    _install_entire_wrappers(repo, env, tmp_path)
    _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)

    check = _run(["bash", "scripts/install_git_hooks.sh", "--check"], cwd=repo, env=env)
    reported = {line.split(":", 1)[0] for line in check.stdout.splitlines() if ": ok (" in line}
    assert reported == declared


def test_foreign_hook_is_preserved_and_skipped(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    hooks_dir = repo / ".git/hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    # Custom hook created manually by a user (no Entire marker, no generated marker)
    foreign_content = '#!/usr/bin/env bash\nset -euo pipefail\nprintf "foreign-commit-msg\\n" >> "$HOOK_LOG"\nexit 0\n'
    _write_executable(hooks_dir / "commit-msg", foreign_content)

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert result.returncode == 0
    assert "commit-msg: skipped" in result.stdout
    assert "WARN:" in result.stderr
    assert "pre-commit: installed" in result.stdout

    # Foreign hook was NOT overwritten
    assert (hooks_dir / "commit-msg").read_text(encoding="utf-8") == foreign_content

    # When committing inside a LINKED worktree, foreign hook runs and tracked commit-msg does not run
    worktree = tmp_path / "worktree"
    _git(repo, "worktree", "add", "-b", "feature-foreign", str(worktree), env=env)
    (worktree / "wt-foreign.txt").write_text("foreign hook test\n", encoding="utf-8")
    _git(worktree, "add", "wt-foreign.txt", env=env)
    _git(worktree, "commit", "-m", "foreign hook commit", env=env)

    hook_log = Path(env["HOOK_LOG"]).read_text(encoding="utf-8").splitlines()
    assert "foreign-commit-msg" in hook_log
    assert "pre-commit" in hook_log
    assert not any(line.startswith("commit-msg:") for line in hook_log)
    assert (hooks_dir / "commit-msg").read_text(encoding="utf-8") == foreign_content


def test_preserves_custom_core_hooks_path(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    custom_path = tmp_path / "custom-hooks"
    _git(repo, "config", "core.hooksPath", str(custom_path), env=env)

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert result.returncode == 0
    assert f"Found explicit core.hooksPath={custom_path}" in result.stdout
    assert _git(repo, "config", "--get", "core.hooksPath", env=env).stdout.strip() == str(custom_path)


def test_extra_executable_hook_gets_delegator(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    _write_executable(
        repo / ".githooks/reference-transaction",
        '#!/usr/bin/env bash\nset -euo pipefail\nprintf "ref-tx:%s\\n" "$1" >> "$HOOK_LOG"\n',
    )

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert result.returncode == 0
    assert "reference-transaction: installed" in result.stdout

    delegator = repo / ".git/hooks/reference-transaction"
    assert delegator.is_file()
    assert os.access(delegator, os.X_OK)


def test_installer_refuses_incomplete_hook_directory_and_leaves_hooks_untouched(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    (repo / ".githooks/commit-msg").unlink()

    # Ensure common hooks dir doesn't exist yet
    hooks_dir = repo / ".git/hooks"
    if hooks_dir.exists():
        shutil.rmtree(hooks_dir)

    result = _run(
        ["bash", "scripts/install_git_hooks.sh"],
        cwd=repo,
        env=env,
        check=False,
    )
    assert result.returncode == 1
    assert "Expected executable hook at" in result.stderr
    assert "commit-msg" in result.stderr
    # Validation ran before touching common hooks dir
    assert not hooks_dir.exists()


def test_installer_refuses_missing_support_file_and_leaves_hooks_untouched(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    (repo / ".githooks/check-pytest-stamp.py").unlink()

    hooks_dir = repo / ".git/hooks"
    if hooks_dir.exists():
        shutil.rmtree(hooks_dir)

    result = _run(
        ["bash", "scripts/install_git_hooks.sh"],
        cwd=repo,
        env=env,
        check=False,
    )
    assert result.returncode == 1
    assert "Expected readable hook support file at" in result.stderr
    assert "check-pytest-stamp.py" in result.stderr
    assert not hooks_dir.exists()


def test_installer_refuses_non_executable_hook(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    (repo / ".githooks/pre-push").chmod(0o644)

    result = _run(
        ["bash", "scripts/install_git_hooks.sh"],
        cwd=repo,
        env=env,
        check=False,
    )
    assert result.returncode == 1
    assert "Expected executable hook at" in result.stderr
    assert "pre-push" in result.stderr
