"""Tests for the Git hook delegator installer (scripts/install_git_hooks.sh)."""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INSTALLER_SCRIPT = REPO_ROOT / "scripts/install_git_hooks.sh"


def _clean_env(extra: dict[str, str] | None = None) -> dict[str, str]:
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    if extra:
        env.update(extra)
    return env


def _run(
    command: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        capture_output=True,
        check=check,
        cwd=cwd,
        env=_clean_env(env),
        text=True,
        timeout=60,
    )


def _git(
    repo: Path,
    *args: str,
    env: dict[str, str] | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    return _run(["git", *args], cwd=repo, env=env, check=check)


def _write_executable(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    path.chmod(0o755)


def _fixture_repository(tmp_path: Path) -> tuple[Path, dict[str, str]]:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-b", "main")
    _git(repo, "config", "user.email", "hook-test@example.invalid")
    _git(repo, "config", "user.name", "Hook Test")

    (repo / "scripts").mkdir()
    shutil.copy2(INSTALLER_SCRIPT, repo / "scripts/install_git_hooks.sh")
    (repo / "scripts/install_git_hooks.sh").chmod(0o755)

    hook_log = tmp_path / "hook.log"
    env = {
        "HOOK_LOG": str(hook_log),
    }

    # Tracked minimal commit-msg hook
    _write_executable(
        repo / ".githooks/commit-msg",
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        'printf "commit-msg:%s\\n" "$1" >> "$HOOK_LOG"\n',
    )
    # Tracked minimal pre-commit hook
    _write_executable(
        repo / ".githooks/pre-commit",
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        'printf "pre-commit\\n" >> "$HOOK_LOG"\n',
    )
    # Support files to ensure installer ignores them
    (repo / ".githooks/_lib.sh").write_text("# support library\n", encoding="utf-8")
    (repo / ".githooks/pytest_stamp.py").write_text("# python helper\n", encoding="utf-8")

    (repo / "README.md").write_text("initial\n", encoding="utf-8")
    _git(repo, "add", ".")
    _git(repo, "commit", "-m", "initial commit", env=env)

    return repo, env


def test_installer_unsets_core_hooks_path_and_creates_delegators(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    # Simulate prior state where core.hooksPath was pointed at .githooks
    _git(repo, "config", "core.hooksPath", ".githooks", env=env)
    assert _git(repo, "config", "--get", "core.hooksPath", env=env).stdout.strip() == ".githooks"

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert result.returncode == 0
    assert "commit-msg: installed" in result.stdout
    assert "pre-commit: installed" in result.stdout

    # (a) core.hooksPath is unset
    check_config = _git(repo, "config", "--get", "core.hooksPath", env=env, check=False)
    assert check_config.returncode != 0

    # (b) delegators present + executable
    hooks_dir = repo / ".git/hooks"
    for hook_name in ("commit-msg", "pre-commit"):
        delegator = hooks_dir / hook_name
        assert delegator.is_file(), f"Expected delegator at {delegator}"
        assert os.access(delegator, os.X_OK), f"Delegator at {delegator} must be executable"
        content = delegator.read_text(encoding="utf-8")
        assert "# generated by scripts/install_git_hooks.sh" in content
        assert f'hook="$root/.githooks/{hook_name}"' in content

    # Non-hook files must not have delegators
    assert not (hooks_dir / "_lib.sh").exists()
    assert not (hooks_dir / "pytest_stamp.py").exists()


def test_commit_in_linked_worktree_triggers_tracked_hook(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)

    worktree = tmp_path / "worktree"
    _git(repo, "worktree", "add", "-b", "feature", str(worktree), env=env)

    (worktree / "change.txt").write_text("worktree change\n", encoding="utf-8")
    _git(worktree, "add", "change.txt", env=env)
    _git(worktree, "commit", "-m", "feature commit", env=env)

    hook_log = Path(env["HOOK_LOG"]).read_text(encoding="utf-8").splitlines()
    # (c) commit-msg and pre-commit in linked worktree triggered the tracked hook
    assert "pre-commit" in hook_log
    assert any(line.startswith("commit-msg:") for line in hook_log)


def test_installer_is_idempotent(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)

    # First run: installed
    run1 = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert run1.returncode == 0
    assert "commit-msg: installed" in run1.stdout
    assert "pre-commit: installed" in run1.stdout

    # Second run: kept
    run2 = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert run2.returncode == 0
    assert "commit-msg: kept" in run2.stdout
    assert "pre-commit: kept" in run2.stdout

    check_config = _git(repo, "config", "--get", "core.hooksPath", env=env, check=False)
    assert check_config.returncode != 0


def test_pre_existing_entire_wrapper_is_preserved_and_chained(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    hooks_dir = repo / ".git/hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    # Pre-existing Entire CLI wrapper
    entire_wrapper_content = (
        "#!/bin/sh\n"
        "# Entire CLI hooks\n"
        'printf "entire-commit-msg-wrapper\\n" >> "$HOOK_LOG"\n'
        'if [ -x "$0.pre-entire" ]; then\n'
        '    exec "$0.pre-entire" "$@"\n'
        "fi\n"
    )
    _write_executable(hooks_dir / "commit-msg", entire_wrapper_content)

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert result.returncode == 0
    assert "commit-msg: chained-under-entire" in result.stdout
    assert "pre-commit: installed" in result.stdout

    # (e) Entire wrapper preserved at commit-msg
    commit_msg_hook = hooks_dir / "commit-msg"
    assert commit_msg_hook.read_text(encoding="utf-8") == entire_wrapper_content

    # Delegator written to commit-msg.pre-entire
    pre_entire = hooks_dir / "commit-msg.pre-entire"
    assert pre_entire.is_file()
    assert os.access(pre_entire, os.X_OK)
    assert "# generated by scripts/install_git_hooks.sh" in pre_entire.read_text(encoding="utf-8")

    # When committing, both Entire wrapper and tracked hook run via chain
    (repo / "newfile.txt").write_text("payload\n", encoding="utf-8")
    _git(repo, "add", "newfile.txt", env=env)
    _git(repo, "commit", "-m", "test chained commit", env=env)

    hook_log = Path(env["HOOK_LOG"]).read_text(encoding="utf-8").splitlines()
    assert "entire-commit-msg-wrapper" in hook_log
    assert any(line.startswith("commit-msg:") for line in hook_log)

    # Re-running installer preserves Entire wrapper and chaining (idempotent)
    run_again = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert run_again.returncode == 0
    assert "commit-msg: chained-under-entire" in run_again.stdout
    assert commit_msg_hook.read_text(encoding="utf-8") == entire_wrapper_content


def test_foreign_hook_is_preserved_and_skipped(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    hooks_dir = repo / ".git/hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    # Custom hook created manually by a user (no Entire marker, no generated marker)
    foreign_content = "#!/bin/sh\n# Custom personal hook\nexit 0\n"
    _write_executable(hooks_dir / "commit-msg", foreign_content)

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert result.returncode == 0
    assert "commit-msg: skipped" in result.stdout
    assert "WARN:" in result.stderr
    assert "pre-commit: installed" in result.stdout

    # Foreign hook was NOT overwritten
    assert (hooks_dir / "commit-msg").read_text(encoding="utf-8") == foreign_content


def test_preserves_custom_core_hooks_path(tmp_path: Path) -> None:
    repo, env = _fixture_repository(tmp_path)
    custom_path = tmp_path / "custom-hooks"
    _git(repo, "config", "core.hooksPath", str(custom_path), env=env)

    result = _run(["bash", "scripts/install_git_hooks.sh"], cwd=repo, env=env)
    assert result.returncode == 0
    assert f"Found explicit core.hooksPath={custom_path}" in result.stdout
    assert _git(repo, "config", "--get", "core.hooksPath", env=env).stdout.strip() == str(custom_path)
