from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient

import scripts.api.governance_router as governance_router
import scripts.api.main as api_main
from scripts.audit import check_adrs

client = TestClient(api_main.app, raise_server_exceptions=False)


def _write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _write_decisions(path: Path, *, expires: str = "2099-01-01") -> None:
    _write(
        path,
        f"""decisions:
  - id: dec-test
    status: active
    date: "2026-01-01"
    expires: "{expires}"
    scope: tooling
    title: "Test decision"
    reasoning: "Fixture"
    evidence: "Fixture"
    alternatives: []
    superseded_by: null
    depends_on: []
""",
    )


def _write_adr(path: Path, *, status: str = "Accepted") -> None:
    _write(
        path,
        f"""# ADR-001: Fixture ADR

**Status**: {status}
**Date**: 2026-01-01
**Deciders**: Codex Test
**Related**:
- dec-test

## Context

Fixture.
""",
    )


def _write_adr_readme(path: Path) -> None:
    _write(
        path,
        """# ADR Index

<!-- ADR-INDEX-START generated by scripts/audit/check_adrs.py --rebuild-index -->
| ID  | Title | Status |
|-----|-------|--------|
| [ADR-001](adr-001-fixture.md) | Fixture ADR | Accepted |
<!-- ADR-INDEX-END -->
""",
    )


def _patch_governance_paths(monkeypatch, tmp_path: Path) -> tuple[Path, Path]:
    decisions_file = tmp_path / "docs" / "decisions" / "decisions.yaml"
    adr_dir = tmp_path / "docs" / "architecture" / "adr"
    monkeypatch.setattr(governance_router, "DECISIONS_FILE", decisions_file)
    monkeypatch.setattr(check_adrs, "PROJECT_ROOT", tmp_path)
    monkeypatch.setattr(check_adrs, "DECISIONS_YAML", decisions_file)
    monkeypatch.setattr(check_adrs, "ADR_DIR", adr_dir)
    monkeypatch.setattr(check_adrs, "README_PATH", adr_dir / "README.md")
    return decisions_file, adr_dir


def test_governance_endpoint_returns_decisions_and_adrs() -> None:
    response = client.get("/api/state/governance")

    assert response.status_code == 200
    body = response.json()
    assert "decisions" in body
    assert "adrs" in body
    assert "total" in body["decisions"]
    assert "total" in body["adrs"]


def test_governance_counters_consistent() -> None:
    response = client.get("/api/state/governance")

    assert response.status_code == 200
    body = response.json()
    assert body["decisions"]["total"] == len(body["decisions"]["all"])
    assert body["adrs"]["total"] == len(body["adrs"]["index"])


def test_orient_includes_governance_block() -> None:
    response = client.get("/api/orient?fresh=true")

    assert response.status_code == 200
    governance = response.json()["meta"]["governance"]
    assert {
        "decisions_total",
        "decisions_stale",
        "adrs_total",
        "adrs_warnings",
    } <= set(governance)


def test_stale_decisions_flagged(tmp_path: Path, monkeypatch) -> None:
    decisions_file, adr_dir = _patch_governance_paths(monkeypatch, tmp_path)
    _write_decisions(decisions_file, expires="2026-01-01")
    _write_adr(adr_dir / "adr-001-fixture.md")
    _write_adr_readme(adr_dir / "README.md")

    response = client.get("/api/state/governance")

    assert response.status_code == 200
    stale = response.json()["decisions"]["stale"]
    assert [decision["id"] for decision in stale] == ["dec-test"]


def test_adr_broken_chain_flagged(tmp_path: Path, monkeypatch) -> None:
    decisions_file, adr_dir = _patch_governance_paths(monkeypatch, tmp_path)
    _write_decisions(decisions_file)
    _write_adr(
        adr_dir / "adr-001-fixture.md",
        status="Superseded by ADR-999",
    )
    _write_adr_readme(adr_dir / "README.md")

    response = client.get("/api/state/governance")

    assert response.status_code == 200
    broken_chains = response.json()["adrs"]["broken_chains"]
    assert len(broken_chains) == 1
    assert "ADR-999" in broken_chains[0]
