#!/usr/bin/env python3
"""Gemini / AGY long-horizon session canary: mint, score, hydrate, hand back.

The operational canary remains the shared 8/10 recall test.  Gemini adds the
v1.2 hydration gate after PASS and closes its exact lease after FAIL-HANDOFF.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.session_canary import grok_lane as _gl
from scripts.session_canary import shared_hydration

EPIC_STREAM_DEFAULTS = dict(_gl.EPIC_STREAM_DEFAULTS)

_HOLDER_AGENT = "gemini"
_HOLDER_HARNESS = "agy"


def _utc_now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _epic_dir(repo: Path, epic: str) -> Path:
    return repo / ".claude" / f"{epic}-epic"


def _handoff_candidates(repo: Path, epic: str) -> list[Path]:
    base = _epic_dir(repo, epic)
    return [
        base / "GEMINI-DRIVER-HANDOFF.md",
        base / "INTERIM-DRIVER-HANDOFF.md",
        base / "CLAUDE-DRIVER-HANDOFF.md",
        base / "CODEX-DRIVER-HANDOFF.md",
    ]


def _cold_start_body(*, epic: str, stream_id: str, handoff_rel: str, lease_summary: str) -> str:
    return f"""# Gemini cold-start — {epic} / {stream_id}

> Generated by `scripts.session_canary.gemini_lane bootstrap` at {_utc_now()}.
> **No secrets.** Drive only the next unblocked action for this stream.

## Identity
- **Seat:** Gemini / AGY orchestrator
- **Epic:** `{epic}`
- **Stream:** `{stream_id}`
- **Lease:** {lease_summary}
- **Handoff dual-write:** `{handoff_rel}`

## Immediate steps
1. Read the stream tail and this handoff.
2. Mint a canary: `.venv/bin/python -m scripts.session_canary.gemini_lane mint --epic {epic} --stream {stream_id}`.
3. Score from memory. PASS auto-hydrates; FAIL-HANDOFF writes handback and closes the exact lease.
4. Continue only when the hydration capsule has `execution_allowed: true`.
"""


def _with_gemini_handoffs(function: Any, args: argparse.Namespace) -> int:
    original = _gl._handoff_candidates
    try:
        _gl._handoff_candidates = lambda repo, epic: _handoff_candidates(repo, epic)  # type: ignore[assignment]
        return int(function(args))
    finally:
        _gl._handoff_candidates = original


def _cmd_mint_gemini(args: argparse.Namespace) -> int:
    return _with_gemini_handoffs(_gl.cmd_mint, args)


def _stream_id(args: argparse.Namespace) -> str:
    return str(getattr(args, "stream", None) or EPIC_STREAM_DEFAULTS.get(args.epic, f"epic:{args.epic}"))


def _read_lease_environment(env_path: Path) -> dict[str, str]:
    """Parse the launcher receipt without sourcing a shell file."""
    environment: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("export SESSION_STREAM_") or "=" not in line:
            continue
        key, value = line.removeprefix("export ").split("=", 1)
        environment[key] = value.strip().strip("'\"")
    return environment


def _close_exact_lease(repo: Path, epic: str) -> bool:
    """Close only the lease recorded by this lane's launcher receipt."""
    env_path = _epic_dir(repo, epic) / "session-lease.env"
    if not env_path.is_file():
        return False
    environment = _read_lease_environment(env_path)
    try:
        from agents_extensions.shared.session_streams.db import SessionStreamDatabase
        from agents_extensions.shared.session_streams.hooks import clean_exit_hook, lease_from_environment
        from agents_extensions.shared.session_streams.store import SessionStreamStore

        clean_exit_hook(SessionStreamStore(SessionStreamDatabase()), lease_from_environment(environment))
    except (OSError, ValueError, RuntimeError):
        return False
    return True


def cmd_hydrate(args: argparse.Namespace) -> int:
    capsule = shared_hydration.build_hydration_capsule(_stream_id(args), _HOLDER_AGENT)
    print(json.dumps(capsule, ensure_ascii=False, sort_keys=True))
    if not capsule["execution_allowed"]:
        print("ACTION: hydration blocked — do not continue this driver.", file=sys.stderr)
        return 2
    print("ACTION: hydration ready — continue the current driver.")
    return 0


def cmd_score(args: argparse.Namespace) -> int:
    """Score shared canary, then route PASS and FAIL-HANDOFF through their paths."""
    args.no_hydrate = True  # Gemini hydrates with the v1.2 capsule, not diary text.
    score_rc = _with_gemini_handoffs(_gl.cmd_score, args)
    if score_rc == 0:
        hydrate_rc = cmd_hydrate(args)
        if hydrate_rc != 0:
            _close_exact_lease(Path(args.repo).resolve(), args.epic)
        return hydrate_rc
    if score_rc == 2:
        closed = _close_exact_lease(Path(args.repo).resolve(), args.epic)
        detail = "exact lease closed" if closed else "handback written; exact lease receipt unavailable"
        print(f"ACTION: FAIL-HANDOFF — {detail}; exit this Gemini driver.")
    return score_rc


def cmd_bootstrap(args: argparse.Namespace) -> int:
    """Write a non-authoritative cold-start board; launchers own lease acquisition."""
    repo = Path(args.repo).resolve()
    epic = args.epic.strip().lower()
    args.epic = epic
    stream_id = _stream_id(args)
    epic_path = _epic_dir(repo, epic)
    epic_path.mkdir(parents=True, exist_ok=True)
    handoffs = _handoff_candidates(repo, epic)
    handoff_rel = (
        str(handoffs[0].relative_to(repo))
        if handoffs[0].exists()
        else f".claude/{epic}-epic/GEMINI-DRIVER-HANDOFF.md"
    )
    board_path = epic_path / "GEMINI-COLD-START.md"
    board_path.write_text(
        _cold_start_body(
            epic=epic,
            stream_id=stream_id,
            handoff_rel=handoff_rel,
            lease_summary=f"stream {stream_id}; verify launcher-owned lease before driving",
        ),
        encoding="utf-8",
    )
    print(f"Bootstrapped Gemini cold-start board: {board_path.relative_to(repo)}")
    return 0


def cmd_protocol(args: argparse.Namespace) -> int:
    stream = _stream_id(args)
    print(
        f"""## Gemini lane canary

Stream: **{stream}**

1. Mint 10 durable anchors.
2. Score from memory (8/10 PASS threshold).
3. PASS → emit and validate HydrationCapsuleV1 v1.2, then continue only if allowed.
4. FAIL-HANDOFF → shared handback, exact lease close, and exit.
"""
    )
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    canary_dir = Path(args.out_dir) if args.out_dir else _epic_dir(Path(args.repo).resolve(), args.epic) / "canary"
    verdict = canary_dir / "last_verdict.json"
    print(f"Gemini canary status: {'verdict present' if verdict.is_file() else 'not yet scored'} for {args.epic}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="python -m scripts.session_canary.gemini_lane")
    parser.add_argument("--repo", type=Path, default=ROOT)
    sub = parser.add_subparsers(dest="subcommand", required=True)

    boot = sub.add_parser("bootstrap", help="Write Gemini cold-start board")
    boot.add_argument("--epic", required=True)
    boot.add_argument("--stream", default=None)
    boot.set_defaults(func=cmd_bootstrap)

    mint = sub.add_parser("mint", help="Freeze 10 durable canary anchors")
    mint.add_argument("--epic", required=True)
    mint.add_argument("--stream", default=None)
    mint.add_argument("--handoff", default=None)
    mint.add_argument("--out-dir", default=None)
    mint.add_argument("--stream-limit", type=int, default=40)
    mint.set_defaults(func=_cmd_mint_gemini)

    questions = sub.add_parser("questions", help="Print canary questions without answers")
    questions.add_argument("--epic", default="harness")
    questions.add_argument("--out-dir", default=None)
    questions.add_argument("--out", default=None)
    questions.set_defaults(func=_gl.cmd_questions)

    score = sub.add_parser("score", help="Score then hydrate/hand back")
    score.add_argument("--epic", default="harness")
    score.add_argument("--stream", default=None)
    score.add_argument("--out-dir", default=None)
    score.add_argument("--answers", required=True)
    score.add_argument("--context-tokens", type=int, default=0)
    score.add_argument("--model", default="gemini-3.1-pro-high")
    score.add_argument("--pass-ratio", type=float, default=_gl.DEFAULT_PASS_RATIO)
    score.add_argument("--threshold", type=float, default=_gl.DEFAULT_SIM_THRESHOLD)
    score.add_argument("--handoff", default=None)
    score.add_argument("--next-drive", default="")
    score.add_argument("--pins", default="")
    score.add_argument("--open-prs", default="")
    score.add_argument("--hands-off", default="")
    score.add_argument("--pending-user", default="")
    score.add_argument("--worktrees", default="")
    score.set_defaults(func=cmd_score)

    hydrate = sub.add_parser("hydrate", help="Emit a validated v1.2 hydration capsule")
    hydrate.add_argument("--epic", required=True)
    hydrate.add_argument("--stream", default=None)
    hydrate.set_defaults(func=cmd_hydrate)

    status = sub.add_parser("status", help="Show canary verdict presence")
    status.add_argument("--epic", required=True)
    status.add_argument("--out-dir", default=None)
    status.set_defaults(func=cmd_status)

    protocol = sub.add_parser("protocol", help="Print canary lifecycle")
    protocol.add_argument("--epic", required=True)
    protocol.add_argument("--stream", default=None)
    protocol.set_defaults(func=cmd_protocol)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
