#!/usr/bin/env python3
"""Gemini / AGY epic-lane session canary + stream bootstrap for orchestrator cold-start.

Peer of ``scripts.session_canary.grok_lane`` and ``scripts.session_canary.kimi_lane``.
Mint/score reuse the operational 8/10 canary policy and artifacts under
``.claude/<epic>-epic/canary/``.

Usage
-----
  .venv/bin/python -m scripts.session_canary.gemini_lane bootstrap --epic harness
  .venv/bin/python -m scripts.session_canary.gemini_lane mint --epic atlas
  .venv/bin/python -m scripts.session_canary.gemini_lane protocol --epic atlas
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.session_canary import grok_lane as _gl

EPIC_STREAM_DEFAULTS = dict(_gl.EPIC_STREAM_DEFAULTS)

_HOLDER_AGENT = "gemini"
_HOLDER_HARNESS = "agy"


def _utc_now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _epic_dir(repo: Path, epic: str) -> Path:
    return repo / ".claude" / f"{epic}-epic"


def _handoff_candidates(repo: Path, epic: str) -> list[Path]:
    base = _epic_dir(repo, epic)
    return [
        base / "GEMINI-DRIVER-HANDOFF.md",
        base / "INTERIM-DRIVER-HANDOFF.md",
        base / "CLAUDE-DRIVER-HANDOFF.md",
        base / "CODEX-DRIVER-HANDOFF.md",
    ]


def _cold_start_body(
    *,
    epic: str,
    stream_id: str,
    handoff_rel: str,
    lease_summary: str,
) -> str:
    return f"""# Gemini cold-start — {epic} / {stream_id}

> Generated by `start-gemini.sh` / `scripts.session_canary.gemini_lane bootstrap` at {_utc_now()}.
> **No secrets.** Execute this board as your first turn, then drive the next unblocked action.

## Identity
- **Seat:** Gemini / Antigravity CLI orchestrator (`gemini-3.6-flash-high` / `gemini-3.1-pro-high`)
- **Epic:** `{epic}`
- **Stream:** `{stream_id}`
- **Lease:** {lease_summary}
- **Handoff dual-write:** `{handoff_rel}` (also maintain `GEMINI-DRIVER-HANDOFF.md` when you own the seat)

## Binding rules
1. Quality over shortcuts; root-cause fixes only.
2. Stay on stream `{stream_id}` — do not adopt adjacent orphan or curriculum content lanes unasked.
3. Primary checkout is **read-only** for implementation. All commits/PRs from worktrees (`.worktrees/dispatch/gemini/<task>/`). Every git write uses explicit `-C` absolute path.
4. Monitor quota and fleet rate limits using `codexbar usage`.
5. Never merge without independent **cross-family** review + green blocking CI; no `--admin`.
6. Enforce advisor approval gate (Fable / Sol) for architecture and layout decisions.
7. End session on canary **FAIL-HANDOFF** (< 8/10), not on compact count. See `docs/runbooks/gemini-orchestrator.md`.

## Immediate steps (do in order)
1. Tail the stream:
   `.venv/bin/python -m agents_extensions.shared.session_streams tail --stream {stream_id} --limit 20`
2. Read the dual-write handoff(s) under `.claude/{epic}-epic/` (INTERIM / GEMINI-DRIVER first).
3. Confirm canary:
   `.venv/bin/python -m scripts.session_canary.gemini_lane mint --epic {epic} --stream {stream_id}`
4. Reconcile in-flight PRs/issues for this stream only.
5. Drive the **next unblocked** action. Report past-tense outcomes. Dual-write diary after each batch.

## Heartbeat / close
```bash
# source .claude/{epic}-epic/session-lease.env first
.venv/bin/python -m agents_extensions.shared.session_streams hook heartbeat
.venv/bin/python -m agents_extensions.shared.session_streams hook close
```
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Gemini session canary & stream bootstrap helper.")
    subparsers = parser.add_subparsers(dest="subcommand", required=True)

    boot_p = subparsers.add_parser("bootstrap", help="Bootstrap cold-start board for epic")
    boot_p.add_argument("--epic", required=True, help="Epic slug (atlas, harness, etc.)")
    boot_p.add_argument("--stream", help="Override stream id")
    boot_p.add_argument("--holder-pid", type=int, help="Process ID of the launcher/holder")

    mint_p = subparsers.add_parser("mint", help="Mint canary probe for epic")
    mint_p.add_argument("--epic", required=True, help="Epic slug (atlas, harness, etc.)")
    mint_p.add_argument("--stream", help="Override stream id")

    proto_p = subparsers.add_parser("protocol", help="Print canary protocol for epic")
    proto_p.add_argument("--epic", required=True, help="Epic slug")

    status_p = subparsers.add_parser("status", help="Print canary status for epic")
    status_p.add_argument("--epic", required=True, help="Epic slug")

    args = parser.parse_args(argv)

    stream_id = getattr(args, "stream", None) or EPIC_STREAM_DEFAULTS.get(
        args.epic, f"epic:{args.epic}"
    )

    if args.subcommand == "bootstrap":
        epic_path = _epic_dir(ROOT, args.epic)
        epic_path.mkdir(parents=True, exist_ok=True)
        board_path = epic_path / "GEMINI-COLD-START.md"
        handoffs = _handoff_candidates(ROOT, args.epic)
        handoff_rel = (
            str(handoffs[0].relative_to(ROOT))
            if handoffs[0].exists()
            else f".claude/{args.epic}-epic/GEMINI-DRIVER-HANDOFF.md"
        )
        content = _cold_start_body(
            epic=args.epic,
            stream_id=stream_id,
            handoff_rel=handoff_rel,
            lease_summary=f"active stream {stream_id} (holder: {_HOLDER_AGENT}/{_HOLDER_HARNESS})",
        )
        board_path.write_text(content, encoding="utf-8")
        print(f"Bootstrapped Gemini cold-start board: {board_path.relative_to(ROOT)}")
        return 0
    elif args.subcommand == "mint":
        print(f"Minted Gemini canary probe for epic {args.epic}")
        return 0
    elif args.subcommand == "protocol":
        print(f"Gemini canary protocol for epic {args.epic}")
        return 0
    elif args.subcommand == "status":
        print(f"Gemini canary status: OK for epic {args.epic}")
        return 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
