#!/usr/bin/env python3
"""GLM epic-lane session canary + stream bootstrap for orchestrator cold-start.

GLM-5.2 is a Zhipu AI code and review model routed via opencode.
LOCAL-ONLY: GLM egresses prompt data to China — forbidden in CI / automated pipelines.

Usage
-----
  .venv/bin/python -m scripts.session_canary.glm_lane bootstrap --epic harness
  .venv/bin/python -m scripts.session_canary.glm_lane probe
  .venv/bin/python -m scripts.session_canary.glm_lane mint --epic harness
  .venv/bin/python -m scripts.session_canary.glm_lane protocol --epic harness
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.agent_runtime.adapters.glm import (
    _CI_ENV_VARS,
    _OPENCODE_MODEL_ROUTES,
    GlmAdapter,
    GlmEgressForbiddenError,
    assert_glm_egress_allowed,
)
from scripts.session_canary import grok_lane as _gl
from scripts.session_canary import shared_hydration

EPIC_STREAM_DEFAULTS = dict(_gl.EPIC_STREAM_DEFAULTS)

_HOLDER_AGENT = "glm"
_HOLDER_HARNESS = "opencode-glm"
_DEFAULT_MODEL = "glm-5.2"

FIXED_PROBE_PROMPT = (
    "CANARY PROBE: What is the return value of fn() where def fn(): return 'GLM-CANARY-7718'? "
    "Reply ONLY with the exact token GLM-CANARY-7718."
)
EXPECTED_PROBE_TOKEN = "GLM-CANARY-7718"


def _utc_now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _epic_dir(repo: Path, epic: str) -> Path:
    return repo / ".claude" / f"{epic}-epic"


GLM_PREFERRED_HANDOFFS: list[str] = ["GLM-DRIVER-HANDOFF.md"]


def _handoff_candidates(repo: Path, epic: str) -> list[Path]:
    return _gl._handoff_candidates(repo, epic, preferred=GLM_PREFERRED_HANDOFFS)


def _cold_start_body(
    *,
    epic: str,
    stream_id: str,
    handoff_rel: str,
    lease_summary: str,
) -> str:
    return f"""# GLM cold-start — {epic} / {stream_id}

> Generated by `scripts.session_canary.glm_lane bootstrap` at {_utc_now()}.
> **No secrets. LOCAL-ONLY: China-egress model — never run in CI.**

## Identity
- **Seat:** GLM-5.2 orchestrator (Zhipu family; opencode transport)
- **Epic:** `{epic}`
- **Stream:** `{stream_id}`
- **Lease:** {lease_summary}
- **Handoff dual-write:** `{handoff_rel}` (maintain `GLM-DRIVER-HANDOFF.md` when you own the seat)

## Binding rules
1. Quality over shortcuts; root-cause fixes only.
2. LOCAL-ONLY: prompt data egresses to China — NEVER invoke in CI/automated environments.
3. Stay on stream `{stream_id}` — do not adopt adjacent orphan or curriculum content lanes unasked.
4. Primary checkout is **read-only** for implementation. All commits/PRs from worktrees (`.worktrees/dispatch/glm/<task>/`). Every git write uses explicit `-C` absolute path.
5. End session on canary **FAIL-HANDOFF** (< 8/10), not on compact count.

## Immediate steps (do in order)
1. Tail the stream:
   `.venv/bin/python -m agents_extensions.shared.session_streams tail --stream {stream_id} --limit 20`
2. Read the dual-write handoff(s) under `.claude/{epic}-epic/`.
3. Confirm canary:
   `.venv/bin/python -m scripts.session_canary.glm_lane mint --epic {epic} --stream {stream_id}`
4. Reconcile in-flight PRs/issues for this stream only.
5. Drive the **next unblocked** action.
"""


def verify_transport_preconditions() -> dict[str, Any]:
    """Verify transport preconditions for GLM canary.

    Returns receipt dict with status ('ok', 'refused', or 'failed') and reason/message.
    """
    try:
        assert_glm_egress_allowed("glm_lane")
    except GlmEgressForbiddenError as exc:
        return {
            "status": "refused",
            "reason": "ci_egress_forbidden",
            "message": str(exc),
        }

    opencode_bin = shutil.which("opencode")
    if not opencode_bin:
        return {
            "status": "failed",
            "reason": "opencode_binary_missing",
            "message": "opencode binary not found on PATH. Install opencode CLI or add it to PATH.",
        }

    route = _OPENCODE_MODEL_ROUTES.get(_DEFAULT_MODEL, f"zai-coding-plan/{_DEFAULT_MODEL}")
    if not route:
        return {
            "status": "failed",
            "reason": "glm_route_unresolvable",
            "message": f"No opencode route mapping for model {_DEFAULT_MODEL}.",
        }

    return {
        "status": "ok",
        "reason": "preconditions_satisfied",
        "opencode_binary": opencode_bin,
        "model_route": route,
    }


def run_glm_probe(
    *,
    repo: Path | None = None,
    prompt: str | None = None,
    expected_token: str | None = None,
    timeout: float = 30.0,
    adapter: Any | None = None,
) -> dict[str, Any]:
    """Run a short deterministic probe through the REAL glm transport and score reply shape."""
    precond = verify_transport_preconditions()
    if precond["status"] != "ok":
        return precond

    probe_prompt = prompt or FIXED_PROBE_PROMPT
    target_token = expected_token or EXPECTED_PROBE_TOKEN
    cwd = (repo or ROOT).resolve()
    glm_adapter = adapter or GlmAdapter()

    try:
        plan = glm_adapter.build_invocation(
            prompt=probe_prompt,
            mode="read-only",
            cwd=cwd,
            model=_DEFAULT_MODEL,
        )
    except GlmEgressForbiddenError as exc:
        return {
            "status": "refused",
            "reason": "ci_egress_forbidden",
            "message": str(exc),
        }
    except Exception as exc:
        return {
            "status": "failed",
            "reason": "invocation_plan_error",
            "message": f"Failed to build invocation plan: {exc}",
        }

    env = os.environ.copy()
    if plan.env_overrides:
        env.update(plan.env_overrides)

    start_time = datetime.now(UTC)
    try:
        proc = subprocess.run(
            plan.cmd,
            cwd=plan.cwd,
            input=plan.stdin_payload,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        parse_res = glm_adapter.parse_response(
            stdout=proc.stdout,
            stderr=proc.stderr,
            returncode=proc.returncode,
            plan=plan,
        )
    except subprocess.TimeoutExpired:
        return {
            "status": "failed",
            "reason": "probe_timeout",
            "message": f"opencode invocation timed out after {timeout}s",
        }
    except Exception as exc:
        return {
            "status": "failed",
            "reason": "invocation_execution_error",
            "message": f"Invocation execution error: {exc}",
        }

    elapsed_ms = (datetime.now(UTC) - start_time).total_seconds() * 1000.0
    reply_text = parse_res.response or ""
    score_ok = parse_res.ok and (target_token in reply_text)

    return {
        "status": "ok" if score_ok else "failed",
        "reason": "probe_passed" if score_ok else ("probe_shape_mismatch" if parse_res.ok else "adapter_parse_failed"),
        "score": 1.0 if score_ok else 0.0,
        "expected_token": target_token,
        "received_text": reply_text[:500],
        "opencode_ok": parse_res.ok,
        "stderr_excerpt": parse_res.stderr_excerpt,
        "elapsed_ms": round(elapsed_ms, 2),
    }


def _stream_id(args: argparse.Namespace) -> str:
    return str(getattr(args, "stream", None) or EPIC_STREAM_DEFAULTS.get(args.epic, f"epic:{args.epic}"))


def _cmd_mint_glm(args: argparse.Namespace) -> int:
    if not getattr(args, "preferred", None):
        args.preferred = GLM_PREFERRED_HANDOFFS
    return _gl.cmd_mint(args)


def _read_lease_environment(env_path: Path) -> dict[str, str]:
    environment: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("export SESSION_STREAM_") or "=" not in line:
            continue
        key, value = line.removeprefix("export ").split("=", 1)
        environment[key] = value.strip().strip("'\"")
    return environment


def _close_exact_lease(repo: Path, epic: str) -> bool:
    env_path = _epic_dir(repo, epic) / "session-lease.env"
    if not env_path.is_file():
        return False
    environment = _read_lease_environment(env_path)
    try:
        from agents_extensions.shared.session_streams.db import SessionStreamDatabase
        from agents_extensions.shared.session_streams.hooks import clean_exit_hook, lease_from_environment
        from agents_extensions.shared.session_streams.store import SessionStreamStore

        clean_exit_hook(SessionStreamStore(SessionStreamDatabase()), lease_from_environment(environment))
    except (OSError, ValueError, RuntimeError):
        return False
    return True


def cmd_probe(args: argparse.Namespace) -> int:
    """Run GLM transport probe and print result JSON receipt."""
    repo = Path(args.repo).resolve()
    timeout = float(getattr(args, "timeout", 30.0))
    receipt = run_glm_probe(repo=repo, timeout=timeout)
    print(json.dumps(receipt, ensure_ascii=False, indent=2))
    return 0 if receipt.get("status") == "ok" else 2


def cmd_hydrate(args: argparse.Namespace) -> int:
    capsule = shared_hydration.build_hydration_capsule(_stream_id(args), _HOLDER_AGENT)
    print(json.dumps(capsule, ensure_ascii=False, sort_keys=True))
    if not capsule["execution_allowed"]:
        print("ACTION: hydration blocked — do not continue this driver.", file=sys.stderr)
        return 2
    print("ACTION: hydration ready — continue the current driver.")
    return 0


def cmd_score(args: argparse.Namespace) -> int:
    if not getattr(args, "preferred", None):
        args.preferred = GLM_PREFERRED_HANDOFFS
    args.no_hydrate = True
    score_rc = _gl.cmd_score(args)
    if score_rc == 0:
        hydrate_rc = cmd_hydrate(args)
        if hydrate_rc != 0:
            _close_exact_lease(Path(args.repo).resolve(), args.epic)
        return hydrate_rc
    if score_rc == 2:
        closed = _close_exact_lease(Path(args.repo).resolve(), args.epic)
        detail = "exact lease closed" if closed else "handback written; exact lease receipt unavailable"
        print(f"ACTION: FAIL-HANDOFF — {detail}; exit this GLM driver.")
    return score_rc


def cmd_bootstrap(args: argparse.Namespace) -> int:
    repo = Path(args.repo).resolve()
    epic = args.epic.strip().lower()
    stream_id = _stream_id(args)

    precond = verify_transport_preconditions()
    if precond["status"] != "ok":
        print(f"bootstrap warning: transport precondition {precond['status']}: {precond['message']}", file=sys.stderr)

    epic_dir = _epic_dir(repo, epic)
    epic_dir.mkdir(parents=True, exist_ok=True)
    handoffs = _handoff_candidates(repo, epic)
    handoff_rel = (
        str(handoffs[0].relative_to(repo))
        if handoffs[0].exists()
        else f".claude/{epic}-epic/GLM-DRIVER-HANDOFF.md"
    )

    board_path = epic_dir / "GLM-COLD-START.md"
    lease_summary = f"stream {stream_id}; verify lease before driving"
    board_path.write_text(
        _cold_start_body(
            epic=epic,
            stream_id=stream_id,
            handoff_rel=handoff_rel,
            lease_summary=lease_summary,
        ),
        encoding="utf-8",
    )

    glm_handoff = epic_dir / "GLM-DRIVER-HANDOFF.md"
    if not glm_handoff.is_file():
        glm_handoff.write_text(
            f"# GLM driver handoff — stream {stream_id}\n\n"
            f"> Seat: GLM-5.2 · Epic: {epic} · Stream: {stream_id}\n"
            f"> **Last diary stamp:** {_utc_now()}\n\n"
            "## Next drive order\n1. Cold-start from stream tail\n2. Drive next unblocked action\n\n"
            "## Hands-off\n- Foreign stream leases; CI automation\n\n"
            "## 📔 Diary — reverse chrono (newest first)\n"
            f"### {_utc_now()} — created by bootstrap\n- Initialized GLM driver handoff\n",
            encoding="utf-8",
        )

    print(f"Bootstrapped GLM cold-start board: {board_path.relative_to(repo)}")
    return 0


def cmd_protocol(args: argparse.Namespace) -> int:
    stream = _stream_id(args)
    print(
        f"""## GLM lane session canary

Stream: **{stream}** (LOCAL-ONLY: China-egress guard active)

1. Mint 10 durable anchors.
2. Score from memory (8/10 PASS threshold).
3. PASS → emit and validate HydrationCapsuleV1 v1.2, then continue only if allowed.
4. FAIL-HANDOFF → shared handback, exact lease close, and exit.
5. `python -m scripts.session_canary.glm_lane probe` tests real transport preconditions.
"""
    )
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    canary_dir = Path(args.out_dir) if args.out_dir else _epic_dir(Path(args.repo).resolve(), args.epic) / "canary"
    verdict = canary_dir / "last_verdict.json"
    precond = verify_transport_preconditions()
    print(
        f"GLM canary status: {'verdict present' if verdict.is_file() else 'not yet scored'} for {args.epic}\n"
        f"Transport status: {precond['status']} ({precond['reason']})"
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="python -m scripts.session_canary.glm_lane")
    parser.add_argument("--repo", type=Path, default=ROOT)
    sub = parser.add_subparsers(dest="subcommand", required=True)

    boot = sub.add_parser("bootstrap", help="Write GLM cold-start board and handoff skeleton")
    boot.add_argument("--epic", required=True)
    boot.add_argument("--stream", default=None)
    boot.set_defaults(func=cmd_bootstrap)

    probe = sub.add_parser("probe", help="Run GLM transport precondition check and live probe")
    probe.add_argument("--repo", type=Path, default=ROOT)
    probe.add_argument("--timeout", type=float, default=30.0)
    probe.set_defaults(func=cmd_probe)

    mint = sub.add_parser("mint", help="Freeze 10 durable canary anchors")
    mint.add_argument("--epic", required=True)
    mint.add_argument("--stream", default=None)
    mint.add_argument("--handoff", default=None)
    mint.add_argument("--out-dir", default=None)
    mint.add_argument("--stream-limit", type=int, default=40)
    mint.set_defaults(func=_cmd_mint_glm)

    questions = sub.add_parser("questions", help="Print canary questions without answers")
    questions.add_argument("--epic", default="harness")
    questions.add_argument("--out-dir", default=None)
    questions.add_argument("--out", default=None)
    questions.set_defaults(func=_gl.cmd_questions)

    score = sub.add_parser("score", help="Score then hydrate/hand back")
    score.add_argument("--epic", default="harness")
    score.add_argument("--stream", default=None)
    score.add_argument("--out-dir", default=None)
    score.add_argument("--answers", required=True)
    score.add_argument("--context-tokens", type=int, default=0)
    score.add_argument("--model", default="glm-5.2")
    score.add_argument("--pass-ratio", type=float, default=_gl.DEFAULT_PASS_RATIO)
    score.add_argument("--threshold", type=float, default=_gl.DEFAULT_SIM_THRESHOLD)
    score.add_argument("--handoff", default=None)
    score.add_argument("--next-drive", default="")
    score.add_argument("--pins", default="")
    score.add_argument("--open-prs", default="")
    score.add_argument("--hands-off", default="")
    score.add_argument("--pending-user", default="")
    score.add_argument("--worktrees", default="")
    score.set_defaults(func=cmd_score)

    hydrate = sub.add_parser("hydrate", help="Emit a validated v1.2 hydration capsule")
    hydrate.add_argument("--epic", required=True)
    hydrate.add_argument("--stream", default=None)
    hydrate.set_defaults(func=cmd_hydrate)

    status = sub.add_parser("status", help="Show canary verdict presence and transport status")
    status.add_argument("--epic", required=True)
    status.add_argument("--out-dir", default=None)
    status.set_defaults(func=cmd_status)

    protocol = sub.add_parser("protocol", help="Print canary lifecycle")
    protocol.add_argument("--epic", required=True)
    protocol.add_argument("--stream", default=None)
    protocol.set_defaults(func=cmd_protocol)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not hasattr(args, "repo") or args.repo is None:
        args.repo = ROOT
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
