#!/usr/bin/env python3
"""Kimi epic-lane session canary + stream bootstrap for orchestrator cold-start.

Peer of ``scripts.session_canary.grok_lane``. Mint/score reuse the same
operational 8/10 canary policy and artifacts under
``.claude/<epic>-epic/canary/``. Bootstrap opens (or reclaims expired) a session
stream lease as holder agent ``kimi``, writes ``session-lease.env``, and emits
``KIMI-COLD-START.md`` for interactive first-message guidance.

Usage
-----
  .venv/bin/python -m scripts.session_canary.kimi_lane bootstrap --epic harness --holder-pid $$
  .venv/bin/python -m scripts.session_canary.kimi_lane mint --epic harness
  .venv/bin/python -m scripts.session_canary.kimi_lane protocol --epic harness
"""

from __future__ import annotations

import argparse
import os
import sys
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.session_canary import grok_lane as _gl

EPIC_STREAM_DEFAULTS = dict(_gl.EPIC_STREAM_DEFAULTS)

_HOLDER_AGENT = "kimi"
_HOLDER_HARNESS = "kimi-code"


def _utc_now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _epic_dir(repo: Path, epic: str) -> Path:
    return repo / ".claude" / f"{epic}-epic"


def _handoff_candidates(repo: Path, epic: str) -> list[Path]:
    base = _epic_dir(repo, epic)
    return [
        base / "KIMI-DRIVER-HANDOFF.md",
        base / "INTERIM-DRIVER-HANDOFF.md",
        base / "CLAUDE-DRIVER-HANDOFF.md",
        base / "CODEX-DRIVER-HANDOFF.md",
    ]


def _cold_start_body(
    *,
    epic: str,
    stream_id: str,
    handoff_rel: str,
    lease_summary: str,
) -> str:
    return f"""# Kimi cold-start — {epic} / {stream_id}

> Generated by `start-kimi.sh` / `scripts.session_canary.kimi_lane bootstrap` at {_utc_now()}.
> **No secrets.** Execute this board as your first turn, then drive the next unblocked action.

## Identity
- **Seat:** Kimi Code orchestrator (Moonshot family; native OAuth)
- **Epic:** `{epic}`
- **Stream:** `{stream_id}`
- **Lease:** {lease_summary}
- **Handoff dual-write:** `{handoff_rel}` (also maintain `KIMI-DRIVER-HANDOFF.md` when you own the seat)

## Binding rules
1. Quality over shortcuts; root-cause fixes only.
2. Stay on stream `{stream_id}` — do not adopt adjacent orphan or curriculum content lanes unasked.
3. Primary checkout is **read-only** for implementation. All commits/PRs from worktrees (`.worktrees/dispatch/kimi/<task>/`). Every git write uses explicit `-C` absolute path.
4. Never merge without independent **cross-family** review + green blocking CI; no `--admin`.
5. Formal sealed CF: Kimi is **fail-closed** today (#5556) — orchestrate and code; do not self-serve as formal CF gate until isolation is proven.
6. End session on canary **FAIL-HANDOFF** (< 8/10), not on compact count. See `docs/runbooks/kimi-orchestrator.md`.

## Immediate steps (do in order)
1. Tail the stream:
   `.venv/bin/python -m agents_extensions.shared.session_streams tail --stream {stream_id} --limit 20`
2. Read the dual-write handoff(s) under `.claude/{epic}-epic/` (INTERIM / KIMI-DRIVER first).
3. Confirm canary:
   `.venv/bin/python -m scripts.session_canary.kimi_lane mint --epic {epic} --stream {stream_id}`
4. Reconcile in-flight PRs/issues for this stream only.
5. Drive the **next unblocked** action. Report past-tense outcomes. Dual-write diary after each batch.

## Heartbeat / close
```bash
# source .claude/{epic}-epic/session-lease.env first
.venv/bin/python -m agents_extensions.shared.session_streams hook heartbeat
.venv/bin/python -m agents_extensions.shared.session_streams hook close
```

## Hands-off
- Curriculum content authoring lanes (folk/bio product content)
- Stealing another live seat's stream lease
- Silent production cutovers of fleet-comms defaults
"""


def _process_alive(pid: int) -> bool:
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def _write_lease_env(path: Path, lease: Any, holder: Any) -> None:
    path.write_text(
        "\n".join(
            [
                f"export SESSION_STREAM_ID={lease.stream_id}",
                f"export SESSION_STREAM_SESSION_ID={lease.session_id}",
                f"export SESSION_STREAM_LEASE_ID={lease.lease_id}",
                f"export SESSION_STREAM_FENCING_TOKEN={lease.fencing_token}",
                f"export SESSION_STREAM_GENERATION={lease.generation}",
                f"export SESSION_STREAM_AGENT={holder.agent}",
                f"export SESSION_STREAM_HARNESS={holder.harness}",
                f"export SESSION_STREAM_INSTANCE_ID={holder.instance_id}",
                f"export SESSION_STREAM_PROCESS_ID={holder.process_id}",
                f"export SESSION_STREAM_TASK_ID={holder.task_id}",
                f"export SESSION_STREAM_TTL_SECONDS={lease.ttl_seconds}",
                f"export SESSION_STREAM_VERSION={lease.version}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_lease_env_from_row(path: Path, row: Any) -> None:
    path.write_text(
        "\n".join(
            [
                f"export SESSION_STREAM_ID={row['stream_id']}",
                f"export SESSION_STREAM_SESSION_ID={row['session_id']}",
                f"export SESSION_STREAM_LEASE_ID={row['lease_id']}",
                f"export SESSION_STREAM_FENCING_TOKEN={row['fencing_token']}",
                f"export SESSION_STREAM_GENERATION={row['generation']}",
                f"export SESSION_STREAM_AGENT={row['holder_agent']}",
                f"export SESSION_STREAM_HARNESS={row['holder_harness']}",
                f"export SESSION_STREAM_INSTANCE_ID={row['holder_instance_id']}",
                f"export SESSION_STREAM_PROCESS_ID={row['holder_process_id']}",
                f"export SESSION_STREAM_TASK_ID={row['holder_task_id']}",
                f"export SESSION_STREAM_TTL_SECONDS={row['ttl_seconds']}",
                f"export SESSION_STREAM_VERSION={row['version']}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_cold_start(
    epic_dir: Path,
    *,
    epic: str,
    stream_id: str,
    lease_summary: str,
    repo: Path,
) -> None:
    handoff_rel = f".claude/{epic}-epic/INTERIM-DRIVER-HANDOFF.md"
    for cand in _handoff_candidates(repo, epic):
        if cand.is_file():
            try:
                handoff_rel = str(cand.relative_to(repo))
            except ValueError:
                handoff_rel = str(cand)
            break
    (epic_dir / "KIMI-COLD-START.md").write_text(
        _cold_start_body(
            epic=epic,
            stream_id=stream_id,
            handoff_rel=handoff_rel,
            lease_summary=lease_summary,
        ),
        encoding="utf-8",
    )


def cmd_bootstrap(args: argparse.Namespace) -> int:
    """Open/reclaim stream lease, mint canary, write KIMI-COLD-START.md + session-lease.env."""
    repo = Path(args.repo).resolve()
    epic = args.epic.strip().lower()
    stream_id = (args.stream or EPIC_STREAM_DEFAULTS.get(epic) or "").strip()
    if not stream_id:
        print(
            f"error: no stream for epic {epic!r}; pass --stream epic:N",
            file=sys.stderr,
        )
        return 1

    try:
        from agents_extensions.shared.session_streams.db import SessionStreamDatabase
        from agents_extensions.shared.session_streams.model import (
            EntryType,
            LeaseHolder,
        )
        from agents_extensions.shared.session_streams.store import (
            LeaseConflictError,
            LifecycleError,
            SessionStreamStore,
        )
    except ImportError as exc:
        print(f"error: session streams unavailable: {exc}", file=sys.stderr)
        return 1

    epic_dir = _epic_dir(repo, epic)
    epic_dir.mkdir(parents=True, exist_ok=True)
    store = SessionStreamStore(SessionStreamDatabase())
    conn = SessionStreamDatabase().connect()
    row = conn.execute(
        "SELECT * FROM stream_leases WHERE stream_id = ?", (stream_id,)
    ).fetchone()

    # Prefer the long-lived shell/kimi PID (start-kimi.sh passes $$ before exec).
    holder_pid = int(args.holder_pid) if args.holder_pid else os.getpid()
    holder = LeaseHolder(
        agent=_HOLDER_AGENT,
        harness=_HOLDER_HARNESS,
        instance_id=f"kimi-orch-{uuid.uuid4().hex[:12]}",
        task_id=f"kimi-cold-start-{epic}-{_utc_now()[:10]}",
        process_id=holder_pid,
    )

    lease: Any = None
    lease_summary = "none"
    blocked = False

    if row is not None and str(row["state"]) == "active":
        expires_at = datetime.fromisoformat(str(row["expires_at"]).replace("Z", "+00:00"))
        now = datetime.now(UTC)
        prior_pid = int(row["holder_process_id"])
        prior_agent = str(row["holder_agent"])
        prior_alive = _process_alive(prior_pid)
        if now < expires_at and prior_alive:
            if (
                prior_agent == _HOLDER_AGENT
                and str(row["holder_harness"]) == _HOLDER_HARNESS
            ):
                lease_summary = (
                    f"LIVE (kimi pid={prior_pid}); session={row['session_id']} "
                    f"fence={row['fencing_token']}"
                )
                _write_lease_env_from_row(epic_dir / "session-lease.env", row)
                print(f"bootstrap: stream {stream_id} already held ({lease_summary})")
            else:
                blocked = True
                lease_summary = (
                    f"BLOCKED: live lease held by {prior_agent}/{row['holder_harness']} "
                    f"pid={prior_pid} until {row['expires_at']}"
                )
                print(
                    f"bootstrap: refusing to steal live stream {stream_id} ({lease_summary})",
                    file=sys.stderr,
                )
                _write_cold_start(
                    epic_dir,
                    epic=epic,
                    stream_id=stream_id,
                    lease_summary=lease_summary,
                    repo=repo,
                )
                return 2
        elif now < expires_at and not prior_alive:
            # Store only force-closes after TTL; dead holder still blocks open.
            # Soft-continue: mint canary + cold-start; stream writes wait for expiry.
            lease_summary = (
                f"STALE_DEAD: prior {prior_agent}/{row['holder_harness']} pid={prior_pid} "
                f"dead but TTL until {row['expires_at']} — stream writes blocked until then "
                f"(or prior seat hook close)"
            )
            print(f"bootstrap: {lease_summary}", file=sys.stderr)
            _write_lease_env_from_row(epic_dir / "session-lease.env", row)
            blocked = True  # skip open_session; still mint + cold-start below
        else:
            try:
                store.force_close_expired_session(
                    stream_id=stream_id,
                    session_id=str(row["session_id"]),
                    candidate=holder,
                    reason=(
                        "kimi bootstrap reclaim: prior holder process dead or TTL expired"
                    ),
                )
                print(
                    f"bootstrap: force-closed expired session {row['session_id']} "
                    f"(agent={prior_agent} pid={prior_pid})"
                )
            except (LeaseConflictError, LifecycleError) as exc:
                print(f"bootstrap: force-close refused: {exc}", file=sys.stderr)
                return 2

    if (
        not blocked
        and lease is None
        and not lease_summary.startswith("LIVE")
        and not lease_summary.startswith("STALE_DEAD")
    ):
        try:
            lease = store.open_session(
                stream_id=stream_id,
                holder=holder,
                lineage_id=f"lineage-kimi-{epic}-{uuid.uuid4().hex[:10]}",
                ttl_seconds=int(args.ttl_seconds),
                reason=f"kimi orchestrator cold-start epic={epic}",
            )
            lease_summary = (
                f"opened session={lease.session_id} fence={lease.fencing_token} "
                f"gen={lease.generation} holder_pid={holder_pid}"
            )
            _write_lease_env(epic_dir / "session-lease.env", lease, holder)
            print(f"bootstrap: {lease_summary}")
            try:
                store.append_entry(
                    lease,
                    entry_type=EntryType.STATE,
                    body=(
                        f"Kimi orchestrator cold-start for {epic}/{stream_id}. "
                        f"Lease {lease.session_id} fence={lease.fencing_token}."
                    ),
                    idempotency_key=f"kimi-bootstrap-state-{lease.session_id}",
                )
                store.append_entry(
                    lease,
                    entry_type=EntryType.NEXT_ACTION,
                    body=(
                        f"KIMI DRIVER: read .claude/{epic}-epic/KIMI-COLD-START.md; "
                        "reconcile stream tail + dual-write handoff; drive next unblocked action."
                    ),
                    idempotency_key=f"kimi-bootstrap-next-{lease.session_id}",
                )
            except Exception as exc:
                print(f"warning: stream append failed: {exc}", file=sys.stderr)
        except LifecycleError as exc:
            print(f"bootstrap: open_session failed: {exc}", file=sys.stderr)
            return 2

    mint_ns = argparse.Namespace(
        repo=str(repo),
        epic=epic,
        stream=stream_id,
        handoff=None,
        out_dir=None,
        stream_limit=40,
    )
    original_candidates = _gl._handoff_candidates
    try:
        _gl._handoff_candidates = lambda r, e: _handoff_candidates(r, e)  # type: ignore[assignment]
        mint_rc = _gl.cmd_mint(mint_ns)
    finally:
        _gl._handoff_candidates = original_candidates
    if mint_rc != 0:
        print(
            f"warning: canary mint returned {mint_rc} (cold-start file still written)",
            file=sys.stderr,
        )

    _write_cold_start(
        epic_dir,
        epic=epic,
        stream_id=stream_id,
        lease_summary=lease_summary,
        repo=repo,
    )

    kimi_handoff = epic_dir / "KIMI-DRIVER-HANDOFF.md"
    if not kimi_handoff.is_file():
        kimi_handoff.write_text(
            f"""# Kimi driver handoff — stream {stream_id}

> Seat: Kimi · Epic: {epic} · Stream: {stream_id}
> **Last diary stamp:** {_utc_now()}

## Next drive (ordered)
1. Cold-start from stream tail + this diary
2. Drive next unblocked action for this stream only

## In flight
| ID | What | State |
| --- | --- | --- |
| — | (fill on first batch) | — |

## Hands-off
- Curriculum content lanes; other seats' live streams
- Formal CF gate (fail-closed for Kimi until #5556)

## Diary — reverse chrono
### {_utc_now()} — seat file created by bootstrap
""",
            encoding="utf-8",
        )
        print(f"bootstrap: created {kimi_handoff.relative_to(repo)}")

    print(f"bootstrap: ok epic={epic} stream={stream_id}")
    if lease_summary.startswith("STALE_DEAD"):
        # Soft success: orchestrator can still run; stream dual-write after TTL.
        return 0 if mint_rc == 0 else mint_rc
    if blocked and lease_summary.startswith("BLOCKED"):
        return 2
    return 0 if mint_rc == 0 else mint_rc


def cmd_protocol(args: argparse.Namespace) -> int:
    epic = (args.epic or "harness").strip().lower()
    stream = args.stream or EPIC_STREAM_DEFAULTS.get(epic, "epic:?")
    print(
        f"""## Kimi lane session canary + stream orchestration

You are bound to epic **{epic}** / stream **{stream}**.

### SSOT
- Session stream dual-write
- `.claude/{epic}-epic/KIMI-DRIVER-HANDOFF.md` and/or INTERIM-DRIVER-HANDOFF.md
- `.claude/{epic}-epic/KIMI-COLD-START.md`

### End signal = canary score, NOT compact count
- FAIL-HANDOFF (< 8/10) → handback + stream close + quit

### CLI
```bash
./start-kimi.sh --epic {epic}
.venv/bin/python -m scripts.session_canary.kimi_lane mint --epic {epic}
.venv/bin/python -m scripts.session_canary.kimi_lane protocol --epic {epic}
```

See `docs/runbooks/kimi-orchestrator.md`.
"""
    )
    return 0


def _cmd_mint_kimi(args: argparse.Namespace) -> int:
    original = _gl._handoff_candidates
    try:
        _gl._handoff_candidates = lambda r, e: _handoff_candidates(r, e)  # type: ignore[assignment]
        return _gl.cmd_mint(args)
    finally:
        _gl._handoff_candidates = original


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m scripts.session_canary.kimi_lane",
        description="Kimi orchestrator canary + stream bootstrap",
    )
    parser.add_argument("--repo", type=Path, default=ROOT)
    sub = parser.add_subparsers(dest="command", required=True)

    boot = sub.add_parser(
        "bootstrap",
        help="Open/reclaim stream lease, mint canary, write KIMI-COLD-START.md",
    )
    boot.add_argument("--epic", required=True)
    boot.add_argument("--stream", default=None)
    boot.add_argument(
        "--holder-pid",
        type=int,
        default=None,
        help="Long-lived process id for the lease (start-kimi.sh passes $$ before exec)",
    )
    boot.add_argument("--ttl-seconds", type=int, default=21600)
    boot.set_defaults(func=cmd_bootstrap)

    mint = sub.add_parser("mint", help="Freeze 10 durable anchors (stream + handoff)")
    mint.add_argument("--epic", required=True)
    mint.add_argument("--stream", default=None)
    mint.add_argument("--handoff", default=None)
    mint.add_argument("--out-dir", default=None)
    mint.add_argument("--stream-limit", type=int, default=40)
    mint.set_defaults(func=_cmd_mint_kimi)

    questions = sub.add_parser("questions", help="Print/write id→question map")
    questions.add_argument("--epic", default="harness")
    questions.add_argument("--out-dir", default=None)
    questions.add_argument("--out", default=None)
    questions.set_defaults(func=_gl.cmd_questions)

    score = sub.add_parser("score", help="Score answers vs probe (rc 2 = FAIL-HANDOFF)")
    score.add_argument("--epic", default="harness")
    score.add_argument("--out-dir", default=None)
    score.add_argument("--answers", required=True)
    score.add_argument("--context-tokens", type=int, default=0)
    score.add_argument("--model", default="kimi-code/k3")
    score.add_argument("--pass-ratio", type=float, default=_gl.DEFAULT_PASS_RATIO)
    score.add_argument("--threshold", type=float, default=_gl.DEFAULT_SIM_THRESHOLD)
    score.add_argument("--handoff", default=None)
    score.add_argument("--next-drive", default="")
    score.add_argument("--pins", default="")
    score.add_argument("--open-prs", default="")
    score.add_argument("--hands-off", default="")
    score.add_argument("--pending-user", default="")
    score.add_argument("--worktrees", default="")
    score.set_defaults(func=_gl.cmd_score)

    status = sub.add_parser("status", help="Show canary artifacts + last verdict")
    status.add_argument("--epic", default="harness")
    status.add_argument("--out-dir", default=None)
    status.set_defaults(func=_gl.cmd_status)

    protocol = sub.add_parser("protocol", help="Print agent-facing lifecycle protocol")
    protocol.add_argument("--epic", default="harness")
    protocol.add_argument("--stream", default=None)
    protocol.set_defaults(func=cmd_protocol)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    # Ensure nested cmds that read args.repo always have it.
    if not hasattr(args, "repo") or args.repo is None:
        args.repo = ROOT
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
