"""Per-attempt stdio sources MCP launcher and receipt ledger provisioner.

Issue: #8517 (Refs #8430, #8397)

Provisions a per-attempt MCP configuration and empty receipt ledger for review
seats. Formal reviews require audit-grade receipts recorded over stdio via
attempt-specific environment variables:
- LU_REVIEW_ATTEMPT_ID
- LU_REVIEW_MANIFEST_SHA256
- LU_REVIEW_LEDGER_PATH

The generated MCP configuration defines exclusively a `sources` server started
over stdio from the primary checkout's virtual environment and server script,
bypassing the shared streamable-HTTP daemon (127.0.0.1:8766).

Codex has no ``--mcp-config`` flag, and per-invocation ``-c mcp_servers.X`` overrides
MERGE with the user's global ``~/.codex/config.toml``. A Codex attempt therefore also
gets a scoped ``CODEX_HOME`` directory (``<attempt_id>.codex-home/``, always the sibling
of the attempt's ``.mcp.json``) holding a ``config.toml`` that registers only the stdio
``sources`` server, plus an ``auth.json`` symlink. Because trusted *project* config can
still add servers, the worker runs ``verify_codex_review_effective_mcp`` before launch
and refuses the attempt unless the effective server set is exactly that one server.

Note: Ledger creation and sidecar management will be consolidated once R1
(cursor/impl-review-r1-schema-ledger) merges to main.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import re
import shutil
import subprocess
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from scripts.common.repo_root import resolve_repo_root
from scripts.review.receipts.ledger import REVIEW_TOOLS

ENV_ATTEMPT_ID = "LU_REVIEW_ATTEMPT_ID"
ENV_MANIFEST_SHA256 = "LU_REVIEW_MANIFEST_SHA256"
ENV_LEDGER_PATH = "LU_REVIEW_LEDGER_PATH"
ENV_KEYS = (ENV_ATTEMPT_ID, ENV_MANIFEST_SHA256, ENV_LEDGER_PATH)

SUPPORTED_HARNESSES: frozenset[str] = frozenset({"claude", "codex", "cursor"})

UNSUPPORTED_HARNESS_REASONS: dict[str, str] = {
    "agy": "AGY has one global MCP config (~/.gemini/config/mcp_config.json) without per-invocation MCP config support",
    "gemini": "Gemini has one global MCP config without per-invocation MCP config support",
    "grok": "not yet proven",
    "grok-build": "not yet proven",
    "kimicc": "not yet supported",
    "kimi": "Native Kimi Code reads global profile config and cannot take a per-attempt stdio config",
    "grok-hermes": "Hermes-routed agents read global ~/.hermes/config.yaml and cannot take a per-attempt stdio config",
    "deepseek": "Hermes-routed agents read global ~/.hermes/config.yaml and cannot take a per-attempt stdio config",
    "qwen": "Hermes-routed agents read global ~/.hermes/config.yaml and cannot take a per-attempt stdio config",
}

_TOKEN_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_EMPTY_SHA256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
_MCP_CONFIG_SUFFIX = ".mcp.json"
_CODEX_HOME_SUFFIX = ".codex-home"
_CODEX_MCP_LIST_TIMEOUT_S = 60.0


class CodexReviewMcpGateError(ValueError):
    """The effective Codex MCP server set for a review attempt is not exactly ``sources``."""


@dataclass(frozen=True)
class ReviewMcpPlan:
    """Plan and options for running a review attempt with isolated stdio sources MCP."""

    config_path: Path
    adapter_options: dict[str, Any]
    ledger_path: Path
    sidecar_path: Path
    manifest_sha256: str
    review_id: str
    attempt_id: str
    harness: str
    codex_home: Path | None = None

    @property
    def mcp_config_path(self) -> Path:
        return self.config_path

    @property
    def strict_mcp_config(self) -> bool:
        return True


def review_tools_allowed_csv(harness: str) -> str | None:
    """Return the explicit sources permission grant for Claude review attempts."""
    if harness.lower().strip() != "claude":
        return None
    return ",".join(f"mcp__sources__{name}" for name in sorted(REVIEW_TOOLS))


def codex_review_home_path(config_path: Path | str) -> Path:
    """Return the scoped ``CODEX_HOME`` directory that pairs with an attempt's ``.mcp.json``."""
    config = Path(config_path)
    if not config.name.endswith(_MCP_CONFIG_SUFFIX):
        raise ValueError(f"review MCP config path must end in {_MCP_CONFIG_SUFFIX}: {config}")
    return config.with_name(config.name[: -len(_MCP_CONFIG_SUFFIX)] + _CODEX_HOME_SUFFIX)


def _toml_string(value: str) -> str:
    # JSON string escapes are a subset of TOML basic-string escapes.
    return json.dumps(value, ensure_ascii=True)


def _render_codex_review_config(python_bin: Path, sources_server: Path, env: dict[str, str]) -> str:
    """Render the minimal Codex config: one stdio ``sources`` server, nothing else."""
    lines = [
        "# Auto-generated by review_mcp.prepare_review_attempt (#8517).",
        "# Scoped CODEX_HOME for ONE review attempt: only the stdio sources server.",
        "",
        "[mcp_servers.sources]",
        f"command = {_toml_string(str(python_bin))}",
        f"args = [{_toml_string(str(sources_server))}]",
        "required = true",
        'default_tools_approval_mode = "approve"',
        "",
        "[mcp_servers.sources.env]",
    ]
    lines.extend(f"{key} = {_toml_string(value)}" for key, value in env.items())
    return "\n".join(lines) + "\n"


def _link_codex_auth(codex_home: Path) -> None:
    """Symlink the user's Codex ``auth.json`` (as ``_ensure_codex_writer_home`` does)."""
    real_auth = Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex") / "auth.json"
    if real_auth.exists():
        (codex_home / "auth.json").symlink_to(real_auth)


def prepare_review_attempt(
    review_id: str,
    attempt_id: str,
    manifest_path: Path | str,
    harness: str,
    *,
    receipts_root: Path | None = None,
) -> ReviewMcpPlan:
    """Prepare the per-attempt stdio sources MCP config, empty ledger, and sidecar.

    Args:
        review_id: Identifier of the formal review job.
        attempt_id: Unique attempt identifier.
        manifest_path: Path to the review manifest YAML.
        harness: Agent harness name (e.g. 'claude', 'cursor').
        receipts_root: Optional override for the receipts base directory (used in tests).

    Returns:
        ReviewMcpPlan containing the written config path and adapter options.

    Raises:
        ValueError: If tokens are invalid or harness is unsupported.
        FileExistsError: If ledger, sidecar, or config already exists.
        FileNotFoundError: If manifest_path does not exist.
    """
    if not isinstance(review_id, str) or not _TOKEN_RE.match(review_id):
        raise ValueError(f"invalid review_id: {review_id!r}")
    if not isinstance(attempt_id, str) or not _TOKEN_RE.match(attempt_id):
        raise ValueError(f"invalid attempt_id: {attempt_id!r}")

    canonical_harness = (harness or "").lower().strip()
    if canonical_harness in UNSUPPORTED_HARNESS_REASONS:
        raise ValueError(
            f"review attempt refused for {canonical_harness}: {UNSUPPORTED_HARNESS_REASONS[canonical_harness]} (#8517)"
        )
    if canonical_harness not in SUPPORTED_HARNESSES:
        raise ValueError(f"review attempt refused for unsupported harness {canonical_harness!r} (#8517)")

    manifest_file = Path(manifest_path).resolve()
    if not manifest_file.is_file():
        raise FileNotFoundError(f"review manifest file not found: {manifest_file}")

    manifest_bytes = manifest_file.read_bytes()
    manifest_sha256 = hashlib.sha256(manifest_bytes).hexdigest()

    # Primary checkout root: resolved via repository helper scripts.common.repo_root
    primary_root = resolve_repo_root(Path(__file__), 2)
    python_bin = primary_root / ".venv" / "bin" / "python"
    sources_server = primary_root / ".mcp" / "servers" / "sources" / "server.py"

    base_dir = receipts_root if receipts_root is not None else (primary_root / "batch_state" / "review-receipts")
    review_dir = base_dir / review_id
    review_dir.mkdir(parents=True, exist_ok=True)

    ledger_path = review_dir / f"{attempt_id}.jsonl"
    sidecar_path = review_dir / f"{attempt_id}.jsonl.sha256"
    config_path = review_dir / f"{attempt_id}.mcp.json"
    codex_home = codex_review_home_path(config_path) if canonical_harness == "codex" else None

    # Driver settlement 5: create ledger, sidecar, and config with O_EXCL; refuse if any already exists
    if (
        ledger_path.exists()
        or sidecar_path.exists()
        or config_path.exists()
        or (codex_home is not None and (codex_home.exists() or codex_home.is_symlink()))
    ):
        raise FileExistsError(f"review attempt {attempt_id!r} already exists for review {review_id!r}")

    sidecar_bytes = f"{_EMPTY_SHA256}\n".encode("ascii")
    config_payload = {
        "mcpServers": {
            "sources": {
                "command": str(python_bin),
                "args": [str(sources_server)],
                "env": {
                    ENV_ATTEMPT_ID: attempt_id,
                    ENV_MANIFEST_SHA256: manifest_sha256,
                    ENV_LEDGER_PATH: str(ledger_path),
                },
            }
        }
    }
    config_bytes = (json.dumps(config_payload, indent=2) + "\n").encode("utf-8")

    created_paths: list[Path] = []

    def _rollback() -> None:
        for path in reversed(created_paths):
            with contextlib.suppress(OSError):
                if path.is_dir() and not path.is_symlink():
                    shutil.rmtree(path, ignore_errors=True)
                else:
                    path.unlink(missing_ok=True)

    try:
        # Create empty ledger (0 bytes, 0o600) exclusively
        fd_ledger = os.open(ledger_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        os.close(fd_ledger)
        created_paths.append(ledger_path)

        # Create sidecar containing empty SHA-256 + newline exclusively
        fd_sidecar = os.open(sidecar_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd_sidecar, "wb") as handle:
            handle.write(sidecar_bytes)
        created_paths.append(sidecar_path)

        # Create config exclusively
        fd_config = os.open(config_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd_config, "wb") as handle:
            handle.write(config_bytes)
        created_paths.append(config_path)

        for target in created_paths:
            if (target.stat().st_mode & 0o777) != 0o600:
                os.chmod(target, 0o600)

        if codex_home is not None:
            # Exclusive mkdir: refuses a pre-existing (or pre-planted) home.
            os.mkdir(codex_home, 0o700)
            created_paths.append(codex_home)
            fd_toml = os.open(codex_home / "config.toml", os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(fd_toml, "w", encoding="utf-8") as handle:
                handle.write(
                    _render_codex_review_config(
                        python_bin, sources_server, config_payload["mcpServers"]["sources"]["env"]
                    )
                )
            _link_codex_auth(codex_home)
    except FileExistsError as exc:
        _rollback()
        raise FileExistsError(f"review attempt {attempt_id!r} already exists for review {review_id!r}") from exc
    except BaseException:
        _rollback()
        raise

    adapter_options: dict[str, Any] = {
        "mcp_config_path": str(config_path),
        "strict_mcp_config": True,
        "mcp_server_names": ["sources"],
    }
    allowed_tools = review_tools_allowed_csv(canonical_harness)
    if allowed_tools is not None:
        adapter_options["allowed_tools"] = allowed_tools
    if codex_home is not None:
        adapter_options["codex_home_override"] = str(codex_home)

    return ReviewMcpPlan(
        config_path=config_path,
        adapter_options=adapter_options,
        ledger_path=ledger_path,
        sidecar_path=sidecar_path,
        manifest_sha256=manifest_sha256,
        review_id=review_id,
        attempt_id=attempt_id,
        harness=canonical_harness,
        codex_home=codex_home,
    )


def _config_flags(argv: Sequence[str]) -> list[str]:
    """Return the config-affecting flags (``-c``/``--enable``/``--disable`` pairs) of a Codex argv."""
    flags: list[str] = []
    for index, item in enumerate(argv[:-1]):
        if item in {"-c", "--config", "--enable", "--disable"}:
            flags.extend([item, argv[index + 1]])
    return flags


def verify_codex_review_effective_mcp(
    *,
    config_path: Path | str,
    cwd: Path | str,
    config_flags: Sequence[str] = (),
    codex_bin: str | None = None,
    timeout: float = _CODEX_MCP_LIST_TIMEOUT_S,
) -> None:
    """Refuse a Codex review attempt unless its effective MCP set is exactly ``sources``.

    Runs ``codex mcp list --json`` with the attempt's scoped ``CODEX_HOME``, the launch
    cwd and the launch config flags, so trusted project config and ``-c`` overrides are
    counted. Fails closed: a failed probe is a refusal, never a pass.

    Raises:
        CodexReviewMcpGateError: on any deviation, naming #8517.
    """
    config = Path(config_path)

    def refuse(reason: str) -> CodexReviewMcpGateError:
        return CodexReviewMcpGateError(f"codex review attempt refused: {reason} (#8517)")

    try:
        expected = json.loads(config.read_text(encoding="utf-8"))["mcpServers"]["sources"]
    except (OSError, ValueError, KeyError, TypeError) as exc:
        raise refuse(f"cannot read the attempt MCP config {config}: {exc}") from exc
    codex_home = codex_review_home_path(config)
    if not (codex_home / "config.toml").is_file():
        raise refuse(f"scoped CODEX_HOME {codex_home} has no config.toml")

    binary = codex_bin or shutil.which("codex") or "codex"
    env = {**os.environ, "CODEX_HOME": str(codex_home)}
    try:
        proc = subprocess.run(
            [binary, "mcp", "list", "--json", *config_flags],
            cwd=str(cwd),
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise refuse(f"could not compute the effective MCP set ({type(exc).__name__}: {exc})") from exc
    if proc.returncode != 0:
        raise refuse(f"`codex mcp list` exited {proc.returncode}: {proc.stderr.strip()[:200]}")
    try:
        servers = json.loads(proc.stdout)
    except ValueError as exc:
        raise refuse(f"`codex mcp list --json` did not return JSON: {exc}") from exc
    if not isinstance(servers, list):
        raise refuse("`codex mcp list --json` did not return a list")

    names = sorted(str(item.get("name")) if isinstance(item, dict) else repr(item) for item in servers)
    if names != ["sources"]:
        raise refuse(f"effective MCP servers are {names!r}; exactly ['sources'] is allowed")
    server = servers[0]
    transport = server.get("transport") or {}
    if server.get("enabled") is not True:
        raise refuse("the sources server is not enabled")
    if transport.get("type") != "stdio":
        raise refuse(f"the sources server transport is {transport.get('type')!r}, not stdio")
    if transport.get("command") != expected["command"] or list(transport.get("args") or []) != expected["args"]:
        raise refuse("the sources server command/args differ from the attempt's .mcp.json")
    if dict(transport.get("env") or {}) != expected["env"]:
        raise refuse("the sources server env differs from the attempt's .mcp.json")


def verify_codex_review_launch(
    *,
    config_path: Path | str,
    cwd: Path,
    mode: str,
    model: str | None,
    effort: str | None,
    task_id: str,
    tool_config: dict[str, Any],
) -> None:
    """Run the effective-config gate with the exact flags the Codex adapter will launch with."""
    from scripts.agent_runtime.adapters.codex import CodexAdapter

    plan = CodexAdapter().build_invocation(
        prompt="",
        mode=mode,
        cwd=cwd,
        model=model,
        task_id=task_id,
        session_id=None,
        tool_config=dict(tool_config),
        effort=effort,
    )
    try:
        verify_codex_review_effective_mcp(
            config_path=config_path,
            cwd=plan.cwd,
            config_flags=_config_flags(plan.cmd),
            codex_bin=plan.cmd[0],
        )
    finally:
        with contextlib.suppress(OSError):
            Path(plan.output_file).unlink(missing_ok=True)
