// This file is generated by scripts/generate-types.mjs from lu.activity.v1.schema.json.
// Do not edit directly.

export type LuActivityType = "true-false" | "cloze" | "match-up";

export interface LuProvenance {
  source: string;
  generator: string;
  gates: Array<string>;
}

export type LuTrueFalsePayload = {
  type: "true-false";
  id?: string;
  instruction: string;
  notes?: string;
  items: Array<{
    statement: string;
    correct: boolean;
    explanation?: string;
  }>;
  title?: string;
};

export type LuClozePayload = {
  type: "cloze";
  id?: string;
  instruction: string;
  notes?: string;
  text: string;
  options?: Array<string>;
  blanks: Array<{
    id: number;
    answer: string;
    options: Array<string>;
  }>;
  title?: string;
};

export type LuMatchUpPayload = {
  type: "match-up";
  id?: string;
  instruction: string;
  notes?: string;
  pairs: Array<{
    left: string;
    right: string;
  }>;
  title?: string;
};

export type LuTrueFalseAnswerKey = {
  items: Array<{
    index: number;
    correct: boolean;
  }>;
};

export type LuClozeAnswerKey = {
  blanks: Array<{
    id: number;
    answer: string;
  }>;
};

export type LuMatchUpAnswerKey = {
  pairs: Array<{
    left_index: number;
    right_index: number;
  }>;
};

interface LuActivityBase<TType extends LuActivityType, TPayload, TAnswerKey> {
  id: string;
  type: TType;
  title: string;
  level: "b1";
  payload: TPayload;
  answer_key: TAnswerKey;
  provenance: LuProvenance;
}

export type LuTrueFalseActivityV1 = LuActivityBase<'true-false', LuTrueFalsePayload, LuTrueFalseAnswerKey>;
export type LuClozeActivityV1 = LuActivityBase<'cloze', LuClozePayload, LuClozeAnswerKey>;
export type LuMatchUpActivityV1 = LuActivityBase<'match-up', LuMatchUpPayload, LuMatchUpAnswerKey>;

export type LuActivityV1 =
  | LuTrueFalseActivityV1
  | LuClozeActivityV1
  | LuMatchUpActivityV1;
