// This file is generated by scripts/generate-types.mjs from lu.activity.v1.schema.json.
// Do not edit directly.

export type LuActivityType = "true-false" | "cloze" | "match-up" | "text-questions" | "multiple-choice" | "quiz" | "mark-the-words" | "fill-in" | "glossary" | "form-build" | "error-correction" | "paraphrase" | "continue-sentence" | "roleplay-dialog" | "short-writing";

export interface LuProvenance {
  source: string;
  generator: string;
  gates: Array<string>;
}

export type LuTrueFalsePayload = {
  type: "true-false";
  instruction: string;
  items: Array<{
    statement: string;
    correct: boolean;
    explanation?: string;
  }>;
};

export type LuClozePayload = {
  type: "cloze";
  instruction: string;
  text: string;
  blanks: Array<{
    id: number;
    answer: string;
    options: Array<string>;
  }>;
};

export type LuMatchUpPayload = {
  type: "match-up";
  instruction: string;
  pairs: Array<{
    left: string;
    right: string;
  }>;
};

export type LuTextQuestionsPayload = {
  type: "text-questions";
  instruction: string;
  source_ref?: string;
  items: Array<string>;
};

export type LuMultipleChoicePayload = {
  type: "multiple-choice";
  instruction: string;
  items: Array<{
    prompt: string;
    options: Array<string>;
  }>;
};

export type LuQuizPayload = {
  type: "quiz";
  instruction: string;
  items: Array<{
    question: string;
    options: Array<string>;
    correct: number;
    explanation?: string;
  }>;
};

export type LuMarkTheWordsPayload = {
  type: "mark-the-words";
  instruction: string;
  text: string;
  target_words: Array<string>;
  criteria?: string;
};

export type LuFillInPayload = {
  type: "fill-in";
  instruction: string;
  items: Array<{
    sentence: string;
    answer: string;
    options?: Array<string>;
    explanation?: string;
  }>;
};

export type LuGlossaryPayload = {
  type: "glossary";
  instruction: string;
  gloss_lang: string;
  items: Array<{
    term: string;
    gloss: string;
  }>;
};

export type LuFormBuildPayload = {
  type: "form-build";
  instruction: string;
  items: Array<string>;
};

export type LuErrorCorrectionPayload = {
  type: "error-correction";
  instruction: string;
  items: Array<string>;
};

export type LuParaphrasePayload = {
  type: "paraphrase";
  instruction: string;
  items: Array<string>;
};

export type LuContinueSentencePayload = {
  type: "continue-sentence";
  instruction: string;
  items: Array<string>;
};

export type LuRoleplayDialogPayload = {
  type: "roleplay-dialog";
  instruction: string;
  scenario: string;
  prompts: Array<string>;
};

export type LuShortWritingPayload = {
  type: "short-writing";
  prompt: string;
  source_ref?: string;
};

export type LuTrueFalseAnswerKey = {
  items: Array<{
    index: number;
    correct: boolean;
  }>;
};

export type LuClozeAnswerKey = {
  blanks: Array<{
    id: number;
    answer: string;
  }>;
};

export type LuMatchUpAnswerKey = {
  pairs: Array<{
    left_index: number;
    right_index: number;
  }>;
};

export type LuTextQuestionsAnswerKey = {
  guidance: string;
  model_answers?: Array<string>;
  model_answer?: string;
  rubric?: string;
};

export type LuMultipleChoiceAnswerKey = {
  items: Array<{
    index: number;
    correct: string;
  }>;
};

export type LuQuizAnswerKey = {
  items: Array<{
    index: number;
    correct: number;
  }>;
};

export type LuMarkTheWordsAnswerKey = {
  target_words: Array<string>;
};

export type LuFillInAnswerKey = {
  items: Array<string>;
};

export type LuGlossaryAnswerKey = {
  guidance: string;
  model_answers?: Array<string>;
  model_answer?: string;
  rubric?: string;
};

export type LuFormBuildAnswerKey = {
  items: Array<string>;
};

export type LuErrorCorrectionAnswerKey = {
  items: Array<string>;
};

export type LuParaphraseAnswerKey = {
  items: Array<string>;
};

export type LuContinueSentenceAnswerKey = {
  guidance: string;
  model_answers?: Array<string>;
  model_answer?: string;
  rubric?: string;
};

export type LuRoleplayDialogAnswerKey = {
  guidance: string;
  model_answers?: Array<string>;
  model_answer?: string;
  rubric?: string;
};

export type LuShortWritingAnswerKey = {
  guidance: string;
  model_answers?: Array<string>;
  model_answer?: string;
  rubric?: string;
};

interface LuActivityBase<TType extends LuActivityType, TPayload, TAnswerKey> {
  id: string;
  type: TType;
  title: string;
  level: "b1";
  payload: TPayload;
  answer_key: TAnswerKey;
  provenance: LuProvenance;
}

export type LuTrueFalseActivityV1 = LuActivityBase<'true-false', LuTrueFalsePayload, LuTrueFalseAnswerKey>;
export type LuClozeActivityV1 = LuActivityBase<'cloze', LuClozePayload, LuClozeAnswerKey>;
export type LuMatchUpActivityV1 = LuActivityBase<'match-up', LuMatchUpPayload, LuMatchUpAnswerKey>;
export type LuTextQuestionsActivityV1 = LuActivityBase<'text-questions', LuTextQuestionsPayload, LuTextQuestionsAnswerKey>;
export type LuMultipleChoiceActivityV1 = LuActivityBase<'multiple-choice', LuMultipleChoicePayload, LuMultipleChoiceAnswerKey>;
export type LuQuizActivityV1 = LuActivityBase<'quiz', LuQuizPayload, LuQuizAnswerKey>;
export type LuMarkTheWordsActivityV1 = LuActivityBase<'mark-the-words', LuMarkTheWordsPayload, LuMarkTheWordsAnswerKey>;
export type LuFillInActivityV1 = LuActivityBase<'fill-in', LuFillInPayload, LuFillInAnswerKey>;
export type LuGlossaryActivityV1 = LuActivityBase<'glossary', LuGlossaryPayload, LuGlossaryAnswerKey>;
export type LuFormBuildActivityV1 = LuActivityBase<'form-build', LuFormBuildPayload, LuFormBuildAnswerKey>;
export type LuErrorCorrectionActivityV1 = LuActivityBase<'error-correction', LuErrorCorrectionPayload, LuErrorCorrectionAnswerKey>;
export type LuParaphraseActivityV1 = LuActivityBase<'paraphrase', LuParaphrasePayload, LuParaphraseAnswerKey>;
export type LuContinueSentenceActivityV1 = LuActivityBase<'continue-sentence', LuContinueSentencePayload, LuContinueSentenceAnswerKey>;
export type LuRoleplayDialogActivityV1 = LuActivityBase<'roleplay-dialog', LuRoleplayDialogPayload, LuRoleplayDialogAnswerKey>;
export type LuShortWritingActivityV1 = LuActivityBase<'short-writing', LuShortWritingPayload, LuShortWritingAnswerKey>;

export type LuActivityV1 =
  | LuTrueFalseActivityV1
  | LuClozeActivityV1
  | LuMatchUpActivityV1
  | LuTextQuestionsActivityV1
  | LuMultipleChoiceActivityV1
  | LuQuizActivityV1
  | LuMarkTheWordsActivityV1
  | LuFillInActivityV1
  | LuGlossaryActivityV1
  | LuFormBuildActivityV1
  | LuErrorCorrectionActivityV1
  | LuParaphraseActivityV1
  | LuContinueSentenceActivityV1
  | LuRoleplayDialogActivityV1
  | LuShortWritingActivityV1;
