// This file is generated by scripts/generate-types.mjs from lu.lesson.v1.schema.json.
// Do not edit directly.

import type { LuActivityV1 } from './lu.activity.v1.generated';

export type LuLessonStatus = "draft" | "baking" | "ready" | "failed";

export type LuLessonDuration = 45 | 60 | 90;

export type LuLessonBlockProvenance = {
  source: "anchor" | "generated" | "teacher";
  generator: string;
  gates: Array<string>;
  external_options: boolean;
};

export type LuLessonBlock = {
  id: string;
  phase: 1 | 2 | 3;
  type: "true-false" | "cloze" | "match-up" | "text-questions" | "multiple-choice" | "quiz" | "mark-the-words" | "fill-in" | "glossary" | "form-build" | "error-correction" | "paraphrase" | "continue-sentence" | "roleplay-dialog" | "short-writing";
  mode: "усно" | "письмово" | "вдома";
  activity: LuActivityV1;
  answer_key: string | Record<string, unknown> | Array<unknown> | null;
  mark: "ok" | "warn";
  note: string | null;
  edited: boolean;
  provenance: {
    source: "anchor" | "generated" | "teacher";
    generator: string;
    gates: Array<string>;
    external_options: boolean;
  };
};

export type LuRejectedDraft = {
  type: "true-false" | "cloze" | "match-up" | "text-questions" | "multiple-choice" | "quiz" | "mark-the-words" | "fill-in" | "glossary" | "form-build" | "error-correction" | "paraphrase" | "continue-sentence" | "roleplay-dialog" | "short-writing";
  activity: LuActivityV1;
  reason: string;
};

export type LuLessonV1 = {
  schema: "lu.lesson.v1";
  id: string;
  title: string;
  level: "B1";
  method: "ttt";
  focus: string | null;
  anchor: {
    text: string;
    source: "teacher-paste" | "teacher-url";
    chars: number;
  };
  duration: 45 | 60 | 90;
  version: 1;
  status: "draft" | "baking" | "ready" | "failed";
  last_error: string | null;
  accepted: boolean;
  blocks: Array<{
    id: string;
    phase: 1 | 2 | 3;
    type: "true-false" | "cloze" | "match-up" | "text-questions" | "multiple-choice" | "quiz" | "mark-the-words" | "fill-in" | "glossary" | "form-build" | "error-correction" | "paraphrase" | "continue-sentence" | "roleplay-dialog" | "short-writing";
    mode: "усно" | "письмово" | "вдома";
    activity: LuActivityV1;
    answer_key: string | Record<string, unknown> | Array<unknown> | null;
    mark: "ok" | "warn";
    note: string | null;
    edited: boolean;
    provenance: {
      source: "anchor" | "generated" | "teacher";
      generator: string;
      gates: Array<string>;
      external_options: boolean;
    };
  }>;
  rejected: Array<{
    type: "true-false" | "cloze" | "match-up" | "text-questions" | "multiple-choice" | "quiz" | "mark-the-words" | "fill-in" | "glossary" | "form-build" | "error-correction" | "paraphrase" | "continue-sentence" | "roleplay-dialog" | "short-writing";
    activity: LuActivityV1;
    reason: string;
  }>;
  created_at: string;
  updated_at: string;
};
