// This file is generated by scripts/generate-types.mjs from lu.lesson-support.v1.schema.json.
// Do not edit directly.

export type LuLessonSupportVocabularyItem = {
  surface: string;
  lemma: string;
  stress: string;
  pos: string;
  gloss: string;
  vesum_analysis: Record<string, unknown> | string;
};

export type LuLessonSupportTheoryItem = {
  id: string;
  body: string;
  callouts: Array<string>;
};

export type LuLessonSupportAssetItem = {
  id: string;
  transcript: string;
  sha256: string;
};

export type LuLessonSupportV1 = {
  schema: "lu.lesson-support.v1";
  vocabulary: Array<LuLessonSupportVocabularyItem>;
  theory: Array<LuLessonSupportTheoryItem>;
  assets: Array<LuLessonSupportAssetItem>;
};
