"""Pipeline package — decomposed from pipeline_v5.py."""

from pipeline.consultation import (
    ConsultationResult,
    TemplateChange,
    apply_template_patch,
    parse_consultation,
    queue_for_approval,
    record_consultation,
)
from pipeline.fixes import (
    _apply_find_replace_fixes,
    _apply_fixes_with_rollback,
    _apply_module_fixes,
    _clean_fix_text,
    _count_diff_lines,
    _log_d1_edits,
    _module_file_paths,
    _snapshot_module_files,
)
from pipeline.parsing import (
    _build_d3_context,
    _compute_metrics_direct,
    _extract_audit_failures,
    _extract_delimiter,
    _extract_delimiter_tolerant,
    _extract_fix_plan,
    _extract_gate_blockers,
    _extract_h2_sections,
    _extract_vesum_failures,
    _format_deterministic_issues,
    _format_filler_phrases,
    _format_vesum_verification,
    _get_russicism_table,
    _get_track_calibration,
    _inject_file_contents,
    _inject_metrics_into_prompt,
    _parse_d1_review,
    _parse_factual_review,
    _quick_review_quality_gate,
    _scan_llm_filler,
)
from pipeline.screen import (
    _deterministic_fix_mtimes,
    _deterministic_screen,
    _run_deterministic_fixes,
)
from pipeline.state import (
    _fresh_state,
    _migrate_v4_to_v5,
    _state_file,
    is_complete,
    load_state,
    mark_complete,
    mark_failed,
    save_state,
)

__all__ = [
    # consultation
    "ConsultationResult",
    "TemplateChange",
    "_apply_find_replace_fixes",
    "_apply_fixes_with_rollback",
    "_apply_module_fixes",
    "_build_d3_context",
    "_clean_fix_text",
    "_compute_metrics_direct",
    "_count_diff_lines",
    "_deterministic_fix_mtimes",
    "_deterministic_screen",
    "_extract_audit_failures",
    # parsing
    "_extract_delimiter",
    "_extract_delimiter_tolerant",
    "_extract_fix_plan",
    "_extract_gate_blockers",
    "_extract_h2_sections",
    "_extract_vesum_failures",
    "_format_deterministic_issues",
    "_format_filler_phrases",
    "_format_vesum_verification",
    "_fresh_state",
    "_get_russicism_table",
    "_get_track_calibration",
    "_inject_file_contents",
    "_inject_metrics_into_prompt",
    "_log_d1_edits",
    "_migrate_v4_to_v5",
    # fixes
    "_module_file_paths",
    "_parse_d1_review",
    "_parse_factual_review",
    "_quick_review_quality_gate",
    # screen
    "_run_deterministic_fixes",
    "_scan_llm_filler",
    "_snapshot_module_files",
    # state
    "_state_file",
    "apply_template_patch",
    "is_complete",
    "load_state",
    "mark_complete",
    "mark_failed",
    "parse_consultation",
    "queue_for_approval",
    "record_consultation",
    "save_state",
]
