"""Host-only UA-GEC fixtures generated by each selected CLI component."""

from dataclasses import asdict, replace

from .. import bindings
from ..components import MutationFixture
from ..contract import canonical
from ..errors import require
from . import c1_ua_gec
from .ua_gec_split import UaGecAttribution, exclusion


def component_mutations(ctx, candidates, gate):
    """Yield private probes; the generic framework enforces their refusals."""
    component = candidates[0].component if candidates else None
    require(component in {"C1", "C6a"}, "mutation_unavailable")
    store = ctx.reader.files["ua-gec"]
    # These probes use exactly the reader and effective policy being verified.
    require(gate is not None and gate.reader is ctx.reader, "mutation_context")
    fixtures = []
    if component == "C1":
        seen = set()
        for row in store.all_rows("corpus"):
            if row["layer"] != "gec-only":
                continue
            reason = exclusion(row, store.splits)
            if reason and reason not in seen:
                seen.add(reason)
                fixtures.append((reason, c1_ua_gec.candidate(row, store.splits), "roles", reason))
        require(seen == {"test_source", "dev_source", "sensitive_source", "ruler_overlap"}, "mutation_unavailable")
    else:
        mixed = next((c for c in candidates if c.reason == "mixed_to_c1"), None)
        require(mixed is not None, "mutation_unavailable")
        fixtures.append(("mixed_edit", mixed, "roles", "mixed_edit"))
    admitted = [c for c in candidates if c.outcome == "accepted"]
    require(len(admitted) >= 2, "mutation_unavailable")
    base = admitted[0]
    donor = next(c for c in admitted if c.unit_id != base.unit_id)
    fixtures.append(("wrong_reference", replace(base, response=donor.response), "binding", "binding_row"))
    target = replace(base.response[0], text=base.response[0].text + "\0")
    fixtures.append(("absent_quote", replace(base, response=(target,)), "quote", "quote_mismatch"))
    fixtures.append(
        ("paraphrase", replace(base, response=(replace(target, transform="paraphrase"),)), "quote", "unknown_transform")
    )
    fixtures.append(("attribution_placeholder", base, "attribution", "attribution_unresolved"))
    for name, candidate, mechanism, expected in fixtures:
        candidate = replace(
            candidate, outcome="accepted", reason="aligned_pair" if component == "C1" else "calque_only", evidence=()
        )

        def check(candidate=candidate, mechanism=mechanism):
            if mechanism == "roles":
                gate.roles.check(candidate.slots[0].citations[0], candidate, set())
            elif mechanism == "binding":
                bindings.check(candidate, gate.spec(candidate)["binding"], ctx.reader, {})
            elif mechanism == "attribution":
                citation = candidate.slots[0].citations[0]
                UaGecAttribution(store).resolve("<author> <year>", citation, ctx.reader.row(citation), ctx.reader)
            else:
                gate.quote(candidate)

        yield MutationFixture(name, canonical(asdict(candidate)) + b"\n", expected, check)
