#!/usr/bin/env python3
"""List wiki articles generated by a Flash-tier Gemini model."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from wiki.config import WIKI_DIR


def parse_wiki_meta(article_text: str) -> dict:
    """Parse the lightweight ``wiki-meta`` block without PyYAML."""
    start = article_text.find("<!-- wiki-meta")
    if start == -1:
        return {}
    end = article_text.find("-->", start)
    if end == -1:
        return {}

    meta: dict[str, object] = {}
    body = article_text[start + len("<!-- wiki-meta"):end]
    for raw_line in body.splitlines():
        line = raw_line.strip()
        if not line or ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            items = [item.strip() for item in value[1:-1].split(",") if item.strip()]
            meta[key] = items
        else:
            meta[key] = value
    meta.setdefault("generated_by_model", "unknown")
    return meta


def iter_wiki_articles() -> list[Path]:
    """Return committed wiki article paths, excluding reviews and the index."""
    return sorted(
        path
        for path in WIKI_DIR.rglob("*.md")
        if ".reviews" not in path.parts and path.name != "index.md"
    )


def is_flash_model(model: object) -> bool:
    """Return True for Flash-tier Gemini model identifiers."""
    normalized = str(model or "").strip().lower()
    return "flash" in normalized


def main() -> int:
    flagged = []
    for path in iter_wiki_articles():
        meta = parse_wiki_meta(path.read_text(encoding="utf-8"))
        model = meta.get("generated_by_model", "unknown")
        if is_flash_model(model):
            flagged.append(path.relative_to(WIKI_DIR.parent))

    for relpath in flagged:
        print(relpath)
    print(f"Count: {len(flagged)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
