#!/usr/bin/env bash
# Single-source orphan allowlist for scripts/deploy_prompts.sh and
# scripts/check_rules_deployment.sh.
#
# Pure variable assignments — no side effects. Source from both consumers;
# do not execute directly.
#
# Declared orphan paths (relative to destination). Space-separated.
# Format: paths that exist in destination but NOT in source. rsync
# --delete will skip these, preserving them on every deploy.

# --- shared → .claude ---
# scheduled_tasks.lock is a runtime state file managed by Claude
# Code's task scheduler — it must never be deleted by the deploy
# script or in-flight scheduled tasks get orphaned.
# *-epic/ — curriculum-track driver handoffs (CLAUDE-DRIVER-HANDOFF.md), e.g.
#          folk-epic/ bio-epic/ atlas-epic/. Live here as gitignored LOCAL state,
#          NOT a source artifact (user policy 2026-06-23: driver handoffs out of
#          git/PRs, in .claude/). Runtime-only, machine-specific. Declared as a
#          GLOB so rsync --delete preserves them AND future epics don't re-break
#          deploy (the enumerated form silently orphaned atlas-epic — a new epic
#          the allowlist hadn't been told about — aborting every deploy).
ORPHAN_PATHS_CLAUDE="scheduled_tasks.lock worktrees *-epic"

# --- shared → .agent ---
# wake/  — scheduled-task state written by the Claude Code wake scheduler.
# cache/ — Monitor API client disk cache (see scripts/ai_agent_bridge/_monitor_cache.py),
#          stores rules.body/session.body + ETag metadata so cold-start is ~780 B instead of 75 KB.
#          Runtime-only; NOT source-tracked. rsync --delete must preserve both.
# *-thread-bootstrap.md / *-handoff.md / *-thread-lease.json — per-agent handoff state in .agent/.
#          *-thread-*.md are generated by scripts/orchestration/thread_handoff.py; *-handoff.md
#          also covers manually-maintained role/lane handoffs (e.g. claude-infra-handoff.md from
#          the 2026-06-20 fleet restructure). The *-handoff.md glob is deliberately broad: ANY
#          <agent>-<kind>-handoff.md is per-machine runtime state, never a source artifact (verified
#          no *-handoff.md exists under agents_extensions/shared/). Runtime-only, machine-specific
#          (live timestamps + snapshot); NOT source-tracked. Without these entries the deploy aborts
#          on any machine where a handoff has been written.
# prompts/ — per-dispatch prompt files (.agent/prompts/<task_id>.md) written into
#          .agent/ by the dispatch tooling when a dispatch fires. Runtime-only,
#          NOT source-tracked. Without this entry the deploy aborts on any machine
#          where a dispatch has run since the last clean .agent/ deploy.
# tmp/ — runtime scratch (issue/PR draft bodies, transient tarballs) written into
#          .agent/ by orchestration tooling. Runtime-only, NOT source-tracked.
#          Same rationale as prompts/: declare so rsync --delete preserves it.
# *-brief.md / dispatch-*.md — transient dispatch briefs (.agent/atlas-3150-brief.md,
#          .agent/dispatch-3098-slice3.md) hand-authored by orchestrators when firing a
#          dispatch. Same category as prompts/ and tmp/: runtime-only scratch, NOT
#          source-tracked. Without these patterns a single in-flight brief aborts the
#          ENTIRE deploy (every target), so committed source prompt fixes silently never
#          reach .claude/ + .codex/ + .agent/ runtime — agents keep running stale prompts (#3456).
# dispatch-briefs/ — the DIRECTORY successor to the top-level dispatch-*.md scatter:
#          orchestrators now collect per-dispatch briefs under .agent/dispatch-briefs/
#          (e.g. 4497-runner-failover.md). The dispatch-*.md FILE glob does not match a
#          directory, so without this entry the first collected brief aborts every
#          deploy — the #3456 failure class again, one level down.
ORPHAN_PATHS_AGENT="wake cache prompts tmp *-thread-bootstrap.md *-handoff.md *-thread-lease.json *-brief.md dispatch-*.md dispatch-briefs"

# --- shared/skills → .agents/skills ---
ORPHAN_PATHS_AGENTS=""

# --- shared → .codex (rsync orphan excludes only; overlay paths below) ---
# agents/curriculum-orchestrator.toml and agents/curriculum-writer.toml —
# Codex agent definitions with no source equivalent.
# config.toml — Codex CLI configuration managed directly by Codex.
ORPHAN_PATHS_CODEX="agents/curriculum-orchestrator.toml agents/curriculum-writer.toml config.toml"

# --- deploy-owned: Codex overlay paths (checker mirrors for .codex drift) ---
# Managed by agents_extensions/codex/, not by the shared tree. Exclude them from
# the shared rsync/delete pass, then verify them with the overlay drift check.
# hooks.json is intentionally here, not in ORPHAN_PATHS_CODEX.
CODEX_OVERLAY_PATHS="hooks.json memory"

# --- gemini_extensions → .gemini ---
# tmp/ — Gemini CLI runtime workspace (e.g. .gemini/tmp/learn-ukrainian/);
#        local working state, NOT a deploy artifact. Preserve across rsync --delete.
# config.yaml — repository-level Gemini Code Assist for GitHub configuration.
#        It disables GitHub PR reviews while preserving local Gemini CLI tooling.
ORPHAN_PATHS_GEMINI="config.yaml docs/ rules/ tmp/"

# --- deploy-owned: Claude autoload excludes (checker mirrors for .claude drift) ---
# Claude Code auto-loads every unscoped file in `.claude/rules/` into the system
# prompt. These always-load rules are served by the Monitor API and must not be
# deployed to the Claude target. Other targets still receive them from shared.
CLAUDE_RULE_AUTOLOAD_EXCLUDES=(
    "rules/critical-rules.md"
    "rules/non-negotiable-rules.md"
    "rules/workflow.md"
    "rules/delegate-must-use-worktree.md"
    "rules/cli-help-standard.md"
    "rules/model-assignment.md"
    "rules/operator-expectations.md"
)
CLAUDE_RULE_AUTOLOAD_EXCLUDE_PATHS="${CLAUDE_RULE_AUTOLOAD_EXCLUDES[*]}"
