#!/usr/bin/env python3
"""
Extract activities from checkpoint/review modules that don't have # Activities header.
These modules have ## activity-type: headers directly in the file.
"""

import re
import sys
import yaml
from pathlib import Path

# Import parsers from md_to_yaml.py
sys.path.insert(0, str(Path(__file__).parent))
from md_to_yaml import (
    ACTIVITY_PARSERS,
    parse_activities_section,
    strip_activities_from_md
)

ACTIVITY_TYPES = [
    'match-up', 'quiz', 'fill-in', 'true-false', 'group-sort',
    'anagram', 'unjumble', 'error-correction', 'cloze',
    'mark-the-words', 'select', 'translate'
]


def extract_activities_directly(md_content: str) -> str | None:
    """Find the first activity type header and extract everything from there to Summary/Vocabulary."""
    activity_pattern = r'^##\s+(' + '|'.join(ACTIVITY_TYPES) + r'):\s*'
    
    match = re.search(activity_pattern, md_content, re.MULTILINE | re.IGNORECASE)
    if not match:
        return None
    
    start_pos = match.start()
    remaining = md_content[start_pos:]
    
    # Find end - look for # Summary or # Vocabulary
    end_pattern = r'^#\s*(Summary|Vocabulary|Словник|Підсумок)\s*$'
    end_match = re.search(end_pattern, remaining, re.MULTILINE)
    
    if end_match:
        return remaining[:end_match.start()].strip()
    
    return remaining.strip()


def convert_checkpoint(md_path: Path) -> bool:
    """Convert a checkpoint module's activities to YAML."""
    if not md_path.exists():
        print(f"❌ File not found: {md_path}")
        return False
    
    with open(md_path, 'r', encoding='utf-8') as f:
        md_content = f.read()
    
    # Extract activities section directly
    activities_section = extract_activities_directly(md_content)
    if not activities_section:
        print(f"⚠️  No activities found in {md_path.name}")
        return False
    
    # Parse activities
    activities = parse_activities_section(activities_section)
    if not activities:
        print(f"⚠️  Could not parse activities in {md_path.name}")
        return False
    
    # Create YAML file
    activities_dir = md_path.parent / 'activities'
    activities_dir.mkdir(exist_ok=True)
    yaml_path = activities_dir / (md_path.stem + '.yaml')
    
    # Format for YAML output
    yaml_content = f"# Activities extracted from {md_path.name}\n"
    yaml_content += "# Generated by extract_checkpoint_activities.py\n\n"
    yaml_content += yaml.dump(activities, allow_unicode=True, default_flow_style=False, sort_keys=False)
    
    with open(yaml_path, 'w', encoding='utf-8') as f:
        f.write(yaml_content)
    
    print(f"✅ Created {yaml_path.name} with {len(activities)} activities")
    
    # Now strip activities from MD
    activity_pattern = r'^##\s+(' + '|'.join(ACTIVITY_TYPES) + r'):\s*'
    first_activity = re.search(activity_pattern, md_content, re.MULTILINE | re.IGNORECASE)
    
    if first_activity:
        start_pos = first_activity.start()
        remaining = md_content[start_pos:]
        
        # Find where to stop
        end_pattern = r'^#\s*(Summary|Vocabulary|Словник|Підсумок)\s*$'
        end_match = re.search(end_pattern, remaining, re.MULTILINE)
        
        if end_match:
            end_pos = start_pos + end_match.start()
            new_content = md_content[:start_pos].rstrip('\n') + '\n\n' + md_content[start_pos + end_match.start():]
        else:
            new_content = md_content[:start_pos].rstrip('\n') + '\n'
        
        # Cleanup extra newlines
        new_content = re.sub(r'\n{3,}', '\n\n', new_content)
        
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        
        old_lines = len(md_content.splitlines())
        new_lines = len(new_content.splitlines())
        print(f"   Stripped {old_lines - new_lines} lines from {md_path.name}")
    
    return True


def main():
    # Target files
    files = [
        Path('curriculum/l2-uk-en/a1/34-checkpoint-final-review.md'),
        Path('curriculum/l2-uk-en/a2/56-grammar-review.md'),
        Path('curriculum/l2-uk-en/a2/57-final-review.md'),
    ]
    
    print("=" * 60)
    print("Extracting activities from checkpoint/review modules")
    print("=" * 60)
    
    success = 0
    for f in files:
        if convert_checkpoint(f):
            success += 1
        print()
    
    print(f"📊 Summary: {success}/{len(files)} modules converted")


if __name__ == '__main__':
    main()
