#!/usr/bin/env bash
# Configure Git hook delegators in the untracked common hooks directory
# so that tracked hooks in .githooks are invoked for all linked worktrees
# without core.hooksPath pointing at a tracked directory.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
tracked_hooks_dir="$repo_root/.githooks"
if [[ ! -d "$tracked_hooks_dir" ]]; then
    echo "Tracked hooks directory not found at $tracked_hooks_dir" >&2
    exit 1
fi

required_hooks=(
    pre-commit
    commit-msg
    pre-push
    post-merge
    post-checkout
    post-commit
)
for hook_name in "${required_hooks[@]}"; do
    if [[ ! -x "$tracked_hooks_dir/$hook_name" ]]; then
        echo "Expected executable hook at $tracked_hooks_dir/$hook_name" >&2
        exit 1
    fi
done

for support_file in _lib.sh check-pytest-stamp.py pytest_stamp.py; do
    if [[ ! -r "$tracked_hooks_dir/$support_file" ]]; then
        echo "Expected readable hook support file at $tracked_hooks_dir/$support_file" >&2
        exit 1
    fi
done

git_common_dir="$(git rev-parse --git-common-dir)"
if [[ "$git_common_dir" != /* ]]; then
    git_common_dir="$repo_root/$git_common_dir"
fi
hooks_dir="$git_common_dir/hooks"
mkdir -p "$hooks_dir"

# 1. Unset core.hooksPath if set to .githooks (leave any other explicit value alone)
current_hooks_path="$(git config --get core.hooksPath 2>/dev/null || true)"
if [[ "$current_hooks_path" == ".githooks" ]]; then
    git config --unset core.hooksPath
elif [[ -n "$current_hooks_path" ]]; then
    echo "Found explicit core.hooksPath=$current_hooks_path; leaving untouched"
fi

marker="# generated by scripts/install_git_hooks.sh"
entire_marker="# Entire CLI hooks"

generate_delegator() {
    local hook_name="$1"
    cat <<EOF
#!/usr/bin/env bash
# generated by scripts/install_git_hooks.sh — delegates to the tracked hook in the CURRENT worktree
set -euo pipefail
root="\$(git rev-parse --show-toplevel)"
hook="\$root/.githooks/$hook_name"
[[ -x "\$hook" ]] || exit 0
exec "\$hook" "\$@"
EOF
}

# 2. For every executable hook in .githooks whose name is a git hook name:
for hook_path in "$tracked_hooks_dir"/*; do
    [[ -e "$hook_path" ]] || continue
    hook_name="$(basename "$hook_path")"
    case "$hook_name" in
        _lib.sh|*.py|*.md|*.sh|_*|*.pre-entire|*.sample)
            continue
            ;;
    esac
    [[ -x "$hook_path" ]] || continue

    target="$hooks_dir/$hook_name"
    expected_content="$(generate_delegator "$hook_name")"

    if [[ ! -e "$target" ]]; then
        generate_delegator "$hook_name" > "$target"
        chmod +x "$target"
        echo "$hook_name: installed"
    elif grep -qF "$entire_marker" "$target" 2>/dev/null; then
        pre_entire="$hooks_dir/$hook_name.pre-entire"
        if [[ ! -e "$pre_entire" ]]; then
            generate_delegator "$hook_name" > "$pre_entire"
            chmod +x "$pre_entire"
            echo "$hook_name: chained-under-entire"
        elif grep -qF "$marker" "$pre_entire" 2>/dev/null; then
            current_pre_content="$(cat "$pre_entire")"
            if [[ "$current_pre_content" != "$expected_content" ]]; then
                generate_delegator "$hook_name" > "$pre_entire"
                chmod +x "$pre_entire"
            fi
            echo "$hook_name: chained-under-entire"
        else
            echo "WARN: $pre_entire exists and was not generated by scripts/install_git_hooks.sh; skipping" >&2
            echo "$hook_name: skipped"
        fi
    elif grep -qF "$marker" "$target" 2>/dev/null; then
        current_content="$(cat "$target")"
        if [[ "$current_content" == "$expected_content" ]]; then
            echo "$hook_name: kept"
        else
            generate_delegator "$hook_name" > "$target"
            chmod +x "$target"
            echo "$hook_name: installed"
        fi
    else
        echo "WARN: $target exists and was not generated by scripts/install_git_hooks.sh; skipping" >&2
        echo "$hook_name: skipped"
    fi
done

# 4. Sparse worktree materialization
while IFS= read -r worktree; do
    if [[ -n "$worktree" ]] && [[ "$(git -C "$worktree" config --bool core.sparseCheckout 2>/dev/null || true)" == "true" ]]; then
        git -C "$worktree" sparse-checkout add --skip-checks .githooks
    fi
done < <(git -C "$repo_root" worktree list --porcelain | sed -n 's/^worktree //p')
