#!/usr/bin/env bash
# Configure Git hook delegators in the untracked common hooks directory
# so that tracked hooks in .githooks are invoked for all linked worktrees
# without core.hooksPath pointing at a tracked directory.
#
# Usage:
#   scripts/install_git_hooks.sh          install or refresh the delegators
#   scripts/install_git_hooks.sh --check  read-only: fail when a hook stage declared in
#                                         .pre-commit-config.yaml has no reachable delegator
set -euo pipefail

mode="install"
case "${1-}" in
    "") ;;
    --check) mode="check" ;;
    -h|--help)
        sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'
        exit 0
        ;;
    *)
        echo "Unknown argument: $1 (expected --check or --help)" >&2
        exit 2
        ;;
esac

repo_root="$(git rev-parse --show-toplevel)"
tracked_hooks_dir="$repo_root/.githooks"
if [[ ! -d "$tracked_hooks_dir" ]]; then
    echo "Tracked hooks directory not found at $tracked_hooks_dir" >&2
    exit 1
fi

required_hooks=(
    pre-commit
    commit-msg
    pre-push
    post-merge
    post-checkout
    post-commit
)
for hook_name in "${required_hooks[@]}"; do
    if [[ ! -x "$tracked_hooks_dir/$hook_name" ]]; then
        echo "Expected executable hook at $tracked_hooks_dir/$hook_name" >&2
        exit 1
    fi
done

for support_file in _lib.sh check-pytest-stamp.py pytest_stamp.py; do
    if [[ ! -r "$tracked_hooks_dir/$support_file" ]]; then
        echo "Expected readable hook support file at $tracked_hooks_dir/$support_file" >&2
        exit 1
    fi
done

marker="# generated by scripts/install_git_hooks.sh"
entire_marker="# Entire CLI hooks"

generate_delegator() {
    local hook_name="$1"
    cat <<EOF
#!/usr/bin/env bash
# generated by scripts/install_git_hooks.sh — delegates to the tracked hook in the CURRENT worktree
set -euo pipefail
root="\$(git rev-parse --show-toplevel)"
hook="\$root/.githooks/$hook_name"
[[ -x "\$hook" ]] || exit 0
exec "\$hook" "\$@"
EOF
}

# Entire CLI (0.8.42) writes this block into its wrapper only when <name>.pre-entire
# already exists at the moment Entire writes the wrapper; it never adds it later.
# The block is the wrapper's last command, so the chained hook's exit status is the
# wrapper's exit status. Byte-identical to Entire's own output, so an Entire reinstall
# (which sees the .pre-entire file) regenerates the same wrapper.
entire_chain_block() {
    local hook_name="$1"
    cat <<EOF
# Chain: run pre-existing hook
_entire_hook_dir="\$(dirname "\$0")"
if [ -x "\$_entire_hook_dir/$hook_name.pre-entire" ]; then
    "\$_entire_hook_dir/$hook_name.pre-entire" "\$@"
fi
EOF
}

entire_chains_to_pre_entire() {
    local wrapper="$1" hook_name="$2"
    grep -qxF "    \"\$_entire_hook_dir/$hook_name.pre-entire\" \"\$@\"" "$wrapper" 2>/dev/null
}

is_current_delegator() {
    local path="$1" hook_name="$2"
    [[ -f "$path" && -x "$path" && "$(cat "$path")" == "$(generate_delegator "$hook_name")" ]]
}

# Hook types .pre-commit-config.yaml asks to run, from a real YAML parse
# (default_install_hook_types, default_stages, and every hook's stages).
declared_stages() {
    local config="$1"
    (cd "$repo_root" && bash scripts/pre_commit/project_python.sh \
        scripts/pre_commit/declared_hook_stages.py "$config")
}

run_check() {
    local config="$repo_root/.pre-commit-config.yaml"
    if [[ ! -f "$config" ]]; then
        echo "check: no .pre-commit-config.yaml at $config" >&2
        return 1
    fi
    local hooks_dir
    hooks_dir="$(git rev-parse --path-format=absolute --git-path hooks)"
    local stages failures=0 stage wrapper pre_entire
    if ! stages="$(declared_stages "$config")"; then
        echo "check: cannot parse declared hook stages from $config; failing closed" >&2
        return 1
    fi
    if [[ -z "$stages" ]]; then
        echo "check: no hook stages declared in $config" >&2
        return 1
    fi
    while IFS= read -r stage; do
        wrapper="$hooks_dir/$stage"
        pre_entire="$hooks_dir/$stage.pre-entire"
        if [[ ! -x "$tracked_hooks_dir/$stage" ]]; then
            echo "$stage: UNREACHABLE — no executable tracked hook at $tracked_hooks_dir/$stage" >&2
            failures=$((failures + 1))
        elif is_current_delegator "$wrapper" "$stage"; then
            echo "$stage: ok (delegator)"
        elif [[ -x "$wrapper" ]] && grep -qF "$entire_marker" "$wrapper" \
            && entire_chains_to_pre_entire "$wrapper" "$stage" \
            && is_current_delegator "$pre_entire" "$stage"; then
            echo "$stage: ok (chained under Entire)"
        else
            echo "$stage: UNREACHABLE — $wrapper does not run the current repo delegator (rerun scripts/install_git_hooks.sh)" >&2
            failures=$((failures + 1))
        fi
    done <<<"$stages"
    if ((failures > 0)); then
        echo "check: $failures declared hook stage(s) unreachable in $hooks_dir" >&2
        return 1
    fi
}

if [[ "$mode" == "check" ]]; then
    run_check
    exit $?
fi

git_common_dir="$(git rev-parse --git-common-dir)"
if [[ "$git_common_dir" != /* ]]; then
    git_common_dir="$repo_root/$git_common_dir"
fi
hooks_dir="$git_common_dir/hooks"
mkdir -p "$hooks_dir"

# 1. Unset core.hooksPath if set to .githooks (leave any other explicit value alone)
current_hooks_path="$(git config --get core.hooksPath 2>/dev/null || true)"
if [[ "$current_hooks_path" == ".githooks" ]]; then
    git config --unset core.hooksPath
elif [[ -n "$current_hooks_path" ]]; then
    echo "Found explicit core.hooksPath=$current_hooks_path; leaving untouched"
fi

# Make Entire's wrapper run <name>.pre-entire. Entire's post-rewrite chain replays a
# saved stdin that its own command consumed, so the generic block would be wrong there.
ensure_entire_chain() {
    local wrapper="$1" hook_name="$2"
    entire_chains_to_pre_entire "$wrapper" "$hook_name" && return 0
    if [[ "$hook_name" == "post-rewrite" ]]; then
        echo "WARN: $wrapper does not chain to $hook_name.pre-entire; run 'entire configure --force' to regenerate it" >&2
        return 0
    fi
    [[ -z "$(tail -c 1 "$wrapper")" ]] || printf '\n' >> "$wrapper"
    entire_chain_block "$hook_name" >> "$wrapper"
    echo "$hook_name: added Entire chain to $hook_name.pre-entire"
}

# 2. For every executable hook in .githooks whose name is a git hook name:
for hook_path in "$tracked_hooks_dir"/*; do
    [[ -e "$hook_path" ]] || continue
    hook_name="$(basename "$hook_path")"
    case "$hook_name" in
        _lib.sh|*.py|*.md|*.sh|_*|*.pre-entire|*.sample)
            continue
            ;;
    esac
    [[ -x "$hook_path" ]] || continue

    target="$hooks_dir/$hook_name"
    expected_content="$(generate_delegator "$hook_name")"

    if [[ ! -e "$target" ]]; then
        generate_delegator "$hook_name" > "$target"
        chmod +x "$target"
        echo "$hook_name: installed"
    elif grep -qF "$entire_marker" "$target" 2>/dev/null; then
        pre_entire="$hooks_dir/$hook_name.pre-entire"
        if [[ ! -e "$pre_entire" ]]; then
            generate_delegator "$hook_name" > "$pre_entire"
            chmod +x "$pre_entire"
            ensure_entire_chain "$target" "$hook_name"
            echo "$hook_name: chained-under-entire"
        elif grep -qF "$marker" "$pre_entire" 2>/dev/null; then
            current_pre_content="$(cat "$pre_entire")"
            if [[ "$current_pre_content" != "$expected_content" ]]; then
                generate_delegator "$hook_name" > "$pre_entire"
            fi
            chmod +x "$pre_entire"
            ensure_entire_chain "$target" "$hook_name"
            echo "$hook_name: chained-under-entire"
        else
            echo "WARN: $pre_entire exists and was not generated by scripts/install_git_hooks.sh; skipping" >&2
            echo "$hook_name: skipped"
        fi
    elif grep -qF "$marker" "$target" 2>/dev/null; then
        current_content="$(cat "$target")"
        if [[ "$current_content" == "$expected_content" ]]; then
            echo "$hook_name: kept"
        else
            generate_delegator "$hook_name" > "$target"
            chmod +x "$target"
            echo "$hook_name: installed"
        fi
    else
        echo "WARN: $target exists and was not generated by scripts/install_git_hooks.sh; skipping" >&2
        echo "$hook_name: skipped"
    fi
done

# 4. Sparse worktree materialization
while IFS= read -r worktree; do
    if [[ -n "$worktree" ]] && [[ "$(git -C "$worktree" config --bool core.sparseCheckout 2>/dev/null || true)" == "true" ]]; then
        git -C "$worktree" sparse-checkout add --skip-checks .githooks
    fi
done < <(git -C "$repo_root" worktree list --porcelain | sed -n 's/^worktree //p')
