import { readFile, writeFile } from 'node:fs/promises';
import { URL } from 'node:url';

const schemaUrl = new URL('../src/lu.activity.v1.schema.json', import.meta.url);
const upstreamSchemaUrl = new URL('../../../schemas/activity-v2.schema.json', import.meta.url);
const outputUrl = new URL('../src/lu.activity.v1.generated.ts', import.meta.url);
const schema = JSON.parse(await readFile(schemaUrl, 'utf8'));
const upstreamSchema = JSON.parse(await readFile(upstreamSchemaUrl, 'utf8'));

function dereference(reference) {
  const [url, fragment = ''] = reference.split('#');
  const document = !url || url === schema.$id ? schema : url === upstreamSchema.$id ? upstreamSchema : null;

  if (!document || !fragment.startsWith('/')) {
    throw new Error(`Unsupported schema reference: ${reference}`);
  }

  return fragment.slice(1).split('/').reduce((value, key) => value[key], document);
}

function mergeSchema(node) {
  if (node.$ref) return mergeSchema(dereference(node.$ref));
  if (!node.allOf) return node;

  return node.allOf.map(mergeSchema).reduce((merged, part) => ({
    ...merged,
    ...part,
    properties: { ...merged.properties, ...part.properties },
    required: [...new Set([...(merged.required ?? []), ...(part.required ?? [])])],
  }), {});
}

function typeFor(node, depth = 0) {
  const resolved = mergeSchema(node);
  const indent = '  '.repeat(depth);
  const childIndent = '  '.repeat(depth + 1);

  if (resolved.const !== undefined) return JSON.stringify(resolved.const);
  if (resolved.enum) return resolved.enum.map((value) => JSON.stringify(value)).join(' | ');
  if (resolved.oneOf) return resolved.oneOf.map((option) => typeFor(option, depth)).join(' | ');
  if (resolved.type === 'string') return 'string';
  if (resolved.type === 'boolean') return 'boolean';
  if (resolved.type === 'integer' || resolved.type === 'number') return 'number';
  if (resolved.type === 'array') return `Array<${typeFor(resolved.items, depth)}>`;

  if (resolved.type === 'object' || resolved.properties) {
    const required = new Set(resolved.required ?? []);
    const properties = Object.entries(resolved.properties ?? {}).map(([name, property]) => (
      `${childIndent}${name}${required.has(name) ? '' : '?'}: ${typeFor(property, depth + 1)};`
    ));
    return `{\n${properties.join('\n')}\n${indent}}`;
  }

  throw new Error(`Unsupported schema shape: ${JSON.stringify(resolved)}`);
}

function pascalCase(value) {
  return value.replace(/(^|[-_])([a-z])/g, (_, __, letter) => letter.toUpperCase());
}

const activityTypes = schema.properties.type.enum;
const constraints = new Map(schema.allOf.map((rule) => [
  rule.if.properties.type.const,
  rule.then.properties,
]));

if (activityTypes.length !== constraints.size) {
  throw new Error('Each activity type needs a payload and answer-key constraint.');
}

const variants = activityTypes.map((activityType) => {
  const properties = constraints.get(activityType);
  const name = pascalCase(activityType);
  const payload = typeFor(properties.payload);
  const answerKey = typeFor(properties.answer_key);

  return {
    activityType,
    name,
    payload,
    answerKey,
  };
});

const provenance = typeFor(schema.properties.provenance);
const activityType = typeFor(schema.properties.type);
const level = typeFor(schema.properties.level);
const source = `// This file is generated by scripts/generate-types.mjs from lu.activity.v1.schema.json.\n// Do not edit directly.\n\nexport type LuActivityType = ${activityType};\n\nexport interface LuProvenance ${provenance}\n\n${variants.map(({ name, payload }) => `export type Lu${name}Payload = ${payload};`).join('\n\n')}\n\n${variants.map(({ name, answerKey }) => `export type Lu${name}AnswerKey = ${answerKey};`).join('\n\n')}\n\ninterface LuActivityBase<TType extends LuActivityType, TPayload, TAnswerKey> {\n  id: string;\n  type: TType;\n  title: string;\n  level: ${level};\n  payload: TPayload;\n  answer_key: TAnswerKey;\n  provenance: LuProvenance;\n}\n\n${variants.map(({ activityType, name }) => `export type Lu${name}ActivityV1 = LuActivityBase<'${activityType}', Lu${name}Payload, Lu${name}AnswerKey>;`).join('\n')}\n\nexport type LuActivityV1 =\n${variants.map(({ name }) => `  | Lu${name}ActivityV1`).join('\n')};\n`;

await writeFile(outputUrl, source);
