// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';
import starlightDocSearch from '@astrojs/starlight-docsearch';
import rehypeMermaid from 'rehype-mermaid';
import vocabEtymologyLinker from './plugins/vocab-etymology-link.mjs';


// https://astro.build/config
export default defineConfig({
  site: 'https://learn-ukrainian.github.io',
  trailingSlash: 'always',

  compressHTML: true,

  markdown: {
    remarkPlugins: [vocabEtymologyLinker],
    rehypePlugins: [rehypeMermaid],
  },

  // Prevent duplicate React instances (SSR + client hydration)
  vite: {
    resolve: {
      dedupe: ['react', 'react-dom'],
    },
    optimizeDeps: {
      include: ['react', 'react-dom'],
    },
  },

  integrations: [
    starlight({
      title: 'Learn Ukrainian',
      tagline: 'Мова – душа народу • Language is the soul of a nation',
      logo: {
        src: './src/assets/logo.svg',
        alt: 'Learn Ukrainian logo',
      },
      social: [
        {
          label: 'GitHub',
          icon: 'github',
          href: 'https://github.com/learn-ukrainian/learn-ukrainian.github.io',
        },
      ],
      head: [
        {
          tag: 'meta',
          attrs: {
            name: 'algolia-site-verification',
            content: '1DB51F4A18C9DC67',
          },
        },
        // Privacy-respecting analytics — no cookies, GDPR-compliant
        // To activate: sign up at plausible.io and set data-domain
        {
          tag: 'script',
          attrs: {
            defer: true,
            'data-domain': 'learn-ukrainian.github.io',
            src: 'https://plausible.io/js/script.js',
          },
        },
      ],
      credits: false,
      components: {
        Header: './src/components/overrides/Header.astro',
        Head: './src/components/overrides/Head.astro',
        PageTitle: './src/components/overrides/PageTitle.astro',
        Sidebar: './src/components/overrides/Sidebar.astro',
        Footer: './src/components/overrides/Footer.astro',
      },
      customCss: [
        './src/css/custom.css',
        './src/styles/lesson.css',
      ],
      plugins: [
        starlightDocSearch({
          appId: 'MFWOKG2YFD',
          apiKey: '4413bc11f7878cb2605766f6a050bdcc',
          indexName: 'https_learn_ukrainian_github_io_pages',
          searchParameters: {
            // Note: removed 'docusaurus_tag' — that was a Docusaurus-specific facet
            // that does not exist in Starlight and caused zero search results.
            facetFilters: [
              ['language:en', 'language:uk'],
            ],
          },
        }),
      ],
      sidebar: [
        { label: 'Getting Started', slug: 'index' },
        // Starlight 0.39.0 breaking change: autogenerated sidebar groups must
        // wrap their `autogenerate` config inside an `items: []` array so
        // manual links and autogenerated links can co-exist.
        // https://github.com/withastro/starlight/blob/main/packages/starlight/CHANGELOG.md
        { label: 'Лексикон (Word Atlas)', link: '/lexicon/' },
        { label: 'A1 - Beginner', collapsed: true, items: [{ autogenerate: { directory: 'a1' } }] },
        { label: 'A2 - Elementary', collapsed: true, items: [{ autogenerate: { directory: 'a2' } }] },
        { label: 'B1 - Intermediate', collapsed: true, items: [{ autogenerate: { directory: 'b1' } }] },
        { label: 'B2 - Upper-Intermediate', collapsed: true, items: [{ autogenerate: { directory: 'b2' } }] },
        { label: 'C1 - Advanced', collapsed: true, items: [{ autogenerate: { directory: 'c1' } }] },
        { label: 'C2 - Mastery', collapsed: true, items: [{ autogenerate: { directory: 'c2' } }] },
        { label: 'LIT - Literature', collapsed: true, items: [{ autogenerate: { directory: 'lit' } }] },
        { label: 'HIST - Історія України', collapsed: true, items: [{ autogenerate: { directory: 'hist' } }] },
        { label: 'ISTORIO - Історіографія', collapsed: true, items: [{ autogenerate: { directory: 'istorio' } }] },
        { label: 'BIO - Біографії українців', collapsed: true, items: [{ autogenerate: { directory: 'bio' } }] },
        { label: 'B2-PRO - Професійна українська', collapsed: true, items: [{ autogenerate: { directory: 'b2-pro' } }] },
        { label: 'C1-PRO - Фахова українська', collapsed: true, items: [{ autogenerate: { directory: 'c1-pro' } }] },
        { label: 'OES - Old East Slavic', collapsed: true, items: [{ autogenerate: { directory: 'oes' } }] },
        { label: 'RUTH - Ruthenian', collapsed: true, items: [{ autogenerate: { directory: 'ruth' } }] },
      ],
    }),
    react(),
    sitemap(),
  ],
});
