"""Copy ignored worker evidence before removal; failures retain the checkout (#9449)."""

from __future__ import annotations

import contextlib
import errno
import hashlib
import os
import re
import shlex
import stat
import subprocess
import tempfile
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from scripts.orchestration import reaper_lifecycle as reaper_lifecycle
from scripts.orchestration.dead_worker_state import task_state_lock as task_state_lock

REGENERABLE_CACHE_DIRECTORIES = frozenset(
    {
        ".pytest_cache",
        ".ruff_cache",
        ".mypy_cache",
        "__pycache__",
    }
)
_DISPOSABLE_DIRECTORIES = REGENERABLE_CACHE_DIRECTORIES | frozenset(
    {
        ".git",
        ".pytest_breadcrumbs",  # Pytest diagnostics are regenerated by test runs.
        ".astro",  # Astro rebuilds its content store and generated types.
        ".hypothesis",  # Hypothesis regenerates its local example database.
        ".tox",  # Tox recreates its test environments.
        ".nox",  # Nox recreates its session environments.
    }
)


def is_disposable_path(path: Path, *, worktree: Path | None = None, primary: Path | None = None) -> bool:
    """One removal taxonomy: caches and verified provisioned links only.

    Real environments can hold unique work, even beneath a cache directory.
    Arbitrary .cache files and loose bytecode are output, regardless of suffix.
    """
    provisioned = {"data/sources.db", "data/vesum.db", "node_modules", "site/node_modules"}
    if worktree is not None and primary is not None and worktree.resolve() != primary.resolve():
        for prefix in (path, *path.parents):
            if prefix.as_posix() in provisioned:
                link = worktree / prefix
                try:
                    if link.is_symlink() and link.resolve(strict=True) == (primary / prefix).resolve(strict=True):
                        return True
                except (OSError, RuntimeError):
                    return False
    if {".venv", "node_modules"}.intersection(path.parts):
        return False
    if _DISPOSABLE_DIRECTORIES.intersection(path.parts[:-1]) or (
        path.is_relative_to(".entire/logs") and path != Path(".entire/logs")
    ):
        return True
    if worktree is None or (path.name not in _DISPOSABLE_DIRECTORIES and path != Path(".entire/logs")):
        return False
    # Only a cache-directory candidate needs filesystem inspection. Ordinary
    # worker tokens may not be representable filenames; the named-artifact
    # resolver owns that classification and its privacy-safe refusals.
    resolved = _resolve_named(worktree.resolve(), path.parts)
    return resolved is not None and stat.S_ISDIR(resolved[1].st_mode) and not (worktree / path).is_symlink()


_CONFIG_INDIRECTION_RE = re.compile(
    r"^\s*(\[\s*include(if)?\b|include(if)?\b)",
    re.IGNORECASE | re.MULTILINE,
)
_REDIRECTED_WORKTREE_RE = re.compile(
    r"\bworktree\s*=",
    re.IGNORECASE,
)
_DANGEROUS_CONFIG_RE = re.compile(
    r"(\b(clean|smudge|process|command|textconv|fsmonitor|hookspath|sshcommand|askpass|editor|pager|helper|driver|cmd|promisor|partialclone|uploadpack|receivepack|trustctime|checkstat)\s*=|\bext::|\bprotocol\.[^.\s]+\.allow\s*=)",
    re.IGNORECASE,
)


def _safe_git_env() -> dict[str, str]:
    """Return an isolated Git environment with global and system configuration disabled."""
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env["GIT_CONFIG_GLOBAL"] = os.devnull
    env["GIT_CONFIG_SYSTEM"] = os.devnull
    env["GIT_CONFIG_NOSYSTEM"] = "1"
    env["GIT_OPTIONAL_LOCKS"] = "0"
    env["GIT_TERMINAL_PROMPT"] = "0"
    env["GIT_NO_REPLACE_OBJECTS"] = "1"
    return env


def _git_paths(worktree: Path, *args: str) -> list[str]:
    """Read NUL-delimited paths, refusing an unavailable inventory."""
    result = subprocess.run(
        ["git", "ls-files", "-z", *args],
        cwd=worktree,
        env=_safe_git_env(),
        capture_output=True,
        check=True,
        timeout=30,
    )
    return [os.fsdecode(path) for path in result.stdout.split(b"\0") if path]


def _symlink_record_bytes(target: str) -> bytes:
    """Inert link record: the type and the raw target string, never the target's bytes."""
    return b"symlink\n" + os.fsencode(target)


_DIRECTORY_FLAGS = os.O_RDONLY | os.O_CLOEXEC | os.O_DIRECTORY | os.O_NOFOLLOW
_LEAF_FLAGS = os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW | os.O_NONBLOCK


def _open_directory(path: Path) -> int:
    """Open ``path`` without following a symlink at its final component."""
    fd = os.open(path, _DIRECTORY_FLAGS)
    try:
        if not stat.S_ISDIR(os.fstat(fd).st_mode):
            raise ValueError("artifact is not a regular file")
    except (OSError, ValueError):
        os.close(fd)
        raise
    return fd


def _read_regular(fd: int) -> bytes:
    """Read one regular file from an already-opened descriptor."""
    info = os.fstat(fd)
    if not stat.S_ISREG(info.st_mode):
        raise ValueError("artifact is not a regular file")
    size = info.st_size
    chunks: list[bytes] = []
    remaining = size
    while remaining > 0:
        chunk = os.read(fd, min(remaining, 1024 * 1024))
        if not chunk:
            break
        chunks.append(chunk)
        remaining -= len(chunk)
    payload = b"".join(chunks)
    after = os.fstat(fd)
    if (
        after.st_dev != info.st_dev
        or after.st_ino != info.st_ino
        or not stat.S_ISREG(after.st_mode)
        or after.st_size != size
        or len(payload) != size
    ):
        raise ValueError("artifact size or SHA-256 changed during preservation")
    return payload


def _read_preserved_bytes(path: Path) -> bytes:
    """Read a regular file, or a symlink's inert record, without following links.

    The parent is a verified directory descriptor. The leaf is opened once,
    relative to that descriptor, with ``O_NOFOLLOW``. ``fstat`` must show a
    regular file, and both the fingerprint and the preserved bytes come from
    that same descriptor. A symlink is not opened. Replacing a regular file
    with a symlink after the type check refuses; the new target is not read.
    """
    parent_fd = _open_directory(path.parent)
    try:
        name = path.name
        # The check can go stale before the open. ``O_NOFOLLOW`` below refuses
        # that replacement instead of following the new link.
        if path.is_symlink():
            try:
                target = os.readlink(name, dir_fd=parent_fd)
            except FileNotFoundError:
                raise
            except OSError as exc:
                raise ValueError("artifact changed during preservation") from exc
            return _symlink_record_bytes(target)
        try:
            leaf_fd = os.open(name, _LEAF_FLAGS, dir_fd=parent_fd)
        except FileNotFoundError:
            raise
        except OSError as exc:
            if exc.errno == errno.ELOOP:
                raise ValueError("artifact changed during preservation") from exc
            raise
        try:
            return _read_regular(leaf_fd)
        finally:
            os.close(leaf_fd)
    finally:
        os.close(parent_fd)


def _fingerprint(path: Path) -> tuple[int, str]:
    """Hash file bytes, or the inert link record when ``path`` is a symlink.

    Regular-file bytes come from one ``O_NOFOLLOW`` descriptor. A symlink is
    never opened, so a dangling link and a link out of the checkout contribute
    only their target string.
    """
    payload = _read_preserved_bytes(path)
    return len(payload), hashlib.sha256(payload).hexdigest()


def _write_verified_bytes(payload: bytes, destination: Path) -> None:
    """Write bytes already taken from a verified source descriptor."""
    with destination.open("wb") as handle:
        handle.write(payload)
        handle.flush()
        os.fsync(handle.fileno())


def _copy_verified(source: Path, destination: Path) -> None:
    """Copy atomically, verifying size and SHA-256 and refusing conflicting evidence.

    A symlink is written as an inert link record. The destination is never a
    live symlink, and the source target is not opened or copied. Regular-file
    bytes are read once from an ``O_NOFOLLOW`` descriptor and that buffer is
    what gets written; the source path is not opened again.
    """
    payload = _read_preserved_bytes(source)
    before = (len(payload), hashlib.sha256(payload).hexdigest())
    destination.parent.mkdir(parents=True, exist_ok=True)
    # ``exists`` follows links, so a dangling destination symlink must be caught separately.
    if destination.exists() or destination.is_symlink():
        if destination.is_symlink() or _fingerprint(destination) != before:
            raise ValueError("preserved artifact already exists with different bytes")
        return
    fd, temporary_name = tempfile.mkstemp(prefix=".preserve-", dir=destination.parent)
    temporary = Path(temporary_name)
    try:
        os.close(fd)
        _write_verified_bytes(payload, temporary)
        if _fingerprint(temporary) != before:
            raise ValueError("artifact size or SHA-256 changed during preservation")
        # Another checkout of this task may preserve concurrently. Never replace
        # evidence it published after our initial existence check.
        os.link(temporary, destination)
        if _fingerprint(destination) != before:
            raise ValueError("preserved artifact size or SHA-256 mismatch")
    finally:
        temporary.unlink(missing_ok=True)


def _resolve_named(root: Path, parts: tuple[str, ...]) -> tuple[Path, os.stat_result] | None:
    """Resolve a name as the filesystem does; ``None`` when nothing exists there.

    No lexical normalization: ``..`` after a symlinked directory applies to the
    link's target. A name too long for the filesystem or holding a NUL byte
    cannot refer to a file, so it is no evidence (long URLs and tokens in a
    worker response must not retain the checkout). Any other resolver failure
    may hide an existing file and refuses removal, naming only the failure
    class, never the path text.
    """
    try:
        resolved = Path(os.path.realpath(root.joinpath(*parts)))
        return resolved, resolved.stat()
    except (FileNotFoundError, NotADirectoryError, ValueError):
        return None
    except RuntimeError:
        kind = "symlink loop"
    except OSError as exc:
        if exc.errno == errno.ENAMETOOLONG:
            return None
        kind = "symlink loop" if exc.errno == errno.ELOOP else errno.errorcode.get(exc.errno or 0, type(exc).__name__)
    raise ValueError(f"a named artifact path cannot be resolved ({kind})")


def _leaves_through_link(root: Path, parts: tuple[str, ...]) -> bool:
    """Whether resolving ``parts`` leaves the checkout through a link inside it.

    Climbing out of the root with ``..`` is not a checkout name; removal
    cannot take what such a name reaches.
    """
    current = root
    for part in parts:
        inside = current.is_relative_to(root)
        current = current.parent if part == ".." else Path(os.path.realpath(current / part))
        if part != ".." and inside and not current.is_relative_to(root):
            return True
    return False


def _named_artifact_files(worktree: Path, record: Mapping[str, Any], *, primary: Path) -> set[str]:
    """Inventory only explicitly named, non-empty ignored files outside caches.

    Tracked files survive in Git; directories are not evidence inventories.
    A name stands for the file the filesystem resolves it to: a target inside
    the checkout is inventoried under its resolved path, because removal
    destroys it; a target file reached through a link out of the checkout
    cannot be preserved here and refuses removal, unless it already lives
    under the primary's batch_state. Backticks/quotes and Markdown links
    support spaced paths.
    """
    root = worktree.resolve()
    shared_state = primary / "batch_state"
    files: set[str] = set()
    text = str(record.get("response") or "")
    result_file = record.get("result_file")
    if result_file:
        result_path = Path(str(result_file))
        if not result_path.is_absolute():
            result_path = worktree / result_path
        if result_path.is_file():
            text += "\n" + result_path.read_text(encoding="utf-8")
    candidates = re.findall(r"[`\"']([^`\"'\n]+)[`\"']|\[[^\]\n]*\]\(([^)]+)\)|([^\s`\"'<>(),;]+)", text)
    for match in candidates:
        candidate = next(part for part in match if part).rstrip(".:!?")
        candidate = re.sub(r":\d+(?::\d+)?$", "", candidate)
        if not candidate:
            continue
        path = Path(candidate)
        if path.is_absolute():
            base = next((base for base in (worktree, root) if path.is_relative_to(base)), None)
            if base is None:
                continue
            path = path.relative_to(base)
        parts = path.parts
        if is_disposable_path(path, worktree=worktree, primary=primary):
            continue
        found = _resolve_named(root, parts)
        if found is None:
            continue
        resolved, status = found
        if not stat.S_ISREG(status.st_mode) or not status.st_size:
            continue
        if not resolved.is_relative_to(root):
            # Never copied: following an outbound link would read outside the checkout.
            if not resolved.is_relative_to(shared_state) and _leaves_through_link(root, parts):
                raise ValueError(f"named artifact {path.as_posix()} links outside the checkout and cannot be preserved")
            continue
        relative = resolved.relative_to(root)
        if is_disposable_path(relative, worktree=worktree, primary=primary):
            continue
        name = relative.as_posix()
        ignored = _git_paths(worktree, "--others", "--ignored", "--exclude-standard", "--", name)
        if name in ignored:
            files.add(name)
    return files


def _inspect_directory_artifact(source: Path, name: str, *, worktree: Path) -> list[str]:
    """Inspect a directory entry in the ignored inventory.

    If it contains a nested git repository or linked worktree, verifies commit
    and pointer safety, failing closed with actionable diagnostics or refusing
    discard of unpushed commits. If it is a directory of ordinary files, yields
    the non-empty regular files inside it. Symlinks are collected as links and
    not followed. Any other non-regular file fails closed.
    """
    clean_name = name.rstrip("/")
    dot_git = source / ".git"

    if dot_git.is_symlink():
        raise ValueError(f"artifact has a symlinked .git entry: {name}")

    if dot_git.exists():
        # Check linked worktree gitdir pointer
        if dot_git.is_file():
            try:
                content = dot_git.read_text(encoding="utf-8").strip()
            except (OSError, UnicodeDecodeError) as exc:
                raise ValueError(f"artifact has an unreadable .git file ({exc}): {name}") from exc
            if content.startswith("gitdir:"):
                target_str = content.removeprefix("gitdir:").strip()
                target_path = Path(target_str)
                if not target_path.is_absolute():
                    target_path = (source / target_path).resolve()
                else:
                    target_path = target_path.resolve()
                if target_path.is_relative_to(worktree.resolve()):
                    target_rel = target_path.relative_to(worktree.resolve()).as_posix()
                    raise ValueError(
                        f"artifact is a nested linked worktree whose gitdir pointer "
                        f"points at another artifact ({target_rel}): {name}"
                    )

        # Check for executable, filter, redirection, or indirection configuration in git configs
        config_files: list[Path] = []
        if dot_git.is_dir():
            for p in dot_git.glob("config*"):
                if p.is_file():
                    config_files.append(p)
            wt_dir = dot_git / "worktrees"
            if wt_dir.is_dir():
                for p in wt_dir.rglob("config*"):
                    if p.is_file():
                        config_files.append(p)
            commondir_file = dot_git / "commondir"
            if commondir_file.is_file():
                try:
                    commondir_text = commondir_file.read_text(encoding="utf-8", errors="replace").strip()
                    commondir_path = Path(commondir_text)
                    if not commondir_path.is_absolute():
                        commondir_path = (dot_git / commondir_path).resolve()
                    for p in commondir_path.glob("config*"):
                        if p.is_file():
                            config_files.append(p)
                    cwt_dir = commondir_path / "worktrees"
                    if cwt_dir.is_dir():
                        for p in cwt_dir.rglob("config*"):
                            if p.is_file():
                                config_files.append(p)
                except OSError:
                    pass
        elif dot_git.is_file():
            with contextlib.suppress(OSError):
                gitdir_text = dot_git.read_text(encoding="utf-8", errors="replace").strip()
                if gitdir_text.startswith("gitdir:"):
                    gitdir_path = Path(gitdir_text[7:].strip())
                    if not gitdir_path.is_absolute():
                        gitdir_path = (source / gitdir_path).resolve()
                    for p in gitdir_path.glob("config*"):
                        if p.is_file():
                            config_files.append(p)
                    commondir_file = gitdir_path / "commondir"
                    if commondir_file.is_file():
                        commondir_text = commondir_file.read_text(encoding="utf-8", errors="replace").strip()
                        commondir_path = Path(commondir_text)
                        if not commondir_path.is_absolute():
                            commondir_path = (gitdir_path / commondir_path).resolve()
                        for p in commondir_path.glob("config*"):
                            if p.is_file():
                                config_files.append(p)
                        cwt_dir = commondir_path / "worktrees"
                        if cwt_dir.is_dir():
                            for p in cwt_dir.rglob("config*"):
                                if p.is_file():
                                    config_files.append(p)

        seen_configs: set[Path] = set()
        for cfg_path in config_files:
            if cfg_path in seen_configs:
                continue
            seen_configs.add(cfg_path)
            if not cfg_path.is_file():
                continue
            try:
                cfg_text = cfg_path.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                raise ValueError(f"failed to read git config in nested repository {name}: {exc}") from exc

            cleaned_lines: list[str] = []
            for line in cfg_text.splitlines():
                stripped = line.strip()
                if stripped.startswith(("#", ";")):
                    continue
                cleaned_lines.append(line)
            cleaned_text = "\n".join(cleaned_lines)

            if _CONFIG_INDIRECTION_RE.search(cleaned_text):
                raise ValueError(
                    f"artifact is a nested git repository with configuration indirection (include/includeIf): {name}; "
                    f"refusing removal to prevent code execution"
                )

            if _REDIRECTED_WORKTREE_RE.search(cleaned_text):
                raise ValueError(
                    f"artifact is a nested git repository with redirected worktree (core.worktree): {name}; "
                    f"refusing removal"
                )

            if _DANGEROUS_CONFIG_RE.search(cleaned_text):
                raise ValueError(
                    f"artifact is a nested git repository with executable or filter configuration: {name}; "
                    f"refusing removal to prevent code execution"
                )

        if dot_git.is_dir() and (dot_git / "commondir").is_file():
            raise ValueError(
                f"artifact is a nested git repository with commondir metadata indirection: {name}; "
                f"refusing removal to prevent code execution"
            )

        # Count regular files and compute total size in bytes,
        # and pre-inspect for embedded git repositories.
        file_count = 0
        total_size = 0
        has_embedded_git = False
        resolved_dot_git = dot_git.resolve()
        for root_dir, dirs, filenames in os.walk(source):
            current_path = Path(root_dir).resolve()
            if (
                current_path != source.resolve()
                and current_path != resolved_dot_git
                and resolved_dot_git not in current_path.parents
                and (
                    ".git" in dirs
                    or ".git" in filenames
                    or (current_path / ".git").exists()
                    or (current_path / ".git").is_symlink()
                )
            ):
                has_embedded_git = True
            for fname in filenames:
                fpath = Path(root_dir) / fname
                try:
                    st = fpath.lstat()
                    file_count += 1
                    total_size += st.st_size
                except OSError:
                    pass

        has_submodules = has_embedded_git or (source / ".gitmodules").is_file()
        if not has_submodules:
            modules_dirs: list[Path] = []
            if dot_git.is_dir():
                modules_dirs.append(dot_git / "modules")
            elif dot_git.is_file():
                with contextlib.suppress(OSError):
                    gitdir_text = dot_git.read_text(encoding="utf-8", errors="replace").strip()
                    if gitdir_text.startswith("gitdir:"):
                        gitdir_path = Path(gitdir_text[7:].strip())
                        if not gitdir_path.is_absolute():
                            gitdir_path = (source / gitdir_path).resolve()
                        modules_dirs.append(gitdir_path / "modules")
                        commondir_file = gitdir_path / "commondir"
                        if commondir_file.is_file():
                            cd_text = commondir_file.read_text(encoding="utf-8", errors="replace").strip()
                            cd_path = Path(cd_text)
                            if not cd_path.is_absolute():
                                cd_path = (gitdir_path / cd_path).resolve()
                            modules_dirs.append(cd_path / "modules")
            for mdir in modules_dirs:
                if mdir.is_dir():
                    has_submodules = True
                    break
        if not has_submodules:
            submodule_section_re = re.compile(r"^\s*\[\s*submodule\b", re.IGNORECASE | re.MULTILINE)
            for cfg_path in seen_configs:
                try:
                    cfg_text = cfg_path.read_text(encoding="utf-8", errors="replace")
                    if submodule_section_re.search(cfg_text):
                        has_submodules = True
                        break
                except OSError:
                    pass

        if has_submodules:
            raise ValueError(
                f"artifact is a nested git repository with unverified submodules "
                f"({file_count} files, {total_size} bytes): {name}; "
                f"submodules must not be discarded without independent verification"
            )

        env = _safe_git_env()
        git_cmd = [
            "git",
            "--no-lazy-fetch",
            "-c",
            "core.fsmonitor=",
            "-c",
            "core.hooksPath=/dev/null",
            "-c",
            "protocol.ext.allow=never",
            "-c",
            "core.alternateRefsCommand=",
            "-c",
            "core.attributesFile=/dev/null",
            "-c",
            "core.trustctime=true",
            "-c",
            "core.checkStat=default",
        ]
        try:
            toplevel_proc = subprocess.run(
                [*git_cmd, "rev-parse", "--show-toplevel"],
                cwd=source,
                capture_output=True,
                env=env,
                timeout=15,
                check=False,
            )
            if toplevel_proc.returncode != 0:
                err = toplevel_proc.stderr.decode("utf-8", "replace").strip()
                raise ValueError(f"artifact is an invalid nested git repository ({err}): {name}")

            toplevel_str = toplevel_proc.stdout.decode("utf-8", "replace").strip()
            if not toplevel_str:
                raise ValueError(f"artifact is an invalid nested git repository (no toplevel): {name}")
            toplevel_path = Path(toplevel_str).resolve()
            if toplevel_path != source.resolve():
                raise ValueError(
                    f"artifact git repository worktree ({toplevel_path}) does not match "
                    f"expected directory ({source.resolve()}): {name}; refusing removal"
                )

            # Check for gitlinks (mode 160000) and verify tracked file contents independently
            stage_proc = subprocess.run(
                [*git_cmd, "ls-files", "--stage", "-z"],
                cwd=source,
                capture_output=True,
                env=env,
                timeout=15,
                check=False,
            )
            if stage_proc.returncode != 0:
                err = stage_proc.stderr.decode("utf-8", "replace").strip()
                raise ValueError(f"artifact is an invalid nested git repository ({err}): {name}")

            stage_entries: list[tuple[bytes, bytes, bytes]] = []
            for entry in stage_proc.stdout.split(b"\0"):
                if not entry:
                    continue
                meta, path_b = entry.split(b"\t", 1)
                mode_b, sha_b, _stage_b = meta.split(b" ")
                if mode_b == b"160000":
                    raise ValueError(
                        f"artifact is a nested git repository with unverified submodules "
                        f"({file_count} files, {total_size} bytes): {name}; "
                        f"submodules must not be discarded without independent verification"
                    )
                stage_entries.append((mode_b, sha_b, path_b))

            head_proc = subprocess.run(
                [*git_cmd, "rev-parse", "--verify", "HEAD"],
                cwd=source,
                capture_output=True,
                env=env,
                timeout=15,
                check=False,
            )
            if head_proc.returncode == 0:
                tree_proc = subprocess.run(
                    [*git_cmd, "ls-tree", "-r", "HEAD"],
                    cwd=source,
                    capture_output=True,
                    env=env,
                    timeout=15,
                    check=False,
                )
                if tree_proc.returncode != 0:
                    err = tree_proc.stderr.decode("utf-8", "replace").strip()
                    raise ValueError(f"artifact is an invalid nested git repository ({err}): {name}")

                for raw_line in tree_proc.stdout.decode("utf-8", "replace").splitlines():
                    line = raw_line.strip()
                    if line.startswith("160000 "):
                        raise ValueError(
                            f"artifact is a nested git repository with unverified submodules "
                            f"({file_count} files, {total_size} bytes): {name}; "
                            f"submodules must not be discarded without independent verification"
                        )

            ls_proc = subprocess.run(
                [*git_cmd, "ls-files", "-v"],
                cwd=source,
                capture_output=True,
                env=env,
                timeout=15,
                check=False,
            )
            if ls_proc.returncode != 0:
                err = ls_proc.stderr.decode("utf-8", "replace").strip()
                raise ValueError(f"artifact is an invalid nested git repository ({err}): {name}")

            concealed_files: list[str] = []
            for raw_line in ls_proc.stdout.decode("utf-8", "replace").splitlines():
                line = raw_line.strip()
                if not line:
                    continue
                tag = line[0]
                if tag == "S" or tag.islower():
                    concealed_files.append(line)

            if concealed_files:
                concealed_summary = ", ".join(concealed_files[:3]) + ("..." if len(concealed_files) > 3 else "")
                raise ValueError(
                    f"artifact is a nested git repository with concealed tracked changes (assume-unchanged or skip-worktree) "
                    f"({file_count} files, {total_size} bytes; concealed: {concealed_summary}): {name}; "
                    f"uncommitted work must not be discarded"
                )

            status_proc = subprocess.run(
                [*git_cmd, "status", "--porcelain", "-uall", "--ignored", "--ignore-submodules=none"],
                cwd=source,
                capture_output=True,
                env=env,
                timeout=15,
                check=False,
            )
            if status_proc.returncode != 0:
                err = status_proc.stderr.decode("utf-8", "replace").strip()
                raise ValueError(f"artifact is an invalid nested git repository ({err}): {name}")

            dirty_lines: list[str] = []
            for raw_line in status_proc.stdout.decode("utf-8", "replace").splitlines():
                if not raw_line or len(raw_line) < 3:
                    continue
                code = raw_line[:2]
                path_str = raw_line[3:].strip()
                if code == "!!" and is_disposable_path(Path(path_str), worktree=source):
                    continue
                dirty_lines.append(raw_line.strip())

            if dirty_lines:
                dirty_summary = ", ".join(dirty_lines[:3]) + ("..." if len(dirty_lines) > 3 else "")
                raise ValueError(
                    f"artifact is a nested git repository with uncommitted or ignored changes "
                    f"({file_count} files, {total_size} bytes; uncommitted: {dirty_summary}): {name}; "
                    f"uncommitted work must not be discarded"
                )

            for mode_b, sha_b, path_b in stage_entries:
                rel_path = os.fsdecode(path_b)
                target_path = source / path_b.decode("utf-8", "surrogateescape")
                if mode_b in (b"100644", b"100755"):
                    if not target_path.is_file() or target_path.is_symlink():
                        raise ValueError(
                            f"artifact is a nested git repository with uncommitted or missing tracked files "
                            f"({file_count} files, {total_size} bytes; missing: {rel_path}): {name}; "
                            f"uncommitted work must not be discarded"
                        )
                    try:
                        content = target_path.read_bytes()
                    except OSError as exc:
                        raise ValueError(f"artifact tracked file unreadable ({exc}): {name}") from exc
                    header = f"blob {len(content)}\0".encode("ascii")
                    hasher = hashlib.sha256() if len(sha_b) == 64 else hashlib.sha1()
                    hasher.update(header)
                    hasher.update(content)
                    if hasher.hexdigest().encode("ascii") != sha_b:
                        raise ValueError(
                            f"artifact is a nested git repository with uncommitted tracked changes "
                            f"({file_count} files, {total_size} bytes; modified: {rel_path}): {name}; "
                            f"uncommitted work must not be discarded"
                        )
                elif mode_b == b"120000":
                    if not target_path.is_symlink():
                        raise ValueError(
                            f"artifact is a nested git repository with uncommitted tracked changes "
                            f"({file_count} files, {total_size} bytes; modified symlink: {rel_path}): {name}; "
                            f"uncommitted work must not be discarded"
                        )
                    try:
                        target = os.readlink(target_path).encode("utf-8", "surrogateescape")
                    except OSError as exc:
                        raise ValueError(f"artifact tracked symlink unreadable ({exc}): {name}") from exc
                    header = f"blob {len(target)}\0".encode("ascii")
                    hasher = hashlib.sha256() if len(sha_b) == 64 else hashlib.sha1()
                    hasher.update(header)
                    hasher.update(target)
                    if hasher.hexdigest().encode("ascii") != sha_b:
                        raise ValueError(
                            f"artifact is a nested git repository with uncommitted tracked changes "
                            f"({file_count} files, {total_size} bytes; modified symlink: {rel_path}): {name}; "
                            f"uncommitted work must not be discarded"
                        )

            rev_list_args = [*git_cmd, "rev-list", "--all", "--reflog"]
            if head_proc.returncode == 0:
                rev_list_args.append("HEAD")
            rev_list_args.extend(["--not", "--remotes"])

            res = subprocess.run(
                rev_list_args,
                cwd=source,
                capture_output=True,
                env=env,
                timeout=15,
                check=False,
            )
            if res.returncode != 0:
                err = res.stderr.decode("utf-8", "replace").strip()
                raise ValueError(f"artifact is an invalid nested git repository ({err}): {name}")

            unpushed = [line.strip() for line in res.stdout.decode("ascii", "replace").split() if line.strip()]
            if unpushed:
                commits_summary = ", ".join(unpushed[:3]) + ("..." if len(unpushed) > 3 else "")
                raise ValueError(
                    f"artifact is a nested git repository with unpushed commits "
                    f"({file_count} files, {total_size} bytes; unpushed: {commits_summary}): {name}; "
                    f"unpushed work must not be discarded"
                )
        except (subprocess.SubprocessError, OSError) as exc:
            raise ValueError(f"failed to check git status in nested repository {name}: {exc}") from exc

        quoted_clean_name = shlex.quote(clean_name)
        raise ValueError(
            f"artifact is a nested git repository with no unpushed commits "
            f"({file_count} files, {total_size} bytes): {name}; "
            f"clear with: rm -rf {quoted_clean_name}"
        )

    # Directory of ordinary files (no .git). Never descend through a symlink:
    # os.walk classifies a directory link as a directory, so drop those names
    # from ``dirs`` before the walk continues.
    collected: list[str] = []
    for root_dir, dirs, filenames in os.walk(source, followlinks=False):
        root_path = Path(root_dir)
        kept_dirs: list[str] = []
        for directory in dirs:
            child = root_path / directory
            relative = child.relative_to(worktree)
            if child.is_symlink():
                collected.append(relative.as_posix())
                continue
            if not is_disposable_path(relative, worktree=worktree):
                kept_dirs.append(directory)
        dirs[:] = kept_dirs
        for fname in filenames:
            fpath = root_path / fname
            relative = fpath.relative_to(worktree)
            if fpath.is_symlink():
                collected.append(relative.as_posix())
                continue
            if fpath.resolve() != fpath.absolute() or not stat.S_ISREG(fpath.lstat().st_mode):
                raise ValueError(f"artifact is not a local regular file: {relative.as_posix()}")
            if fpath.stat().st_size:
                collected.append(relative.as_posix())
    return collected
