"""Literal evidence anchors, checked independently of the production matcher.

These are printed condemned forms, not generated test sentences. Presence is
necessary citation evidence; source interpretation still requires independent
review. Typography and line wrapping alone are normalized by the audit.
"""

EVIDENCE_FORMS = {
    "participation": "прийняли участь",
    "temporal-protiah": "на протязі року",
    "dependence": "в залежності від успіхів",
    "point-of-view": "з точки зору",
    "relation": "по відношенню",
    "all-respects": "у всіх відношеннях",
    "for-appearance": "для вигляду",
    "feign": "зробити (робити) вигляд",
    "show-appearance": "показував вигляд",
    "last-time": "в останній час",
    "these-days": "на цих днях",
    "instalments": "у розстрочку",
    "cash-on-delivery": "накладною платою",
    "consciousness-loss": "втратив свідомість",
    "consciousness-return": "повернувся до свідомості",
    "matter-is": "справа в тім, що",
    "what-matter": "в чому справа",
    "goods-release": "відпуск товарів",
    "power-on": "включити електрику",
    "power-off": "виключи струм",
    "alarm": "забили тривогу",
    "clock-wind": "заведи годинника",
    "eye-catching": "кидається в очі",
    "step-march": "кроком руш",
    "represents": "уявляє собою",
    "mere-thought": "при одній думці",
    "by-origin": "по походженню",
    "any-circumstances": "при всіх обставинах",
    "skin-idiom": "із шкіри вилузувалися",
    "miropryiemstvo": "міроприємство",
    "coincide": "не співпадає",
    "leaf-through": "листати",
    "concluding": "заключна вистава",
    "conclude": "заключив договір",
    "conclusion": "на заключення зльоту",
    "akin": "зрідні",
    "self-sufficient": "самодовліючий",
    "welcome": "добро пожалувати",
    "sleepless-eye": "недрімаюче око",
    "disarm": "обеззброїти",
    "subscription": "підписка на газети",
    "other-time": "у інший час",
    "tuesdays": "по вівторках",
    "fridays": "по п'ятницях",
    "in-language": "на англійській мові",
    "account-of-self": "здавати собі відчиту",
    "last-year": "в минулому році",
    "year-before-last": "в позаминулому році",
    "at-wish": "при бажанні",
    "at-construction": "при будуванні",
    "breath": "затамувати подих",
    "intermittently": "ні-ні та й",
    "timelessness": "безчасся",
    "new-moon": "новомісяччя",
    "helpless-position": "безвихідному становищі",
    "eager-participle": "бажаючі",
    "resting-participle": "відпочиваючих",
    "dominant-participle": "пануючий",
    "travel-participle": "подорожуючих",
    "beginner-participle": "початкуючі письменники",
    "exciting-participle": "захоплюючі і привабливі подорожі",
    "worker-participle": "працюючий",
    "moving-participle": "хвилююча розповідь",
    "drowning-participle": "утопаючий",
    "sinking-participle": "потопаючий",
    "jumping-participle": "стрибаючий хлопчик",
    "weeping-participle": "плачуча мати",
    "lagging-participle": "відстаючих",
    "knowing-participle": "знаючої людини",
    "farming-calque": "землеробство",
    "farmer-calque": "землероб",
    "farming-adjective-calque": "землеробський",
}
