"""Batch heteronyms expansion dataset for #8039 batch 3 (epic #4387).

Admitted third-tier heteronym batch (32 lemmas, following the 40-lemma
admission in curated_heteronyms_batch.py / PR #8043 and the 32-lemma
admission in curated_heteronyms_batch2.py). Selection method:
`enrich_heteronyms.py --scan` residual after correcting the true-heteronym
denominator (422, not 467 -- see the `--scan` distinct-stress filter fix in
`enrich_heteronyms.py`) filtered to lemmas that are (a) present as live
entries in `site/src/data/lexicon-manifest.json`, and (b) whose dictionary
headword pair carries genuinely distinct stress positions.

Senses are taken from the actual СУМ-11 dictionary body text (not guessed);
stress positions and full inflectional paradigms are taken from VESUM
(`data/vesum.db`, table `forms_all`) where the lemma is attested there, with
each paradigm's stressed forms derived by locating the stressed vowel's
character offset in the headword and re-applying it at the same offset
across every VESUM-attested unstressed case form (safe for these lemmas
because none of them has stress mobility that crosses that offset; the one
exception, the archaic "peasant" sense of землянин, has its plural omitted
rather than guessed, since VESUM does not independently attest a mobile
plural for that sense). All lemmas in this batch are attested in VESUM's
`forms_all` (`heritage_status.vesum_attested` is `True` throughout); an
earlier draft of this batch included `гвоздик`, whose paradigm VESUM does
not attest at all (0 rows) -- flagged by cross-family review (PR #8073) as
an unverified extrapolation and replaced with `випробування`
(ви́пробування "testing, the act of trying something" vs випро́бування
"trial, ordeal, hardship"), which carries a full VESUM-attested paradigm for
both stress variants. The same review also caught a wrong locative singular
for земля́нин -- corrected from the elided "(на) земля́ні" to the
VESUM-attested "на земля́нині / земля́нинові / земля́нину".

Several of this batch's stress/sense pairings correct errors present in the
originating task brief (which had them reversed or misattributed relative to
both СУМ-11 and VESUM); the entries below match the verified dictionary
sources, not the brief's paraphrase. Notably: `колон` follows VESUM's
current stress assignment (коло́н = colonus/peasant, ко́лон = the metrics
"colon" term), which is the *reverse* of СУМ-11's 1970s headword order --
VESUM is the actively-maintained morphological source of record for stress,
СУМ-11 remains the source for the definitions themselves. `дихання` was
dropped from the original candidate list: its second СУМ-11 headword
(диха́ння, dial.) is glossed simply "= дихання" -- a dialectal accent variant
of the identical word, not a distinct sense -- so it fails the genuine-
heteronym bar and is not a curation-worthy pair. `вигідний` (ви́гідний
"profitable" vs вигі́дний "comfortable") was admitted in its place: a
high-frequency, pedagogically classic A2/B1 heteronym pair confirmed
two-way-ambiguous by the ukrainian-word-stress oracle. Two further brief
candidates, `варення` and `бубон`, turned out to already be curated (in
batch 2 and batch 1 respectively) -- admitting them again would have made
this batch net +30, not +32. They are replaced here by `копати`
(ко́пати "kick" vs копа́ти "dig", both A1, extremely common) and `коханий`
(ко́ханий, archaic/poetic "tended, cultivated" -- a participle of кохати in
its older "to tend, cultivate" sense -- vs коха́ний "beloved, sweetheart"),
both drawn from
the same atlas-manifest-present, distinct-stress residual as the rest of
this batch.
"""

from __future__ import annotations

from typing import Any

CURATED_HETERONYMS_BATCH_3: dict[str, list[dict[str, Any]]] = {
    "господарський": [
        {
            "headword": "госпо́дарський",
            "short_label": "належний господареві (B1)",
            "gloss": "of/belonging to the master of the house or estate; personal, domestic",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ɦɔˈspɔdɐrsʲkɪj]", "source": "VESUM"},
            "stress": {"form": "госпо́дарський", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["панський", "хазяйський"]},
            },
            "distinction_note": "Не плутати з омографом «господа́рський» (наголос на третьому складі: пов'язаний з господарством, економікою).",
        },
        {
            "headword": "господа́рський",
            "short_label": "пов'язаний з господарством (B1)",
            "gloss": "of/relating to the economy, farming, or management of an estate/enterprise",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ɦɔspɔˈdarsʲkɪj]", "source": "VESUM"},
            "stress": {"form": "господа́рський", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["економічний", "хазяйновитий"]},
            },
            "distinction_note": "Не плутати з омографом «госпо́дарський» (наголос на другому складі: належний господареві, особистий).",
        },
    ],
    "замковий": [
        {
            "headword": "за́мковий",
            "short_label": "прикм. до за́мок (B1)",
            "gloss": "of/relating to a castle or fortress",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈzamkɔwɪj]", "source": "VESUM"},
            "stress": {"form": "за́мковий", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["фортечний"]},
            },
            "distinction_note": "Не плутати з омографом «замкови́й» (наголос на останньому складі: пов'язаний із замко́м на дверях).",
        },
        {
            "headword": "замкови́й",
            "short_label": "прикм. до замо́к (B1)",
            "gloss": "of/relating to a door lock or padlock",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɐmkɔˈwɪj]", "source": "VESUM"},
            "stress": {"form": "замкови́й", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["дверний"]},
            },
            "distinction_note": "Не плутати з омографом «за́мковий» (наголос на першому складі: пов'язаний із за́мком-фортецею).",
        },
    ],
    "верхом": [
        {
            "headword": "ве́рхом",
            "short_label": "по верхній частині (B1)",
            "gloss": "along/over the top of something; filled to the brim, heaped over the rim",
            "pos": "adverb",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɛrxɔm]", "source": "VESUM"},
            "stress": {"form": "ве́рхом", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прислівник", "paradigm": {"kind": "adverb"}},
            "distinction_note": "Не плутати з омографом «верхо́м» (наголос на другому складі, рідко: те саме, що «верхи» -- сидячи на коні).",
        },
        {
            "headword": "верхо́м",
            "short_label": "сидячи на коні (рідко, B1)",
            "gloss": "mounted, astride, on horseback (rare synonym of верхи)",
            "pos": "adverb",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɛˈrxɔm]", "source": "VESUM"},
            "stress": {"form": "верхо́м", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прислівник", "paradigm": {"kind": "adverb"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["верхи"]},
            },
            "distinction_note": "Не плутати з омографом «ве́рхом» (наголос на першому складі: по верхній частині чого-небудь, з верхом).",
        },
    ],
    "вибухати": [
        {
            "headword": "вибуха́ти",
            "short_label": "вибухати, розриватися (A2)",
            "gloss": "to explode, detonate with great force; (of feelings, events) to erupt suddenly",
            "pos": "verb",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɪbuˈxatɪ]", "source": "VESUM"},
            "stress": {"form": "вибуха́ти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["розриватися", "детонувати"]},
            },
            "distinction_note": "Не плутати з омографом «ви́бухати» (наголос на першому складі, док., розм.: раптом сказати все одразу).",
        },
        {
            "headword": "ви́бухати",
            "short_label": "раптом усе сказати (розм., B1)",
            "gloss": "to blurt out, say everything suddenly (colloquial, perfective)",
            "pos": "verb",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɪbuxɐtɪ]", "source": "VESUM"},
            "stress": {"form": "ви́бухати", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "доконаний"}},
            "distinction_note": "Не плутати з омографом «вибуха́ти» (наголос на третьому складі, недок.: розриватися з силою і звуком).",
        },
    ],
    "вивозити": [
        {
            "headword": "виво́зити",
            "short_label": "везти геть, експортувати (A2)",
            "gloss": "to carry/take out of a place; (also) to export goods to another country",
            "pos": "verb",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɪˈwɔzɪtɪ]", "source": "VESUM"},
            "stress": {"form": "виво́зити", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["експортувати"]},
            },
            "distinction_note": "Не плутати з омографом «ви́возити» (наголос на першому складі, док.: вивезти все за кілька разів; розм. забруднити одяг).",
        },
        {
            "headword": "ви́возити",
            "short_label": "забруднити, вивезти все (розм., B1)",
            "gloss": "to remove/carry away entirely by repeated trips; (colloquial) to get one's clothes dirty while working",
            "pos": "verb",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɪwɔzɪtɪ]", "source": "VESUM"},
            "stress": {"form": "ви́возити", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "доконаний"}},
            "distinction_note": "Не плутати з омографом «виво́зити» (наголос на другому складі, недок.: везти геть, експортувати).",
        },
    ],
    "виганяти": [
        {
            "headword": "виганя́ти",
            "short_label": "проганяти, виводити геть (A2)",
            "gloss": "to drive out, expel, evict (people); to drive/take livestock out to pasture",
            "pos": "verb",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɪɦɐˈnʲatɪ]", "source": "VESUM"},
            "stress": {"form": "виганя́ти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["проганяти", "виводити"]},
            },
            "distinction_note": "Не плутати з омографом «ви́ганяти» (наголос на першому складі, док., рідко: набігатися по багатьох місцях; інший корінь -- від «ганяти», не «гнати»).",
        },
        {
            "headword": "ви́ганяти",
            "short_label": "набігатися (рідко, розм.)",
            "gloss": "to have spent time running about to many places (rare, colloquial; from ганяти, unrelated to виганяти/гнати)",
            "pos": "verb",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɪɦɐnʲɐtɪ]", "source": "VESUM"},
            "stress": {"form": "ви́ганяти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "доконаний"}},
            "distinction_note": "Не плутати з омографом «виганя́ти» (наголос на третьому складі, недок.: проганяти когось геть, виганяти худобу на пасовище).",
        },
    ],
    "вилітати": [
        {
            "headword": "виліта́ти",
            "short_label": "вилітати, відправлятися (A2)",
            "gloss": "to fly out, take off, depart by air; (colloquial) to be expelled, fired",
            "pos": "verb",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɪɫʲiˈtatɪ]", "source": "VESUM"},
            "stress": {"form": "виліта́ти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["відлітати"]},
            },
            "distinction_note": "Не плутати з омографом «ви́літати» (наголос на першому складі, док.: пробути якийсь час літаючи).",
        },
        {
            "headword": "ви́літати",
            "short_label": "пробути якийсь час у польоті (B1)",
            "gloss": "to spend time flying, fly around for a while (delimitative perfective)",
            "pos": "verb",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɪɫʲitɐtɪ]", "source": "VESUM"},
            "stress": {"form": "ви́літати", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "доконаний"}},
            "distinction_note": "Не плутати з омографом «виліта́ти» (наголос на третьому складі, недок.: вилітати, відправлятися в політ).",
        },
    ],
    "витягати": [
        {
            "headword": "витяга́ти",
            "short_label": "тягнучи, виймати (A2)",
            "gloss": "to pull out, extract, stretch out; to help someone out of a difficult situation",
            "pos": "verb",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɪtʲɐˈɦatɪ]", "source": "VESUM"},
            "stress": {"form": "витяга́ти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["виймати", "видобувати"]},
            },
            "distinction_note": "Не плутати з омографом «ви́тягати» (наголос на першому складі, док.: вибрати щось звідкись за кілька разів).",
        },
        {
            "headword": "ви́тягати",
            "short_label": "вибрати за кілька разів (B1)",
            "gloss": "to pick out/draw out repeatedly, several times (perfective)",
            "pos": "verb",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɪtʲɐɦɐtɪ]", "source": "VESUM"},
            "stress": {"form": "ви́тягати", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "доконаний"}},
            "distinction_note": "Не плутати з омографом «витяга́ти» (наголос на третьому складі, недок.: тягнучи, виймати, розтягувати).",
        },
    ],
    "відкликання": [
        {
            "headword": "відкли́кання",
            "short_label": "позбавлення повноважень (B2)",
            "gloss": "recall, withdrawal (of deputies, ambassadors, officials from their post)",
            "pos": "noun",
            "cefr": "B2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wʲiˈdkɫɪkɐnnʲɐ]", "source": "VESUM"},
            "stress": {"form": "відкли́кання", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "відкли́кання", "plural": "відкли́кання"},
                        "родовий": {"singular": "відкли́кання", "plural": "відкли́кань"},
                        "давальний": {"singular": "відкли́канню", "plural": "відкли́канням"},
                        "знахідний": {"singular": "відкли́кання", "plural": "відкли́кання"},
                        "орудний": {"singular": "відкли́канням", "plural": "відкли́каннями"},
                        "місцевий": {"singular": "(у) відкли́канні / відкли́канню", "plural": "відкли́каннях"},
                        "кличний": {"singular": "відкли́кання", "plural": "відкли́кання"},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["звільнення", "усунення"]},
            },
            "distinction_note": "Не плутати з омографом «відклика́ння» (наголос на третьому складі: здатність відкликатися, відгук на поклик).",
        },
        {
            "headword": "відклика́ння",
            "short_label": "відгук на поклик (B2)",
            "gloss": "responsiveness; the act of answering a call (per the verb відклика́тися)",
            "pos": "noun",
            "cefr": "B2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wʲidkɫɪˈkannʲɐ]", "source": "VESUM"},
            "stress": {"form": "відклика́ння", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "відклика́ння", "plural": "відклика́ння"},
                        "родовий": {"singular": "відклика́ння", "plural": "відклика́нь"},
                        "давальний": {"singular": "відклика́нню", "plural": "відклика́нням"},
                        "знахідний": {"singular": "відклика́ння", "plural": "відклика́ння"},
                        "орудний": {"singular": "відклика́нням", "plural": "відклика́ннями"},
                        "місцевий": {"singular": "(у) відклика́нні / відклика́нню", "plural": "відклика́ннях"},
                        "кличний": {"singular": "відклика́ння", "plural": "відклика́ння"},
                    },
                },
            },
            "distinction_note": "Не плутати з омографом «відкли́кання» (наголос на другому складі: позбавлення повноважень депутата, посла).",
        },
    ],
    "відповідний": [
        {
            "headword": "відпові́дний",
            "short_label": "підхожий, належний (A2)",
            "gloss": "suitable, appropriate, corresponding (fitting for a given case)",
            "pos": "adjective",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wʲidpɔˈwʲidnɪj]", "source": "VESUM"},
            "stress": {"form": "відпові́дний", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["підхожий", "належний"]},
            },
            "distinction_note": "Не плутати з омографом «відповідни́й» (наголос на останньому складі: даний у відповідь -- відповідний лист).",
        },
        {
            "headword": "відповідни́й",
            "short_label": "даний у відповідь (B2)",
            "gloss": "given in reply/response (e.g. an answering letter or diplomatic note)",
            "pos": "adjective",
            "cefr": "B2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wʲidpɔwʲiˈdnɪj]", "source": "VESUM"},
            "stress": {"form": "відповідни́й", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "distinction_note": "Не плутати з омографом «відпові́дний» (наголос на третьому складі: підхожий, належний для якогось випадку).",
        },
    ],
    "вітряний": [
        {
            "headword": "ві́тряний",
            "short_label": "з вітром (A2)",
            "gloss": "windy (accompanied by wind); (figuratively, of a person) flighty, frivolous",
            "pos": "adjective",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwʲitrɐnɪj]", "source": "VESUM"},
            "stress": {"form": "ві́тряний", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["буряний"]},
                "antonyms": {"source": "СУМ-11", "items": ["тихий", "безвітряний"]},
            },
            "distinction_note": "Не плутати з омографом «вітряни́й» (наголос на останньому складі: що діє за допомогою вітру -- вітряний млин).",
        },
        {
            "headword": "вітряни́й",
            "short_label": "що діє вітром (B1)",
            "gloss": "wind-powered (e.g. a windmill)",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wʲitrɐˈnɪj]", "source": "VESUM"},
            "stress": {"form": "вітряни́й", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "distinction_note": "Не плутати з омографом «ві́тряний» (наголос на першому складі: з вітром, вітряна погода).",
        },
    ],
    "водяний": [
        {
            "headword": "водя́ний",
            "short_label": "водянистий (B1)",
            "gloss": "watery, diluted, waterlogged (of soil, food); rich in water",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɔˈdʲanɪj]", "source": "VESUM"},
            "stress": {"form": "водя́ний", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["водянистий"]},
            },
            "distinction_note": "Не плутати з омографом «водяни́й» (наголос на останньому складі: пов'язаний з водою -- водяний млин, водяний спорт).",
        },
        {
            "headword": "водяни́й",
            "short_label": "пов'язаний з водою (A2)",
            "gloss": "aquatic, water-related, water-powered (of mills, sports, plants/animals); (dated, as a noun) a water spirit",
            "pos": "adjective",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɔdʲɐˈnɪj]", "source": "VESUM"},
            "stress": {"form": "водяни́й", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["водний"]},
            },
            "distinction_note": "Не плутати з омографом «водя́ний» (наголос на другому складі: водянистий, багатий на воду).",
        },
    ],
    "воловий": [
        {
            "headword": "во́ловий",
            "short_label": "прикм. до во́ло (діал.)",
            "gloss": "relating to воло -- the crop (craw) of a bird; (dialectal, folk) relating to a goiter",
            "pos": "adjective",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɔɫɔwɪj]", "source": "VESUM"},
            "stress": {"form": "во́ловий", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "distinction_note": "Не плутати з омографом «воло́вий» (наголос на другому складі: прикметник до «віл» -- волова шкура, воловий плуг).",
        },
        {
            "headword": "воло́вий",
            "short_label": "прикм. до віл (B1)",
            "gloss": "of/relating to an ox (ox-hide, ox-drawn, ox-meat); (figuratively) extremely strong, tough",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɔˈɫɔwɪj]", "source": "VESUM"},
            "stress": {"form": "воло́вий", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "distinction_note": "Не плутати з омографом «во́ловий» (наголос на першому складі, діал.: прикметник до «воло» -- воло птаха або зоб).",
        },
    ],
    "гукати": [
        {
            "headword": "гу́кати",
            "short_label": "видавати гучний звук (розм., B1)",
            "gloss": "to make a loud, sharp sound; to hoot (of trains, thunder)",
            "pos": "verb",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈɦukɐtɪ]", "source": "VESUM"},
            "stress": {"form": "гу́кати", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "distinction_note": "Не плутати з омографом «гука́ти» (наголос на другому складі: голосно кликати когось, звертатися до когось).",
        },
        {
            "headword": "гука́ти",
            "short_label": "голосно кликати (A2)",
            "gloss": "to call out loudly, summon; to shout at someone",
            "pos": "verb",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ɦuˈkatɪ]", "source": "VESUM"},
            "stress": {"form": "гука́ти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["кликати", "гукнути"]},
            },
            "distinction_note": "Не плутати з омографом «гу́кати» (наголос на першому складі, розм.: видавати гучний, різкий звук -- про грім, потяг).",
        },
    ],
    "випробування": [
        {
            "headword": "ви́пробування",
            "short_label": "процес перевірки, тестування (A2)",
            "gloss": "the act or process of testing, trying (something) out (act per значенням «ви́пробувати»)",
            "pos": "noun",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɪprɔbʊwɐnʲːɐ]", "source": "VESUM"},
            "stress": {"form": "ви́пробування", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "ви́пробування", "plural": "ви́пробування"},
                        "родовий": {"singular": "ви́пробування", "plural": "ви́пробувань"},
                        "давальний": {"singular": "ви́пробуванню", "plural": "ви́пробуванням"},
                        "знахідний": {"singular": "ви́пробування", "plural": "ви́пробування"},
                        "орудний": {"singular": "ви́пробуванням", "plural": "ви́пробуваннями"},
                        "місцевий": {"singular": "(на/у) ви́пробуванні / ви́пробуванню", "plural": "ви́пробуваннях"},
                        "кличний": {"singular": "ви́пробування", "plural": "ви́пробування"},
                    },
                },
            },
            "distinction_note": "Не плутати з омографом «випро́бування» (наголос на третьому складі: перевірка якостей, властивостей когось/чогось, іспит; тяжкі переживання, лихо).",
        },
        {
            "headword": "випро́бування",
            "short_label": "іспит; тяжке переживання (B1)",
            "gloss": "a test, trial, examination of someone's/something's qualities or properties; (also) an ordeal, hardship, tribulation",
            "pos": "noun",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɪˈprɔbʊwɐnʲːɐ]", "source": "VESUM"},
            "stress": {"form": "випро́бування", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "випро́бування", "plural": "випро́бування"},
                        "родовий": {"singular": "випро́бування", "plural": "випро́бувань"},
                        "давальний": {"singular": "випро́буванню", "plural": "випро́буванням"},
                        "знахідний": {"singular": "випро́бування", "plural": "випро́бування"},
                        "орудний": {"singular": "випро́буванням", "plural": "випро́буваннями"},
                        "місцевий": {"singular": "(на/у) випро́буванні / випро́буванню", "plural": "випро́буваннях"},
                        "кличний": {"singular": "випро́бування", "plural": "випро́бування"},
                    },
                },
            },
            "distinction_note": "Не плутати з омографом «ви́пробування» (наголос на першому складі: дія за значенням «ви́пробувати», процес тестування).",
        },
    ],
    "гладкий": [
        {
            "headword": "гла́дкий",
            "short_label": "рівний, без нерівностей (A2)",
            "gloss": "smooth, even, without bumps or folds",
            "pos": "adjective",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈɦɫadkɪj]", "source": "VESUM"},
            "stress": {"form": "гла́дкий", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["рівний"]},
                "antonyms": {"source": "СУМ-11", "items": ["шорсткий", "нерівний"]},
            },
            "distinction_note": "Не плутати з омографом «гладки́й» (наголос на другому складі: вгодований, ситий, повний тілом).",
        },
        {
            "headword": "гладки́й",
            "short_label": "вгодований, ситий (B1)",
            "gloss": "plump, corpulent, well-fed",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ɦɫɐˈdkɪj]", "source": "VESUM"},
            "stress": {"form": "гладки́й", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["вгодований", "ситий"]},
                "antonyms": {"source": "СУМ-11", "items": ["худий"]},
            },
            "distinction_note": "Не плутати з омографом «гла́дкий» (наголос на першому складі: рівний, без нерівностей і виступів).",
        },
    ],
    "діяння": [
        {
            "headword": "ді́яння",
            "short_label": "дія, вчинок (B1)",
            "gloss": "a deed, act, action; (plural) conduct, deeds",
            "pos": "noun",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈdʲijɐnnʲɐ]", "source": "VESUM"},
            "stress": {"form": "ді́яння", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "ді́яння", "plural": "ді́яння"},
                        "родовий": {"singular": "ді́яння", "plural": "ді́янь"},
                        "давальний": {"singular": "ді́янню", "plural": "ді́янням"},
                        "знахідний": {"singular": "ді́яння", "plural": "ді́яння"},
                        "орудний": {"singular": "ді́янням", "plural": "ді́яннями"},
                        "місцевий": {"singular": "(у) ді́янні / ді́янню", "plural": "ді́яннях"},
                        "кличний": {"singular": "ді́яння", "plural": "ді́яння"},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["дія", "вчинок"]},
            },
            "distinction_note": "Не плутати з омографом «дія́ння» (наголос на другому складі, рел.: церковне читання про діяння апостолів).",
        },
        {
            "headword": "дія́ння",
            "short_label": "церк. читання про апостолів",
            "gloss": "(religious) the church reading of the Acts of the Apostles; «Діяння апостолів» = the Acts of the Apostles",
            "pos": "noun",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[dʲiˈjannʲɐ]", "source": "VESUM"},
            "stress": {"form": "дія́ння", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "дія́ння", "plural": "дія́ння"},
                        "родовий": {"singular": "дія́ння", "plural": "дія́нь"},
                        "давальний": {"singular": "дія́нню", "plural": "дія́нням"},
                        "знахідний": {"singular": "дія́ння", "plural": "дія́ння"},
                        "орудний": {"singular": "дія́нням", "plural": "дія́ннями"},
                        "місцевий": {"singular": "(у) дія́нні / дія́нню", "plural": "дія́ннях"},
                        "кличний": {"singular": "дія́ння", "plural": "дія́ння"},
                    },
                },
            },
            "distinction_note": "Не плутати з омографом «ді́яння» (наголос на першому складі: дія, вчинок, учинки людини).",
        },
    ],
    "добродійство": [
        {
            "headword": "добро́дійство",
            "short_label": "шановне товариство (заст., збірн.)",
            "gloss": "the esteemed folk, ladies and gentlemen (archaic collective address term; see добродій)",
            "pos": "noun",
            "cefr": None,
            "heritage_status": {
                "classification": "authentic-archaism",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": "treasured",
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[dɔˈbrɔdʲijstwɔ]", "source": "VESUM"},
            "stress": {"form": "добро́дійство", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "добро́дійство", "plural": "добро́дійства"},
                        "родовий": {"singular": "добро́дійства", "plural": "добро́дійств"},
                        "давальний": {"singular": "добро́дійству", "plural": "добро́дійствам"},
                        "знахідний": {"singular": "добро́дійство", "plural": "добро́дійства"},
                        "орудний": {"singular": "добро́дійством", "plural": "добро́дійствами"},
                        "місцевий": {"singular": "(у) добро́дійстві / добро́дійству", "plural": "добро́дійствах"},
                        "кличний": {"singular": "добро́дійство", "plural": "добро́дійства"},
                    },
                },
            },
            "distinction_note": "Не плутати з омографом «доброді́йство» (наголос на третьому складі, розм.: доброчинність, добра справа).",
        },
        {
            "headword": "доброді́йство",
            "short_label": "доброчинність (розм., B2)",
            "gloss": "beneficence, charity; a good/charitable deed (= добродіяння)",
            "pos": "noun",
            "cefr": "B2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[dɔbrɔˈdʲijstwɔ]", "source": "VESUM"},
            "stress": {"form": "доброді́йство", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "доброді́йство", "plural": "доброді́йства"},
                        "родовий": {"singular": "доброді́йства", "plural": "доброді́йств"},
                        "давальний": {"singular": "доброді́йству", "plural": "доброді́йствам"},
                        "знахідний": {"singular": "доброді́йство", "plural": "доброді́йства"},
                        "орудний": {"singular": "доброді́йством", "plural": "доброді́йствами"},
                        "місцевий": {"singular": "(у) доброді́йстві / доброді́йству", "plural": "доброді́йствах"},
                        "кличний": {"singular": "доброді́йство", "plural": "доброді́йства"},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["добродіяння", "доброчинність"]},
            },
            "distinction_note": "Не плутати з омографом «добро́дійство» (наголос на другому складі, заст., збірн.: шановне товариство, зверт. форма).",
        },
    ],
    "духовий": [
        {
            "headword": "духо́вий",
            "short_label": "духовний (діал.)",
            "gloss": "spiritual (dialectal synonym of духовний)",
            "pos": "adjective",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[duˈxɔwɪj]", "source": "VESUM"},
            "stress": {"form": "духо́вий", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "distinction_note": "Не плутати з омографом «духови́й» (наголос на останньому складі: пов'язаний із духовими інструментами або жаром -- духовий оркестр, духова шафа).",
        },
        {
            "headword": "духови́й",
            "short_label": "духові інструменти, жарова піч (A2)",
            "gloss": "wind-instrument-related (of music); operated by hot air (e.g. an oven)",
            "pos": "adjective",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[duxɔˈwɪj]", "source": "VESUM"},
            "stress": {"form": "духови́й", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["жаровий"]},
            },
            "distinction_note": "Не плутати з омографом «духо́вий» (наголос на другому складі, діал.: духовний, пов'язаний із духом).",
        },
    ],
    "забігати": [
        {
            "headword": "забі́гати",
            "short_label": "почати бігати (B1)",
            "gloss": "to begin running about (bounded perfective)",
            "pos": "verb",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɐˈbʲiɦɐtɪ]", "source": "VESUM"},
            "stress": {"form": "забі́гати", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "доконаний"}},
            "distinction_note": "Не плутати з омографом «забіга́ти» (наголос на третьому складі, недок.: заходити ненадовго, забігати наперед).",
        },
        {
            "headword": "забіга́ти",
            "short_label": "заходити ненадовго (A2)",
            "gloss": "to run into somewhere briefly; to drop by; to run ahead",
            "pos": "verb",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɐbʲiˈɦatɪ]", "source": "VESUM"},
            "stress": {"form": "забіга́ти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["заходити", "навідуватися"]},
            },
            "distinction_note": "Не плутати з омографом «забі́гати» (наголос на другому складі, док.: почати бігати).",
        },
    ],
    "загорода": [
        {
            "headword": "за́города",
            "short_label": "загін для худоби (B1)",
            "gloss": "an enclosed pen for keeping domestic animals or birds",
            "pos": "noun",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈzaɦɔrɔdɐ]", "source": "VESUM"},
            "stress": {"form": "за́города", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "за́города", "plural": "за́городи"},
                        "родовий": {"singular": "за́городи", "plural": "за́город"},
                        "давальний": {"singular": "за́городі", "plural": "за́городам"},
                        "знахідний": {"singular": "за́городу", "plural": "за́городи"},
                        "орудний": {"singular": "за́городою", "plural": "за́городами"},
                        "місцевий": {"singular": "(у) за́городі", "plural": "за́городах"},
                        "кличний": {"singular": "за́городо", "plural": "за́городи"},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["загін", "кошара"]},
            },
            "distinction_note": "Не плутати з омографом «загоро́да» (наголос на третьому складі: тин, паркан, огорожа).",
        },
        {
            "headword": "загоро́да",
            "short_label": "тин, огорожа (B1)",
            "gloss": "a fence, wall, or similar barrier that encloses something",
            "pos": "noun",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɐɦɔˈrɔdɐ]", "source": "VESUM"},
            "stress": {"form": "загоро́да", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "загоро́да", "plural": "загоро́ди"},
                        "родовий": {"singular": "загоро́ди", "plural": "загоро́д"},
                        "давальний": {"singular": "загоро́ді", "plural": "загоро́дам"},
                        "знахідний": {"singular": "загоро́ду", "plural": "загоро́ди"},
                        "орудний": {"singular": "загоро́дою", "plural": "загоро́дами"},
                        "місцевий": {"singular": "(у) загоро́ді", "plural": "загоро́дах"},
                        "кличний": {"singular": "загоро́до", "plural": "загоро́ди"},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["тин", "паркан", "огорожа"]},
            },
            "distinction_note": "Не плутати з омографом «за́города» (наголос на першому складі: загороджена ділянка для худоби).",
        },
    ],
    "запальний": [
        {
            "headword": "запа́льний",
            "short_label": "пов'язаний із запалом (спец., B2)",
            "gloss": "relating to a fuse or ignition charge (special/military term)",
            "pos": "adjective",
            "cefr": "B2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɐˈpaɫʲnɪj]", "source": "VESUM"},
            "stress": {"form": "запа́льний", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "distinction_note": "Не плутати з омографом «запальни́й» (наголос на останньому складі: запалювальний; перен. запальна людина -- гарячкувата, схильна до захоплення).",
        },
        {
            "headword": "запальни́й",
            "short_label": "запалювальний; гарячкуватий (B1)",
            "gloss": "incendiary; (figuratively) rousing, passionate, quick-tempered; (medical) inflammatory",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɐpɐɫʲˈnɪj]", "source": "VESUM"},
            "stress": {"form": "запальни́й", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["палкий", "гарячкуватий"]},
                "antonyms": {"source": "СУМ-11", "items": ["спокійний", "стриманий"]},
            },
            "distinction_note": "Не плутати з омографом «запа́льний» (наголос на другому складі, спец.: пов'язаний із запалом -- запальний гніт).",
        },
    ],
    "затока": [
        {
            "headword": "зато́ка",
            "short_label": "бухта (A2)",
            "gloss": "a bay, gulf (part of a sea, lake, or river that cuts into land)",
            "pos": "noun",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɐˈtɔkɐ]", "source": "VESUM"},
            "stress": {"form": "зато́ка", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "зато́ка", "plural": "зато́ки"},
                        "родовий": {"singular": "зато́ки", "plural": "зато́к"},
                        "давальний": {"singular": "зато́ці", "plural": "зато́кам"},
                        "знахідний": {"singular": "зато́ку", "plural": "зато́ки"},
                        "орудний": {"singular": "зато́кою", "plural": "зато́ками"},
                        "місцевий": {"singular": "(у) зато́ці", "plural": "зато́ках"},
                        "кличний": {"singular": "зато́ко", "plural": "зато́ки"},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["бухта", "лиман"]},
            },
            "distinction_note": "Не плутати з омографом «за́тока» (наголос на першому складі, діал.: слизький схил дороги, куди сповзають сани).",
        },
        {
            "headword": "за́тока",
            "short_label": "слизький схил дороги (діал.)",
            "gloss": "(dialectal) a slippery downhill stretch of road where sledges slide off",
            "pos": "noun",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈzatɔkɐ]", "source": "VESUM"},
            "stress": {"form": "за́тока", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "за́тока", "plural": "за́токи"},
                        "родовий": {"singular": "за́токи", "plural": "за́ток"},
                        "давальний": {"singular": "за́тоці", "plural": "за́токам"},
                        "знахідний": {"singular": "за́току", "plural": "за́токи"},
                        "орудний": {"singular": "за́токою", "plural": "за́токами"},
                        "місцевий": {"singular": "(у) за́тоці", "plural": "за́токах"},
                        "кличний": {"singular": "за́токо", "plural": "за́токи"},
                    },
                },
            },
            "distinction_note": "Не плутати з омографом «зато́ка» (наголос на другому складі: частина моря чи озера, що вдається в сушу; бухта).",
        },
    ],
    "збігатися": [
        {
            "headword": "збіга́тися",
            "short_label": "сходитися, збігатися в часі (A2)",
            "gloss": "to run together, converge from different directions; to coincide (in time, opinion); (of fabric) to shrink",
            "pos": "verb",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zbʲiˈɦatɪsʲɐ]", "source": "VESUM"},
            "stress": {"form": "збіга́тися", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["сходитися", "збиратися"]},
            },
            "distinction_note": "Не плутати з омографом «збі́гатися» (наголос на першому складі, док., заст./розм.: набігатися по багатьох місцях, стомитися від бігу).",
        },
        {
            "headword": "збі́гатися",
            "short_label": "набігатися (заст., розм.)",
            "gloss": "(archaic) to have visited many places running about; (colloquial) to tire oneself out from running",
            "pos": "verb",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈzbʲiɦɐtɪsʲɐ]", "source": "VESUM"},
            "stress": {"form": "збі́гатися", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "доконаний"}},
            "distinction_note": "Не плутати з омографом «збіга́тися» (наголос на другому складі, недок.: сходитися докупи, збігатися в часі).",
        },
    ],
    "землянин": [
        {
            "headword": "земля́нин",
            "short_label": "мешканець Землі (A2)",
            "gloss": "an inhabitant of planet Earth, Earthling",
            "pos": "noun",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɛˈmɫʲanɪn]", "source": "VESUM"},
            "stress": {"form": "земля́нин", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "note": "клас іменників на -анин/-янин: у множині суфікс -ин зникає",
                    "cases": {
                        "називний": {"singular": "земля́нин", "plural": "земля́ни"},
                        "родовий": {"singular": "земля́нина", "plural": "земля́н"},
                        "давальний": {"singular": "земля́нинові / земля́нину", "plural": "земля́нам"},
                        "знахідний": {"singular": "земля́нина", "plural": "земля́н"},
                        "орудний": {"singular": "земля́нином", "plural": "земля́нами"},
                        "місцевий": {"singular": "на земля́нині / земля́нинові / земля́нину", "plural": "земля́нах"},
                        "кличний": {"singular": "земля́нине", "plural": "земля́ни"},
                    },
                },
            },
            "sections": {
                "antonyms": {"source": "СУМ-11", "items": ["інопланетянин"]},
            },
            "distinction_note": "Не плутати з омографом «земляни́н» (наголос на останньому складі, заст.: селянин).",
        },
        {
            "headword": "земляни́н",
            "short_label": "селянин (заст.)",
            "gloss": "a peasant, countryman (archaic synonym of селянин)",
            "pos": "noun",
            "cefr": None,
            "heritage_status": {
                "classification": "authentic-archaism",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": "treasured",
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[zɛmɫʲɐˈnɪn]", "source": "VESUM"},
            "stress": {"form": "земляни́н", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "note": "форми множини для цього застарілого значення рідко фіксуються окремо",
                    "cases": {
                        "називний": {"singular": "земляни́н", "plural": None},
                        "родовий": {"singular": "земляни́на", "plural": None},
                        "давальний": {"singular": "земляни́нові / земляни́ну", "plural": None},
                        "знахідний": {"singular": "земляни́на", "plural": None},
                        "орудний": {"singular": "земляни́ном", "plural": None},
                        "місцевий": {"singular": "на земляни́ні / земляни́нові / земляни́ну", "plural": None},
                        "кличний": {"singular": "земляни́не", "plural": None},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["селянин"]},
            },
            "distinction_note": "Не плутати з омографом «земля́нин» (наголос на другому складі: мешканець планети Земля).",
        },
    ],
    "ковтати": [
        {
            "headword": "ковта́ти",
            "short_label": "проковтнути їжу (A1)",
            "gloss": "to swallow (move food/drink from the mouth to the stomach)",
            "pos": "verb",
            "cefr": "A1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[kɔˈwtatɪ]", "source": "VESUM"},
            "stress": {"form": "ковта́ти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["глитати"]},
            },
            "distinction_note": "Не плутати з омографом «ко́втати» (наголос на першому складі, діал.: битися, стукатися).",
        },
        {
            "headword": "ко́втати",
            "short_label": "битися, стукатися (діал.)",
            "gloss": "(dialectal) to knock, hit, bang against something",
            "pos": "verb",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈkɔwtɐtɪ]", "source": "VESUM"},
            "stress": {"form": "ко́втати", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "distinction_note": "Не плутати з омографом «ковта́ти» (наголос на другому складі: проковтнути їжу чи напій).",
        },
    ],
    "колон": [
        {
            "headword": "ко́лон",
            "short_label": "віршовий рядок (спец., C1)",
            "gloss": "a colon -- a rhythmic unit of verse or prose sharing one rhythmic stress (literary/prosody term)",
            "pos": "noun",
            "cefr": "C1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈkɔɫɔn]", "source": "VESUM"},
            "stress": {"form": "ко́лон", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "cases": {
                        "називний": {"singular": "ко́лон", "plural": "ко́лони"},
                        "родовий": {"singular": "ко́лона", "plural": "ко́лонів"},
                        "давальний": {"singular": "ко́лону / ко́лонові", "plural": "ко́лонам"},
                        "знахідний": {"singular": "ко́лон", "plural": "ко́лони"},
                        "орудний": {"singular": "ко́лоном", "plural": "ко́лонами"},
                        "місцевий": {"singular": "(у) ко́лоні / ко́лону / ко́лонові", "plural": "ко́лонах"},
                        "кличний": {"singular": "ко́лоне", "plural": "ко́лони"},
                    },
                },
            },
            "distinction_note": "Не плутати з омографом «коло́н» (наголос на другому складі: селянин-орендар у Римській імперії або середньовіччі).",
        },
        {
            "headword": "коло́н",
            "short_label": "селянин-орендар (іст., C1)",
            "gloss": "a colonus -- a Roman or medieval tenant peasant farmer (historical term)",
            "pos": "noun",
            "cefr": "C1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[kɔˈɫɔn]", "source": "VESUM"},
            "stress": {"form": "коло́н", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "note": "тварин./анімат. відмінювання (родовий = знахідний)",
                    "cases": {
                        "називний": {"singular": "коло́н", "plural": "коло́ни"},
                        "родовий": {"singular": "коло́на", "plural": "коло́нів"},
                        "давальний": {"singular": "коло́ну / коло́нові", "plural": "коло́нам"},
                        "знахідний": {"singular": "коло́на", "plural": "коло́нів"},
                        "орудний": {"singular": "коло́ном", "plural": "коло́нами"},
                        "місцевий": {"singular": "(у) коло́ні / коло́ну / коло́нові", "plural": "коло́нах"},
                        "кличний": {"singular": "коло́не", "plural": "коло́ни"},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["орендар"]},
            },
            "distinction_note": "Не плутати з омографом «ко́лон» (наголос на першому складі: віршовий рядок, ритмічна одиниця тексту).",
        },
    ],
    "колючий": [
        {
            "headword": "ко́лючий",
            "short_label": "яким колють (B1)",
            "gloss": "which pricks/is used for piercing (of an organ or device); causing a sharp, piercing pain sensation",
            "pos": "adjective",
            "cefr": "B1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈkɔɫʲut͡ʃɪj]", "source": "VESUM"},
            "stress": {"form": "ко́лючий", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "distinction_note": "Не плутати з омографом «колю́чий» (наголос на другому складі: колючий терен, колюча борода; перен. дошкульний).",
        },
        {
            "headword": "колю́чий",
            "short_label": "з колючками, дошкульний (A2)",
            "gloss": "prickly, thorny, covered with thorns/spines; (figuratively) sharp-tongued, biting",
            "pos": "adjective",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[kɔˈɫʲut͡ʃɪj]", "source": "VESUM"},
            "stress": {"form": "колю́чий", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["дошкульний"]},
                "antonyms": {"source": "СУМ-11", "items": ["гладенький", "м'який"]},
            },
            "distinction_note": "Не плутати з омографом «ко́лючий» (наголос на першому складі: яким колють, гострий -- колючий апарат, колючий біль).",
        },
    ],
    "копати": [
        {
            "headword": "ко́пати",
            "short_label": "бити ногою (A1)",
            "gloss": "to kick, strike with the foot; (of animals) to buck, kick",
            "pos": "verb",
            "cefr": "A1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈkɔpɐtɪ]", "source": "VESUM"},
            "stress": {"form": "ко́пати", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "distinction_note": "Не плутати з омографом «копа́ти» (наголос на другому складі: розпушувати землю заступом чи лопатою).",
        },
        {
            "headword": "копа́ти",
            "short_label": "розпушувати землю (A1)",
            "gloss": "to dig (loosen soil with a spade or shovel)",
            "pos": "verb",
            "cefr": "A1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[kɔˈpatɪ]", "source": "VESUM"},
            "stress": {"form": "копа́ти", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "дієслово", "paradigm": {"kind": "verb", "aspect": "недоконаний"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["розпушувати"]},
            },
            "distinction_note": "Не плутати з омографом «ко́пати» (наголос на першому складі: бити, штовхати ногою).",
        },
    ],
    "коханий": [
        {
            "headword": "ко́ханий",
            "short_label": "плеканий, доглянутий (поет., рідко)",
            "gloss": "lovingly tended, cultivated (archaic/poetic passive participle of ко́хати in its \"to tend, cultivate\" sense, e.g. of flowers)",
            "pos": "adjective",
            "cefr": None,
            "heritage_status": {
                "classification": "authentic-archaism",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": "treasured",
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈkɔxɐnɪj]", "source": "VESUM"},
            "stress": {"form": "ко́ханий", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "distinction_note": "Не плутати з омографом «коха́ний» (наголос на другому складі: той, кого кохають; милий, любий).",
        },
        {
            "headword": "коха́ний",
            "short_label": "той, кого кохають (A1)",
            "gloss": "beloved; darling, sweetheart (the person one loves)",
            "pos": "adjective",
            "cefr": "A1",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[kɔˈxanɪj]", "source": "VESUM"},
            "stress": {"form": "коха́ний", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["милий", "любий"]},
            },
            "distinction_note": "Не плутати з омографом «ко́ханий» (наголос на першому складі, поет., рідко: плеканий, доглянутий -- дієприкметник до «кохати» квіти).",
        },
    ],
    "ведмежина": [
        {
            "headword": "ведме́жина",
            "short_label": "ведмеже м'ясо (рідко)",
            "gloss": "bear meat (= ведмежатина)",
            "pos": "noun",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɛˈdmɛʒɪnɐ]", "source": "VESUM"},
            "stress": {"form": "ведме́жина", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "note": "переважно вживається в однині",
                    "cases": {
                        "називний": {"singular": "ведме́жина", "plural": None},
                        "родовий": {"singular": "ведме́жини", "plural": None},
                        "давальний": {"singular": "ведме́жині", "plural": None},
                        "знахідний": {"singular": "ведме́жину", "plural": None},
                        "орудний": {"singular": "ведме́жиною", "plural": None},
                        "місцевий": {"singular": "(у) ведме́жині", "plural": None},
                        "кличний": {"singular": "ведме́жино", "plural": None},
                    },
                },
            },
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["ведмежатина"]},
            },
            "distinction_note": "Не плутати з омографом «ведмежи́на» (наголос на третьому складі: дикий кущ родини трояндових з темно-червоними ягодами).",
        },
        {
            "headword": "ведмежи́на",
            "short_label": "дикий кущ з ягодами (рідко)",
            "gloss": "a wild shrub of the rose family (Rosaceae) with dark-red edible berries; the berries themselves",
            "pos": "noun",
            "cefr": None,
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɛdmɛˈʒɪnɐ]", "source": "VESUM"},
            "stress": {"form": "ведмежи́на", "source": "ukrainian-word-stress"},
            "morphology": {
                "pos": "іменник",
                "paradigm": {
                    "kind": "noun",
                    "note": "переважно вживається в однині",
                    "cases": {
                        "називний": {"singular": "ведмежи́на", "plural": None},
                        "родовий": {"singular": "ведмежи́ни", "plural": None},
                        "давальний": {"singular": "ведмежи́ні", "plural": None},
                        "знахідний": {"singular": "ведмежи́ну", "plural": None},
                        "орудний": {"singular": "ведмежи́ною", "plural": None},
                        "місцевий": {"singular": "(у) ведмежи́ні", "plural": None},
                        "кличний": {"singular": "ведмежи́но", "plural": None},
                    },
                },
            },
            "distinction_note": "Не плутати з омографом «ведме́жина» (наголос на другому складі: ведмеже м'ясо).",
        },
    ],
    "вигідний": [
        {
            "headword": "ви́гідний",
            "short_label": "прибутковий (A2)",
            "gloss": "profitable, beneficial (from which one can gain a benefit or profit)",
            "pos": "adjective",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[ˈwɪɦʲidnɪj]", "source": "VESUM"},
            "stress": {"form": "ви́гідний", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["прибутковий", "корисний"]},
                "antonyms": {"source": "СУМ-11", "items": ["невигідний", "збитковий"]},
            },
            "distinction_note": "Не плутати з омографом «вигі́дний» (наголос на другому складі: зручний для користування, приємний).",
        },
        {
            "headword": "вигі́дний",
            "short_label": "зручний (A2)",
            "gloss": "comfortable, convenient (to use), pleasant",
            "pos": "adjective",
            "cefr": "A2",
            "heritage_status": {
                "classification": "standard",
                "is_russianism": False,
                "russian_shadow": False,
                "vesum_attested": True,
                "warning_severity": None,
                "calque_warning": None,
            },
            "pronunciation": {"ipa": "[wɪˈɦʲidnɪj]", "source": "VESUM"},
            "stress": {"form": "вигі́дний", "source": "ukrainian-word-stress"},
            "morphology": {"pos": "прикметник", "paradigm": {"kind": "adjective"}},
            "sections": {
                "synonyms": {"source": "СУМ-11", "items": ["зручний", "приємний"]},
                "antonyms": {"source": "СУМ-11", "items": ["незручний"]},
            },
            "distinction_note": "Не плутати з омографом «ви́гідний» (наголос на першому складі: прибутковий, який дає користь чи прибуток).",
        },
    ],
}
